---
permalink: install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, forced 
summary:  
---
= ONTAP Mediator가 MetroCluster IP 구성에서 자동 계획되지 않은 전환을 지원하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Mediator는 MetroCluster IP 노드의 상태 정보를 저장하는 사서함 LUN을 제공합니다. 이 LUN은 MetroCluster 사이트와 물리적으로 분리된 Linux 호스트에서 실행되는 ONTAP Mediator와 함께 배치됩니다. MetroCluster IP 노드는 사서함 정보를 사용하여 DR(재해 복구) 파트너의 상태를 모니터링하고 재해 발생 시 MAUSO(중재자 지원 계획되지 않은 전환)를 구현할 수 있습니다.


NOTE: MAUSO는 MetroCluster FC 구성에서 지원되지 않습니다.

절체가 필요한 사이트 장애를 감지하면 절체가 적절한지 확인하고, 적절한 경우 절체를 수행한다. 기본적으로 MAUSO는 다음 시나리오에서 시작됩니다.

* 각 노드의 비휘발성 캐시에 대한 SyncMirror 미러링 및 DR 미러링이 모두 작동하고 캐시 및 미러가 장애 시 동기화됩니다.
* 정상적인 사이트의 노드 중 테이크오버 상태가 아닌 노드는 없습니다.
* 사이트 재해가 발생하는 경우 사이트 재해는 동일한 사이트에 있는 _ALL_NODES의 장애입니다.


MAUSO는 다음과 같은 종료 시나리오에서 _NOT_initiated입니다.

* 종료를 시작합니다. 예를 들면 다음과 같습니다.
+
** 노드를 중지합니다
** 노드를 재부팅합니다




각 ONTAP 9 릴리스에서 사용할 수 있는 MAUSO 기능에 대해 알아봅니다.

[cols="1a,5a"]
|===
| 다음으로 시작... | 설명 


 a| 
ONTAP 9.13.1 을 참조하십시오
 a| 
* MAUSO는 인 경우 시작됩니다 <<default_scenarios,기본 시나리오>> 팬 또는 하드웨어 장애가 발생하면 환경 종료가 시작됩니다. 하드웨어 장애의 예로는 고온 또는 저온, 또는 전원 공급 장치, NVRAM 배터리 또는 서비스 프로세서 하트비트 장애가 있습니다.
* MetroCluster IP 구성에서 실패 도메인의 기본값은 "auso-on-dr-group"으로 설정됩니다. ONTAP 9.12.1 이하 버전의 경우 기본값은 "auso-on-cluster-daster"로 설정됩니다.
+
8노드 MetroCluster IP 구성에서 "auso-on-DR-group"은 클러스터 장애 시 또는 하나의 DR 그룹에 있는 HA 쌍 중 하나로 MAUSO를 트리거합니다. HA Pair의 경우 두 노드에서 동시에 장애가 발생해야 합니다.

+
필요한 경우 를 사용하여 장애 도메인 설정을 "auso-on-cluster-daster" 도메인으로 변경할 수 있습니다 `metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster` 두 DR 그룹에 HA 노드 쌍 장애가 있는 경우에만 MAUSO를 트리거하는 명령

* 장애 시 NVRAM이 동기화되지 않은 경우에도 동작을 변경하여 MAUSO를 강제 적용할 수 있습니다.




 a| 
[[mauso-9-12-1]] ONTAP 9.12.1
 a| 
를 사용하여 MetroCluster IP 구성에서 MetroCluster 자동 강제 전환 기능을 활성화할 수 있습니다 `metrocluster modify -allow-auto-forced-switchover true` 명령.

MetroCluster 자동 강제 전환 기능을 활성화하면 사이트 장애가 감지되면 자동으로 전환됩니다. 이 기능을 사용하여 MetroCluster IP 자동 전환 기능을 보완할 수 있습니다.

.MetroCluster 자동 강제 적용 시 위험 및 제한 사항
MetroCluster IP 구성이 자동 강제 적용 스위치오버 모드로 작동하도록 할 경우 다음과 같은 알려진 문제로 인해 데이터가 손실될 수 있습니다.

* 스토리지 컨트롤러의 비휘발성 메모리는 파트너 사이트의 원격 DR 파트너로 미러링되지 않습니다.


* 주의 * : 언급되지 않은 시나리오가 발생할 수 있습니다. NetApp은 MetroCluster 자동 강제 전환 기능을 사용하도록 설정하여 발생할 수 있는 데이터 손상, 데이터 손실 또는 기타 손상에 대해 책임지지 않습니다. 위험 및 제한 사항이 수용할 수 없는 경우에는 MetroCluster 자동 강제 전환 기능을 사용하지 마십시오.

|===