---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: 구성에 미러링되지 않은 애그리게이트가 포함된 경우, 전환 작업 후 잠재적 액세스 문제를 알고 있어야 합니다. 
---
= MetroCluster IP 구성에서 미러링되지 않은 집계에 대해 알아보세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성에 미러링되지 않은 애그리게이트가 포함된 경우, 전환 작업 후 잠재적 액세스 문제를 알고 있어야 합니다.



== 미러링되지 않은 집계 및 계층적 네임스페이스

계층적 네임스페이스를 사용하는 경우 해당 경로의 모든 볼륨이 미러링된 애그리게이트에만 있거나 미러링되지 않은 애그리게이트에만 있도록 접합 경로를 구성해야 합니다. 접합 경로에 미러링되지 않은 애그리게이트와 미러링된 애그리게이트를 혼합하여 구성할 경우, 전환 작업 후 미러링되지 않은 애그리게이트에 액세스하지 못할 수 있습니다.



== 전원 차단이 필요한 미러링되지 않은 집계 및 유지 관리

사이트 전체의 전원을 차단해야 하는 유지 관리를 위한 협상된 전환을 수행하는 경우 먼저 재해 사이트가 소유한 미러링되지 않은 집계를 수동으로 오프라인으로 설정해야 합니다.

재해 사이트가 소유한 미러링되지 않은 집계를 오프라인으로 설정하지 않으면, 다중 디스크 패닉으로 인해 정상 운영 사이트의 노드가 다운될 수 있습니다. 이는 정전이나 ISL 손실로 인해 재해 사이트의 스토리지 연결이 끊어져 스위치오버된 미러링되지 않은 집계가 오프라인 상태가 되거나 누락되는 경우에 발생할 수 있습니다.



== 미러링되지 않은 집계, CRS 메타데이터 볼륨 및 데이터 SVM 루트 볼륨

CRS(구성 복제 서비스) 메타데이터 볼륨 및 데이터 SVM 루트 볼륨은 미러링된 Aggregate에 있어야 합니다. 이러한 볼륨을 미러링되지 않은 애그리게이트로 이동할 수 없습니다. 미러링되지 않은 집계에 있는 경우 협상된 전환 및 스위치백 작업은 거부되며  `metrocluster check` 명령은 경고를 반환합니다.



== 미러링되지 않은 집계 및 SVM

SVM은 미러링된 집계에만 구성하거나 미러링되지 않은 집계에만 구성해야 합니다. 미러링되지 않은 집계와 미러링된 집계를 모두 혼합하여 SVM을 구성하면 전환 작업에 120초가 초과될 수 있습니다. 미러링되지 않은 집계가 온라인 상태가 되지 않으면 데이터 중단이 발생할 수 있습니다.



== 미러링되지 않은 집계 및 SAN

ONTAP 9.9.1 이전에는 LUN을 미러링되지 않은 집계에 위치시키면 안 됩니다. 미러링되지 않은 애그리게이트에 LUN을 구성하면 스위치오버 작업이 120초를 초과하고 데이터 중단이 발생할 수 있습니다.



== 거울이 없는 골재에 보관 선반을 추가합니다.

선반을 추가하고 MetroCluster IP 구성에서 미러링되지 않은 집계에 사용하려는 경우 다음을 수행해야 합니다.

. 쉘프 추가 절차를 시작하기 전에 다음 명령을 실행합니다.
+
MetroCluster modify-enable-미러링되지 않은-aggr-deployment true

. 자동 디스크 할당이 꺼져 있는지 확인합니다.
+
'디스크 옵션 표시'입니다

. 다음 절차에 따라 쉘프를 추가합니다.
. 새 쉘프의 모든 디스크를 미러링되지 않은 애그리게이트 또는 애그리게이트를 소유하는 노드에 수동으로 할당합니다.
. Aggregate 생성:
+
'스토리지 애그리게이트 생성'

. 절차를 완료한 후 다음 명령을 실행합니다.
+
'MetroCluster modify-enable-미러링되지 않은-aggr-deployment false'

. 자동 디스크 할당이 설정되었는지 확인합니다.
+
'디스크 옵션 표시'입니다


