---
permalink: install-ip/concept_considerations_tdm_encryption.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: MetroCluster IP 구성에서 멀티플렉싱 장비를 사용할 때 고려해야 할 몇 가지 사항에 대해 알고 있어야 합니다. 
---
= TDM/xWDM 및 MetroCluster IP 구성이 있는 암호화 장비 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 구성에서 멀티플렉싱 장비를 사용할 때 고려해야 할 몇 가지 사항에 대해 알고 있어야 합니다.

이러한 고려 사항은 MetroCluster 백 엔드 직접 링크 및 스위치에만 적용되며, MetroCluster 이외의 트래픽과 공유되는 링크는 해당되지 않습니다.

Hardware Universe 도구는 MetroCluster IP 구성을 사용하기 위해 TDM/xWDM 장비가 충족해야 하는 요구 사항에 대한 몇 가지 참고 사항을 제공합니다.

https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]



== WDM 또는 외부 암호화 장치에서 암호화 사용

MetroCluster IP 구성에서 WDM 장치에서 암호화를 사용하는 경우 환경은 다음 요구 사항을 충족해야 합니다.

* 외부 암호화 장치 또는 DWDM 장비는 해당 스위치를 사용하여 공급업체에서 인증해야 합니다.
+
인증에는 운영 모드(트렁킹 및 암호화 등)가 포함되어야 합니다.

* 암호화를 포함한 전반적인 엔드 투 엔드 지연 및 지터는 IMT 또는 이 문서에 명시된 최대치를 초과할 수 없습니다.




== SFP 고려 사항

장비 공급업체가 지원하는 모든 SFP 또는 QSFP는 MetroCluster ISL에 대해 지원됩니다. SFP 및 QSFP는 NetApp 또는 장비 공급업체에서 구입할 수 있습니다.



== ISL에 대한 고려 사항

하나의 Fabric에 있는 ISL은 모두 속도와 길이가 같아야 합니다.

하나의 Fabric에 있는 ISL은 모두 동일한 토폴로지를 가져야 합니다. 예를 들어, 모든 링크는 직접 링크이거나 WDM을 사용하는 구성에서는 모두 WDM을 사용해야 합니다.

MetroCluster가 아닌 네트워크와 ISL을 공유하는 경우 섹션의 지침을 따라야 합니다 link:concept_considerations_layer_2.html["개인 계층 2 네트워크 공유를 위한 고려 사항"].

패브릭 1과 패브릭 2 간의 최대 지원 거리 차이는 20km입니다
