---
permalink: install-ip/concept_considerations_drive_assignment.html 
sidebar: sidebar 
keywords: drive auto-assignment, drive, adp, advanced disk partitioning, root disk, unmirrored root, data partition, root partition, shelf-by-shelf, AFF A320, AFF A220, AFF A250, AFF A300, AFF A400, AFF A700, AFF A800, FAS2750, FAS8200, FAS500f, FAS9000 
summary: 'ONTAP 9.4부터 MetroCluster IP 구성은 ADP(고급 드라이브 파티셔닝)를 사용하는 AFF 시스템에 새로 설치할 수 있습니다.' 
---
= ONTAP 9.4 이상의 자동 드라이브 할당 및 ADP 시스템에 대한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4부터 MetroCluster IP 구성은 ADP(고급 드라이브 파티셔닝)를 사용하는 AFF 시스템에 새로 설치할 수 있습니다. 대부분의 구성에서는 MetroCluster 사이트의 초기 구성 중에 파티션 분할 및 디스크 할당이 자동으로 수행됩니다.

ONTAP 9.4 이상 릴리스에는 ADP 지원에 대한 다음과 같은 변경 사항이 포함되어 있습니다.

* 풀 0 디스크 할당은 공장에서 수행됩니다.
* 미러링되지 않은 루트는 공장에서 생성됩니다.
* 데이터 파티션 할당은 설치 절차 중에 고객 사이트에서 수행됩니다.
* 대부분의 경우, 드라이브 할당 및 파티셔닝은 설정 절차 중에 자동으로 수행됩니다.



NOTE: ONTAP 9.4에서 9.5로 업그레이드할 때 시스템은 기존 디스크 할당을 인식합니다.



== 자동 파티셔닝

ADP는 플랫폼의 초기 구성 중에 자동으로 수행됩니다.


NOTE: ONTAP 9.5부터 스토리지 디스크 옵션 수정 - 자동 할당 설정 명령으로 디스크 자동 할당을 활성화해야 합니다.

설치 중에 최대 96개의 드라이브를 자동으로 분할할 수 있습니다. 초기 설치 후에 드라이브를 추가할 수 있습니다.



== Shelf-by-Shelf 자동 할당 작동 방식

사이트당 외부 쉘프가 4개인 경우, 다음 예에 표시된 대로 각 쉘프가 서로 다른 노드 및 풀에 할당됩니다.

* site_a-shelf_1의 모든 디스크가 자동으로 node_A_1의 풀 0에 할당됩니다
* site_a-shelf_3의 모든 디스크가 자동으로 node_A_2의 풀 0에 할당됩니다
* site_B-shelf_1의 모든 디스크가 자동으로 node_B_1의 풀 0에 할당됩니다
* site_B-shelf_3의 모든 디스크가 자동으로 node_B_2의 풀 0에 할당됩니다
* site_B-shelf_2의 모든 디스크가 자동으로 node_A_1의 풀 1에 할당됩니다
* site_B-shelf_4의 모든 디스크가 자동으로 node_A_2의 풀 1에 할당됩니다
* site_A-shelf_2의 모든 디스크가 자동으로 node_B_1의 풀 1에 할당됩니다
* site_A-shelf_4의 모든 디스크가 자동으로 node_B_2의 풀 1에 할당됩니다




== 부분적으로 채워진 셸프를 채우는 방법

구성이 완전히 채워지지 않은 쉘프(빈 드라이브 베이 포함)를 사용하는 경우 디스크 할당 정책에 따라 쉘프 전체에 드라이브를 균등하게 배포해야 합니다. 디스크 할당 정책은 각 MetroCluster 사이트에 있는 쉘프 수에 따라 달라집니다.

각 사이트에서 단일 쉘프(또는 AFF A800 시스템의 내부 쉘프)를 사용하는 경우, 디스크는 쿼터 쉘프 정책을 사용하여 할당됩니다. 쉘프가 완전히 채워지지 않은 경우 모든 분기에 동일한 수준으로 드라이브를 설치합니다.

다음 표에서는 48개 드라이브 내부 쉘프에 24개 디스크를 배치하는 방법의 예를 보여 줍니다. 드라이브의 소유자도 표시됩니다.

|===


| 48개 드라이브 베이는 4개의 쿼터로 나뉩니다. | 매 분기마다 처음 6개 베이에 6개의 드라이브를 설치합니다. 


 a| 
쿼터 1: 베이 0-11
 a| 
베이 0-5



 a| 
2분기: 베이 12-23
 a| 
베이 12-17



 a| 
쿼터 3: 베이 24-35
 a| 
베이 24-29



 a| 
4분기: 베이 36-48
 a| 
베이 36-41

|===
각 사이트에서 2개의 쉘프를 사용하는 경우, 하프 쉘프 정책을 사용하여 디스크가 할당됩니다. 쉘프가 완전히 채워지지 않은 경우, 쉘프 양쪽 끝에서 드라이브를 동일하게 설치합니다.

예를 들어, 24개 드라이브 쉘프에 12개의 드라이브를 설치하는 경우 베이 0-5와 18-23에 드라이브를 설치합니다.



== 수동 드라이브 할당(ONTAP 9.5)

ONTAP 9.5에서는 다음과 같은 쉘프 구성을 가진 시스템에서 드라이브를 수동으로 할당해야 합니다.

* 사이트당 외부 쉘프 3개
+
2개의 쉘프가 반쉘프 할당 정책을 사용하여 자동으로 할당되지만, 세 번째 쉘프는 수동으로 할당되어야 합니다.

* 사이트당 4개 이상의 쉘프와 총 외부 쉘프 수는 4개의 배수가 아닙니다.
+
4개 중 가장 가까운 배수로 위의 추가 쉘프가 할당되지 않은 상태로 남아 있으므로 드라이브를 수동으로 할당해야 합니다. 예를 들어, 사이트에 5개의 외부 쉘프가 있는 경우 쉘프 5개를 수동으로 할당해야 합니다.



할당되지 않은 각 쉘프에서는 단일 드라이브만 수동으로 할당해야 합니다. 그러면 쉘프의 나머지 드라이브가 자동으로 할당됩니다.



== 수동 드라이브 할당(ONTAP 9.4)

ONTAP 9.4에서는 다음과 같은 쉘프 구성을 가진 시스템에서 드라이브를 수동으로 할당해야 합니다.

* 사이트당 외부 쉘프 4개 미만
+
드라이브의 대칭적 할당을 위해 드라이브를 수동으로 할당해야 하며 각 풀에는 동일한 수의 드라이브가 있어야 합니다.

* 사이트당 외부 쉘프 4개 이상 및 총 외부 쉘프 수는 4개의 배수되지 않습니다.
+
4개 중 가장 가까운 배수로 위의 추가 쉘프가 할당되지 않은 상태로 남아 있으므로 드라이브를 수동으로 할당해야 합니다.



드라이브를 수동으로 할당할 때는 디스크를 대칭적으로 할당해야 하며 각 풀에 동일한 수의 드라이브를 할당해야 합니다. 예를 들어, 각 사이트에 2개의 스토리지 쉘프가 있는 경우, 로컬 HA 쌍에 대한 쉘프 하나와 원격 HA 쌍에 대한 쉘프 하나를 수행합니다.

* site_a-shelf_1의 디스크 절반을 node_A_1의 풀 0에 할당합니다.
* site_a-shelf_1의 디스크 절반을 node_A_2의 풀 0에 할당합니다.
* site_A-shelf_2의 디스크 절반을 node_B_1의 풀 1에 할당합니다.
* site_A-shelf_2의 디스크 절반을 node_B_2의 풀 1에 할당합니다.
* site_B-shelf_1의 디스크 절반을 node_B_1의 풀 0에 할당합니다.
* site_B-shelf_1의 디스크 절반을 node_B_2의 풀 0에 할당합니다.
* site_B-shelf_2의 디스크 절반을 node_A_1의 풀 1에 할당합니다.
* site_B-shelf_2의 디스크 절반을 node_A_2의 풀 1에 할당합니다.




== 기존 구성에 쉘프 추가

자동 드라이브 할당을 통해 기존 구성에 쉘프를 대칭 추가할 수 있습니다.

새 셸프가 추가되면 새로 추가된 셸프에 동일한 할당 정책이 적용됩니다. 예를 들어, 사이트당 단일 셸프를 사용하는 경우 추가 셸프가 추가되면 시스템은 쿼터 쉘프 할당 규칙을 새 쉘프에 적용합니다.

link:concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html["MetroCluster IP 구성 요소 및 명명 규칙이 필요합니다"]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"^]



== MetroCluster IP 구성의 시스템별 ADP 및 디스크 할당 차이

MetroCluster IP 구성에서 ADP(고급 드라이브 파티셔닝) 및 자동 디스크 할당의 작동은 시스템 모델에 따라 다릅니다.


NOTE: ADP를 사용하는 시스템에서는 각 드라이브가 P1, P2, P3 파티션으로 분할되는 파티션을 사용하여 애그리게이트를 생성합니다. 루트 애그리게이트는 P3 파티션을 사용하여 생성됩니다.

지원되는 최대 드라이브 수 및 기타 지침에 대해서는 MetroCluster 제한을 충족해야 합니다.

https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]



=== AFF A320 시스템의 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
로컬 HA 쌍에서 하나의 쉘프를 사용합니다. 두 번째 쉘프는 원격 HA 쌍에서 사용됩니다.

각 쉘프의 파티션은 루트 애그리게이트를 만드는 데 사용됩니다. 루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 포함되어 있습니다::
+
--
* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션


--




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A220 시스템의 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
내부 드라이브만 해당합니다
 a| 
내부 드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 그룹은 별도의 풀에 자동으로 할당되고 각 풀은 구성의 개별 컨트롤러에 할당됩니다.


NOTE: MetroCluster를 구성하기 전에 내부 드라이브의 절반이 할당 취소된 상태로 남아 있습니다.
 a| 
현지 HA Pair에 2개의 분기가 사용됩니다. 나머지 2개 분기는 원격 HA 쌍에서 사용됩니다.

루트 애그리게이트에는 각 플렉스에 다음 파티션이 포함되어 있습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 16개
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.

쉘프의 두 분기 동안 동일한 풀을 사용할 수 있습니다. 이 풀은 해당 분기의 노드를 기반으로 선택됩니다.

* 로컬 노드가 소유하는 경우 pool0이 사용됩니다.
* 원격 노드가 소유하는 경우 pool1이 사용됩니다.


예를 들어 분기 1분기에서 4분기까지 다음과 같은 과제가 있을 수 있습니다.

* Q1:node_a_1 pool0
* Q2: node_a_2 pool0
* Q3: node_B_1 pool1
* 4분기: node_B_2 pool1



NOTE: MetroCluster를 구성하기 전에 내부 드라이브의 절반이 할당 취소된 상태로 남아 있습니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 하나의 데이터 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A250 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
로컬 HA 쌍에서 하나의 쉘프를 사용합니다. 두 번째 쉘프는 원격 HA 쌍에서 사용됩니다.

각 쉘프의 파티션은 루트 애그리게이트를 만드는 데 사용됩니다. 루트 애그리게이트에는 각 플렉스에 다음 파티션이 포함되어 있습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 24개 전용
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A300 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
로컬 HA 쌍에서 하나의 쉘프를 사용합니다. 두 번째 쉘프는 원격 HA 쌍에서 사용됩니다.

각 쉘프의 파티션은 루트 애그리게이트를 만드는 데 사용됩니다. 루트 애그리게이트에는 각 플렉스에 다음 파티션이 포함되어 있습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A400 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 20개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A700 시스템의 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 20개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A800 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 애그리게이트에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
내부 드라이브 및 96개의 외부 드라이브
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다. 외부 쉘프의 드라이브는 쉘프 단위로 자동으로 할당되며 각 쉘프의 모든 드라이브는 MetroCluster 구성에서 4개 노드 중 하나에 할당됩니다.
 a| 
루트 애그리게이트는 내부 쉘프에서 12개의 루트 파티션으로 생성됩니다.

루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 24개 전용
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다.
 a| 
루트 애그리게이트는 내부 쉘프에서 12개의 루트 파티션으로 생성됩니다.

루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A900 시스템의 ADP 및 디스크 할당

|===


| 지침 | 사이트당 쉘프 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 20개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== FAS2750 시스템에 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
내부 드라이브 24개 및 외부 드라이브 24개
 a| 
내부 및 외부 쉘프는 같은 2개의 반으로 나뉩니다. 각 절반은 자동으로 다른 풀에 할당됩니다
 a| 
해당 없음.

|===


=== FAS8200 시스템의 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음.

|===


=== FAS500f 시스템에서 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
해당 없음.

|===


=== FAS9000 시스템에서 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
해당 없음.



 a| 
최소 지원 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
최소 지원 드라이브 수(사이트당)(액티브/패시브 HA 구성)

|===