---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: ONTAP 중재 서비스는 ONTAP 9.7부터 상태 정보를 위한 물리적으로 분리된 리포지토리를 제공하여 MetroCluster IP 구성을 지원하여 예상치 못한 자동 전환을 수행할 수 있습니다. 
---
= ONTAP 중재자 서비스 설치 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
환경은 다음 요구 사항을 충족해야 합니다.

[NOTE]
====
* Linux 버전을 업데이트할 계획이라면 최신 ONTAP 중재자 서비스를 설치하기 전에 업데이트를 수행하십시오.
* ONTAP 중재자 서비스와 MetroCluster Tiebreaker 소프트웨어를 동일한 MetroCluster 구성과 함께 사용해서는 안 됩니다.
* ONTAP 중재자는 MetroCluster 사이트와 별도의 위치에 있는 Linux 호스트에 설치해야 합니다.
* ONTAP 중재자 서비스는 최대 5개의 MetroCluster 구성을 동시에 지원할 수 있습니다.
* ONTAP 9.7 이상에서는 자동 비계획 전환이 지원됩니다.


====


== MetroCluster 구성에서 중재자를 사용하기 위한 네트워크 요구 사항

MetroCluster 구성에 ONTAP 중재자 서비스를 설치하려면 구성이 여러 네트워크 요구 사항을 충족하는지 확인해야 합니다.

* 지연 시간
+
왕복 지연 시간은 75ms를 초과할 수 없습니다.

+
지터는 25ms 미만이어야 합니다.

* MTU
+
MTU 크기는 1400 이상이어야 합니다.

* 패킷 손실
+
패킷 손실은 0.01% 이하여야 합니다.

* 대역폭
+
중재자 서비스와 MetroCluster 구성 사이의 링크는 20Gbps 이상의 대역폭을 가져야 합니다.





== ONTAP 중재자를 위한 방화벽 요구 사항

ONTAP 중재자가 여러 포트를 사용하여 특정 서비스와 통신합니다.

타사 방화벽을 사용하는 경우:

* HTTPS 액세스를 활성화해야 합니다.
* 포트 31784 및 3260에서 액세스를 허용하도록 구성해야 합니다.
+
기본 Red Hat 또는 CentOS 방화벽을 사용하는 경우, 중재자를 설치하는 동안 방화벽이 자동으로 구성됩니다.



다음 표에는 방화벽에서 허용해야 하는 포트가 나와 있습니다.

|===


| 포트/서비스 | 출처 | 목적지 | 목적 


 a| 
31784/TCP
 a| 
ONTAP 클러스터 관리 인터페이스
 a| 
ONTAP 중재자 웹 서버
 a| 
REST API(HTTPS)



 a| 
3260/TCP
 a| 
ONTAP 클러스터
 a| 
ONTAP는 iSCSI 대상을 중재합니다
 a| 
메일박스에 대한 iSCSI 데이터 접속

|===


== MetroCluster 구성에서 ONTAP 중재자를 업그레이드하기 위한 지침입니다

ONTAP 중재자를 업그레이드하는 경우 Linux 버전 요구 사항을 충족하고 업그레이드 지침을 따라야 합니다.

* 중재자 서비스는 이전 버전에서 현재 버전으로 업그레이드할 수 있습니다.
* 모든 중재자 버전은 ONTAP 9.7 이상을 실행하는 MetroCluster IP 구성에서 지원됩니다.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["ONTAP 중재자 서비스를 설치하거나 업그레이드합니다"^]



== 업그레이드 후

중재자 및 운영 체제 업그레이드가 완료된 후 'storage iscsi-initiator show' 명령을 실행하여 중재자 연결이 작동 중인지 확인해야 합니다.
