---
permalink: install-ip/concept_considerations_peering.html 
sidebar: sidebar 
keywords: considertaions, cluster peering, shared peering ports, dedicated peering ports 
summary: 각 MetroCluster 사이트는 파트너 사이트에 대한 피어로 구성됩니다. 
---
= MetroCluster IP 구성에서 클러스터 피어링에 대한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 MetroCluster 사이트는 파트너 사이트에 대한 피어로 구성됩니다. 피어링 관계를 구성하기 위한 사전 요구 사항과 지침을 숙지해야 합니다. 이러한 관계에 공유 포트 또는 전용 포트를 사용할지 여부를 결정할 때 이 점이 중요합니다.

.관련 정보
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html["클러스터 및 SVM 피어링 Express 구성"]



== 클러스터 피어링을 위한 사전 요구사항

클러스터 피어링을 설정하기 전에 포트, IP 주소, 서브넷, 방화벽 및 클러스터 명명 요구사항이 충족되는지 확인해야 합니다.



=== 연결 요구 사항

로컬 클러스터의 모든 인터클러스터 LIF는 원격 클러스터의 모든 인터클러스터 LIF와 통신할 수 있어야 합니다.

반드시 필요한 것은 아니지만 일반적으로 동일한 서브넷에 있는 인터클러스터 LIF에 사용되는 IP 주소를 구성하는 것이 더 간단합니다. IP 주소는 데이터 LIF와 동일한 서브넷 또는 다른 서브넷에 상주할 수 있습니다. 각 클러스터에 사용되는 서브넷은 다음 요구사항을 충족해야 합니다.

* 서브넷에는 노드당 하나의 인터클러스터 LIF에 할당할 수 있는 충분한 IP 주소가 있어야 합니다.
+
예를 들어, 4노드 클러스터에서 인터클러스터 통신에 사용되는 서브넷에는 사용 가능한 IP 주소 4개가 있어야 합니다.



각 노드에는 인터클러스터 네트워크의 IP 주소를 사용하는 인터클러스터 LIF가 있어야 합니다.

인터클러스터 LIF는 IPv4 주소 또는 IPv6 주소를 가질 수 있습니다.


NOTE: ONTAP 9를 사용하면 두 프로토콜을 모두 인터클러스터 LIF에 동시에 표시할 수 있도록 선택적으로 허용함으로써 피어링 네트워크를 IPv4에서 IPv6로 마이그레이션할 수 있습니다. 이전 릴리즈에서는 전체 클러스터에 대한 모든 인터클러스터 관계가 IPv4 또는 IPv6였습니다. 이는 프로토콜 변경이 잠재적으로 운영 중단이 발생할 수 있음을 의미합니다.



=== 포트 요구 사항

인터클러스터 통신에 전용 포트를 사용하거나 데이터 네트워크에서 사용하는 포트를 공유할 수 있습니다. 포트는 다음 요구 사항을 충족해야 합니다.

* 지정된 원격 클러스터와 통신하는 데 사용되는 모든 포트는 동일한 IPspace에 있어야 합니다.
+
여러 클러스터를 사용하여 다른 IPspace를 사용할 수 있습니다. IPspace 내에서만 쌍방향 전체 메시 연결이 필요합니다.

* 인터클러스터 통신에 사용되는 브로드캐스트 도메인에는 한 포트에서 다른 포트로 인터클러스터 통신이 페일오버할 수 있도록 노드당 두 개 이상의 포트가 포함되어야 합니다.
+
브로드캐스트 도메인에 추가된 포트는 물리적 네트워크 포트, VLAN 또는 인터페이스 그룹(ifgrp)일 수 있습니다.

* 모든 포트는 케이블로 연결되어야 합니다.
* 모든 포트가 정상 상태여야 합니다.
* 포트의 MTU 설정이 일치해야 합니다.




=== 방화벽 요구 사항

방화벽과 인터클러스터 방화벽 정책은 다음 프로토콜을 허용해야 합니다.

* ICMP 서비스
* TCP - 포트 10000, 11104 및 11105를 통해 모든 인터클러스터 LIF의 IP 주소에 연결
* 인터클러스터 LIF 간 양방향 HTTPS


기본 인터클러스터 방화벽 정책을 사용하면 HTTPS 프로토콜을 통해 모든 IP 주소(0.0.0.0/0)에서 액세스할 수 있습니다. 필요한 경우 정책을 수정하거나 대체할 수 있습니다.



== 전용 포트를 사용할 때의 고려 사항

인터클러스터 복제를 위한 전용 포트를 사용하는 것이 올바른 인터클러스터 네트워크 솔루션인지 결정할 때 LAN 유형, 사용 가능한 WAN 대역폭, 복제 간격, 변경률 및 포트 수와 같은 구성 및 요구 사항을 고려해야 합니다.

전용 포트를 사용하는 것이 최상의 인터클러스터 네트워크 솔루션인지 확인하려면 네트워크의 다음 측면을 고려하십시오.

* 사용 가능한 WAN 대역폭 양이 LAN 포트의 대역폭 용량과 비슷하고 복제 간격이 일반 클라이언트 작업이 있는 동안 복제가 수행되도록 하는 경우, 복제와 데이터 프로토콜 간의 경합을 피하기 위해 클러스터 간 복제용 이더넷 포트를 전용으로 할당해야 합니다.
* 데이터 프로토콜(CIFS, NFS, iSCSI)에서 생성된 네트워크 활용률이 50%를 넘는 경우, 노드 페일오버가 발생했을 때 성능 저하가 발생하지 않도록 복제 전용 포트를 사용합니다.
* 데이터 및 복제에 물리적 10GbE 또는 더 빠른 포트를 사용하는 경우 복제에 사용할 VLAN 포트를 생성하고 인터클러스터 복제에 사용할 논리 포트를 전용으로 지정할 수 있습니다.
+
포트의 대역폭은 모든 VLAN과 기본 포트 간에 공유됩니다.

* 데이터 변경률 및 복제 간격과 각 간격에 복제되어야 하는 데이터의 양에 충분한 대역폭이 필요한지 여부를 고려하십시오. 데이터 포트를 공유하는 경우 데이터 프로토콜과 충돌될 수 있습니다.




== 데이터 포트 공유 시 고려 사항

인터클러스터 복제를 위한 데이터 포트를 공유하는 것이 올바른 인터클러스터 네트워크 솔루션인지 결정할 때 LAN 유형, 사용 가능한 WAN 대역폭, 복제 간격, 변경률 및 포트 수와 같은 구성 및 요구 사항을 고려해야 합니다.

데이터 포트 공유가 최상의 인터클러스터 연결 솔루션인지 여부를 확인하려면 네트워크의 다음 측면을 고려하십시오.

* 40기가비트 이더넷(40-GbE) 네트워크와 같은 고속 네트워크의 경우 데이터 액세스에 사용되는 동일한 40GbE 포트에서 복제를 수행할 수 있도록 충분한 양의 로컬 LAN 대역폭을 사용할 수 있습니다.
+
대부분의 경우 사용 가능한 WAN 대역폭은 10GbE LAN 대역폭보다 훨씬 적습니다.

* 클러스터의 모든 노드는 데이터를 복제하고 사용 가능한 WAN 대역폭을 공유해야 하므로 데이터 포트 공유가 더욱 허용됩니다.
* 데이터 및 복제를 위한 공유 포트를 사용하면 복제를 위해 포트를 전용으로 지정하는 데 필요한 추가 포트 수를 없앨 수 있습니다.
* 복제 네트워크의 MTU(Maximum Transmission Unit) 크기는 데이터 네트워크에서 사용되는 크기와 동일합니다.
* 데이터 변경률 및 복제 간격과 각 간격에 복제되어야 하는 데이터의 양에 충분한 대역폭이 필요한지 여부를 고려하십시오. 데이터 포트를 공유하는 경우 데이터 프로토콜과 충돌될 수 있습니다.
* 인터클러스터 복제를 위한 데이터 포트를 공유하는 경우 LIF를 동일한 노드의 다른 인터클러스터 지원 포트로 마이그레이션하여 복제에 사용되는 특정 데이터 포트를 제어할 수 있습니다.

