---
permalink: install-ip/concept_considerations_drive_assignment.html 
sidebar: sidebar 
keywords: drive auto-assignment, drive, adp, advanced disk partitioning, root disk, unmirrored root, data partition, root partition, shelf-by-shelf, AFF A320, AFF A220, AFF A250, C250, AFF A300, AFF A400, C400, AFF A700, AFF A800, FAS2750, FAS8200, FAS500f, FAS9000 
summary: 'ONTAP 9.4부터 MetroCluster IP 구성은 ADP(고급 드라이브 파티셔닝)를 사용하는 AFF 시스템에 새로 설치할 수 있습니다.' 
---
= 자동 드라이브 할당 및 ADP 시스템에 대한 MetroCluster IP 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4부터 MetroCluster IP 구성에서는 자동 디스크 할당 및 ADP(고급 드라이브 파티셔닝)를 사용하여 새로운 설치를 지원합니다.

MetroCluster IP 구성에서 ADP를 사용할 때 다음 사항을 알고 있어야 합니다.

* AFF 및 ASA 시스템에서 ADP를 MetroCluster IP 구성과 함께 사용하려면 ONTAP 9.4 이상이 필요합니다.
* ADPv2는 MetroCluster IP 구성에서 지원됩니다.
* 루트 애그리게이트는 두 사이트의 모든 노드에 대해 파티션 3에 위치해야 합니다.
* 파티셔닝과 디스크 할당은 MetroCluster 사이트의 초기 구성 중에 자동으로 수행됩니다.
* 풀 0 디스크 할당은 공장에서 수행됩니다.
* 미러링되지 않은 루트는 공장에서 생성됩니다.
* 데이터 파티션 할당은 설치 절차 중에 고객 사이트에서 수행됩니다.
* 대부분의 경우, 드라이브 할당 및 파티셔닝은 설정 절차 중에 자동으로 수행됩니다.
* 디스크와 모든 파티션은 동일한 HA(고가용성) 쌍의 노드가 소유해야 합니다. 단일 드라이브 내에서 파티션 또는 드라이브 소유권을 로컬 HA 쌍과 DR(재해 복구) 파트너 또는 DR 보조 파트너 간에 혼합할 수 없습니다.
+
지원되는 구성의 예:

+
|===


| 드라이브/파티션 | 소유자 


| 드라이브: | `ClusterA-Node01` 


| 파티션 1: | `ClusterA-Node01` 


| 파티션 2: | `ClusterA-Node02` 


| 파티션 3: | `ClusterA-Node01` 
|===



NOTE: ONTAP 9.4에서 9.5로 업그레이드할 때 시스템은 기존 디스크 할당을 인식합니다.



== 자동 파티셔닝

ADP는 시스템의 초기 구성 중에 자동으로 수행됩니다.


NOTE: ONTAP 9.5부터 에서 디스크 자동 할당을 활성화해야 합니다 `storage disk option modify -autoassign on` 명령.

ha-config 상태를 로 설정해야 합니다 `mccip` 자동 용량 할당을 수행하기 전에 적절한 루트 볼륨 크기를 허용하도록 올바른 파티션 크기가 선택되었는지 확인합니다. 자세한 내용은 을 참조하십시오 link:task_sw_config_verify_haconfig.html["구성 요소의 ha-config 상태 확인"].

설치 중에 최대 96개의 드라이브를 자동으로 분할할 수 있습니다. 초기 설치 후에 드라이브를 추가할 수 있습니다.

[NOTE]
====
내부 및 외부 드라이브를 사용하는 경우 먼저 ADP를 사용하는 내부 드라이브만으로 MetroCluster를 초기화합니다. 그런 다음 설치 또는 설정 작업을 완료한 후 외부 선반을 수동으로 연결합니다.

에 나와 있는 것처럼 내부 쉘프의 최소 권장 드라이브 수를 사용해야 합니다 <<adp-disk-assign,시스템별 ADP 및 디스크 할당 차이>>.

내부 및 외부 드라이브 모두에 대해 에 설명된 대로 부분적으로 전체 쉘프를 작성해야 합니다 <<populate-partially-full-shelves,부분적으로 채워진 셸프를 채우는 방법>>.

====


== Shelf-by-Shelf 자동 할당 작동 방식

사이트당 외부 쉘프가 4개인 경우, 다음 예에 표시된 대로 각 쉘프가 서로 다른 노드 및 풀에 할당됩니다.

* site_a-shelf_1의 모든 디스크가 자동으로 node_A_1의 풀 0에 할당됩니다
* site_a-shelf_3의 모든 디스크가 자동으로 node_A_2의 풀 0에 할당됩니다
* site_B-shelf_1의 모든 디스크가 자동으로 node_B_1의 풀 0에 할당됩니다
* site_B-shelf_3의 모든 디스크가 자동으로 node_B_2의 풀 0에 할당됩니다
* site_B-shelf_2의 모든 디스크가 자동으로 node_A_1의 풀 1에 할당됩니다
* site_B-shelf_4의 모든 디스크가 자동으로 node_A_2의 풀 1에 할당됩니다
* site_A-shelf_2의 모든 디스크가 자동으로 node_B_1의 풀 1에 할당됩니다
* site_A-shelf_4의 모든 디스크가 자동으로 node_B_2의 풀 1에 할당됩니다




== 부분적으로 채워진 셸프를 채우는 방법

구성이 완전히 채워지지 않은 쉘프(빈 드라이브 베이 포함)를 사용하는 경우 디스크 할당 정책에 따라 쉘프 전체에 드라이브를 균등하게 배포해야 합니다. 디스크 할당 정책은 각 MetroCluster 사이트에 있는 쉘프 수에 따라 달라집니다.

각 사이트에서 단일 쉘프(또는 AFF A800 시스템의 내부 쉘프)를 사용하는 경우, 디스크는 쿼터 쉘프 정책을 사용하여 할당됩니다. 쉘프가 완전히 채워지지 않은 경우 모든 분기에 동일한 수준으로 드라이브를 설치합니다.

다음 표에서는 48개 드라이브 내부 쉘프에 24개 디스크를 배치하는 방법의 예를 보여 줍니다. 드라이브의 소유자도 표시됩니다.

|===


| 48개 드라이브 베이는 4개의 쿼터로 나뉩니다. | 매 분기마다 처음 6개 베이에 6개의 드라이브를 설치합니다. 


 a| 
쿼터 1: 베이 0-11
 a| 
베이 0-5



 a| 
2분기: 베이 12-23
 a| 
베이 12-17



 a| 
쿼터 3: 베이 24-35
 a| 
베이 24-29



 a| 
4분기: 베이 36-47
 a| 
베이 36-41

|===
다음 표는 24개 드라이브 내부 쉘프에 16개의 디스크를 배치하는 방법의 예를 보여줍니다.

|===


| 24개의 드라이브 베이는 4개의 분기로 나뉩니다. | 각 분기의 처음 4개 베이에 4개의 드라이브를 설치합니다. 


 a| 
1분기: 베이 0-5
 a| 
베이 0-3



 a| 
2분기: 베이 6-11
 a| 
베이 6-9



 a| 
분기 3 : 베이 12~17입니다
 a| 
베이 12-15를 참조하십시오



 a| 
4분기: 18번~23번 베이
 a| 
만 18-21입니다

|===
각 사이트에서 2개의 외부 쉘프를 사용하는 경우 1/2 쉘프 정책을 사용하여 디스크가 할당됩니다. 쉘프가 완전히 채워지지 않은 경우, 쉘프 양쪽 끝에서 드라이브를 동일하게 설치합니다.

예를 들어, 24개 드라이브 쉘프에 12개의 드라이브를 설치하는 경우 베이 0-5와 18-23에 드라이브를 설치합니다.



== 수동 드라이브 할당(ONTAP 9.5)

ONTAP 9.5에서는 다음과 같은 쉘프 구성을 가진 시스템에서 드라이브를 수동으로 할당해야 합니다.

* 사이트당 외부 쉘프 3개
+
2개의 쉘프가 반쉘프 할당 정책을 사용하여 자동으로 할당되지만, 세 번째 쉘프는 수동으로 할당되어야 합니다.

* 사이트당 4개 이상의 쉘프와 총 외부 쉘프 수는 4개의 배수가 아닙니다.
+
4개 중 가장 가까운 배수로 위의 추가 쉘프가 할당되지 않은 상태로 남아 있으므로 드라이브를 수동으로 할당해야 합니다. 예를 들어, 사이트에 5개의 외부 쉘프가 있는 경우 쉘프 5개를 수동으로 할당해야 합니다.



할당되지 않은 각 쉘프에서는 단일 드라이브만 수동으로 할당해야 합니다. 그러면 쉘프의 나머지 드라이브가 자동으로 할당됩니다.



== 수동 드라이브 할당(ONTAP 9.4)

ONTAP 9.4에서는 다음과 같은 쉘프 구성을 가진 시스템에서 드라이브를 수동으로 할당해야 합니다.

* 사이트당 외부 쉘프 4개 미만
+
드라이브의 대칭적 할당을 위해 드라이브를 수동으로 할당해야 하며 각 풀에는 동일한 수의 드라이브가 있어야 합니다.

* 사이트당 외부 쉘프 4개 이상 및 총 외부 쉘프 수는 4개의 배수되지 않습니다.
+
4개 중 가장 가까운 배수로 위의 추가 쉘프가 할당되지 않은 상태로 남아 있으므로 드라이브를 수동으로 할당해야 합니다.



드라이브를 수동으로 할당할 때는 디스크를 대칭적으로 할당해야 하며 각 풀에 동일한 수의 드라이브를 할당해야 합니다. 예를 들어, 각 사이트에 2개의 스토리지 쉘프가 있는 경우, 로컬 HA 쌍에 대한 쉘프 하나와 원격 HA 쌍에 대한 쉘프 하나를 수행합니다.

* site_a-shelf_1의 디스크 절반을 node_A_1의 풀 0에 할당합니다.
* site_a-shelf_1의 디스크 절반을 node_A_2의 풀 0에 할당합니다.
* site_A-shelf_2의 디스크 절반을 node_B_1의 풀 1에 할당합니다.
* site_A-shelf_2의 디스크 절반을 node_B_2의 풀 1에 할당합니다.
* site_B-shelf_1의 디스크 절반을 node_B_1의 풀 0에 할당합니다.
* site_B-shelf_1의 디스크 절반을 node_B_2의 풀 0에 할당합니다.
* site_B-shelf_2의 디스크 절반을 node_A_1의 풀 1에 할당합니다.
* site_B-shelf_2의 디스크 절반을 node_A_2의 풀 1에 할당합니다.




== 기존 구성에 쉘프 추가

자동 드라이브 할당을 통해 기존 구성에 쉘프를 대칭 추가할 수 있습니다.

새 셸프가 추가되면 새로 추가된 셸프에 동일한 할당 정책이 적용됩니다. 예를 들어, 사이트당 단일 셸프를 사용하는 경우 추가 셸프가 추가되면 시스템은 쿼터 쉘프 할당 규칙을 새 쉘프에 적용합니다.

.관련 정보
link:concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html["MetroCluster IP 구성 요소 및 명명 규칙이 필요합니다"]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"^]



== MetroCluster IP 구성의 시스템별 ADP 및 디스크 할당 차이

MetroCluster IP 구성에서 ADP(고급 드라이브 파티셔닝) 및 자동 디스크 할당의 작동은 시스템 모델에 따라 다릅니다.


NOTE: ADP를 사용하는 시스템에서는 각 드라이브가 P1, P2, P3 파티션으로 분할되는 파티션을 사용하여 애그리게이트를 생성합니다. 루트 애그리게이트는 P3 파티션을 사용하여 생성됩니다.

표를 사용하기 전에 다음 요구 사항을 검토하세요.

* 지원되는 드라이브의 최대 수와 기타 지침에 대한 MetroCluster 제한을 충족해야 합니다. 를 참조하세요 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"] .
* 외부 디스크 선반을 재사용하는 경우 컨트롤러에 연결하기 전에 외부 디스크 선반의 디스크 소유권이 제거되었는지 확인하세요. 참조하다link:https://docs.netapp.com/us-en/ontap/disks-aggregates/remove-ownership-disk-task.html["디스크에서 ONTAP 소유권 제거"^] .




=== AFF A320 시스템의 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
로컬 HA 쌍에서 하나의 쉘프를 사용합니다. 두 번째 쉘프는 원격 HA 쌍에서 사용됩니다.

각 쉘프의 파티션은 루트 애그리게이트를 만드는 데 사용됩니다. 루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A150, ASA A150 및 AFF A220 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
내부 드라이브만 해당합니다
 a| 
내부 드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 그룹은 별도의 풀에 자동으로 할당되고 각 풀은 구성의 개별 컨트롤러에 할당됩니다.

* 참고: * 내부 드라이브의 절반은 MetroCluster를 구성하기 전에 할당되지 않은 상태로 남아 있습니다.
 a| 
현지 HA Pair에 2개의 분기가 사용됩니다. 나머지 2개 분기는 원격 HA 쌍에서 사용됩니다.

루트 애그리게이트에는 각 플렉스에 다음 파티션이 포함되어 있습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 16개
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.

쉘프의 두 분기 동안 동일한 풀을 사용할 수 있습니다. 이 풀은 해당 분기의 노드를 기반으로 선택됩니다.

* 로컬 노드가 소유하는 경우 pool0이 사용됩니다.
* 원격 노드가 소유하는 경우 pool1이 사용됩니다.


예를 들어 분기 1분기에서 4분기까지 다음과 같은 과제가 있을 수 있습니다.

* Q1:node_a_1 pool0
* Q2: node_a_2 pool0
* Q3: node_B_1 pool1
* 4분기: node_B_2 pool1


* 참고: * 내부 드라이브의 절반은 MetroCluster를 구성하기 전에 할당되지 않은 상태로 남아 있습니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 두 개의 데이터 파티션
* 두 개의 패리티 파티션
* 예비 부품 없음


|===


=== AFF A250, AFF C250, ASA A250, ASA C250, FAS500f, AFF A20, AFF A30 및 AFF C30 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


.2+| 최소 권장 드라이브 수(사이트당)  a| 
48개 드라이브(외부 드라이브만 해당, 내부 드라이브 없음)
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
로컬 HA 쌍에서 하나의 쉘프를 사용합니다. 두 번째 쉘프는 원격 HA 쌍에서 사용됩니다.

각 쉘프의 파티션은 루트 애그리게이트를 만드는 데 사용됩니다. 루트 애그리게이트에는 각 플렉스에 다음 파티션이 포함되어 있습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
48개 드라이브(외부 및 내부 드라이브)
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다. 외부 쉘프의 드라이브는 4개의 동일한 그룹(분기)으로 분류됩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 16개
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 두 개의 데이터 파티션
* 두 개의 패리티 파티션
* 스페어 파티션이 없습니다


|===


=== AFF A50 및 AFF C60 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


.2+| 최소 권장 드라이브 수(사이트당)  a| 
48개 드라이브(외부 드라이브만 해당, 내부 드라이브 없음)
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
로컬 HA 쌍에는 하나의 쉘프가 사용됩니다. 원격 HA 쌍은 두 번째 쉘프를 사용합니다.

각 쉘프의 파티션은 루트 애그리게이트를 만드는 데 사용됩니다. 루트 애그리게이트에는 각 플렉스에 다음 파티션이 포함되어 있습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
48개 드라이브(외부 및 내부 드라이브)
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다. 외부 쉘프의 드라이브는 4개의 동일한 그룹(분기)으로 분류됩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 24개
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 두 개의 데이터 파티션
* 두 개의 패리티 파티션
* 스페어 파티션이 없습니다


|===


=== AFF A300 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
로컬 HA 쌍에서 하나의 쉘프를 사용합니다. 두 번째 쉘프는 원격 HA 쌍에서 사용됩니다.

각 쉘프의 파티션은 루트 애그리게이트를 만드는 데 사용됩니다. 루트 애그리게이트에는 각 플렉스에 다음 파티션이 포함되어 있습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에 있는 두 플렉스의 각각에는 다음 파티션이 있습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF C400, AFF A400, ASA C400 및 ASA A400 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 20개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A700 시스템의 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 20개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF C800, ASA C800, ASA A800, AFF A800 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 애그리게이트에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
내부 드라이브 및 96개의 외부 드라이브
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다. 외부 쉘프의 드라이브는 쉘프 단위로 자동으로 할당되며 각 쉘프의 모든 드라이브는 MetroCluster 구성에서 4개 노드 중 하나에 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션


* 참고: * 루트 애그리게이트는 내부 셸프에 12개의 루트 파티션으로 생성됩니다.



 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 24개
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


* 참고: * 루트 애그리게이트는 내부 셸프에 12개의 루트 파티션으로 생성됩니다.

|===


=== AFF A70, AFF A90 및 AFF C80 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 애그리게이트에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
내부 드라이브 및 96개의 외부 드라이브
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다. 외부 쉘프의 드라이브는 쉘프 단위로 자동으로 할당되며 각 쉘프의 모든 드라이브는 MetroCluster 구성에서 4개 노드 중 하나에 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 8개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
내부 드라이브 24개
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== AFF A900, ASA A900 및 AFF A1K 시스템에서 ADP 및 디스크 할당

|===


| 지침 | 사이트당 쉘프 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 20개의 파티션
* 두 개의 패리티 파티션
* 두 개의 스페어 파티션




 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
루트 애그리게이트에서의 두 플렉스는 각각 다음과 같습니다.

* 데이터를 위한 세 개의 파티션
* 두 개의 패리티 파티션
* 스페어 파티션 1개


|===


=== FAS2750 시스템에 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
내부 드라이브 24개 및 외부 드라이브 24개
 a| 
내부 및 외부 쉘프는 같은 2개의 반으로 나뉩니다. 각 절반은 자동으로 다른 풀에 할당됩니다
 a| 
해당 없음



 a| 
최소 지원 드라이브 수(사이트당)(액티브/패시브 HA 구성)
 a| 
내부 드라이브만 해당합니다
 a| 
수동 할당이 필요합니다
 a| 
해당 없음

|===


=== FAS8200 시스템의 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
48개 드라이브
 a| 
외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음



 a| 
최소 지원 드라이브 수(사이트당)(액티브/패시브 HA 구성)
 a| 
24개 드라이브
 a| 
수동 할당이 필요합니다.
 a| 
해당 없음

|===


=== FAS500f 시스템에서 디스크 할당

AFF C250 및 AFF A250 시스템에 대한 동일한 디스크 할당 지침 및 규칙이 FAS500f 시스템에 적용됩니다. FAS500f 시스템에 디스크를 할당하는 방법은 을 참조하십시오 <<ADP_FAS500f>> 표.



=== FAS9000, FAS9500, FAS70 및 FAS90 시스템에 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


 a| 
최소 권장 드라이브 수(사이트당)
 a| 
96개 드라이브
 a| 
드라이브는 쉘프별로 자동으로 할당됩니다.
 a| 
해당 없음



 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음

|===


=== FAS50 시스템의 디스크 할당

|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


.2+| 최소 권장 드라이브 수(사이트당)  a| 
48개 드라이브(외부 드라이브만 해당, 내부 드라이브 없음)
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음



 a| 
48개 드라이브(외부 및 내부 드라이브)
 a| 
내부 파티션은 4개의 동일한 그룹(분기)으로 나뉩니다. 각 분기는 자동으로 별도의 풀에 할당됩니다. 외부 쉘프의 드라이브는 4개의 동일한 그룹(분기)으로 분류됩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음



 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개 드라이브
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음

|===


=== Flash Cache를 사용하는 FAS50 시스템의 디스크 할당

ONTAP 9.18.1부터 Flash Cache는 MetroCluster IP 구성을 위한 FAS50 시스템에서 지원됩니다.

[CAUTION]
====
* 내부 선반에 Flash Cache 드라이브가 있는 경우 데이터 집계와 루트 집계를 모두 가질 수 없습니다.
* 슬롯 0과 23은 플래시 캐시 드라이브에 사용됩니다.
* 외부 디스크 선반을 재사용하는 경우 컨트롤러에 연결하기 전에 외부 디스크 선반의 디스크 소유권이 제거되었는지 확인하세요. 참조하다link:https://docs.netapp.com/us-en/ontap/disks-aggregates/remove-ownership-disk-task.html["디스크에서 ONTAP 소유권 제거"] .


====
|===


| 지침 | 사이트당 드라이브 수 | 드라이브 할당 규칙 | 루트 파티션에 대한 ADP 레이아웃입니다 


.2+| 최소 권장 드라이브 수(사이트당)  a| 
48개 드라이브(외부 드라이브만 해당, 내부 드라이브 없음)
 a| 
각 외부 쉘프의 드라이브는 두 개의 동일한 그룹(절반)으로 나뉩니다. 각 반쪽 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음



 a| 
36개 드라이브(12개 내부 드라이브 및 24개 외부 드라이브 - 외부 셸프에 데이터 집계, 내부 셸프에 루트 집계)
 a| 
내부 드라이브는 4개의 동일한 그룹(4분의 1)으로 나뉩니다.  각 분기는 자동으로 별도의 풀에 할당됩니다.  외부 선반의 드라이브는 4개의 동일한 그룹(4분의 1)으로 나뉩니다.  각 4분의 1 선반은 자동으로 별도의 풀에 할당됩니다.

*참고사항:*

* 내부 및 외부 드라이브를 사용하는 경우 먼저 ONTAP 설치하고 내부 드라이브만으로 로컬 클러스터를 구성해야 합니다.  설치나 설정 작업을 완료한 후 외부 선반을 수동으로 연결합니다.
* 루트 집계에는 최소 12개의 내부 드라이브가 필요합니다.  슬롯 1에 루트 내부 드라이브를 배치해야 합니다.  예를 들어, 내부 드라이브가 12개인 경우 슬롯 1-3, 6-8, 12-14, 18-20을 사용합니다.

 a| 
해당 없음



 a| 
최소 지원 드라이브 수(사이트당)
 a| 
24개의 외부 드라이브
 a| 
드라이브는 4개의 동일한 그룹으로 나뉩니다. 각 분기 쉘프는 별도의 풀에 자동으로 할당됩니다.
 a| 
해당 없음

|===