---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: ONTAP 중재 서비스는 ONTAP 9.7부터 상태 정보를 위한 물리적으로 분리된 리포지토리를 제공하여 MetroCluster IP 구성을 지원하여 예상치 못한 자동 전환을 수행할 수 있습니다. 
---
= ONTAP 중재자 서비스 설치 준비
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재 서비스는 ONTAP 9.7부터 상태 정보를 위한 물리적으로 분리된 리포지토리를 제공하여 MetroCluster IP 구성을 지원하여 예상치 못한 자동 전환을 수행할 수 있습니다. 환경은 다음 요구 사항을 충족해야 합니다. Linux 버전을 업데이트해야 할 수 있습니다.

[NOTE]
====
* ONTAP 중재자 서비스와 MetroCluster Tiebreaker 소프트웨어를 동일한 MetroCluster 구성과 함께 사용해서는 안 됩니다.
* ONTAP 중재자는 MetroCluster 사이트와 별도의 위치에 있는 Linux 호스트에 설치해야 합니다.
* ONTAP 중재자 서비스는 최대 5개의 MetroCluster 구성을 동시에 지원할 수 있습니다.
* ONTAP 9.7 이상에서는 자동 비계획 전환이 지원됩니다.


====


== MetroCluster 구성에서 중재자를 사용하기 위한 네트워크 요구 사항

MetroCluster 구성에 ONTAP 중재자 서비스를 설치하려면 구성이 여러 네트워크 요구 사항을 충족하는지 확인해야 합니다.

* 왕복 지연 시간
+
왕복 지연 시간은 25ms 미만이어야 합니다.

* MTU
+
MTU 크기는 1400 이상이어야 합니다.

* 패킷 손실
+
패킷 손실은 0.01% 이하여야 합니다.

* 대역폭
+
중재자 서비스와 MetroCluster 구성 사이의 링크는 최소 1Gbps의 대역폭을 가져야 합니다.





== ONTAP 중재자를 위한 방화벽 요구 사항

ONTAP 중재자가 여러 포트를 사용하여 특정 서비스와 통신합니다.

* 타사 방화벽을 사용하는 경우:
+
** HTTPS 액세스를 활성화해야 합니다.
** 포트 31784 및 3260에서 액세스를 허용하도록 구성해야 합니다.
+
기본 Red Hat 또는 CentOS 방화벽을 사용하는 경우, 중재자를 설치하는 동안 방화벽이 자동으로 구성됩니다.





다음 표에는 방화벽에서 허용해야 하는 포트가 나와 있습니다.

|===


| 포트/서비스 | 출처 | 목적지 | 목적 


 a| 
31784/TCP
 a| 
ONTAP 클러스터 관리 인터페이스
 a| 
ONTAP 중재자 웹 서버
 a| 
REST API(HTTPS)



 a| 
3260/TCP
 a| 
ONTAP 클러스터
 a| 
ONTAP는 iSCSI 대상을 중재합니다
 a| 
메일박스에 대한 iSCSI 데이터 접속

|===


== MetroCluster 구성에서 ONTAP 중재자를 업그레이드하기 위한 지침입니다

ONTAP 중재자를 업그레이드하는 경우 Linux 버전 요구 사항을 충족하고 업그레이드 지침을 따라야 합니다.

* 중재자 서비스는 버전 1.0에서 1.1로 업그레이드할 수 있습니다.
* 모든 중재자 버전은 ONTAP 9.7 이상을 실행하는 MetroCluster IP 구성에서 지원됩니다.




== 호스트 운영 체제와 중재자를 함께 업그레이드

다음 표에는 중재자 버전을 업그레이드할 뿐 아니라 RHEL/CentOS 7.6에서 최신 RHEL/CentOS 릴리즈로 업그레이드하는 경우의 업그레이드 지침이 나와 있습니다.

[cols="20,20,60"]
|===


| 대상 Linux 버전 | 대상 중재자 버전 | 노트 업그레이드 


 a| 
RHEL/CentOS 7.7
 a| 
1.1
 a| 
* 업그레이드는 다음과 같은 순서로 수행해야 합니다.
+
.. RHEL/CentOS 버전 7.6에서 7.7로 운영 체제를 업그레이드합니다.
+
* 참고 *: 운영 체제 업그레이드 중에는 ONTAP 중재자 및 중재자 지원 자동 비계획 전환을 사용할 수 없습니다. 중재자가 버전 1.0 - 1.1의 업그레이드 프로세스를 완료할 때까지 오프라인 상태입니다.

.. 호스트를 재부팅하여 커널 모듈 변경 사항을 적용합니다.
.. 중재자를 버전 1.0에서 1.1로 업그레이드합니다.
+
link:task_install_configure_mediator.html["ONTAP 중재자 서비스 설치 또는 업그레이드"]



* storage iscsi-initiator show 명령은 업그레이드 중에 중재자 서비스에 대한 연결이 중단된다는 것을 보고합니다.
* ONTAP 운영 체제는 업그레이드 중에 cf.mccip.med.auso.stDisabled EMS 이벤트를 생성합니다.
* ONTAP 운영 체제는 예기치 않은 자동 전환이 다시 활성화될 때 cf.mccip.med.auso.stEnabled EMS 이벤트를 생성합니다.




 a| 
RHEL/CentOS 8.0 또는 8.1
 a| 
1.1
 a| 
직접 업그레이드 경로가 없습니다. 운영 체제를 업그레이드한 후 1.0 버전을 제거하고 1.1 버전을 설치해야 합니다.

. ONTAP 구성에서 중재자 서비스를 삭제합니다.
+
'MetroCluster configuration-settings 중재자 제거

. 중재자 서비스의 1.0 버전을 제거합니다.
+
link:../install-ip/task_uninstall_mediator.html["ONTAP 중재자 서비스 제거"]

. Linux 운영 체제를 버전 8.0 또는 8.1로 업그레이드합니다.
. 중재 서비스의 1.1 버전을 설치합니다.
+
link:task_uninstall_mediator.html["ONTAP 중재자 서비스 설치 또는 업그레이드"]

. ONTAP 구성에 중재자 서비스를 추가합니다.
+
'MetroCluster configuration-settings add-imator-address-1.1-ip-address'



|===


== 업그레이드 후

중재자 및 운영 체제 업그레이드가 완료된 후 'storage iscsi-initiator show' 명령을 실행하여 중재자 연결이 작동 중인지 확인해야 합니다.



== 중재자 1.1 설치에서 되돌리기

중재자 버전 1.1에서 1.0으로 직접 되돌릴 수 없습니다. 1.1 버전을 제거하고 1.0 버전을 다시 설치해야 합니다.

. ONTAP 구성에서 중재자 서비스를 삭제합니다.
+
'MetroCluster configuration-settings 중재자 제거

. 중재 서비스의 1.1 버전을 제거합니다.
+
link:../install-ip/task_uninstall_mediator.html["ONTAP 중재자 서비스 제거"]

. 중재자 서비스의 1.0 버전을 설치합니다.
+
link:task_install_configure_mediator.html["ONTAP 중재자 서비스 설치 또는 업그레이드"]

. ONTAP 구성에 중재자 서비스를 추가합니다.
+
'MetroCluster configuration-settings add-중재자-address-1.0-ip-address'





== Linux 커널 업그레이드 복구

ONTAP 중재자를 사용하려면 SCST 커널 모듈이 필요합니다. Linux 커널이 업데이트되면 이 종속 관계가 서비스 손실로 이어질 수 있습니다. 커널 패키지가 변경될 경우 SCST 커널 모듈을 재구축하는 것이 좋습니다.

[NOTE]
====
* ONTAP 중재자 버전 1.0에서 1.1로 업그레이드하면 SCST 모듈이 재생성됩니다.
* 커널 모듈 변경 사항은 Linux 커널이 재부팅된 후에 적용됩니다.


====
다음 절차 중 하나를 사용하여 중재자의 서비스 손실을 초래한 커널 업그레이드를 복구할 수 있습니다.

[cols="30,70"]
|===


| 절차를 참조하십시오 | 단계 


 a| 
SCST 커널 모듈을 제거하고 다시 설치합니다
 a| 
중재자 버전에 사용되는 SCST tar 번들이 있어야 합니다.

* ONTAP 중재자 1.0은 scst-3.3.0.tar.bz2가 필요합니다
* ONTAP 중재자 1.1에는 scst-3.4.0.tar.bz2가 필요합니다
+
.. SCST 모듈을 제거합니다.
+
... 중재자 버전에 필요한 SCST tar 번들을 다운로드하고 압축을 풉니다.
... scst 디렉토리 내에서 다음 명령을 실행합니다.
+
[listing]
----
systemctl stop mediator-scst
make scstadm_uninstall
make iscsi_uninstall
make usr_uninstall
make scst_uninstall
depmod
----


.. scst 디렉토리 내부에서 다음 명령을 실행하여 중재자 버전의 SCST 모듈을 다시 설치합니다.
+
[listing]
----
make scst_install
make usr_install
make iscsi_install
make scstadm_install
depmod
patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch
reboot
----






 a| 
ONTAP 중재자를 제거하고 다시 설치합니다

참고:** ONTAP에서 중재자를 다시 구성해야 합니다.
 a| 
. ONTAP 구성에서 중재자 서비스를 삭제합니다.
+
'MetroCluster configuration-settings 중재자 제거

. link:../install-ip/task_uninstall_mediator.html["ONTAP 중재자 서비스를 제거합니다"].
. link:../install-ip/task_install__configure_mediator.html["중재자 서비스를 다시 설치합니다"].
. ONTAP 구성에 중재자 서비스를 추가합니다.
+
'MetroCluster configuration-settings add-중재자-address-ip-address'



|===