---
permalink: install-ip/concept-requirements-isls.html 
sidebar: sidebar 
keywords: isl, isls, layer 2, layer 3, shared switch 
summary: '이 섹션에서는 모든 MetroCluster IP 구성 및 네트워크 토폴로지에서 MetroCluster 트래픽을 전달하는 ISL(Inter-Switch Link)에 대한 요구 사항을 다룹니다.' 
---
= ISL에 대한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


모든 MetroCluster IP 구성과 네트워크 토폴로지에서 MetroCluster 트래픽을 전달하는 ISL(Inter-Switch Link)에는 특정 요구 사항이 있습니다. 이러한 요구 사항은 고객 스위치 간에 ISL이 직접 또는 공유되는지 여부에 관계없이 MetroCluster 트래픽을 전달하는 모든 ISL에 적용됩니다.



== 일반 MetroCluster ISL 요구사항

다음은 모든 MetroCluster IP 구성의 ISL에 적용됩니다.

* 두 Fabric의 ISL 수는 동일해야 합니다.
* 하나의 Fabric에 있는 ISL은 모두 속도와 길이가 같아야 합니다.
* 두 패브릭의 ISL은 속도와 길이가 같아야 합니다.
* 패브릭 1과 패브릭 2 간의 최대 지원 거리 차이는 20km 또는 0.2ms입니다.
* 한 Fabric의 ISL은 동일한 토폴로지를 가져야 합니다. 예를 들어, 모두 직접 링크여야 하거나 구성에서 WDM을 사용하는 경우 모두 WDM을 사용해야 합니다.
* ISL 속도는 10Gbps 이상이어야 합니다.
* Fabric당 10Gbps ISL 포트가 하나 이상 있어야 합니다.




=== ISL의 지연 시간 및 패킷 손실 제한

다음은 site_A와 site_B에서 MetroCluster IP 스위치 간의 왕복 트래픽에 적용되며, MetroCluster 구성이 정상 작동 중입니다.

* 두 MetroCluster 사이트 간의 거리가 증가하면 지연 시간이 증가하며, 일반적으로 100km(62마일)당 1ms의 왕복 지연 시간이 증가합니다. 지연 시간은 또한 ISL 링크의 대역폭, 패킷 드롭 속도 및 네트워크의 지터 측면에서 네트워크 SLA(Service Level Agreement)에 따라 달라집니다. 낮은 대역폭, 높은 지터 및 임의 패킷 손실은 성공적인 패킷 전달을 위해 스위치에 의한 다른 복구 메커니즘 또는 컨트롤러 모듈의 TCP 엔진으로 이어집니다. 이러한 복구 메커니즘은 전반적인 대기 시간을 늘릴 수 있습니다. 라운드 트립 지연 시간 및 구성에 대한 최대 거리 요구 사항에 대한 자세한 내용은 을 참조하십시오 link:https://hwu.netapp.com/["Hardware Universe를 참조하십시오."^]
* 대기 시간에 영향을 주는 모든 장치를 고려해야 합니다.
* 를 클릭합니다 link:https://hwu.netapp.com/["Hardware Universe를 참조하십시오."^] 거리(km)를 제공합니다 100km당 1ms를 할당해야 합니다. 최대 거리는 가장 먼저 도달한 거리, 최대 왕복 시간(RTT)(ms) 또는 거리(km)에 의해 정의됩니다 예를 들어, _The Hardware Universe_가 300km의 거리를 나열하고 3ms로 변환하면 ISL은 300km를 넘을 수 없으며 최대 RTT는 3ms(둘 중 먼저 도달하는 시간)를 초과할 수 없습니다.
* 패킷 손실은 0.01% 이하여야 합니다. 최대 패킷 손실은 MetroCluster 노드 사이의 경로에 있는 모든 링크의 모든 손실과 로컬 MetroCluster IP 인터페이스의 손실을 합한 것입니다.
* 지원되는 지터 값은 왕복 3ms(단방향: 1.5ms)입니다.
* 네트워크는 트래픽의 마이크로버스트와 급증에 관계없이 MetroCluster 트래픽에 필요한 SLA 대역폭을 할당하고 유지해야 합니다.
* ONTAP 9.7 이상을 사용하는 경우 두 사이트 간의 중간 네트워크는 MetroCluster IP 구성을 위해 최소 4.5Gbps의 대역폭을 제공해야 합니다.




== 트랜시버 및 케이블 고려 사항

장비 공급업체가 지원하는 모든 SFP 또는 QSFP는 MetroCluster ISL에 대해 지원됩니다. NetApp 또는 장비 공급업체에서 제공하는 SFP 및 QSFP는 스위치 및 스위치 펌웨어에서 지원해야 합니다.

컨트롤러를 스위치 및 로컬 클러스터 ISL에 연결할 때는 NetApp에서 제공하는 트랜시버 및 케이블을 MetroCluster와 함께 사용해야 합니다.



== xWDM, TDM 및 외부 암호화 장치 사용

MetroCluster IP 구성에서 xWDM/TDM 장치 또는 암호화를 제공하는 장치를 사용하는 경우 사용자 환경은 다음 요구 사항을 충족해야 합니다.

* MetroCluster IP 스위치를 xWDM/TDM에 연결할 때 외부 암호화 장치 또는 xWDM/TDM 장비는 해당 스위치 및 펌웨어에 대한 공급업체의 인증을 받아야 합니다. 인증서는 작동 모드(트렁킹 및 암호화 등)를 포괄해야 합니다.
* 암호화를 포함한 전반적인 엔드 투 엔드 지연 시간 및 지터는 IMT 및 이 설명서에 명시된 최대 크기보다 클 수 없습니다.




== 지원되는 ISL 및 브레이크아웃 케이블 수

다음 표에서는 RCF(Reference Configuration File) 구성을 사용하여 MetroCluster IP 스위치에서 구성할 수 있는 지원되는 최대 ISL 수를 보여 줍니다.

|===


| MetroCluster IP 스위치 모델 | 포트 유형입니다 | 최대 ISL 수입니다 


 a| 
Broadcom 지원 BES-53248 스위치
 a| 
네이티브 포트
 a| 
10Gbps 또는 25Gbps를 사용하는 4 ISL



 a| 
Broadcom 지원 BES-53248 스위치
 a| 
기본 포트(참고 1)
 a| 
40Gbps 또는 100Gbps를 사용하는 2 ISL



 a| 
Cisco 3132Q-V
 a| 
네이티브 포트
 a| 
40Gbps를 사용하는 ISL 6개



 a| 
Cisco 3132Q-V
 a| 
브레이크아웃 케이블
 a| 
10Gbps를 사용하는 16개의 ISL



 a| 
Cisco 3232C
 a| 
네이티브 포트
 a| 
40Gbps 또는 100Gbps를 사용하는 6 ISL



 a| 
Cisco 3232C
 a| 
브레이크아웃 케이블
 a| 
10Gbps를 사용하는 16개의 ISL



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결 안 됨)
 a| 
네이티브 포트
 a| 
40Gbps 또는 100Gbps를 사용하는 6 ISL



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결 안 됨)
 a| 
브레이크아웃 케이블
 a| 
10을 사용하는 16개의 ISL



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결)
 a| 
기본 포트(참고 2)
 a| 
40Gbps 또는 100Gbps를 사용하는 4 ISL



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결)
 a| 
브레이크아웃 케이블(참고 2)
 a| 
10Gbps를 사용하는 16개의 ISL



 a| 
nVidia SN2100
 a| 
기본 포트(참고 2)
 a| 
40Gbps 또는 100Gbps를 사용하는 2 ISL



 a| 
nVidia SN2100
 a| 
브레이크아웃 케이블(참고 2)
 a| 
10Gbps 또는 25Gbps를 사용하는 8 ISL

|===
*참고 1*: BES-53248 스위치에서 40Gbps 또는 100Gbps ISL을 사용하려면 추가 라이센스가 필요합니다.

* 참고 2 * : 기본 속도 및 브레이크아웃 모드에 동일한 포트가 사용됩니다. RCF 파일을 만들 때 기본 속도 모드 또는 브레이크아웃 모드에서 포트를 사용하도록 선택해야 합니다.

* 하나의 MetroCluster IP 스위치에 있는 모든 ISL은 동일한 속도여야 합니다. 속도가 다른 ISL 포트를 동시에 사용하는 것은 지원되지 않습니다.
* 최적의 성능을 얻으려면 네트워크당 최소 1개의 40Gbps ISL을 사용해야 합니다. FAS9000, AFF A700 또는 기타 대용량 플랫폼에 네트워크당 단일 10Gbps ISL을 사용하면 안 됩니다.



NOTE: NetApp에서는 낮은 대역폭 ISL의 수가 많은 것보다 적은 수의 높은 대역폭 ISL을 구성하는 것이 좋습니다. 예를 들어 4개의 10Gbps ISL 대신 1개의 40Gbps ISL을 구성하는 것이 좋습니다. 여러 ISL을 사용할 경우 통계 로드 밸런싱이 최대 처리량에 영향을 줄 수 있습니다. 불균일한 밸런싱은 단일 ISL의 처리량을 감소시킬 수 있습니다.
