---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: 다양한 MetroCluster 구성에 필요한 구성 요소의 주요 차이점이 있습니다. 
---
= ONTAP 중재자와 MetroCluster Tiebreaker의 차이점
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7부터 MetroCluster IP 구성에서 ONTAP MUSO(중재자 지원 자동 예상치 못한 전환)를 사용하거나 MetroCluster Tiebreaker 소프트웨어를 사용할 수 있습니다. MAUSO 또는 tiebreaker 소프트웨어를 반드시 사용해야 하는 것은 아니지만, 이러한 서비스를 사용하지 않을 경우에는 반드시 사용해야 합니다 link:../disaster-recovery/concept_dr_workflow.html["수동 복구를 수행합니다"] 재해가 발생한 경우

MetroCluster 구성마다 다른 상황에서 자동 전환이 수행됩니다.

* * MetroCluster IP 구성에 없는 AUSO 기능을 사용하는 MetroCluster FC 구성 *
+
이러한 구성에서 AUSO는 컨트롤러에 장애가 발생했지만 스토리지(및 브리지(있는 경우)가 작동 중인 경우 시작됩니다.

* *ONTAP Mediator(ONTAP 9.7 이상)를 사용한 MetroCluster IP 구성*
+
이러한 구성에서 MAUSO는 위에서 설명한 AUSO와 동일한 상황에서 그리고 전체 사이트 장애(컨트롤러, 스토리지 및 스위치)가 발생한 후에 시작됩니다.

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP 중재자가 예기치 않은 자동 전환을 지원하는 방법에 대해 알아보십시오"].

* * 활성 모드에서 Tiebreaker 소프트웨어를 사용하는 MetroCluster IP 또는 FC 구성 *
+
이러한 구성에서 Tiebreaker는 전체 사이트 장애 후 계획되지 않은 전환을 시작합니다.

+
Tiebreaker 소프트웨어를 사용하기 전에 을 검토하십시오 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker 소프트웨어 설치 및 구성"]





== 다른 애플리케이션 및 어플라이언스와 함께 하는 ONTAP 중재자의 상호 운용성

ONTAP 중재자와 함께 전환을 트리거할 수 있는 타사 애플리케이션이나 어플라이언스를 사용할 수 없습니다. 또한 ONTAP 중재자를 사용할 때는 MetroCluster Tiebreaker 소프트웨어를 사용하여 MetroCluster 구성을 모니터링하는 기능이 지원되지 않습니다.
