---
permalink: install-ip/concept_considerations_isls.html 
sidebar: sidebar 
keywords: isl, isls, layer 2, layer 3, shared switch 
summary: 구성에 대한 ISL 요구 사항을 알아야 합니다. 
---
= ISL에 대한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


구성에 대한 ISL 요구 사항을 알아야 합니다.



== 기본 MetroCluster ISL 요구 사항

모든 MetroCluster IP 구성에서 ISL에 대해 다음 요구 사항을 충족해야 합니다.

* 네이티브 속도 ISL 스위치 포트는 네이티브 속도 ISL 스위치 포트에 연결해야 합니다.
+
예를 들어, 40Gbps 포트는 40Gbps 포트에 연결됩니다.

* 기본 모드(즉, 브레이크아웃 케이블을 사용하지 않음)에 있는 10Gbps 포트는 기본 모드에 있는 10Gbps 포트에 연결할 수 있습니다.
* MetroCluster IP 스위치와 고객 네트워크 간의 ISL 및 중간 스위치 간의 ISL은 속도 측면에서 동일한 규칙을 따릅니다.
* MetroCluster 스위치와 고객 네트워크 스위치 사이에 있는 ISL 수와 고객 네트워크 스위치 사이에 있는 ISL 수는 일치시킬 필요가 없습니다.
+
예를 들어, MetroCluster 스위치는 두 ISL을 사용하여 중간 스위치에 연결할 수 있고 중간 스위치는 10 ISL을 사용하여 서로 연결할 수 있습니다.

* MetroCluster 스위치와 고객 네트워크 스위치 사이에 있는 ISL의 속도와 고객 네트워크 스위치 사이에 있는 ISL의 속도는 일치하지 않아도 됩니다.
+
예를 들어, MetroCluster 스위치는 40Gbps ISL을 사용하여 중간 스위치에 연결할 수 있고 중간 스위치는 100Gbps ISL을 사용하여 서로 연결할 수 있습니다.

* 각 MetroCluster 스위치를 중간 스위치에 연결하는 ISL의 수와 속도는 두 MetroCluster 사이트 모두에서 동일해야 합니다.




== 공유 계층 2 네트워크의 ISL 요구 사항

시기 link:../install-ip/concept_considerations_layer_2.html["공유 네트워크에서 ISL 트래픽 공유"]ISL의 용량과 크기가 적절한지 확인해야 합니다. MetroCluster 사이트 간 데이터 복제에는 짧은 지연 시간이 매우 중요합니다. 이러한 연결에서 지연 문제가 클라이언트 입출력에 영향을 줄 수 있습니다

이러한 섹션을 검토하여 ISL의 필요한 종단 간 용량을 정확하게 계산해야 합니다. MetroCluster 구성에서 지연 시간이 짧은 연속 비휘발성 캐시 및 스토리지 복제가 매우 중요합니다. 백엔드 네트워크의 지연 시간은 클라이언트 IO에서 확인되는 지연 시간 및 처리량에 영향을 줍니다.



=== ISL의 지연 시간 및 패킷 손실 제한

사이트_A의 MetroCluster IP 스위치와 사이트_B 간의 라운드 트립 트래픽에 대해 다음 요구 사항을 충족해야 하며, MetroCluster 구성이 안정적 상태 작업이어야 합니다.

* 왕복 지연 시간은 7ms보다 작거나 같아야 합니다.
+
최대 거리는 700km이므로 사이트 간 거리는 지연 시간 또는 최대 거리 중 먼저 도달하는 값에 의해 제한됩니다.

+
두 MetroCluster 사이트 간의 거리가 증가하면 지연 시간이 증가하며, 일반적으로 100km(62마일)당 1ms의 왕복 지연 시간이 증가합니다. 또한 이 지연 시간은 네트워크의 ISL 링크 대역폭, 패킷 손실률 및 지터 측면에서 네트워크 서비스 수준 계약(SLA)에 따라 달라집니다. 낮은 대역폭, 높은 지터 및 랜덤 패킷 드롭은 성공적인 패킷 전송을 위해 컨트롤러 모듈의 스위치 또는 TCP 엔진에 의해 서로 다른 복구 메커니즘으로 이어집니다. 이러한 복구 메커니즘은 전반적인 대기 시간을 늘릴 수 있습니다.

+
대기 시간에 영향을 주는 모든 장치를 고려해야 합니다.

* 패킷 손실은 0.01% 이하여야 합니다.
+
패킷 손실에는 혼잡 또는 초과 가입으로 인한 물리적 손실 또는 손실이 포함됩니다.

+
패킷 드롭은 재전송을 유발하고 정체 기간을 줄일 수 있습니다.

* 지원되는 지터 값은 왕복 3ms입니다(또는 단방향: 1.5ms).
* 네트워크는 MetroCluster 트래픽에 필요한 대역폭에 대한 SLA를 할당 및 유지해야 하며, 이는 트래픽의 마이크로버스트 및 급증에 대한 것입니다.
+
대역폭이 낮으면 대기 지연 및 스위치에서 테일 드롭이 발생할 수 있습니다. ONTAP 9.7 이상을 사용하는 경우 두 사이트 간의 네트워크 중간은 MetroCluster 구성에 대해 최소 4.5Gbps의 대역폭을 제공해야 합니다.

* MetroCluster 트래픽은 전체 대역폭을 소비해서는 안 되며 MetroCluster 외 트래픽에 부정적인 영향을 미칩니다.
* 공유 네트워크에는 ISL의 사용률, 오류(손실, 링크 플랩, 손상 등) 및 장애를 모니터링하도록 구성된 네트워크 모니터링이 있어야 합니다.




=== 고객 스위치의 연결 제한 및 트렁킹

고객이 제공한 중간 스위치는 다음 요구 사항을 충족해야 합니다.

* 중간 스위치 수는 제한되지 않으며 MetroCluster IP 스위치 간에 2개 이상의 스위치가 지원됩니다.
+
MetroCluster IP 스위치는 장거리 링크를 제공하는 중간 스위치에 최대한 가까이 위치해야 합니다. 경로를 따라 있는 모든 ISL 연결은 MetroCluster ISL의 모든 요구 사항을 충족해야 합니다.

* 고객 네트워크의 ISL(고객 스위치 간 ISL)은 충분한 대역폭이 제공되고 전송 순서가 유지되도록 구성해야 합니다.
+
이 작업은 트렁킹에서 충분한 수의 링크를 사용하고 로드 밸런싱 정책을 적용하여 순서를 유지할 수 있습니다.





=== 기타 네트워크 요구 사항

고객이 제공한 중간 스위치는 다음 요구 사항을 충족해야 합니다.

* 고객 네트워크는 RCF 파일에 설정된 MetroCluster VLAN과 일치하는 사이트 간에 동일한 VLAN을 제공해야 합니다.
+
MetroCluster VLAN ID와 일치하는 ID가 있는 계층 2 VLAN은 공유 네트워크를 포괄해야 합니다.

+
** ONTAP 9.7 및 이전 버전에서는 FAS2750 및 AFF A220 시스템에 VLAN 10 및 20이 필요합니다.
** ONTAP 9.8 이상, FAS2750, AFF A220, FAS500f, AFF A250 FAS8300, AFF A400 및 FAS8700 시스템은 기본적으로 VLAN 10 및 20을 사용합니다. 인터페이스 생성 중에 다른 VLAN을 구성할 수 있으며 101-4096 범위를 유지해야 합니다. 앞서 언급한 모든 플랫폼의 경우 인터페이스를 생성하는 동안에만 VLAN을 지정할 수 있습니다. MetroCluster 인터페이스가 생성되면 VLAN ID를 변경할 수 없습니다. 앞서 언급하지 않은 다른 모든 플랫폼에서는 VLAN을 사용할 수 있으며 언제든지 해당 플랫폼의 VLAN ID를 변경할 수 있지만, 새로운 RCF 파일을 생성 및 적용해야 합니다.




--
[NOTE]
====
RcfFileGenerator는 플랫폼에서 지원하지 않는 VLAN을 사용하여 RCF 파일을 생성할 수 없습니다.

RcfFileGenerator는 특정 VLAN ID의 사용을 제한할 수 있습니다(예: 향후 사용을 위해 제공된 경우). 일반적으로 예약된 VLAN은 최대 100개까지 가능합니다.

====
--
* 종단 간 네트워크의 모든 장치에서 MTU 크기를 9216으로 설정해야 합니다.
* 다른 트래픽은 서비스 클래스(COS) 5보다 높은 우선 순위로 구성할 수 없습니다.
* 모든 종단 간 경로에 ECN(명시적 정체 알림)을 구성해야 합니다.




=== 공유 ISL 사용 시 케이블 연결 요구 사항

[role="lead"]
MetroCluster IP 구성에서 공유 ISL을 사용하는 경우 사이트 A의 컨트롤러 포트에서 사이트 B의 컨트롤러 포트로 실행되는 엔드 투 엔드 MetroCluster ISL의 요구 사항을 알아야 합니다


NOTE: 을 따라야 합니다  MetroCluster ISL requirements.



=== 공유 네트워크의 ISL 및 브레이크아웃 케이블 수

MetroCluster IP 스위치를 공유 네트워크에 연결하는 ISL의 수는 스위치 모델 및 포트 유형에 따라 달라집니다.

|===


| MetroCluster IP 스위치 모델 | 포트 유형입니다 | ISL 수 


 a| 
Broadcom 지원 BES-53248 스위치
 a| 
네이티브 포트
 a| 
10 또는 25Gbps 포트를 사용하는 ISL 4개



 a| 
Cisco 3132Q-V
 a| 
네이티브 포트
 a| 
40Gbps 포트를 사용하는 ISL 6개



 a| 
Cisco 3132Q-V
 a| 
브레이크아웃 케이블
 a| 
10-Gbps ISL 16개



 a| 
Cisco 3232C
 a| 
네이티브 포트
 a| 
40 또는 100Gbps 포트를 사용하는 ISL 6개



 a| 
Cisco 3232C
 a| 
브레이크아웃 케이블
 a| 
10-Gbps ISL 16개



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결 안 됨)
 a| 
네이티브 포트
 a| 
40 또는 100Gbps를 사용하는 ISL 6개



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결 안 됨)
 a| 
브레이크아웃 케이블
 a| 
10Gbps 사용 ISL 16개



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결)
 a| 
네이티브 포트(2개)
 a| 
40 또는 100Gbps를 사용하는 ISL 4개



 a| 
Cisco 9336C-FX2(NS224 쉘프 연결)
 a| 
브레이크아웃 케이블(2개)
 a| 
10Gbps 사용 ISL 16개

|===
* BES-53248 스위치에서 40 또는 100Gbps ISL 포트를 사용하려면 추가 라이센스가 필요합니다.
* Cisco 9336C-FX2(NS224 셸프 연결)용 RCF 파일을 생성할 때 ISL을 기본 * 또는 * 브레이크아웃 모드로 구성해야 합니다.
* Cisco 스위치에서 브레이크아웃 케이블(하나의 물리적 포트가 4 x 10Gbps 포트로 사용됨)을 사용할 수 있습니다.
* IP 스위치용 RCF 파일에는 기본 및 브레이크아웃 모드의 포트가 구성되어 있습니다.
+
네이티브 포트 속도 모드와 브레이크아웃 모드의 ISL 포트 혼합은 지원되지 않습니다. MetroCluster IP 스위치에서 하나의 네트워크에 있는 중간 스위치까지의 모든 ISL은 속도와 길이가 같아야 합니다.

* 외부 암호화 장치(예: WDM 장치를 통해 제공되는 외부 링크 암호화 또는 암호화)의 사용은 위 요구 사항 내에 라운드 트립 지연 시간이 유지되는 한 지원됩니다.


최적의 성능을 얻으려면 네트워크당 최소 1 x 40Gbps 또는 여러 10Gbps ISL을 사용해야 합니다. AFF A800 시스템에서 네트워크당 단일 10Gbps ISL을 사용하는 것은 권장하지 않습니다.

공유 ISL의 이론상 최대 처리량(예: 40Gbps ISL 6개를 포함하는 240Gbps)은 최상의 시나리오입니다. 여러 ISL을 사용할 경우 통계 로드 밸런싱이 최대 처리량에 영향을 줄 수 있습니다. 불균일한 밸런싱이 발생할 수 있으며 단일 ISL의 처리량을 줄일 수 있습니다.

구성에서 L2 VLAN을 사용하는 경우 기본적으로 사이트를 포괄해야 합니다. VXLAN(Virtual Extensible LAN)과 같은 VLAN 오버레이는 지원되지 않습니다.

MetroCluster 트래픽을 전달하는 ISL은 스위치 간의 네이티브 링크여야 합니다. MPLS(Multiprotocol Label Switching) 링크와 같은 링크 공유 서비스는 지원되지 않습니다.



=== Broadcom BES-53248 스위치에서 WAN ISL 지원

* Fabric당 최소 WAN ISL 수: 1(10GbE, 25GbE, 40GbE 또는 100GbE)
* Fabric당 최대 10GbE WAN ISL 수: 4
* Fabric당 최대 25GbE WAN ISL 수: 4
* Fabric당 최대 40-GbE WAN ISL 수: 2
* Fabric당 최대 100GbE WAN ISL 수: 2


40GbE 또는 100-GbE WAN ISL은 RCF 파일 버전 1.40 이상이 필요합니다.


NOTE: 추가 포트를 사용하려면 추가 라이센스가 필요합니다.
