---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: 다양한 MetroCluster 구성에 필요한 구성 요소의 주요 차이점이 있습니다. 
---
= ONTAP 중재자와 MetroCluster Tiebreaker의 차이점
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7부터 MetroCluster IP 구성에서 ONTAP MUSO(중재자 지원 자동 예상치 못한 전환)를 사용하거나 MetroCluster Tiebreaker 소프트웨어를 사용할 수 있습니다. 두 서비스 중 하나만 MetroCluster IP 구성에 사용할 수 있습니다.

MetroCluster 구성마다 다른 상황에서 자동 전환이 수행됩니다.

* * MetroCluster IP 구성에 없는 AUSO 기능을 사용하는 MetroCluster FC 구성 *
+
이러한 구성에서 AUSO는 컨트롤러에 장애가 발생했지만 스토리지(및 브리지(있는 경우)가 작동 중인 경우 시작됩니다.

* MetroCluster 중재 서비스(ONTAP 9.7 이상)를 사용하는 * ONTAP IP 구성
+
이러한 구성에서 MAUSO는 위에서 설명한 AUSO와 동일한 상황에서 그리고 전체 사이트 장애(컨트롤러, 스토리지 및 스위치)가 발생한 후에 시작됩니다.

+

NOTE: MAUSO는 비휘발성 캐시 미러링(_DR 미러링_)과 SyncMirror plex 미러링이 장애 발생 시 동기화되는 경우에만 시작됩니다.

* * 활성 모드에서 Tiebreaker 소프트웨어를 사용하는 MetroCluster IP 또는 FC 구성 *
+
이러한 구성에서 Tiebreaker는 전체 사이트 장애 후 계획되지 않은 전환을 시작합니다.

+
Tiebreaker 소프트웨어를 사용하기 전에 을 검토하십시오 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker 소프트웨어 설치 및 구성"]





== 다른 애플리케이션 및 어플라이언스와 함께 하는 ONTAP 중재자의 상호 운용성

ONTAP 중재자와 함께 전환을 트리거할 수 있는 타사 애플리케이션이나 어플라이언스를 사용할 수 없습니다. 또한 ONTAP 중재자를 사용할 때는 MetroCluster Tiebreaker 소프트웨어를 사용하여 MetroCluster 구성을 모니터링하는 기능이 지원되지 않습니다.



== ONTAP 중재자가 자동 계획되지 않은 전환을 지원하는 방법

ONTAP 중재자가 중재자 호스트에 있는 사서함에 MetroCluster 노드에 대한 상태 정보를 저장합니다. MetroCluster 노드는 이 정보를 사용하여 DR 파트너의 상태를 모니터링하고 재해 발생 시 중재자를 통한 자동 계획되지 않은 전환(MAUSO)을 구현할 수 있습니다.

절체가 필요한 사이트 장애를 감지하면 절체가 적절한지 확인하고, 적절한 경우 절체를 수행한다.

MAUSO는 각 노드의 비휘발성 캐시에 대한 SyncMirror 미러링 및 DR 미러링이 모두 작동하고 캐시 및 미러가 장애 시 동기화되는 경우에만 시작됩니다.


IMPORTANT: MAUSO는 사이트 재해가 발생한 경우에만 시작됩니다. 사이트 재해는 동일한 사이트에 있는 * 모든 * 노드의 장애이지만 몇 가지 예외가 있습니다.

MAUSO는 다음과 같은 종료 시나리오에서 * 시작되지 않습니다 *.

* 종료를 시작합니다. 예를 들면 다음과 같습니다.
+
** 노드를 중단합니다
** 노드를 재부팅합니다


* 팬 또는 구성 요소 오류로 인해 시스템 종료 시작(환경 종료)

