---
sidebar: sidebar 
permalink: install-ip/configure-mcc-site-system-manager.html 
keywords: metrocluster, configuration, config, mcc, HA, cluster 
summary: ONTAP 9.8부터 System Manager를 사용하여 MetroCluster IP 구성 작업을 관리할 수 있습니다. 여기에는 두 클러스터를 설정, 피어링 및 구성하는 작업이 포함됩니다. 
---
= MetroCluster IP 사이트를 구성합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8부터 System Manager를 사용하여 MetroCluster IP 구성 작업을 관리할 수 있습니다. 여기에는 두 클러스터 설정, 클러스터 피어링 수행 및 클러스터 구성이 포함됩니다.

.시작하기 전에
다음 절차를 완료하십시오.

* link:set-up-mcc-site-system-manager.html["MetroCluster IP 사이트를 설정합니다"]
* link:set-up-mcc-peering-system-manager.html["MetroCluster IP 피어링을 설정합니다"]




== 클러스터 간 연결을 구성합니다

.단계
. 사이트 중 하나에서 System Manager에 로그인하고 * Dashboard * 를 선택합니다.
+
MetroCluster * 섹션에서 그래픽은 MetroCluster 사이트를 위해 설정하고 피어링한 두 클러스터를 보여줍니다. 작업 중인 클러스터(로컬 클러스터)가 왼쪽에 표시됩니다.

. MetroCluster 구성 * 을 클릭합니다. 이 창에서 다음 단계를 수행하십시오.
+
.. MetroCluster 구성에서 각 클러스터의 노드가 표시됩니다. 드롭다운 목록을 사용하여 원격 클러스터의 노드와 함께 재해 복구 파트너가 될 로컬 클러스터의 노드를 선택합니다.
.. ONTAP Mediator를 구성하려면 확인란을 클릭하세요. 을 link:./task-sm-mediator.html["ONTAP Mediator 구성"]참조하십시오.
.. 두 클러스터에 암호화를 활성화할 수 있는 라이센스가 있으면 * Encryption * 섹션이 표시됩니다.
+
암호화를 활성화하려면 암호를 입력합니다.

.. MetroCluster를 공유 계층 3 네트워크로 구성하려면 이 확인란을 클릭합니다.
+

NOTE: 노드에 연결되는 HA 파트너 노드와 네트워크 스위치에 일치하는 구성이 있어야 합니다.



. MetroCluster 사이트를 구성하려면 * 저장 * 을 클릭합니다.
+
대시보드 * 의 * MetroCluster * 섹션에서 그래픽은 두 클러스터 간의 링크에 확인 표시를 표시하여 양호한 연결을 나타냅니다.


