---
permalink: install-ip/task_changing_mediator_username.html 
sidebar: sidebar 
keywords: mediator, username, change 
summary: ONTAP 중재자 서비스를 설치한 후 암호를 변경할 수 있습니다. 두 가지 방법으로 암호를 변경할 수 있습니다. 
---
= ONTAP 중재자 사용자 이름 변경
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자 서비스를 설치한 후 사용자 이름을 변경할 수 있습니다. 두 가지 방법으로 암호를 변경할 수 있습니다.

이 작업은 ONTAP 중재자 서비스가 설치된 Linux 호스트에서 수행됩니다.

이 명령에 액세스할 수 없는 경우 다음 예에 표시된 대로 전체 경로를 사용하여 명령을 실행해야 할 수 있습니다.

'/usr/local/bin/중재자_username'

다음 옵션 중 하나를 선택하여 사용자 이름을 변경합니다.

* 다음 예제와 같이 중재자_change_user 명령을 실행하고 프롬프트에 응답합니다.
+
....
 [root@mediator-host ~]# mediator_change_user
 Modify the Mediator API username by entering the following values:
     Mediator API User Name: mediatoradmin
                   Password:
 New Mediator API User Name: mediator
 The account username has been modified successfully.
 [root@mediator-host ~]#
....
* 다음 명령을 실행합니다.
+
MDIATOR_USERNAME=중재자_PASSWORD=mediator2 MEDIATOR_NEW_USERNAME=mediatoradmin 중재자_CHANGE_USER

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME= mediator MEDIATOR_PASSWORD='mediator2' MEDIATOR_NEW_USERNAME= mediatoradmin mediator_change_user
 The account username has been modified successfully.
 [root@mediator-host ~]#
....

