---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: MetroCluster IP 구성에서 ONTAP 중재자를 제거할 수 있습니다. 
---
= MetroCluster IP 구성에서 ONTAP Mediator 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 구성에서 ONTAP Mediator의 구성을 해제할 수 있습니다.

.시작하기 전에
MetroCluster 사이트 모두에 접근할 수 있는 네트워크 위치에 ONTAP Mediator를 성공적으로 설치하고 구성했어야 합니다.

.단계
. 다음 명령을 사용하여 ONTAP Mediator 구성을 해제합니다.
+
'MetroCluster configuration-settings 중재자 제거

+
ONTAP 중재자 관리자 계정의 사용자 이름과 암호를 입력하라는 메시지가 표시됩니다.

+

NOTE: ONTAP Mediator가 다운되면  `metrocluster configuration-settings mediator remove` 명령을 실행해도 ONTAP Mediator 관리자 계정에 대한 사용자 이름과 비밀번호를 입력하라는 메시지가 표시되고 MetroCluster 구성에서 ONTAP Mediator가 제거됩니다.

+
.. 다음 명령을 사용하여 손상된 디스크가 있는지 확인합니다.
+
'디스크 쇼-파단'

+
* 예 *

+
....
There are no entries matching your query.
....


. 통신에 HTTPS를 사용하는 ONTAP Mediator를 사용하는 경우 ONTAP Mediator를 제거한 후 CA 인증서를 삭제하십시오.
+
.. 설치된 CA 인증서를 표시합니다.
+
`security certificate show -common-name ONTAPMediatorCA`

.. 설치된 루트 및 중간 인증서를 제거합니다.
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. 두 클러스터 모두에서 다음 명령을 실행하여 ONTAP Mediator가 MetroCluster 구성에서 제거되었는지 확인하십시오.
+
.. `metrocluster configuration-settings mediator show`
+
* 예 *

+
[listing]
----
This table is currently empty.
----



