---
permalink: install-ip/task_install_configure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, install, configure, requirements, mediator requirements 
summary: ONTAP 중재자 서비스를 설치하려면 모든 필수 구성 요소가 충족되었는지 확인하고 설치 패키지를 얻고 호스트에서 설치 관리자를 실행해야 합니다. 
---
= ONTAP 중재자 서비스 설치 또는 업그레이드
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자 서비스를 설치하려면 모든 필수 구성 요소가 충족되었는지 확인하고 설치 패키지를 얻고 호스트에서 설치 관리자를 실행해야 합니다.

다음 필수 조건을 충족해야 합니다.

[cols="30,70"]
|===


| 중재자 버전 | 지원되는 Linux 버전 


 a| 
1.3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 8.0, 8.1
* CentOS: 7.6, 7.7, 7.8


|===

NOTE: 커널 버전이 운영 체제 버전과 일치해야 합니다.

* 64비트 물리적 설치 또는 가상 머신
* 8GB RAM
* 사용자: 루트 액세스


Red Hat Enterprise Linux 또는 CentOS를 설치하는 모범 사례와 시스템에 연결된 리포지토리를 설치하는 방법은 다음과 같습니다. 다른 방식으로 설치 또는 구성된 시스템은 추가 단계가 필요할 수 있습니다.

* Red Hat 모범 사례에 따라 Red Hat Enterprise Linux 또는 CentOS를 설치해야 합니다. CentOS 8.x 버전에 대한 지원 기간이 종료되므로 RHEL 또는 CentOS 7.x 호환 버전을 사용하지 않는 것이 좋습니다
* Red Hat Enterprise Linux 또는 CentOS에 ONTAP 중재자 서비스를 설치하는 동안 시스템은 설치 프로그램이 필요한 모든 소프트웨어 종속성을 액세스하고 설치할 수 있도록 적절한 리포지토리에 액세스할 수 있어야 합니다.
* yum installer가 Red Hat Enterprise Linux 리포지토리에서 종속 소프트웨어를 찾으려면 Red Hat Enterprise Linux를 설치하는 동안 또는 유효한 Red Hat 서브스크립션을 사용하여 시스템을 등록해야 합니다.
+
Red Hat 서브스크립션 관리자에 대한 자세한 내용은 Red Hat 설명서를 참조하십시오.

* 다음 포트는 사용되지 않고 중재자를 위해 사용할 수 있어야 합니다.
+
** 31784
** 3260


* 타사 방화벽을 사용하는 경우 를 참조하십시오 link:concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator["ONTAP 중재자를 위한 방화벽 요구 사항"]
* Linux 호스트가 인터넷에 액세스할 수 없는 위치에 있는 경우 패키지를 수동으로 설치하거나 필요한 패키지를 로컬 저장소에서 사용할 수 있는지 확인해야 합니다.
+
리포지토리 설정에 대한 자세한 내용은 다음 링크를 참조하십시오.

+
Linux 환경에서 LACP(Link Aggregation Control Protocol)를 사용하는 경우 커널을 올바르게 구성하고 'sysctl net.ipv4.conf.all.arp_ignore'가 "2"로 설정되어 있는지 확인해야 합니다.

+
ONTAP 중재자 서비스에는 다음 패키지가 필요합니다.

+
[cols="25,35,40"]
|===


| 모든 RHEL/CentOS 버전 | RHEL/CentOS 7.x용 추가 패키지 | RHEL/CentOS 8.x용 추가 패키지 


 a| 
** OpenSSL
** OpenSSL - devel
** 커널-devel
** GCC 를 참조하십시오
** libselinux-utils
** 만듭니다
** redhat-LSB-core를 참조하십시오
** 패치
** bzip2
** python36
** python36-devel
** Perl - 데이터 - 덤프
** Perl-ExtUtils-MakeMaker
** python3-PIP

 a| 
** 정책 코어 유틸리티 - 비톤
** python36-PIP

 a| 
** elfutils -libelf -devel
** 정책 코어 유틸리티 - 비톤 - 유틸리티


|===
* 서명 확인이 구성된 경우 이를 비활성화해야 합니다. 이 작업은 다음 두 가지 방법 중 하나로 수행할 수 있습니다.
+
** UEFI SecureBoot 메커니즘이 구성된 경우 이를 비활성화합니다.
** grub.cfg 파일을 업데이트하고 다시 생성하여 서명 확인 메커니즘을 비활성화합니다.
+
... /etc/default/grub 파일을 엽니다.
... GRUB_CMDLINE_LINUX 문 끝에 문자열 module.SIG_WERYCE=0을 추가합니다.
... grub.cfg 파일을 다시 생성하여 변경 사항을 구현합니다.
+
'update-bootloader||update-grub||grub2-mkconfig-o/boot/grub2/grub.cfg'

... 호스트를 재부팅합니다.






중재자 설치 패키지는 다음을 포함하는 자동 압축 tar 파일입니다.

* 지원되는 릴리즈의 리포지토리에서 가져올 수 없는 모든 종속성을 포함하는 RPM 파일입니다.
* 설치 스크립트


이 절차에 설명된 대로 유효한 SSL 인증을 권장합니다.

이 절차는 기존 설치의 설치 또는 업그레이드에 사용됩니다.

link:concept_mediator_requirements.html#guidelines-for-upgrading-the-ontap-mediator-in-a-metrocluster-configuration["MetroCluster 구성에서 ONTAP 중재자를 업그레이드하기 위한 지침입니다"]



== 리포지토리에 대한 액세스를 활성화합니다

|===


| 운영 체제가... | 이러한 리포지토리에 대한 액세스를 제공해야 합니다... 


 a| 
RHEL 7.x를 참조하십시오
 a| 
RHEL-7-server-optional-rpms



 a| 
CentOS 7.x
 a| 
C7.6.1810 - 기본 리포지토리입니다



 a| 
RHEL 8.x를 참조하십시오
 a| 
* RHEL-8-for-x86_64-baseos-rpms
* RHEL-8-for-x86_64-appstream-rpms




 a| 
CentOS 8.0
 a| 
커널-devel

|===
중재자가 설치 프로세스 중에 필요한 패키지에 액세스할 수 있도록 위에 나열된 리포지토리에 대한 액세스를 활성화합니다. 사용 중인 운영 체제에 대해 아래 절차를 따르십시오.

* 에 대한 절차 <<rhel7x,RHEL 7.x를 참조하십시오>> 운영 체제.
* 에 대한 절차 <<rhel8x,RHEL 8.x를 참조하십시오>> 운영 체제.
* 에 대한 절차 <<centos7x,CentOS 7.x>> 운영 체제.
* 에 대한 절차 <<centos8x,CentOS 8.0.1095 이상>> 운영 체제.




=== RHEL 7.x 운영 체제에 대한 절차

운영 체제가 * RHEL 7.x * 인 경우:

.단계
. 필요한 리포지토리 구독:
+
'Subscription-manager Repos - -enable rhel-7-server-optional-rpms'

+
다음 예제에서는 이 명령의 실행을 보여 줍니다.

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
. yum repolist 명령을 실행합니다.
+
다음 예제에서는 이 명령의 실행을 보여 줍니다. "rhel-7-server-optional-rpms" 리포지토리가 목록에 나타나야 합니다.

+
[listing]
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group                                               |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo                                          | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db                                          | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----




=== RHEL 8.x 운영 체제에 대한 절차

운영 체제가 * RHEL 8.x * 인 경우:

.단계
. 필요한 리포지토리 구독:
+
'Subscription-manager Repos -- rhel-8-for-x86_64-baseos-rpms'를 활성화합니다

+
'Subscription-manager Repos - -enable rhel-8-for-x86_64-appstream-rpms'

+
다음 예제에서는 이 명령의 실행을 보여 줍니다.

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----
. yum repolist 명령을 실행합니다.
+
새로 가입된 리포지토리가 목록에 나타납니다.





=== CentOS 7.x 운영 체제에 대한 절차

운영 체제가 * CentOS 7.x * 인 경우:

.단계
. C7.6.1810-Base 리포지토리를 추가합니다. C7.6.1810 - 기본 볼트 리포지토리에는 ONTAP 중재자를 위해 필요한 커널-devel 패키지가 포함되어 있습니다.
. /etc/yum.repos.d/CentOS-Vault.repo에 다음 줄을 추가합니다.
+
[listing]
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$
basearch/gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----
. yum repolist 명령을 실행합니다.
+
다음 예제에서는 이 명령의 실행을 보여 줍니다. CentOS-7.6.1810-기본 리포지토리가 목록에 나타나야 합니다.

+
[listing]
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                                   | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz                            | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db                          | 6.0 MB  00:00:04
repo id                                           repo name                                                                                                    status
C7.6.1810-base/x86_64                             CentOS-7.6.1810 - Base                                                                                       10,019
base/7/x86_64                                     CentOS-7 - Base                                                                                              10,097
extras/7/x86_64                                   CentOS-7 - Extras                                                                                               307
updates/7/x86_64                                  CentOS-7 - Updates                                                                                            1,010
repolist: 21,433
[root@localhost ~]#
----




=== CentOS 8.0.1905 이상 운영 체제에 대한 절차


CAUTION: CentOS 8.x의 수명 지원은 2021년 12월 31일에 종료됩니다. ONTAP에서 CentOS를 사용하는 경우 로 되돌리는 것이 좋습니다 <<centos7x,CentOS 7.x>> 운영 체제 또는 RHEL을 사용합니다.

운영 체제가 * CentOS 8.0.1905 이상인 경우 *:

에 있습니다 http://vault.centos.org["CentOS 볼트"]에서 운영 체제와 일치하는 커널-devel 패키지를 찾습니다. 8.0(CentOS 8.0.1905이상) 코어의 최신 버전이 에 있기 때문입니다필요한 커널 모듈을 컴파일하려면 일치하는 kernel-devel 패키지에 대한 액세스를 제공해야 합니다.

.단계
. [[step1-rpm]] 다음 명령을 실행하여 커널-devel 패키지를 직접 설치합니다.
+
rpm -i\http://vault.centos.org/8.0.1905/BaseOS/x86_64/os/Packages/kernel-devel-$(uname -r).rpm

+
--

NOTE: 위의 명령은 CentOS 8.0.1905에만 적용되는 예입니다. 다른 CentoOS 8.x 빌드에 적합한 경로를 변경합니다.

--
. 패키지가 이미 설치되었다는 오류가 시스템에 표시되면 패키지를 제거하고 다시 시도하십시오.
+
.. kernel-devel 패키지를 제거합니다.
+
'yum remove kernel-devel'

.. 에 표시된 "rpm" 명령을 반복합니다 <<step1-rpm,1단계>>.






== 중재자 설치 패키지를 다운로드합니다

.단계
. ONTAP 중재자 페이지에서 중재자 설치 패키지를 다운로드합니다.
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab["ONTAP 중재자 다운로드 페이지"]

. 중재자 설치 패키지가 대상 디렉토리에 있는지 확인합니다.
+
"ls"

+
[listing]
----
[root@mediator-host ~]#ls
./ontap-mediator_1.3
----
+
인터넷에 액세스할 수 없는 위치에 있는 경우 설치 프로그램이 필요한 패키지에 액세스할 수 있는지 확인해야 합니다.

. 필요한 경우, 중재 설치 패키지를 다운로드 디렉토리에서 Linux 중재자 호스트의 설치 디렉토리로 이동합니다.




== ONTAP 중재자 설치 패키지를 설치합니다

.단계
. 중재자 설치 패키지를 설치하고 필요에 따라 프롬프트에 응답합니다.
+
'./ONTAP-중재자_1.3'

+
설치 프로세스가 진행되어 필요한 계정을 생성하고 필요한 패키지를 설치합니다. 호스트에 이전 버전의 중재자가 설치되어 있는 경우 업그레이드할지 확인하는 메시지가 표시됩니다.



link:../media/console_output_mediator_installation.txt["ONTAP 중재자 설치의 예(콘솔 출력)"]



== 설치를 확인합니다

.단계
. 다음 명령을 실행하여 ONTAP 중재자 서비스의 상태를 확인합니다.
+
'스타emctl'입니다

+
[listing]
----
 [root@scspr1915530002 ~]# systemctl status ontap_mediator mediator-scst

        ∙ ontap_mediator.service - ONTAP Mediator
            Loaded: loaded (/opt/netapp/lib/ontap_mediator/systemd/ontap_mediator.service; enabled; vendor preset: disabled)

            Active: active (running) since Thu 2020-06-18 09:55:02 EDT; 3 days ago

         Main PID: 3559 (uwsgi)

            Status: "uWSGI is ready"

            CGroup: /system.slice/ontap_mediator.service

                    \u251c\u25003559 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

                    \u251c\u25004510 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

                    \u2514\u25004512 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini



         Jun 18 09:54:43 scspr1915530002 systemd[1]: Starting ONTAP Mediator...

         Jun 18 09:54:45 scspr1915530002 ontap_mediator[3559]: [uWSGI] getting INI configuration from /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

         Jun 18 09:55:02 scspr1915530002 systemd[1]: Started ONTAP Mediator.



         ∙ mediator-scst.service
            Loaded: loaded (/opt/netapp/lib/ontap_mediator/systemd/mediator-scst.service; enabled; vendor preset: disabled)

            Active: active (running) since Thu 2020-06-18 09:54:51 EDT; 3 days ago

           Process: 3564 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)

         Main PID: 4202 (iscsi-scstd)

            CGroup: /system.slice/mediator-scst.service

                    \u2514\u25004202 /usr/local/sbin/iscsi-scstd



         Jun 18 09:54:43 scspr1915530002 systemd[1]: Starting mediator-scst.service...

         Jun 18 09:54:48 scspr1915530002 iscsi-scstd[4200]: max_data_seg_len 1048576, max_queued_cmds 2048

         Jun 18 09:54:51 scspr1915530002 scst[3564]: Loading and configuring SCST[  OK  ]

         Jun 18 09:54:51 scspr1915530002 systemd[1]: Started mediator-scst.service.

         [root@scspr1915530002 ~]#
----
. ONTAP 중재자 서비스가 사용하는 포트를 확인합니다. netstat
+
[listing]
----
         [root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp        0      0 0.0.0.0:31784           0.0.0.0:*               LISTEN

         tcp        0      0 0.0.0.0:3260            0.0.0.0:*               LISTEN

         tcp6       0      0 :::3260                 :::*                    LISTEN
----




== 결과

이제 ONTAP 중재자 서비스가 설치 및 실행됩니다. 중재자 기능을 사용하려면 ONTAP 스토리지 시스템에서 추가 구성을 수행해야 합니다.
