---
permalink: install-ip/task_switch_config_cisco.html 
sidebar: sidebar 
keywords: ip, switch, configuring, configure, factory defaults, cisco, MACsec encryption, 9336C, 9336, forward error correction, fec 
summary: 클러스터 인터커넥트 및 백엔드 MetroCluster IP 연결에 사용할 Cisco IP 스위치를 구성해야 합니다. 
---
= Cisco IP 스위치 구성
:allow-uri-read: 


[role="lead"]
클러스터 인터커넥트 및 백엔드 MetroCluster IP 연결에 사용할 Cisco IP 스위치를 구성해야 합니다.

.이 작업에 대해
이 섹션의 절차 중 일부는 독립 절차이며, 사용자가 직접 수행했거나 작업과 관련된 절차만 실행해야 합니다.



== Cisco IP 스위치를 출하 시 기본값으로 재설정합니다

RCF 파일을 설치하기 전에 Cisco 스위치 구성을 지우고 기본 구성을 수행해야 합니다. 이전 설치가 실패한 후 동일한 RCF 파일을 다시 설치하거나 새 버전의 RCF 파일을 설치하려는 경우 이 절차가 필요합니다.

.이 작업에 대해
* MetroCluster IP 구성의 각 IP 스위치에서 이 단계를 반복해야 합니다.
* 직렬 콘솔을 사용하여 스위치에 연결해야 합니다.
* 이 작업은 관리 네트워크의 구성을 재설정합니다.


.단계
. 스위치를 출하 시 기본값으로 재설정합니다.
+
.. 기존 구성을 지웁니다.
+
쓰기 지우기

.. 스위치 소프트웨어를 다시 로드합니다.
+
다시 로드

+
시스템이 재부팅되고 구성 마법사가 시작됩니다. 부팅 중에 "'자동 프로비저닝 중단'이라는 메시지가 표시되면 일반 설정으로 계속 진행하시겠습니까? (예/아니요) [n]", 계속하려면 "예"라고 답해야 합니다.

.. 구성 마법사에서 기본 스위치 설정을 입력합니다.
+
*** 관리자 암호입니다
*** 스위치 이름
*** 대역외 관리 구성
*** 기본 게이트웨이
*** SSH 서비스(RSA)
+
구성 마법사를 완료하면 스위치가 재부팅됩니다.



.. 메시지가 표시되면 사용자 이름과 암호를 입력하여 스위치에 로그인합니다.
+
다음 예에서는 스위치를 구성할 때 프롬프트 및 시스템 응답을 보여 줍니다. 꺾쇠 괄호(<<<<)는 사용자가 정보를 입력하는 위치를 표시합니다.

+
[listing]
----
---- System Admin Account Setup ----
Do you want to enforce secure password standard (yes/no) [y]:y  **<<<**

    Enter the password for "admin": password
  Confirm the password for "admin": password
         ---- Basic System Configuration Dialog VDC: 1 ----

This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus3000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus3000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.
----
+
스위치 이름, 관리 주소 및 게이트웨이를 포함하여 다음 프롬프트 세트에 기본 정보를 입력하고 SSH with RSA를 선택합니다.

+
[listing]
----
Would you like to enter the basic configuration dialog (yes/no): yes
  Create another login account (yes/no) [n]:
  Configure read-only SNMP community string (yes/no) [n]:
  Configure read-write SNMP community string (yes/no) [n]:
  Enter the switch name : switch-name **<<<**
  Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]:
    Mgmt0 IPv4 address : management-IP-address  **<<<**
    Mgmt0 IPv4 netmask : management-IP-netmask  **<<<**
  Configure the default gateway? (yes/no) [y]: y **<<<**
    IPv4 address of the default gateway : gateway-IP-address  **<<<**
  Configure advanced IP options? (yes/no) [n]:
  Enable the telnet service? (yes/no) [n]:
  Enable the ssh service? (yes/no) [y]: y  **<<<**
    Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa **<<<**
    Number of rsa key bits <1024-2048> [1024]:
  Configure the ntp server? (yes/no) [n]:
  Configure default interface layer (L3/L2) [L2]:
  Configure default switchport interface state (shut/noshut) [noshut]: shut **<<<**
  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]:
----
+
마지막 프롬프트 세트가 구성을 완료합니다.

+
[listing]
----
The following configuration will be applied:
  password strength-check
  switchname IP_switch_A_1
vrf context management
ip route 0.0.0.0/0 10.10.99.1
exit
  no feature telnet
  ssh key rsa 1024 force
  feature ssh
  system default switchport
  system default switchport shutdown
  copp profile strict
interface mgmt0
ip address 10.10.99.10 255.255.255.0
no shutdown

Would you like to edit the configuration? (yes/no) [n]:

Use this configuration and save it? (yes/no) [y]:
2017 Jun 13 21:24:43 A1 %$ VDC-1 %$ %COPP-2-COPP_POLICY: Control-Plane is protected with policy copp-system-p-policy-strict.

[########################################] 100%
Copy complete.

User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
.
.
.
IP_switch_A_1#
----


. 구성을 저장합니다.
+
[listing]
----
 IP_switch-A-1# copy running-config startup-config
----
. 스위치를 재부팅하고 스위치가 다시 로드될 때까지 기다립니다.
+
[listing]
----
 IP_switch-A-1# reload
----
. MetroCluster IP 구성의 다른 3개 스위치에 대해 이전 단계를 반복합니다.




== Cisco 스위치 NX-OS 소프트웨어 다운로드 및 설치

MetroCluster IP 구성의 각 스위치에 스위치 운영 체제 파일과 RCF 파일을 다운로드해야 합니다.

.이 작업에 대해
이 작업에는 FTP, TFTP, SFTP 또는 SCP와 같은 파일 전송 소프트웨어가 필요합니다. 스위치에 파일을 복사합니다.

이러한 단계는 MetroCluster IP 구성의 각 IP 스위치에서 반복해야 합니다.

지원되는 스위치 소프트웨어 버전을 사용해야 합니다.

https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]

.단계
. 지원되는 NX-OS 소프트웨어 파일을 다운로드합니다.
+
https://software.cisco.com/download/home["Cisco 소프트웨어 다운로드"]

. 스위치 소프트웨어를 스위치에 복사합니다.
+
'copy sftp://root@server-ip-address/tftpboot/nx-os-file-name bootflash:vrf management'

+
이 예제에서 nxos.7.0.3.I4.6.bin 파일은 SFTP 서버 10.10.99.99에서 로컬 bootflash로 복사됩니다.

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/nxos.7.0.3.I4.6.bin bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/nxos.7.0.3.I4.6.bin  /bootflash/nxos.7.0.3.I4.6.bin
Fetching /tftpboot/nxos.7.0.3.I4.6.bin to /bootflash/nxos.7.0.3.I4.6.bin
/tftpboot/nxos.7.0.3.I4.6.bin                 100%  666MB   7.2MB/s   01:32
sftp> exit
Copy complete, now saving to disk (please wait)...
----
. 각 스위치에서 스위치 NX-OS 파일이 각 스위치의 bootflash 디렉토리에 있는지 확인합니다.
+
'dir bootflash:'

+
다음 예제는 파일이 IP_SWITCH_A_1에 있음을 보여줍니다.

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
  698629632    Jun 13 21:37:44 2017  nxos.7.0.3.I4.6.bin
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. 스위치 소프트웨어를 설치합니다.
+
nxos bootflash: nxos.version-number.bin을 모두 설치합니다

+
스위치 소프트웨어가 설치되면 스위치는 자동으로 다시 로드(재부팅)됩니다.

+
다음 예에서는 IP_SWITCH_A_1에 설치된 소프트웨어를 보여 줍니다.

+
[listing]
----
IP_switch_A_1# install all nxos bootflash:nxos.7.0.3.I4.6.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS       [####################] 100%            -- SUCCESS

Performing module support checks.            [####################] 100%            -- SUCCESS

Notifying services about system upgrade.     [####################] 100%            -- SUCCESS



Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless



Images will be upgraded according to following table:
Module       Image   Running-Version(pri:alt)         New-Version   Upg-Required
------  ----------   ------------------------  ------------------   ------------
     1        nxos                7.0(3)I4(1)         7.0(3)I4(6)   yes
     1        bios         v04.24(04/21/2016)  v04.24(04/21/2016)   no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] y


Install is in progress, please wait.

Performing runtime checks.         [####################] 100%    -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
IP_switch_A_1#
----
. 스위치가 다시 로드될 때까지 기다린 다음 스위치에 로그인합니다.
+
스위치가 재부팅되면 로그인 프롬프트가 표시됩니다.

+
[listing]
----
User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.
MDP database restore in progress.
IP_switch_A_1#

The switch software is now installed.
----
. 스위치 소프트웨어가 설치되어 있는지 확인합니다
+
다음 예는 출력을 보여줍니다.

+
[listing]
----
IP_switch_A_1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.

Software
  BIOS: version 04.24
  NXOS: version 7.0(3)I4(6)   **<<< switch software version**
  BIOS compile time:  04/21/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I4.6.bin
  NXOS compile time:  3/9/2017 22:00:00 [03/10/2017 07:05:18]


Hardware
  cisco Nexus 3132QV Chassis
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401416 kB of memory.
  Processor Board ID FOC20123GPS

  Device name: A1
  bootflash:   14900224 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 0 day(s), 0 hour(s), 1 minute(s), 49 second(s)

Last reset at 403451 usecs after  Mon Jun 10 21:43:52 2017

  Reason: Reset due to upgrade
  System version: 7.0(3)I4(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin
IP_switch_A_1#
----
. MetroCluster IP 구성의 나머지 3개 IP 스위치에 대해 이 단계를 반복합니다.




== Cisco IP RCF 파일 다운로드 및 설치

RCF 파일은 MetroCluster IP 구성의 각 스위치에 다운로드해야 합니다.

.이 작업에 대해
이 작업에는 FTP, TFTP, SFTP 또는 SCP와 같은 파일 전송 소프트웨어가 필요합니다. 스위치에 파일을 복사합니다.

이러한 단계는 MetroCluster IP 구성의 각 IP 스위치에서 반복해야 합니다.

지원되는 스위치 소프트웨어 버전을 사용해야 합니다.

https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]

RCF 파일은 MetroCluster IP 구성의 4개 스위치당 하나씩 4개의 파일로 구성됩니다. 사용 중인 스위치 모델에 적합한 RCF 파일을 사용해야 합니다.

|===


| 스위치 | RCF 파일 


 a| 
IP_SWITCH_A_1
 a| 
NX3232_v1.80_Switch-A1.txt



 a| 
IP_SWITCH_A_2
 a| 
NX3232_v1.80_Switch-A2.txt



 a| 
IP_SWITCH_B_1
 a| 
NX3232_v1.80_Switch-B1.txt



 a| 
IP_SWITCH_B_2
 a| 
NX3232_v1.80_Switch-B2.txt

|===
.단계
. MetroCluster IP RCF 파일을 다운로드합니다.
+

NOTE: 다운로드 후 RCF 파일을 수정할 수 없습니다.

. RCF 파일을 스위치에 복사합니다.
+
.. RCF 파일을 첫 번째 스위치에 복사합니다.
+
복사 sftp://root@ftp-server-ip-address/tftpboot/switch-specific-bootRCF flash:vrf management

+
이 예에서 NX3232_v1.80_Switch-A1.txt RCF 파일은 SFTP 서버(10.10.99.99)에서 로컬 bootflash로 복사됩니다. TFTP/SFTP 서버의 IP 주소와 설치해야 하는 RCF 파일의 파일 이름을 사용해야 합니다.

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/NX3232_v1.80_Switch-A1.txt bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/NX3232_v1.80_Switch-A1.txt /bootflash/NX3232_v1.80_Switch-A1.txt
Fetching /tftpboot/NX3232_v1.80_Switch-A1.txt to /bootflash/NX3232_v1.80_Switch-A1.txt
/tftpboot/NX3232_v1.80_Switch-A1.txt          100% 5141     5.0KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
IP_switch_A_1#
----
.. 일치하는 RCF 파일을 해당 스위치에 복사하도록 나머지 세 스위치 각각에 대해 이전 하위 단계를 반복합니다.


. 각 스위치에서 RCF 파일이 각 스위치의 bootflash 디렉토리에 있는지 확인합니다.
+
'dir bootflash:'

+
다음 예제는 파일이 IP_SWITCH_A_1에 있음을 보여줍니다.

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
5514    Jun 13 22:09:05 2017  NX3232_v1.80_Switch-A1.txt
                  .
                  .
                  .

Usage for bootflash://sup-local
1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. Cisco 3132Q-V 및 Cisco 3232C 스위치에서 TCAM 영역을 구성합니다.
+

NOTE: Cisco 3132Q-V 또는 Cisco 3232C 스위치가 없는 경우 이 단계를 건너뛰십시오.

+
.. Cisco 3132Q-V 스위치에서 다음 TCAM 영역을 설정합니다.
+
[listing]
----
conf t
hardware access-list tcam region span 0
hardware access-list tcam region racl 256
hardware access-list tcam region e-racl 256
hardware access-list tcam region qos 256
----
.. Cisco 3232C 스위치에서 다음 TCAM 영역을 설정합니다.
+
[listing]
----
conf t
hardware access-list tcam region span 0
hardware access-list tcam region racl-lite 0
hardware access-list tcam region racl 256
hardware access-list tcam region e-racl 256
hardware access-list tcam region qos 256
----
.. TCAM 영역을 설정한 후 구성을 저장하고 스위치를 다시 로드합니다.
+
[listing]
----
copy running-config startup-config
reload
----


. 로컬 bootflash에서 각 스위치의 실행 구성으로 일치하는 RCF 파일을 복사합니다.
+
bootflash: switch-specific-RCF.txt running-config를 복사합니다

. RCF 파일을 실행 중인 구성에서 각 스위치의 시작 구성으로 복사합니다.
+
'copy running-config startup-config'를 선택합니다

+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
IP_switch_A_1# copy bootflash:NX3232_v1.80_Switch-A1.txt running-config
IP_switch-A-1# copy running-config startup-config
----
. 스위치를 다시 로드하십시오.
+
다시 로드

+
[listing]
----
IP_switch_A_1# reload
----
. MetroCluster IP 구성의 다른 3개 스위치에 대해 이전 단계를 반복합니다.




== 25Gbps 연결을 사용하는 시스템에 대한 Forward Error Correction 설정

시스템이 25Gbps 연결을 사용하여 구성된 경우 RCF 파일을 적용한 후 FEC(Forward Error Correction) 매개변수를 수동으로 OFF로 설정해야 합니다. RCF 파일은 이 설정을 적용하지 않습니다.

.이 작업에 대해
이 절차를 수행하기 전에 25Gbps 포트를 케이블로 연결해야 합니다.

link:port_usage_3232c_9336c.html["Cisco 3232C 또는 Cisco 9336C 스위치에 대한 플랫폼 포트 할당"]

이 작업은 25Gbps 연결을 사용하는 플랫폼에만 적용됩니다.

* AFF A300
* FAS 8200
* FAS 500f
* AFF A250


이 작업은 MetroCluster IP 구성의 4개 스위치 모두에서 수행해야 합니다.

.단계
. 컨트롤러 모듈에 연결된 각 25Gbps 포트에서 FEC 매개변수를 OFF로 설정한 다음 실행 중인 구성을 시작 구성으로 복사합니다.
+
.. 설정 모드 'config t'로 진입한다
.. 구성할 25Gbps interface를 지정한다:'interface-id'
.. FEC를 OFF: FEC OFF로 설정한다
.. 스위치의 각 25Gbps 포트에 대해 이전 단계를 반복합니다.
.. 설정 모드 종료: '종료
+
다음 예에서는 스위치 IP_SWITCH_A_1의 인터페이스 Ethernet1/25/1에 대한 명령을 보여 줍니다.

+
[listing]
----
IP_switch_A_1# conf t
IP_switch_A_1(config)# interface Ethernet1/25/1
IP_switch_A_1(config-if)# fec off
IP_switch_A_1(config-if)# exit
IP_switch_A_1(config-if)# end
IP_switch_A_1# copy running-config startup-config
----


. MetroCluster IP 구성의 다른 3개 스위치에 대해 이전 단계를 반복합니다.




== 사용되지 않는 ISL 포트 및 포트 채널을 비활성화합니다

불필요한 상태 경고를 방지하기 위해 사용하지 않는 ISL 포트 및 포트 채널을 비활성화하는 것이 좋습니다 NetApp.

. 사용되지 않는 ISL 포트 및 포트 채널 식별:
+
인터페이스 요약

. 사용되지 않는 ISL 포트 및 포트 채널을 비활성화합니다.
+
식별된 미사용 포트 또는 포트 채널에 대해 다음 명령을 실행해야 합니다.

+
[listing]
----
SwitchA_1# config t
Enter configuration commands, one per line. End with CNTL/Z.
SwitchA_1(config)# int Eth1/14
SwitchA_1(config-if)# shutdown
SwitchA_12(config-if)# exit
SwitchA_1(config-if)# copy running-config startup-config
[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----

