---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: MetroCluster 9.7부터 ONTAP 중재자인 ONTAP Tiebreaker 소프트웨어 또는 세 번째 사이트에 다운로드하여 설치할 수 있습니다. 
---
= MetroCluster IP 구성을 위한 MetroCluster Tiebreaker 또는 ONTAP Mediator 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 9.7부터 ONTAP 중재자인 ONTAP Tiebreaker 소프트웨어 또는 세 번째 사이트에 다운로드하여 설치할 수 있습니다.

.시작하기 전에
MetroCluster 구성에서 두 클러스터에 대한 네트워크 연결이 가능한 Linux 호스트가 있어야 합니다. 구체적인 요구사항은 MetroCluster Tiebreaker 또는 ONTAP 중재자 설명서에 나와 있습니다.

기존 Tiebreaker 또는 ONTAP Mediator 인스턴스에 연결하는 경우 Tiebreaker 또는 Mediator의 사용자 이름, 비밀번호 및 IP 주소가 필요합니다.

ONTAP 중재자의 새 인스턴스를 설치해야 하는 경우 지침에 따라 소프트웨어를 설치하고 구성합니다.

link:concept_mediator_requirements.html["계획되지 않은 자동 전환을 위해 ONTAP Mediator 구성"]

Tiebreaker 소프트웨어의 새 인스턴스를 설치해야 하는 경우, 에 따르십시오 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["소프트웨어 설치 및 구성 지침"].

.이 작업에 대해
동일한 MetroCluster 구성에서 MetroCluster Tiebreaker 소프트웨어와 ONTAP 중재자를 모두 사용할 수 없습니다.

link:../install-ip/concept_considerations_mediator.html["ONTAP 중재자 또는 MetroCluster Tiebreaker를 사용할 때의 고려 사항"]

.단계
. ONTAP Mediator 또는 Tiebreaker 소프트웨어 구성:
+
** ONTAP Mediator의 기존 인스턴스를 사용하는 경우 ONTAP에 ONTAP Mediator를 추가합니다.
+
'MetroCluster configuration-settings 중재자-address-of-중재자-host'

** Tiebreaker 소프트웨어를 사용하는 경우 을 참조하십시오 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Tiebreaker 문서"].



