---
permalink: install-ip/task_config_switch_health.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, snmp, health, monitoring 
summary: 상태 모니터링에 SNMPv3을 사용하도록 IP 스위치를 구성할 수 있습니다. 
---
= 상태 모니터링을 위해 MetroCluster IP 스위치를 구성합니다
:allow-uri-read: 


[role="lead"]
MetroCluster IP 구성에서 IP 스위치의 상태를 모니터링하도록 SNMPv3을 구성할 수 있습니다.



== 1단계: MetroCluster IP 스위치에서 SNMPv3 사용자를 구성합니다

다음 단계를 사용하여 MetroCluster IP 스위치에서 SNMPv3 사용자를 구성하십시오.


IMPORTANT: 명령에서 인증 및 개인 정보 보호 프로토콜을 모두 사용해야 합니다. 개인 정보 보호 없이 인증을 사용하는 것은 지원되지 않습니다.

[role="tabbed-block"]
====
.Broadcom IP 스위치용
--
.단계
. 'network-admin' 사용자 그룹이 존재하지 않는 경우 다음을 생성합니다.
+
`(IP_switch_1) (Config)# snmp-server group network-admin v3 auth read "Default"`

. 'network-admin' 그룹이 생성되었는지 확인합니다.
+
`(IP_switch_1) (Config)# show snmp group`

. Broadcom IP 스위치에서 SNMPv3 사용자를 구성합니다.
+
[listing]
----
(IP_switch_1)# config
(IP_switch_1) (Config)# snmp-server user <user_name> network-admin auth-sha priv-aes128
----
+
메시지가 나타나면 인증 암호를 입력합니다.

+
[listing]
----
#snmp-server user admin1 network-admin auth-sha priv-aes128

Enter Authentication Password:
----


--
.Cisco IP 스위치의 경우
--
.단계
. 다음 명령을 실행하여 Cisco IP 스위치에서 SNMPv3 사용자를 구성합니다.
+
[listing]
----
IP_switch_A_1 # configure terminal
IP_switch_A_1 (config) # snmp-server user <user_name>  auth [md5/sha/sha-256] <auth_password> priv (aes-128) <priv_password>
----
. SNMPv3 사용자가 스위치에 구성되어 있는지 확인합니다.
+
`IP_switch_A_1(config) # show snmp user <user_name>`

+
다음 출력 예는 해당 사용자를 보여줍니다 `admin` SNMPv3에 대해 구성됨:

+
[listing]
----
IP_switch_A_1(config)# show snmp user admin
User                Auth      Priv(enforce) Groups              acl_filter

____                ____      _____________ ______              __________

admin               md5       aes-128(no)   network-admin
----


--
====


== 2단계: ONTAP에서 SNMPv3 사용자를 구성합니다

ONTAP에서 SNMPv3 사용자를 구성하려면 다음 단계를 따르십시오.

. ONTAP에서 SNMPv3 사용자를 구성합니다.
+
`security login create -user-or-group-name <user_name> -application snmp -authentication-method usm -remote-switch-ipaddress <ip_address>`

. 새 SNMPv3 사용자를 사용하여 스위치를 모니터링하도록 스위치 상태 모니터링을 구성합니다.
+
`system switch ethernet modify -device <device_id> -snmp-version SNMPv3 -community-or-username <user_name>`

. 새로 생성된 SNMPv3 사용자와 함께 모니터링될 장치 일련 번호가 올바른지 확인합니다.
+
.. 스위치 상태 모니터링 폴링 시간 기간을 표시합니다.
+
`system switch ethernet polling-interval show`

.. 폴링 시간이 경과하면 다음 명령을 실행합니다.
+
`system switch ethernet show-all -instance -device <device_serial_number>`





.작업을 마친 후
필요한 경우 의 단계를 link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-log-collection.html["로그 수집을 구성합니다"^]따릅니다.
