---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: ONTAP Mediator는 MetroCluster IP 구성에서 사용하려면 ONTAP 노드에 구성되어야 합니다. 
---
= MetroCluster IP 구성을 위한 ONTAP Mediator 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 구성에서 사용하려면 ONTAP 노드에서 ONTAP Mediator를 구성해야 합니다.

.시작하기 전에
* ONTAP Mediator는 MetroCluster 사이트 둘 다에서 접근할 수 있는 네트워크 위치에 성공적으로 설치되어야 합니다.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["ONTAP Mediator 설치 또는 업그레이드"^]

* ONTAP Mediator를 실행하는 호스트의 IP 주소가 있어야 합니다.
* ONTAP Mediator에 대한 사용자 이름과 비밀번호가 있어야 합니다.
* MetroCluster IP 구성의 모든 노드가 온라인 상태여야 합니다.



CAUTION: ONTAP 9.12.1부터 MetroCluster IP 구성에서 MetroCluster 자동 강제 전환 기능을 활성화할 수 있습니다. 이 기능은 중재자 지원 계획되지 않은 전환을 확장하는 기능입니다. 이 기능을 활성화하기 전에 를 검토하십시오 link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["MetroCluster 자동 강제 적용 시 위험 및 제한 사항"].

.이 작업에 대해
* 이 작업은 기본적으로 예상치 못한 자동 전환을 활성화합니다.
* 이 작업은 MetroCluster IP 구성에 있는 노드의 ONTAP 인터페이스에서 수행할 수 있습니다.
* ONTAP 9.18.1 및 ONTAP Mediator 1.11부터 단일 ONTAP Mediator 인스턴스가 최대 10개의 MetroCluster 구성을 동시에 관리할 수 있습니다.  이전 릴리스에서는 ONTAP Mediator가 최대 5개의 MetroCluster 구성을 동시에 지원할 수 있었습니다.


.단계
. ONTAP 에 ONTAP Mediator를 추가합니다.  단계는 IPv4 주소를 사용할지 IPv6 주소를 사용할지에 따라 달라집니다.
+
[NOTE]
====
** IPv6를 사용하려면 ONTAP 9.18.1 이상 및 ONTAP Mediator 1.11 이상을 실행해야 합니다.
** 클러스터에서 IPv6를 활성화하면 나중에 비활성화할 수 없습니다.


====
+
[role="tabbed-block"]
====
.IPv4 사용
--
.. 다음 명령을 실행하여 ONTAP Mediator를 추가합니다.
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address>`

+

NOTE: Mediator 관리자 계정의 사용자 이름과 비밀번호를 입력하라는 메시지가 표시됩니다.



--
.IPv6 사용
--
.. 두 클러스터에서 다음 명령을 실행합니다.
+
`network options ipv6 modify -enabled true`

.. 4개 노드 모두에서 IPv6 주소를 사용하여 node-mgmt IP 주소를 구성합니다.
.. ONTAP 중재자를 추가합니다.
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address>`

+

NOTE: Mediator 관리자 계정의 사용자 이름과 비밀번호를 입력하라는 메시지가 표시됩니다.



--
====
. 자동 전환 기능이 활성화되어 있는지 확인합니다.
+
MetroCluster 쇼

. 중재자가 실행되고 있는지 확인합니다.
+
.. 중재자 가상 디스크를 표시합니다.
+
'스토리지 디스크 표시 컨테이너 유형 중재자

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. 권한 모드를 고급으로 설정합니다.
+
진일진일보한 것

+
....
 cluster_A::> set advanced
....
.. 중재자 라고 표시된 이니시에이터를 표시합니다.
+
'스토리지 iSCSI - 이니시에이터 표시 레이블 중재자'

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
.. AUSO(Automatic Unplanned Switchover) 장애 도메인의 상태를 확인합니다.
+
MetroCluster 쇼

+

NOTE: 다음 출력 예는 ONTAP 9.13.1 이상에 적용됩니다. ONTAP 9.12.1 이하 버전의 경우 AUSO 오류 도메인 상태는 이어야 합니다 `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----


. 필요에 따라 MetroCluster 자동 강제 전환을 구성합니다.
+
다음 명령은 고급 권한 수준에서만 사용할 수 있습니다.

+

IMPORTANT: 이 명령을 사용하기 전에 를 검토하십시오 link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["MetroCluster 자동 강제 적용 시 위험 및 제한 사항"].

+
`metrocluster modify -allow-auto-forced-switchover true`

+
....
cluster_A::*> metrocluster modify -allow-auto-forced-switchover true
....

