---
permalink: install-ip/using_rcf_generator.html 
sidebar: sidebar 
keywords: cabling, cable, component, link, site, management, network, hardware, component, switch, cluster, connection, management, data, configuring, configure, rcf, file, generator, RcfFileGenerator 
summary: RCF 파일을 올바르게 생성하려면 포트 테이블의 정보를 사용하는 방법을 이해해야 합니다. 
---
= 여러 MetroCluster IP 구성에서 포트 테이블을 사용하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RCF 파일을 올바르게 생성하려면 포트 테이블의 정보를 사용하는 방법을 이해해야 합니다.

.시작하기 전에
표를 사용하기 전에 다음 사항을 검토하십시오.

* 다음 표에는 사이트 A의 포트 사용량이 나와 있습니다 사이트 B에 동일한 케이블이 사용됩니다
* 서로 다른 속도의 포트(예: 100Gbps 포트와 40Gbps 포트 혼합)로 스위치를 구성할 수 없습니다.
* MetroCluster 포트 그룹(MetroCluster 1, MetroCluster 2 등)을 추적합니다. 이 정보는 이 구성 절차의 뒷부분에서 설명하는 대로 RcfFileGenerator 도구를 사용할 때 필요합니다.
* 모든 노드를 동일한 방식으로 케이블로 연결해야 합니다. 노드를 케이블로 연결하는 데 사용할 수 있는 다른 포트 조합 옵션이 있는 경우 모든 노드는 동일한 포트 조합을 사용해야 합니다. 예를 들어, 노드1의 E1A와 노드2의 E1A는 하나의 스위치에 연결해야 합니다. 마찬가지로 두 노드의 두 번째 포트를 두 번째 스위치에 연결해야 합니다.
*  https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["MetroCluster IP용 RcfFileGenerator입니다"^]는 각 스위치에 대한 포트별 케이블 연결 개요도 제공합니다. 이 케이블 연결 개요를 사용하여 케이블 연결을 확인하십시오.




== 스위치에 2개의 MetroCluster 구성을 케이블로 연결합니다

두 개 이상의 MetroCluster 구성을 스위치에 케이블로 연결할 경우, 해당 표에 따라 각 MetroCluster를 케이블로 연결합니다. 예를 들어, FAS2750과 AFF A700을 같은 스위치에 케이블로 연결하는 경우, FAS2750은 표 1의 "MetroCluster 1"에 따라, AFF A700은 표 2의 "MetroCluster 2" 또는 "MetroCluster 3"에 따라 케이블로 연결합니다. FAS2750과 AFF A700을 "MetroCluster 1"로 물리적으로 연결할 수 없습니다.



== 8노드 MetroCluster 구성에 케이블을 연결합니다

ONTAP 9.8 이하를 실행하는 MetroCluster 구성의 경우, 업그레이드를 전환하기 위해 수행되는 일부 절차에서는 임시 8노드 구성을 만들기 위해 구성에 두 번째 4노드 DR 그룹을 추가해야 합니다.  ONTAP 9.9.1부터 영구 8노드 MetroCluster 구성이 지원됩니다.

.이 작업에 대해
8노드 구성의 경우 위에 설명된 것과 동일한 방법을 사용합니다. 보조 MetroCluster 대신 4노드 DR 그룹을 추가로 케이블로 연결합니다.

예를 들어, 사용자의 구성에는 다음이 포함됩니다.

* Cisco 3132Q-V 스위치
* MetroCluster 1:FAS2750 플랫폼
* MetroCluster 2: AFF A700 플랫폼(이러한 플랫폼은 2번째 4노드 DR 그룹으로 추가됨)


.단계
. MetroCluster 1의 경우, FAS2750 플랫폼 테이블과 MetroCluster 1 인터페이스 행을 사용하여 Cisco 3132Q-V 스위치에 케이블을 연결합니다.
. MetroCluster 2(두 번째 DR 그룹)의 경우 AFF A700 플랫폼 테이블과 MetroCluster 2 인터페이스 행을 사용하여 Cisco 3132Q-V 스위치에 케이블을 연결합니다.

