---
permalink: disaster-recovery/task_verify_port_mcfc.html 
sidebar: sidebar 
keywords: verify, port, environmental, metrocluster, configuration 
summary: MetroCluster 구성을 준비하려면 노드에서 환경 변수를 설정한 다음 전원을 꺼야 합니다. 
---
= 포트 구성 확인(MetroCluster FC 구성만 해당)
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성을 준비하려면 노드에서 환경 변수를 설정한 다음 전원을 꺼야 합니다.

이 절차는 유지보수 모드의 교체 컨트롤러 모듈을 사용하여 수행됩니다.

포트 구성을 확인하는 단계는 FC 또는 CNA 포트가 이니시에이터 모드에서 사용되는 시스템에서만 필요합니다.

.단계
. 유지보수 모드에서 다음 명령을 입력하여 FC 포트 구성을 복원합니다.
+
'ucadmin modify -m fc -t initiatoradapter_name'입니다

+
이니시에이터 구성에서 포트 쌍 중 하나만 사용하려면 정확한 어댑터 이름을 입력합니다.

. 구성에 따라 다음 작업 중 하나를 수행합니다.
+
|===


| FC 포트 구성이 다음과 같은 경우 | 그러면... 


 a| 
두 포트도 동일합니다
 a| 
포트 쌍의 한 포트를 수정하면 다른 포트도 수정되기 때문에 시스템에서 메시지가 나타나면 y를 선택합니다.



 a| 
다릅니다
 a| 
.. 시스템에 의해 메시지가 나타나면 "n"을 선택합니다.
.. FC 포트 구성을 복원하려면 다음 명령을 입력합니다.


'ucadmin modify -m fc-t initiator|targetadapter_name'

|===
. 'halt' 명령어를 입력하여 Maintenance Mode를 종료한다
+
명령을 실행한 후 LOADER 프롬프트에서 시스템이 중지될 때까지 기다립니다.

. 구성 변경 사항을 적용하려면 노드를 다시 유지보수 모드로 부팅합니다.
+
boot_ONTAP maint를 선택합니다

. 다음 명령을 입력하여 변수 값을 확인합니다.
+
'ucadmin 쇼'

. 유지보수 모드를 종료하고 LOADER 프롬프트에서 "HALT"를 표시합니다

