---
permalink: disaster-recovery/task_cfg_switches_mcfc.html 
sidebar: sidebar 
keywords: configure, fc, switches, metrocluster, configuration 
summary: 재해 사이트에서 FC 스위치를 교체한 경우 공급업체별 절차를 사용하여 구성해야 합니다. 
---
= FC 스위치 구성(MetroCluster FC 구성만 해당)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재해 사이트에서 FC 스위치를 교체한 경우 공급업체별 절차를 사용하여 구성해야 합니다. 하나의 스위치를 구성하고 정상 작동하는 사이트의 스토리지 액세스가 영향을 받지 않는지 확인한 다음 두 번째 스위치를 구성해야 합니다.

.관련 작업
link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["9.0을 사용하는 경우 FC 스위치에 대한 포트 할당"]

link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["ONTAP 9.1 이상을 사용할 경우 FC 스위치에 대한 포트 할당"]



== 사이트 재해 후 Brocade FC 스위치 구성

이 Brocade 관련 절차를 사용하여 교체 스위치를 구성하고 ISL 포트를 활성화해야 합니다.

.이 작업에 대해
이 절차의 예는 다음과 같은 가정을 기반으로 합니다.

* 사이트 A는 재해 사이트입니다.
* fc_switch_a_1이 교체되었습니다.
* fc_switch_a_2가 교체되었습니다.
* 사이트 B는 정상적인 사이트입니다.
* fc_switch_B_1이 정상 상태임.
* fc_switch_B_2가 정상 상태임.


FC 스위치에 케이블을 연결할 때 지정한 포트 할당을 사용하고 있는지 확인해야 합니다.

* link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["ONTAP 9.0을 사용하는 경우 FC 스위치에 대한 포트 할당"]
* link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["ONTAP 9.1 이상을 사용할 경우 FC 스위치에 대한 포트 할당"]


이 예에는 FC-to-SAS 브릿지 2개가 나와 있습니다. 브리지가 더 있는 경우 추가 포트를 비활성화한 후 활성화해야 합니다.

.단계
. 새 스위치를 부팅하고 사전 구성합니다.
+
.. 새 스위치의 전원을 켜고 부팅하십시오.
.. 스위치의 펌웨어 버전이 다른 FC 스위치의 버전과 일치하는지 확인합니다.
+
'firmwareswHow'입니다

.. 다음 항목에서 설명하는 대로 새 스위치를 구성하면 스위치에서 조닝 구성 단계가 생략됩니다.
+
link:../install-fc/index.html["패브릭 연결 MetroCluster 설치 및 구성"]

+
link:../install-stretch/concept_considerations_differences.html["스트레치 MetroCluster 설치 및 구성"]

.. 스위치를 영구적으로 비활성화합니다.
+
'위치cfgpersistentdisable'

+
재부팅 또는 빠른 부팅 후에도 스위치는 비활성화 상태로 유지됩니다. 이 명령어를 사용할 수 없으면 'witchdisable' 명령어를 사용해야 한다.

+
다음 예에서는 Brocad데SwitchA에 대한 명령을 보여 줍니다.

+
[listing]
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
+
다음 예에서는 Brocadad데SwitchB에 대한 명령을 보여 줍니다.

+
[listing]
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----


. 새 스위치의 전체 구성:
+
.. 정상 사이트에서 ISL 사용:
+
포트 번호 portcfgpersistentenable 포트 번호

+
[listing]
----
FC_switch_B_1:admin> portcfgpersistentenable 10
FC_switch_B_1:admin> portcfgpersistentenable 11
----
.. 교체 스위치에서 ISL 활성화:
+
포트 번호 portcfgpersistentenable 포트 번호

+
[listing]
----
FC_switch_A_1:admin> portcfgpersistentenable 10
FC_switch_A_1:admin> portcfgpersistentenable 11
----
.. 교체 스위치(이 예에서는 FC_SWITCH_A_1)에서 ISL이 온라인 상태인지 확인합니다.
+
재치쇼

+
[listing]
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 71.2
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       4
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
==============================================
...
10   10    030A00 id   16G     Online  FC E-Port 10:00:00:05:33:86:89:cb "FC_switch_A_1"
11   11    030B00 id   16G     Online  FC E-Port 10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)
...
----


. 스위치를 영구적으로 활성화합니다.
+
'위치cfgpersistentenable'

. 포트가 온라인 상태인지 확인합니다.
+
재치쇼





== 사이트 재해 후 Cisco FC 스위치 구성

Cisco 관련 절차를 사용하여 교체 스위치를 구성하고 ISL 포트를 활성화해야 합니다.

.이 작업에 대해
이 절차의 예는 다음과 같은 가정을 기반으로 합니다.

* 사이트 A는 재해 사이트입니다.
* fc_switch_a_1이 교체되었습니다.
* fc_switch_a_2가 교체되었습니다.
* 사이트 B는 정상적인 사이트입니다.
* fc_switch_B_1이 정상 상태임.
* fc_switch_B_2가 정상 상태임.


.단계
. 스위치 구성:
+
.. 을 참조하십시오 link:../install-fc/index.html["패브릭 연결 MetroCluster 설치 및 구성"]
.. 의 스위치 구성 단계를 따릅니다 link:../install-fc/task_reset_the_cisco_fc_switch_to_factory_defaults.html["Cisco FC 스위치 구성"] "Cisco FC 스위치에서 조닝 구성" 섹션의 _ 제외:
+
이 절차의 뒷부분에서 조닝을 구성합니다.



. 정상 스위치(이 예에서는 FC_SWITCH_B_1)에서 ISL 포트를 활성화합니다.
+
다음 예는 포트를 활성화하는 명령을 보여줍니다.

+
[listing]
----
FC_switch_B_1# conf t
FC_switch_B_1(config)# int fc1/14-15
FC_switch_B_1(config)# no shut
FC_switch_B_1(config)# end
FC_switch_B_1# copy running-config startup-config
FC_switch_B_1#
----
. show interface brief 명령을 사용하여 ISL 포트가 작동하는지 확인합니다.
. 패브릭에서 조닝 정보를 검색합니다.
+
다음 예에서는 조닝 구성을 분산하는 명령을 보여 줍니다.

+
[listing]
----
FC_switch_B_1(config-zone)# zoneset distribute full vsan 10
FC_switch_B_1(config-zone)# zoneset distribute full vsan 20
FC_switch_B_1(config-zone)# end
----
+
FC_SWITCH_B_1은 "VSAN 10" 및 "VSAN 20"에 대한 Fabric의 다른 모든 스위치에 배포되며 조닝 정보는 FC_SWITCH_A_1에서 검색됩니다.

. 정상 스위치에서 파트너 스위치에서 조닝 정보가 올바르게 검색되는지 확인합니다.
+
'조수 구역'

+
[listing]
----
FC_switch_B_1# show zone
zone name FC-VI_Zone_1_10 vsan 10
  interface fc1/1 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/2 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/1 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/2 swwn 20:00:54:7f:ee:b8:24:c0

zone name STOR_Zone_1_20_25A vsan 20
  interface fc1/5 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0

zone name STOR_Zone_1_20_25B vsan 20
  interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/5 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0
FC_switch_B_1#
----
. 스위치 Fabric에 있는 스위치의 WWN(World Wide Name)을 확인합니다.
+
이 예에서 두 스위치 WWN은 다음과 같습니다.

+
** fc_switch_a_1:20:00:54:7F:ee:B8:24:c0
** fc_switch_B_1:20:00:54:7F:ee:C6:80:78


+
[listing]
----
FC_switch_B_1# show wwn switch
Switch WWN is 20:00:54:7f:ee:c6:80:78
FC_switch_B_1#

FC_switch_A_1# show wwn switch
Switch WWN is 20:00:54:7f:ee:b8:24:c0
FC_switch_A_1#
----
. 영역에 대한 구성 모드를 시작하고 두 스위치의 스위치 WWN에 속하지 않는 영역 구성원을 제거합니다.
+
--
멤버 인터페이스 없음 - IDE WWN이 찌푸렸다

이 예제에서 다음 멤버는 Fabric에 있는 스위치 중 하나의 WWN과 연결되지 않으므로 제거해야 합니다.

** 존 이름 FC-VI_Zone_1_10 VSAN 10
+
*** 인터페이스 FC1/1은 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/2 swwn 20:00:54:7F:ee:E3:86:50





NOTE: AFF A700 및 FAS9000 시스템은 FC-VI 포트 4개를 지원합니다. FC-VI 영역에서 포트 4개를 모두 제거해야 합니다.

** 존 이름 STOR_Zone_1_20_25A VSAN 20
+
*** 인터페이스 FC1/5 swwn 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/8 swwn 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/9 swwn 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/10이 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/11이 20:00:54:7F:ee:E3:86:50


** 존 이름 STOR_Zone_1_20_25B VSAN 20
+
*** 인터페이스 FC1/8 swwn 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/9 swwn 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/10이 20:00:54:7F:ee:E3:86:50
*** 인터페이스 FC1/11이 20:00:54:7F:ee:E3:86:50




다음 예는 이러한 인터페이스를 제거하는 방법을 보여줍니다.

[listing]
----

 FC_switch_B_1# conf t
 FC_switch_B_1(config)# zone name FC-VI_Zone_1_10 vsan 10
 FC_switch_B_1(config-zone)# no member interface fc1/1 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/2 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25A vsan 20
 FC_switch_B_1(config-zone)# no member interface fc1/5 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25B vsan 20
 FC_switch_B_1(config-zone)# no member interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# save running-config startup-config
 FC_switch_B_1(config-zone)# zoneset distribute full 10
 FC_switch_B_1(config-zone)# zoneset distribute full 20
 FC_switch_B_1(config-zone)# end
 FC_switch_B_1# copy running-config startup-config
----
--


. [[step8]] 새 스위치의 포트를 영역에 추가합니다.
+
다음 예에서는 교체 스위치의 케이블이 이전 스위치와 같다고 가정합니다.

+
[listing]
----

 FC_switch_B_1# conf t
 FC_switch_B_1(config)# zone name FC-VI_Zone_1_10 vsan 10
 FC_switch_B_1(config-zone)# member interface fc1/1 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/2 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25A vsan 20
 FC_switch_B_1(config-zone)# member interface fc1/5 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25B vsan 20
 FC_switch_B_1(config-zone)# member interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# save running-config startup-config
 FC_switch_B_1(config-zone)# zoneset distribute full 10
 FC_switch_B_1(config-zone)# zoneset distribute full 20
 FC_switch_B_1(config-zone)# end
 FC_switch_B_1# copy running-config startup-config
----
. 조닝이 올바르게 구성되어 있는지 'Zone을 표시합니다'
+
다음 출력 예에서는 세 개의 영역을 보여 줍니다.

+
[listing]
----

 FC_switch_B_1# show zone
   zone name FC-VI_Zone_1_10 vsan 10
     interface fc1/1 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/2 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/1 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/2 swwn 20:00:54:7f:ee:b8:24:c0

   zone name STOR_Zone_1_20_25A vsan 20
     interface fc1/5 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0

   zone name STOR_Zone_1_20_25B vsan 20
     interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/5 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0
 FC_switch_B_1#
----

