---
permalink: disaster-recovery/task_complete_recovery.html 
sidebar: sidebar 
keywords: object, fabricpool, mirror, co-located, metrocluster, disaster, site, destroy, reestablish, store, reestablish, store, configuration, verify, license, replace, node, perform, switchback, successful, root, aggregates, replacement, health, reconfiguring, reconfigure, ontap, mediator, service, ip, configuration 
summary: FabricPool 미러에 있는 오브젝트 저장소 중 하나가 MetroCluster 재해 사이트와 공동으로 배치되고 폐기된 경우 오브젝트 저장소와 FabricPool 미러를 재설정해야 합니다. 
---
= 복구를 완료하는 중입니다
:icons: font
:imagesdir: ../media/




== FabricPool 구성에 대한 오브젝트 저장소를 다시 설정합니다

FabricPool 미러에 있는 오브젝트 저장소 중 하나가 MetroCluster 재해 사이트와 공동으로 배치되고 폐기된 경우 오브젝트 저장소와 FabricPool 미러를 재설정해야 합니다.

.이 작업에 대해
* 오브젝트 저장소가 원격이고 MetroCluster 사이트가 손상된 경우 오브젝트 저장소를 재구축할 필요가 없으며 원본 오브젝트 저장소 구성과 콜드 데이터 콘텐츠가 보존됩니다.
* FabricPool 구성에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"^].


.단계
. 의 "MetroCluster 구성에서 FabricPool 미러 교체" 절차를 따릅니다 link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"^].




== 교체된 노드에서 라이센스 확인

장애가 발생한 노드가 표준(노드 잠김) 라이센스가 필요한 ONTAP 기능을 사용 중인 경우 교체 노드에 대한 새 라이센스를 설치해야 합니다. 표준 라이센스가 있는 기능의 경우 클러스터의 각 노드에 기능에 대한 자체 키가 있어야 합니다.

라이센스 키를 설치하기 전까지는 표준 라이센스가 필요한 기능을 교체 노드에서 계속 사용할 수 있습니다. 그러나 손상된 노드가 클러스터의 유일한 노드인 경우 해당 기능에 대한 라이센스가 있으면 기능을 변경할 수 없습니다. 또한 노드에서 라이센스가 없는 기능을 사용하면 라이센스 계약을 준수하지 않을 수 있으므로 가능한 한 빨리 교체 노드에 교체 라이센스 키 또는 키를 설치해야 합니다.

라이센스 키는 28자 형식이어야 합니다.

라이센스 키를 설치할 수 있는 90일의 유예 기간이 있습니다. 유예 기간이 지나면 모든 이전 라이센스가 무효화됩니다. 유효한 라이센스 키를 설치한 후 유예 기간이 끝나기 전에 모든 키를 24시간 동안 설치해야 합니다.


NOTE: 사이트의 모든 노드를 교체한 경우(2노드 MetroCluster 구성의 경우 단일 노드), 교체 노드에 라이센스 키를 스위치백 전에 설치해야 합니다.

.단계
. 노드에서 라이센스를 식별합니다.
+
'라이선스 쇼'

+
다음 예에서는 시스템의 라이센스에 대한 정보를 표시합니다.

+
[listing]
----
cluster_B::>  license show
         (system license show)

Serial Number: 1-80-00050
Owner: site1-01
Package           Type       Description             Expiration
-------          -------     -------------           -----------
Base             license     Cluster Base License        -
NFS              site        NFS License                 -
CIFS             site        CIFS License                -
iSCSI            site        iSCSI License               -
FCP              site        FCP License                 -
FlexClone        site        FlexClone License           -

6 entries were displayed.
----
. 스위치백 후 노드에 대한 라이센스가 올바른지 확인합니다.
+
'MetroCluster check license show'

+
다음 예는 노드에 적합한 라이센스를 표시합니다.

+
[listing]
----
cluster_B::> metrocluster check license show

Cluster           Check                             Result
-------           -------                           -------------
Cluster_B         negotiated-switchover-ready       not-applicable
NFS               switchback-ready                  not-applicable
CIFS              job-schedules                     ok
iSCSI             licenses                          ok
FCP               periodic-check-enabled            ok
----
. 새 라이센스 키가 필요한 경우 소프트웨어 라이센스 아래의 내 지원 섹션에 있는 NetApp Support 사이트에서 교체용 라이센스 키를 받으십시오.
+

NOTE: 필요한 새 라이센스 키는 자동으로 생성되어 파일의 이메일 주소로 전송됩니다. 30일 이내에 라이센스 키가 포함된 이메일을 받지 못한 경우 기술 지원 부서에 문의하십시오.

. 각 라이센스 키 설치:
+
'시스템 라이선스 추가 라이선스 코드 라이선스 키, 라이선스 키...+'

. 필요한 경우 이전 라이센스를 제거합니다.
+
.. 사용하지 않는 라이센스 확인:
+
라이선스 정리 - 미사용 - 시뮬레이션

.. 목록이 올바르면 사용하지 않는 라이센스를 제거합니다.
+
라이선스 정리 - 미사용







== 스위치백을 수행합니다

MetroCluster 구성을 복구한 후 MetroCluster 스위치백 작업을 수행할 수 있습니다. MetroCluster 스위치백 작업을 수행하면 재해 사이트의 동기식 소스 스토리지 가상 머신(SVM)이 활성화되어 로컬 디스크 풀에서 데이터를 제공하는 구성을 정상 운영 상태로 되돌릴 수 있습니다.

.시작하기 전에
* 재해 클러스터가 정상적으로 작동하는 클러스터로 전환되어야 합니다.
* 데이터 및 루트 애그리게이트에 대해 복구를 수행해야 합니다.
* 정상적인 클러스터 노드는 HA 페일오버 상태가 아니어야 합니다(모든 노드가 각 HA 쌍에 대해 작동 및 실행 중이어야 함).
* 재해 사이트 컨트롤러 모듈은 HA 테이크오버 모드가 아닌 완전히 부팅되어야 합니다.
* 루트 애그리게이트는 미러링해야 합니다.
* ISL(Inter-Switch Link)이 온라인 상태여야 합니다.
* 필요한 라이센스는 시스템에 설치해야 합니다.


.단계
. 모든 노드가 설정 상태인지 확인합니다.
+
'MetroCluster node show'

+
다음 예제에서는 enabled 상태의 노드를 표시합니다.

+
[listing]
----
cluster_B::>  metrocluster node show

DR                        Configuration  DR
Group Cluster Node        State          Mirroring Mode
----- ------- ----------- -------------- --------- --------------------
1     cluster_A
              node_A_1    configured     enabled   heal roots completed
              node_A_2    configured     enabled   heal roots completed
      cluster_B
              node_B_1    configured     enabled   waiting for switchback recovery
              node_B_2    configured     enabled   waiting for switchback recovery
4 entries were displayed.
----
. 모든 SVM에서 재동기화가 완료되었는지 확인합니다.
+
'MetroCluster vserver show'

. 복구 작업에 의해 수행되는 자동 LIF 마이그레이션이 성공적으로 완료되었는지 확인합니다.
+
'MetroCluster check lif show'

. 정상적인 클러스터에 있는 모든 노드에서 MetroCluster 스위치백 명령을 실행하여 스위치백을 수행합니다.
. 스위치백 작업의 진행률을 확인합니다.
+
MetroCluster 쇼

+
출력에 "대기 중 - 스위치백"이 표시되면 스위치백 작업이 진행 중입니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                switchover
                          AUSO Failure Domain -
Remote: cluster_A         Configuration state configured
                          Mode                waiting-for-switchback
                          AUSO Failure Domain -
----
+
출력이 "정상"으로 표시되면 스위치백 작업이 완료된 것입니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain -
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain -
----
+
스위치백을 완료하는 데 시간이 오래 걸리는 경우 고급 권한 수준에서 다음 명령을 사용하여 진행 중인 기준선의 상태를 확인할 수 있습니다.

+
'MetroCluster config-replication resync-status show'를 선택합니다

. SnapMirror 또는 SnapVault 구성을 다시 설정합니다.
+
ONTAP 8.3에서는 MetroCluster 스위치백 작업 후 손실된 SnapMirror 구성을 수동으로 재설정해야 합니다. ONTAP 9.0 이상에서는 관계가 자동으로 다시 설정됩니다.





== 스위치백을 성공적으로 확인하는 중입니다

스위치백을 수행한 후 모든 애그리게이트 및 SVM(스토리지 가상 머신)이 온라인 상태로 전환되었는지 확인할 수 있습니다.

.단계
. 전환된 데이터 애그리게이트가 다시 전환되는지 확인합니다.
+
'스토리지 집계 쇼'

+
다음 예제에서 노드 B2의 aggr_b2는 다시 전환되었습니다.

+
[listing]
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal

node_A_1::> aggr show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2          -         -     - unknown      - node_A_1
----
+
재해 사이트에 미러링되지 않은 애그리게이트가 포함되어 있고 미러링되지 않은 애그리게이트가 더 이상 존재하지 않는 경우, 스토리지 aggregate show 명령의 출력에 ""알 수 없음"" 상태가 표시됩니다. 기술 지원 부서에 문의하여 미러링되지 않은 애그리게이트에 대한 오래된 항목을 제거하십시오.

. 정상 작동하는 클러스터의 모든 동기화 대상 SVM이 휴면 상태(관리 상태 "최고" 표시)이고 재해 클러스터의 동기화 소스 SVM이 실행 중인지 확인합니다.
+
'vserver show-subtype sync-source'를 선택합니다

+
[listing]
----
node_B_1::> vserver show -subtype sync-source
                               Admin      Root                       Name    Name
Vserver     Type    Subtype    State      Volume     Aggregate       Service Mapping
----------- ------- ---------- ---------- ---------- ----------      ------- -------
...
vs1a        data    sync-source
                               running    vs1a_vol   node_B_2        file    file
                                                                     aggr_b2

node_A_1::> vserver show -subtype sync-destination
                               Admin      Root                         Name    Name
Vserver            Type    Subtype    State      Volume     Aggregate  Service Mapping
-----------        ------- ---------- ---------- ---------- ---------- ------- -------
...
cluster_A-vs1a-mc  data    sync-destination
                                      stopped    vs1a_vol   sosb_      file    file
                                                                       aggr_b2
----
+
MetroCluster 구성의 동기화 대상 애그리게이트에는 쉽게 식별할 수 있도록 이름에 접미사 "-mc"가 자동으로 추가됩니다.

. MetroCluster operation show 명령을 사용하여 스위치백 작업이 성공했는지 확인합니다.
+
|===


| 명령 출력에 다음과 같은 내용이 표시되는 경우 | 그러면... 


 a| 
스위치백 작업 상태가 성공입니다.
 a| 
스위치백 프로세스가 완료되었으며 시스템 작동을 계속할 수 있습니다.



 a| 
스위치백 작업 또는 스위치백 연속 - 상담원 작업이 부분적으로 성공했음을 나타냅니다.
 a| 
MetroCluster operation show 명령의 출력에 제공된 권장 해결 방법을 수행합니다.

|===


반대 방향으로 스위치백을 수행하려면 이전 섹션을 반복해야 합니다. site_A가 site_B의 전환을 수행하는 경우 site_B가 site_A의 전환을 수행합니다



== 교체 노드의 루트 애그리게이트를 미러링합니다

디스크를 교체한 경우 재해 사이트에서 새 노드의 루트 애그리게이트를 미러링해야 합니다.

.단계
. 재해 사이트에서 미러링되지 않은 애그리게이트를 식별합니다.
+
'스토리지 집계 쇼'

+
[listing]
----
cluster_A::> storage aggregate show

Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
node_A_1_aggr0
            1.49TB   74.12GB   95% online       1 node_A_1         raid4,
                                                                   normal
node_A_2_aggr0
            1.49TB   74.12GB   95% online       1 node_A_2         raid4,
                                                                   normal
node_A_1_aggr1
            1.49TB   74.12GB   95% online       1 node_A_1         raid 4, normal
                                                                   mirrored
node_A_2_aggr1
            1.49TB   74.12GB   95% online       1 node_A_2         raid 4, normal
                                                                   mirrored
4 entries were displayed.

cluster_A::>
----
. 루트 애그리게이트 중 하나를 미러링합니다.
+
'스토리지 집계 미러 집계 루트 애그리게이트'

+
다음 예에서는 명령이 디스크를 선택하는 방법과 Aggregate를 미러링할 때 확인을 위한 프롬프트를 표시합니다.

+
[listing]
----
cluster_A::> storage aggregate mirror -aggregate node_A_2_aggr0

Info: Disks would be added to aggregate "node_A_2_aggr0" on node "node_A_2" in
      the following manner:

      Second Plex

        RAID Group rg0, 3 disks (block checksum, raid4)
          Position   Disk                      Type                  Size
          ---------- ------------------------- ---------- ---------------
          parity     2.10.0                    SSD                      -
          data       1.11.19                   SSD                894.0GB
          data       2.10.2                    SSD                894.0GB

      Aggregate capacity available for volume use would be 1.49TB.

Do you want to continue? {y|n}: y

cluster_A::>
----
. 루트 애그리게이트 미러링이 완료되었는지 확인:
+
'스토리지 집계 쇼'

+
다음 예에서는 루트 애그리게이트가 미러링되는 것을 보여 줍니다.

+
[listing]
----
cluster_A::> storage aggregate show

Aggregate     Size Available Used% State   #Vols  Nodes       RAID Status
--------- -------- --------- ----- ------- ------ ----------- ------------
node_A_1_aggr0
            1.49TB   74.12GB   95% online       1 node_A_1    raid4,
                                                              mirrored,
                                                              normal
node_A_2_aggr0
            2.24TB   838.5GB   63% online       1 node_A_2    raid4,
                                                              mirrored,
                                                              normal
node_A_1_aggr1
            1.49TB   74.12GB   95% online       1 node_A_1    raid4,
                                                              mirrored,
                                                              normal
node_A_2_aggr1
            1.49TB   74.12GB   95% online       1 node_A_2    raid4
                                                              mirrored,
                                                              normal
4 entries were displayed.

cluster_A::>
----
. 다른 루트 애그리게이트에 대해 이 단계를 반복합니다.
+
미러링된 상태가 없는 루트 애그리게이트는 미러링해야 합니다.





== ONTAP 중재자 서비스 재구성(MetroCluster IP 구성)

ONTAP 중재자 서비스로 구성된 MetroCluster IP 구성이 있는 경우 중재자와 연결을 제거하고 다시 구성해야 합니다.

.시작하기 전에
* ONTAP 중재자 서비스를 위한 IP 주소와 사용자 이름 및 암호가 있어야 합니다.
* ONTAP 중재자 서비스는 Linux 호스트에서 구성 및 운영되어야 합니다.


.단계
. 기존 ONTAP 중재자 구성을 제거합니다.
+
'MetroCluster configuration-settings 중재자 제거

. ONTAP 중재자 구성 재구성:
+
MetroCluster 설정-설정 중재자 추가-주소 중재자-IP-주소





== MetroCluster 구성 상태 확인

MetroCluster 구성 상태를 점검하여 올바르게 작동하는지 확인해야 합니다.

.단계
. 각 클러스터에서 MetroCluster가 정상 모드로 구성되어 있는지 확인합니다.
+
MetroCluster 쇼

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
. 각 노드에서 미러링이 활성화되어 있는지 확인합니다.
+
'MetroCluster node show'

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
. MetroCluster 구성 요소가 정상인지 점검한다.
+
'MetroCluster check run

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the `metrocluster check show -instance` command or sub-commands in `metrocluster check` directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run `metrocluster switchover -simulate` or `metrocluster switchback -simulate`, respectively.
----
. 상태 경고가 없는지 확인합니다.
+
'시스템 상태 경고 표시

. 스위치오버 작업 시뮬레이션:
+
.. 노드의 프롬프트에서 고급 권한 레벨로 변경합니다.
+
세트 프리빌리지 고급

+
고급 모드로 계속 진행하고 고급 모드 프롬프트(*>)를 보려면 "y"로 응답해야 합니다.

.. '-simulate' 파라미터로 절체 동작 수행:
+
'MetroCluster switchover-simulate

.. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다



. ONTAP 중재자 서비스를 사용하는 MetroCluster IP 구성의 경우 중재자 서비스가 작동 중인지 확인합니다.
+
.. 중재 디스크가 시스템에 표시되는지 확인합니다.
+
스토리지 페일오버 사서함-디스크 쇼

+
다음 예에서는 메일박스 디스크가 인식되었음을 보여 줍니다.

+
[listing]
----
node_A_1::*> storage failover mailbox-disk show
                 Mailbox
Node             Owner     Disk    Name        Disk UUID
-------------     ------   -----   -----        ----------------
sti113-vsim-ucs626g
.
.
     local     0m.i2.3L26      7BBA77C9:AD702D14:831B3E7E:0B0730EE:00000000:00000000:00000000:00000000:00000000:00000000
     local     0m.i2.3L27      928F79AE:631EA9F9:4DCB5DE6:3402AC48:00000000:00000000:00000000:00000000:00000000:00000000
     local     0m.i1.0L60      B7BCDB3C:297A4459:318C2748:181565A3:00000000:00000000:00000000:00000000:00000000:00000000
.
.
.
     partner   0m.i1.0L14      EA71F260:D4DD5F22:E3422387:61D475B2:00000000:00000000:00000000:00000000:00000000:00000000
     partner   0m.i2.3L64      4460F436:AAE5AB9E:D1ED414E:ABF811F7:00000000:00000000:00000000:00000000:00000000:00000000
28 entries were displayed.
----
.. 고급 권한 레벨로 변경:
+
세트 프리빌리지 고급

.. 메일박스 LUN이 시스템에 표시되는지 확인합니다.
+
'Storage iSCSI-initiator show'를 선택합니다

+
출력에는 메일박스 LUN이 표시됩니다.

+
[listing]
----

Node    Type       Label      Target Portal     Target Name                                 Admin/Op
----    ----       --------   ---------    --------- --------------------------------       --------
.
.
.
.node_A_1
               mailbox
                     mediator 172.16.254.1    iqn.2012-05.local:mailbox.target.db5f02d6-e3d3    up/up
.
.
.
17 entries were displayed.
----
.. 관리 권한 수준으로 돌아가기:
+
'Set-Privilege admin'입니다




