---
permalink: disaster-recovery/task_boot_ontap_mcip.html 
sidebar: sidebar 
keywords: metrocluster, ip, configuration, replacement, controller, module, disaster, site, boot 
summary: 재해 사이트의 교체 노드를 ONTAP 운영 체제로 부팅해야 합니다. 
---
= MetroCluster IP 구성의 교체 컨트롤러 모듈에서 ONTAP로 부팅합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재해 사이트의 교체 노드를 ONTAP 운영 체제로 부팅해야 합니다.

.이 작업에 대해
이 작업은 유지보수 모드의 재해 사이트에 있는 노드에서 시작합니다.

.단계
. 교체 노드 중 하나에서 LOADER 프롬프트인 HALT로 나갑니다
. 부팅 메뉴 'boot_ontap menu'를 표시합니다
. 부팅 메뉴에서 옵션 6, * 백업 구성에서 플래시 업데이트 * 를 선택합니다.
+
시스템이 두 번 부팅됩니다. 계속 진행하라는 메시지가 나타나면 "예"로 답해야 합니다. 두 번째 부팅 후 시스템 ID 불일치에 대한 메시지가 나타나면 y로 응답해야 합니다.

+

NOTE: 사용한 교체 컨트롤러 모듈의 NVRAM 내용을 지우지 않은 경우 "패닉: NVRAM 컨텐츠가 잘못되었습니다."라는 패닉 메시지가 나타날 수 있습니다 이 경우 시스템을 ONTAP 프롬프트(boot_ontap menu)로 다시 부팅합니다. 그런 다음 해야 합니다 <<Reset-the-boot-recovery,boot_recovery 및 rdb_corrupt boots를 재설정합니다>>

+
** 계속하려면 확인 프롬프트:
+
[listing]
----
Selection (1-9)? 6

This will replace all flash-based configuration with the last backup to
disks. Are you sure you want to continue?: yes
----
** 시스템 ID 불일치 프롬프트:
+
[listing]
----
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
----


. 정상적인 사이트에서 올바른 파트너 시스템 ID가 노드에 적용되었는지 확인합니다.
+
MetroCluster node show-fields node-systemid, ha-partner-systemid, dr-partner-systemid, dr-auxiliary-systemid

+
--
이 예에서는 출력에 다음과 같은 새 시스템 ID가 나타나야 합니다.

** Node_A_1:1574774970
** Node_A_2:1574774991


"ha-partner-systemid" 열에 새 시스템 ID가 표시되어야 합니다.

[listing]
----
metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid

dr-group-id cluster    node      node-systemid ha-partner-systemid dr-partner-systemid dr-auxiliary-systemid
----------- ---------- --------  ------------- ------ ------------ ------ ------------ ------ --------------
1           Cluster_A  Node_A_1  1574774970    1574774991          4068741254          4068741256
1           Cluster_A  Node_A_2  1574774991    1574774970          4068741256          4068741254
1           Cluster_B  Node_B_1  -             -                   -                   -
1           Cluster_B  Node_B_2  -             -                   -                   -
4 entries were displayed.
----
--
. 파트너 시스템 ID가 올바르게 설정되지 않은 경우 올바른 값을 수동으로 설정해야 합니다.
+
.. 노드를 중지하고 노드에 로더 프롬프트를 표시합니다.
.. partner-sysid bootarg의 현재 값을 확인합니다.
+
'printenv'

.. 값을 올바른 파트너 시스템 ID로 설정합니다.
+
'setenv PARTNER-sysid PARTNER-sysid

.. 노드를 부팅합니다.
+
부트 ONTAP

.. 필요한 경우 다른 노드에서 이러한 하위 단계를 반복합니다.


. 재해 사이트의 교체 노드가 스위치백 준비가 되었는지 확인합니다.
+
'MetroCluster node show'

+
교체 노드가 스위치백 복구 모드를 기다리고 있어야 합니다. 대신 정상 모드인 경우 교체 노드를 재부팅할 수 있습니다. 그런 다음 노드가 스위치백 복구 모드를 기다리고 있어야 합니다.

+
다음 예에서는 교체 노드가 스위치백 준비가 되었음을 보여줍니다.

+
[listing]
----
cluster_B::> metrocluster node show
DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_B
              node_B_1           configured     enabled   switchover completed
              node_B_2           configured     enabled   switchover completed
      cluster_A
              node_A_1           configured     enabled   waiting for switchback recovery
              node_A_2           configured     enabled   waiting for switchback recovery
4 entries were displayed.

cluster_B::>
----
. MetroCluster 연결 구성 설정을 확인합니다.
+
'MetroCluster configuration-settings connection show'를 선택합니다

+
구성 상태가 완료로 표시되어야 합니다.

+
[listing]
----
cluster_B::*> metrocluster configuration-settings connection show
DR                    Source          Destination
Group Cluster Node    Network Address Network Address Partner Type Config State
----- ------- ------- --------------- --------------- ------------ ------------
1     cluster_B
              node_B_2
                 Home Port: e5a
                      172.17.26.13    172.17.26.12    HA Partner   completed
                 Home Port: e5a
                      172.17.26.13    172.17.26.10    DR Partner   completed
                 Home Port: e5a
                      172.17.26.13    172.17.26.11    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.12    HA Partner   completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.10    DR Partner   completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.11    DR Auxiliary completed
              node_B_1
                 Home Port: e5a
                      172.17.26.12    172.17.26.13    HA Partner   completed
                 Home Port: e5a
                      172.17.26.12    172.17.26.11    DR Partner   completed
                 Home Port: e5a
                      172.17.26.12    172.17.26.10    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.13    HA Partner   completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.11    DR Partner   completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.10    DR Auxiliary completed
      cluster_A
              node_A_2
                 Home Port: e5a
                      172.17.26.11    172.17.26.10    HA Partner   completed
                 Home Port: e5a
                      172.17.26.11    172.17.26.12    DR Partner   completed
                 Home Port: e5a
                      172.17.26.11    172.17.26.13    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.11    172.17.27.10    HA Partner   completed
                 Home Port: e5b
                      172.17.27.11    172.17.27.12    DR Partner   completed
                 Home Port: e5b
                      172.17.27.11    172.17.27.13    DR Auxiliary completed
              node_A_1
                 Home Port: e5a
                      172.17.26.10    172.17.26.11    HA Partner   completed
                 Home Port: e5a
                      172.17.26.10    172.17.26.13    DR Partner   completed
                 Home Port: e5a
                      172.17.26.10    172.17.26.12    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.10    172.17.27.11    HA Partner   completed
                 Home Port: e5b
                      172.17.27.10    172.17.27.13    DR Partner   completed
                 Home Port: e5b
                      172.17.27.10    172.17.27.12    DR Auxiliary completed
24 entries were displayed.

cluster_B::*>
----
. 재해 사이트의 다른 노드에서 이전 단계를 반복합니다.




=== [[Reset-the-boot-recovery]] boot_recovery와 RDB_corrupt boots를 재설정합니다

[role="lead"]
필요한 경우 boot_recovery 및 rdb_corrupt_boots를 재설정할 수 있습니다

.단계
. 노드를 다시 LOADER 프롬프트로 중단합니다.
+
[listing]
----
node_A_1::*> halt -node _node-name_
----
. 다음 boots가 설정되었는지 확인합니다.
+
[listing]
----
LOADER> printenv bootarg.init.boot_recovery
LOADER> printenv bootarg.rdb_corrupt
----
. bootarg 중 하나가 값으로 설정된 경우 설정을 해제하고 ONTAP를 부팅합니다.
+
[listing]
----
LOADER> unsetenv bootarg.init.boot_recovery
LOADER> unsetenv bootarg.rdb_corrupt
LOADER> saveenv
LOADER> bye
----

