---
permalink: transition/concept_switchover_and_switchback_operations_during_transition.html 
sidebar: sidebar 
keywords: stage, transition, process, metrocluster, switchover, heal, switchback, operation, fc, ip, workflow 
summary: 전환 프로세스의 단계에 따라 MetroCluster 전환, 복구 및 스위치백 작업에서 MetroCluster FC 또는 MetroCluster IP 워크플로우를 사용합니다. 
---
= 무중단 전환 중 전환, 복구, 스위치백 작업
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 프로세스의 단계에 따라 MetroCluster 전환, 복구 및 스위치백 작업에서 MetroCluster FC 또는 MetroCluster IP 워크플로우를 사용합니다.

다음 표에서는 전환 프로세스의 여러 단계에서 사용되는 워크플로우를 보여 줍니다. 일부 단계에서는 스위치오버 및 스위치백을 지원하지 않습니다.

* MetroCluster FC 워크플로우에서 스위치오버, 복구 및 스위치백 단계는 MetroCluster FC 구성에서 사용되는 단계입니다.
* MetroCluster IP 워크플로우에서 스위치오버, 복구 및 스위치백 단계는 MetroCluster IP 구성에서 사용되는 단계입니다.
* 통합 워크플로우에서 FC 노드와 IP 노드를 모두 구성할 경우, 통계청 또는 USO 수행 여부에 따라 단계가 달라집니다. 자세한 내용은 표에 나와 있습니다.


전환, 복구 및 스위치백을 위한 MetroCluster FC 및 IP 워크플로우에 대한 자세한 내용은 을 참조하십시오 link:../manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html["MetroCluster 데이터 보호 및 재해 복구 이해"].


NOTE: 전환 프로세스 중에는 자동 계획되지 않은 전환을 사용할 수 없습니다.

[cols="c*"]
|===
| 전환 단계 | 협상된 전환은 이 워크플로우를 사용합니다 | 계획되지 않은 전환을 사용할 경우 이 워크플로우가... 


 a| 
MetroCluster IP 노드가 클러스터에 연결되기 전
 a| 
MetroCluster FC를 참조하십시오
 a| 
MetroCluster FC를 참조하십시오



 a| 
MetroCluster IP 노드가 클러스터에 결합된 후 MetroCluster configure 명령을 수행하기 전에
 a| 
지원되지 않습니다
 a| 
MetroCluster FC를 참조하십시오



 a| 
MetroCluster configure 명령을 실행한 후 볼륨 이동이 진행 중일 수 있습니다.
 a| 
통합: 모든 원격 사이트 노드가 작동 상태로 유지되고 복구가 자동으로 수행됩니다
 a| 
통합:

* MetroCluster FC 노드가 소유한 미러링된 애그리게이트는 스토리지에 액세스할 수 있는 경우 미러링되며, 전환 후 다른 모든 애그리게이트는 성능이 저하됩니다
* 모든 원격 사이트 노드가 부팅될 수 있습니다.
* 환원 Aggregate 및 환원 루트 명령을 수동으로 실행해야 합니다.




 a| 
MetroCluster FC 노드는 구성되지 않았습니다.
 a| 
지원되지 않습니다
 a| 
MetroCluster IP를 선택합니다



 a| 
MetroCluster FC 노드에서 cluster unjoin 명령이 수행되었습니다.
 a| 
MetroCluster IP를 선택합니다
 a| 
MetroCluster IP를 선택합니다

|===