---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: ONTAP 9.13.1 부터는 기존 8노드 MetroCluster FC 구성에서 새로운 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다. 
---
= MetroCluster FC에서 MetroCluster IP 구성으로 중단 없이 전환(ONTAP 9.8 이상)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 MetroCluster FC 구성에서 새로운 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다.

ONTAP 9.13.1부터 이 절차는 MetroCluster와 드라이브 쉘프가 동일한 IP 스위치(공유 스토리지 스위치 구성)에 연결되는 MetroCluster IP 구성에서 지원됩니다.

ONTAP 9.13.1부터 기존 8노드 MetroCluster FC 구성에서 새로운 8노드 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다.  이 절차를 사용하여 4노드 FC DR 그룹 하나를 전환하고, 빈 FC DR 그룹을 제거한 다음, 두 번째 FC DR 그룹에 대해 절차를 반복합니다. 

ONTAP 9.8부터 기존 4노드 MetroCluster FC 구성에서 새로운 4노드 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다.  전환을 완료한 후 필요한 경우 8노드 MetroCluster IP 구성으로 확장할 수 있습니다. 보다link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["MetroCluster IP 구성을 확장합니다"] .

* 이 절차는 무중단으로 수행할 수 있으며
+
MetroCluster 구성은 작업 중에도 데이터를 계속 제공할 수 있습니다.

* 이 절차는 4노드 및 8노드 MetroCluster FC 구성에만 적용됩니다.
+
2노드 MetroCluster FC 구성이 있는 경우 를 참조하십시오 link:concept_choosing_your_transition_procedure_mcc_transition.html["전환 절차 선택"].

* 이 절차에서는 4노드 FC DR 그룹 하나를 전환하는 데 필요한 단계를 설명합니다. 8노드 구성(FC DR 그룹 2개)이 있는 경우 각 FC DR 그룹에 대해 전체 절차를 반복해야 합니다.
+

NOTE: 이 절차의 일부로 DR 그룹을 추가하거나 제거하는 경우 다른 DR 그룹을 추가하거나 제거하기 전에 DR 그룹 제거 또는 추가가 성공적으로 완료되었는지 확인해야 합니다.

* 모든 요구 사항을 충족하고 절차의 모든 단계를 따라야 합니다.


.이전 플랫폼 모델을 추가하는 경우 중요한 정보
다음 지침은 ONTAP 9.15.1 이전에 출시된 플랫폼인 이전 플랫폼 모델을 ONTAP 9.15.1 이상에서 출시된 최신 플랫폼 모델이 포함된 기존 MetroCluster 구성에 추가해야 하는 흔하지 않은 시나리오를 위한 것입니다.  8노드 FC에서 IP로 전환하는 경우, 첫 번째 FC DR 그룹을 ONTAP 9.15.1 이상에서 도입된 플랫폼 모델로 전환했고 두 번째 DR 그룹을 ONTAP 9.15.1 이전에 도입된 플랫폼으로 전환할 계획이라면 이 지침이 적용됩니다.

기존 MetroCluster 구성에 *공유 클러스터/HA 포트*( ONTAP 9.15.1 이상에서 출시된 플랫폼)를 사용하는 플랫폼이 포함된 경우, 구성의 모든 노드를 ONTAP 9.15.1P11 또는 ONTAP 9.16.1P4 이상으로 업그레이드하지 않고는 *공유 MetroCluster/HA 포트*( ONTAP 9.15.1 이전에 출시된 플랫폼)를 사용하는 플랫폼을 추가할 수 없습니다.

[CAUTION]
====
*공유/ MetroCluster HA 포트*를 사용하는 이전 플랫폼 모델을 *공유 클러스터/HA 포트*를 사용하는 최신 플랫폼 모델이 포함된 MetroCluster 에 추가하는 것은 흔하지 않은 시나리오이며 대부분의 조합에는 영향을 미치지 않습니다.

====
다음 표를 사용하여 해당 조합이 영향을 받는지 확인하세요.  기존 플랫폼이 첫 번째 열에 나열되어 있고, 구성에 추가하려는 플랫폼이 두 번째 열에 나열되어 있는 경우, 새 DR 그룹을 추가하려면 구성의 모든 노드가 ONTAP 9.15.1P11 또는 ONTAP 9.16.1P4 이상을 실행해야 합니다.

[cols="20,20,20,20,20"]
|===
2+| 기존 MetroCluster에 다음이 포함되어 있는 경우.. 2+| 그리고 당신이 추가하는 플랫폼은... | 그러면... 


 a| 
*공유 클러스터/HA 포트*를 사용하는 AFF 시스템:

* AFF A20 를 참조하십시오
* AFF A30
* AFF C30
* AFF A50 를 참조하십시오
* AFF C60
* AFF C80 를 참조하십시오
* AFF A70 를 참조하십시오
* AFF A90 를 참조하십시오
* AFF A1K 를 참조하십시오

 a| 
*공유 클러스터/HA 포트*를 사용하는 FAS 시스템:

* FAS50를 참조하십시오
* FAS70를 참조하십시오
* FAS90를 참조하십시오

 a| 
*공유 MetroCluster/HA 포트*를 사용하는 AFF 시스템:

* AFF A150, ASA A150
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
*공유 MetroCluster/HA 포트*를 사용하는 FAS 시스템:

* FAS2750
* 500f로 설정합니다
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| 기존 MetroCluster 구성에 새 플랫폼을 추가하기 전에 기존 및 새 구성의 모든 노드를 ONTAP 9.15.1P11 또는 ONTAP 9.16.1P4 이상으로 업그레이드하세요. 
|===