---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: ONTAP 9.13.1 부터는 기존 8노드 MetroCluster FC 구성에서 새로운 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다. 
---
= MetroCluster FC에서 MetroCluster IP 구성으로 중단 없이 전환(ONTAP 9.8 이상)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 MetroCluster FC 구성에서 새로운 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다.

ONTAP 9.13.1부터 이 절차는 MetroCluster와 드라이브 쉘프가 동일한 IP 스위치(공유 스토리지 스위치 구성)에 연결되는 MetroCluster IP 구성에서 지원됩니다.

ONTAP 9.13.1 부터는 기존 8노드 MetroCluster FC 구성에서 새로운 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다.

ONTAP 9.8부터 기존 4노드 MetroCluster FC 구성에서 새로운 MetroCluster IP 구성으로 워크로드와 데이터를 중단 없이 전환할 수 있습니다.

* 이 절차는 무중단으로 수행할 수 있으며
+
MetroCluster 구성은 작업 중에도 데이터를 계속 제공할 수 있습니다.

* 이 절차는 4노드 및 8노드 MetroCluster FC 구성에만 적용됩니다.
+
2노드 MetroCluster FC 구성이 있는 경우 를 참조하십시오 link:concept_choosing_your_transition_procedure_mcc_transition.html["전환 절차 선택"].

* 이 절차에서는 4노드 FC DR 그룹 하나를 전환하는 데 필요한 단계를 설명합니다. 8노드 구성(FC DR 그룹 2개)이 있는 경우 각 FC DR 그룹에 대해 전체 절차를 반복해야 합니다.
* 모든 요구 사항을 충족하고 절차의 모든 단계를 따라야 합니다.

