---
permalink: transition/concept_requirements_for_fc_to_ip_transition_mcc.html 
sidebar: sidebar 
keywords: start, transition, process, configuration, requirement, nondisruptive, fc-to-ip 
summary: 전환 프로세스를 시작하기 전에 구성이 요구사항을 충족하는지 확인해야 합니다. 
---
= 무중단 FC-to-IP 전환 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 프로세스를 시작하기 전에 구성이 요구사항을 충족하는지 확인하십시오.

구성이 다음 요구사항을 충족하는 경우 FC-to-IP 전환을 중단 없이 수행할 수 있습니다.

* 8노드 구성의 경우 모든 노드에서 ONTAP 9.13.1 이상을 실행합니다.
* 4노드 구성의 경우 모든 노드에서 ONTAP 9.8 이상을 실행합니다.
* 기존 플랫폼과 신규 플랫폼은 전환을 지원하는 조합입니다.
+
link:concept_choosing_your_transition_procedure_mcc_transition.html["무중단 전환을 지원하는 플랫폼"]

* 이 구성은 스위치 클러스터 구성을 지원합니다.
+
https://hwu.netapp.com["Hardware Universe"^]



[CAUTION]
====
공유 스토리지 MetroCluster 스위치를 사용하는 경우 4노드 MetroCluster IP 구성으로만 전환할 수 있습니다. 공유 스토리지 MetroCluster 스위치를 사용하여 8노드 MetroCluster IP 구성으로 전환하는 것은 지원되지 않습니다. 4노드 MetroCluster IP 구성으로 전환을 완료한 후에는 다음을 수행할 수 link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["8노드 MetroCluster IP 구성으로 확장"]있습니다.

====
* 이 구성은 모든 요구 사항을 충족하며 다음_MetroCluster 설치 및 구성_절차에 설명된 대로 케이블로 연결됩니다.
+
link:../install-fc/index.html["패브릭 연결 MetroCluster 설치 및 구성"]

+
link:../install-stretch/concept_considerations_differences.html["스트레치 MetroCluster 설치 및 구성"]


