---
permalink: transition/task_verify_mcc_health_fc_to_ip.html 
sidebar: sidebar 
keywords: Verifying the health of the MetroCluster configuration, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: 전환을 수행하기 전에 MetroCluster 구성의 상태와 연결을 확인해야 합니다. 
---
= MetroCluster 구성 상태 확인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환을 수행하기 전에 MetroCluster 구성의 상태와 연결을 확인해야 합니다

. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템의 다중 경로: 노드 run-node-name sysconfig-a를 확인한다
.. 두 클러스터에 대한 상태 경고 '시스템 상태 알림 표시'를 확인합니다
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 'MetroCluster show'인지 확인한다
.. 'MetroCluster check run'이라는 MetroCluster check을 수행한다
.. MetroCluster 체크 표시 결과를 MetroCluster check show로 출력한다
.. 스위치의 상태 경고(있는 경우) '스토리지 스위치 표시'를 확인합니다
.. Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.


. 클러스터 상태가 양호한지 확인합니다. 'cluster show'
+
....
cluster_A::> cluster show
Node           Health  Eligibility   Epsilon
-------------- ------  -----------   -------
node_A_1_FC    true    true          false
node_A_2_FC    true    true          false

cluster_A::>
....
. 모든 클러스터 포트가 작동 중인지 확인합니다. 'network port show-ipSpace cluster'
+
....
cluster_A::> network port show -ipspace cluster

Node: node_A_1_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

cluster_A::>
....
. 모든 클러스터 LIF가 작동 중인지 확인합니다. 'network interface show -vserver cluster'
+
각 클러스터 LIF는 "홈"에 대해 "참"으로, "상태 관리/작업"에 대해 "위쪽/위쪽"으로 표시되어야 합니다.

+
....
cluster_A::> network interface show -vserver cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A-1_FC_clus1
                       up/up      169.254.209.69/16  node_A-1_FC   e0a     true
            node_A_1_FC_clus2
                       up/up      169.254.49.125/16  node_A_1_FC   e0b     true
            node_A_2_FC_clus1
                       up/up      169.254.47.194/16  node_A_2_FC   e0a     true
            node_A_2_FC_clus2
                       up/up      169.254.19.183/16  node_A_2_FC   e0b     true

4 entries were displayed.

cluster_A::>
....
. 모든 클러스터 LIF에서 'network interface show-vserver Cluster-fields auto-revert'라는 자동 되돌리기 기능이 설정되어 있는지 확인합니다
+
....
cluster_A::> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
           node_A_1_FC_clus1
                        true
           node_A_1_FC_clus2
                        true
           node_A_2_FC_clus1
                        true
           node_A_2_FC_clus2
                        true

    4 entries were displayed.

cluster_A::>
....

