---
permalink: transition/task_return_the_system_to_normal_operation_2n_mcc_transition_supertask.html 
sidebar: sidebar 
keywords: perform, final, configuration, return, metrocluster, normal, operation, system, verify, assign, drive, transition, install, license, module, complete, completing, node, send, custom, autosupport, message, maintenance 
summary: 최종 구성 단계를 수행하고 MetroCluster 구성을 정상 작동 상태로 되돌리십시오. 
---
= 시스템을 정상 작동 상태로 되돌리기
:icons: font
:imagesdir: ../media/


[role="lead"]
최종 구성 단계를 수행하고 MetroCluster 구성을 정상 작동 상태로 되돌리십시오.



== 전환 후 MetroCluster 작업 확인 및 드라이브 할당

[role="lead"]
MetroCluster가 올바르게 작동하는지 확인하고 드라이브를 두 번째 쌍의 새 노드(node_A_2-IP 및 node_B_2-IP)에 할당해야 합니다.

. MetroCluster configuration-type이 IP-fabric인 MetroCluster show인지 확인한다
. MetroCluster 검사를 수행합니다.
+
.. MetroCluster check run 명령을 발행한다
.. MetroCluster 체크 표시 결과를 MetroCluster check show로 출력한다


. MetroCluster IP 노드의 DR 그룹이 'MetroCluster node show'로 설정되어 있는지 확인합니다
. 필요에 따라 각 사이트에서 컨트롤러 node_A_2-IP 및 node_B_2-IP에 대한 추가 데이터 애그리게이트를 생성하고 미러링합니다.




== 새 컨트롤러 모듈에 대한 라이센스 설치

[role="lead"]
표준(노드 잠김) 라이센스가 필요한 모든 ONTAP 서비스에 대해 새 컨트롤러 모듈에 대한 라이센스를 추가해야 합니다. 표준 라이센스가 있는 기능을 사용하려면 클러스터의 각 노드에 해당 기능에 대한 자체 키가 있어야 합니다.

라이센스에 대한 자세한 내용은 기술 자료 문서 3013749: Data ONTAP 8.2 라이센스 개요 및 NetApp Support 사이트 및 _시스템 관리 참조_를 참조하십시오.

. 필요한 경우 소프트웨어 라이센스의 내 지원 섹션에서 NetApp Support 사이트의 새 노드에 대한 라이센스 키를 얻습니다.
+
사이트에 필요한 라이센스 키가 없는 경우 영업 담당자 또는 지원 담당자에게 문의하십시오.

. 각 라이센스 키를 설치하려면 다음 명령을 실행하십시오. 'system license add-license-code license_key'
+
license_key의 길이는 28자입니다.

+
필요한 각 표준(노드 잠김) 라이센스에 대해 이 단계를 반복합니다.





== 노드 구성을 완료합니다

[role="lead"]
절차를 완료하기 전에 수행할 수 있는 기타 구성 단계가 있습니다. 이러한 단계 중 일부는 선택 사항입니다.

. Service Processor를 'System service-processor network modify'로 설정한다
. 새 노드에서 AutoSupport를 설정합니다: 'system node AutoSupport modify'
. 전환 과정에서 컨트롤러 이름을 선택적으로 바꿀 수 있습니다. 'system node rename -node <old-name> -newname <new-name>' 컨트롤러의 이름을 바꾸는 데 사용되는 명령은 다음과 같습니다
+
이름 바꾸기 작업을 완료하는 데 몇 분 정도 걸릴 수 있습니다. system show-fields node 명령을 사용하여 다른 단계를 계속하기 전에 이름 변경 내용이 각 노드에 전파되었는지 확인합니다.

. 필요에 따라 모니터링 서비스를 구성합니다.
+
링크:../install-ip/concept_considerations_adoc

+
link:../install-ip/concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html["계획되지 않은 자동 전환을 위한 ONTAP 중재자 서비스 구성"]

+
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Tiebreaker 소프트웨어 설치 및 구성"]





== 유지 관리 후 사용자 지정 AutoSupport 메시지 보내기

[role="lead"]
전환을 완료한 후 유지 관리 완료를 나타내는 AutoSupport 메시지를 보내야 자동 케이스 생성이 재개됩니다.

. 자동 지원 케이스 생성을 재개하려면 유지 관리가 완료되었음을 나타내는 AutoSupport 메시지를 보냅니다.
+
.. 'system node AutoSupport invoke -node * -type all-message maINT=end' 명령을 발행한다
.. 파트너 클러스터에서 명령을 반복합니다.



