---
permalink: transition/task_move_data_to_new_drive_shelves.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: 전환 중에 MetroCluster FC 구성의 드라이브 쉘프에서 새로운 MetroCluster IP 구성으로 데이터를 이동합니다. 
---
= 데이터를 새 드라이브 쉘프로 이동
:allow-uri-read: 


[role="lead"]
전환 중에 MetroCluster FC 구성의 드라이브 쉘프에서 새로운 MetroCluster IP 구성으로 데이터를 이동합니다.

.시작하기 전에
타겟 또는 IP 노드에 새로운 SAN LIF를 생성하고 볼륨을 새 애그리게이트로 이동하기 전에 호스트를 연결해야 합니다.

. 자동 지원 케이스 생성을 재개하려면 유지 관리가 완료되었음을 나타내는 AutoSupport 메시지를 보냅니다.
+
.. 'system node AutoSupport invoke -node * -type all-message maINT=end' 명령을 발행한다
.. 파트너 클러스터에서 명령을 반복합니다.


. 데이터 볼륨을 새 컨트롤러의 aggregate로 한 번에 하나씩 이동합니다.
+
의 절차를 사용합니다 http://["Aggregate 생성 및 볼륨을 새 노드로 이동"].

. 최근에 추가한 노드에서 SAN LIF를 생성합니다.
+
의 다음 절차를 사용합니다 http://["새 노드의 LUN 경로를 업데이트하는 중입니다"^].

. FC 노드에 노드 잠김 라이센스가 있는지 확인합니다. 있는 경우 새로 추가된 노드에 노드를 추가해야 합니다.
+
의 다음 절차를 사용합니다 http://["노드 잠김 라이센스 추가"^].

. 데이터 LIF 마이그레이션
+
의 절차를 사용합니다  http://["SAN이 아닌 데이터 LIF 및 클러스터 관리 LIF를 새로운 노드로 이동"^] 그러나 클러스터 관리 LIF를 마이그레이션하기 위한 마지막 두 단계를 * 수행하지 * 마십시오.



[NOTE]
====
* VAAI(VMware vStorage APIs for Array Integration)를 사용하면 복사 오프로드 작업에 사용되는 LIF를 마이그레이션할 수 없습니다.
* MetroCluster 노드를 FC에서 IP로 전환한 후 iSCSI 호스트 연결을 새 노드로 이동해야 할 수 있습니다. 를 참조하십시오 link:task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html["Linux iSCSI 호스트를 MetroCluster FC에서 MetroCluster IP 노드로 이동"]


====