---
permalink: transition/task_remove_mc_fc_controllers.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: 전환을 위한 구성을 준비하려면 새 노드를 기존 MetroCluster 구성에 추가한 다음 데이터를 새 노드로 이동합니다. 
---
= MetroCluster FC 컨트롤러 분리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정리 작업을 수행하고 MetroCluster 구성에서 이전 컨트롤러 모듈을 제거해야 합니다.

. 자동 지원 케이스 생성을 방지하려면 유지 관리가 진행 중임을 알리는 AutoSupport 메시지를 보내십시오.
+
.. 'system node AutoSupport invoke -node * -type all-message MAINT=maintenance -window-in-hours' 명령을 실행합니다
+
유지 보수 기간 - 시간 단위 는 유지 보수 기간 길이를 최대 72시간으로 지정합니다. 유지 보수 작업이 경과 시간 전에 완료되면 유지 보수 기간이 종료되었음을 나타내는 AutoSupport 메시지('시스템 노드 AutoSupport invoke-node * -type all-message MAINT=end')를 호출할 수 있습니다

.. 파트너 클러스터에서 명령을 반복합니다.


. 삭제해야 하는 MetroCluster FC 구성에 호스팅된 애그리게이트를 식별합니다.
+
이 예제에서 다음 데이터 애그리게이트는 MetroCluster FC cluster_B에 의해 호스팅되므로 aggr_data_a1과 aggr_data_a2를 삭제해야 합니다.

+

NOTE: 양쪽 클러스터에서 데이터 애그리게이트를 확인, 오프라인 및 삭제하기 위한 단계를 수행해야 합니다. 이 예는 하나의 클러스터에만 해당됩니다.

+
....
cluster_B::> aggr show

Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_node_A_1-FC
           349.0GB   16.83GB   95% online       1 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_2-FC
           349.0GB   16.83GB   95% online       1 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.63GB   95% online       1 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.62GB   95% online       1 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a1
            1.02TB    1.02TB    0% online       0 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a2
            1.02TB    1.02TB    0% online       0 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a3
            1.37TB    1.35TB    1% online       3 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a4
            1.25TB    1.24TB    1% online       2 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
8 entries were displayed.

cluster_B::>
....
. FC 노드의 데이터 애그리게이트에 MDV_AUD 볼륨이 있는지 확인한 후 애그리게이트를 삭제하기 전에 삭제하십시오.
+
이동할 수 없으므로 MDV_AUD 볼륨을 삭제해야 합니다.

. 각 애그리게이트를 오프라인 상태로 전환하고 삭제합니다.
+
.. '스토리지 집계 오프라인-집계 집계-이름'을 집계하여 오프라인으로 전환합니다
+
다음 예에서는 오프라인인 집계 aggr_data_A1을 보여 줍니다.

+
....
cluster_B::> storage aggregate offline -aggregate aggr_data_a1

Aggregate offline successful on aggregate: aggr_data_a1
....
.. 'Storage aggregate delete-aggregate aggregate-name'이라는 애그리게이트를 삭제합니다
+
메시지가 표시되면 플렉스를 폐기할 수 있습니다.

+
다음 예제는 삭제되는 집계 aggr_data_A1을 보여줍니다.

+
....
cluster_B::> storage aggregate delete -aggregate aggr_data_a1
Warning: Are you sure you want to destroy aggregate "aggr_data_a1"? {y|n}: y
[Job 123] Job succeeded: DONE

cluster_B::>
....


. 제거해야 하는 MetroCluster FC DR 그룹을 식별합니다.
+
다음 예에서는 MetroCluster FC 노드가 DR 그룹 '1'에 있으며, 이 그룹은 제거해야 하는 DR 그룹입니다.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        configured     enabled   normal
              node_A_2-FC        configured     enabled   normal
      cluster_B
              node_B_1-FC        configured     enabled   normal
              node_B_2-FC        configured     enabled   normal
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_3-IP        configured     enabled   normal
8 entries were displayed.

cluster_B::>
....
. 클러스터 관리 LIF를 MetroCluster FC 노드에서 MetroCluster IP 노드로 이동합니다. 'cluster_B:::> network interface migrate-vserver svm-name -lif cluster_mgmt -destination-node -in-MetroCluster-ip-dr-group-destination-port available-port'
. 클러스터 관리 LIF의 홈 노드 및 홈 포트를 'cluster_B:::> 네트워크 인터페이스 modify -vserver svm -name -lif cluster_mgmt -service -policy default-management-home-node-in-MetroCluster-ip-dr-group-home-port lif-port'로 변경합니다
. MetroCluster FC 노드에서 MetroCluster IP 노드로 epsilon 이동:
+
.. 현재 epsilon의 "cluster show-fields epsilon"이 있는 노드를 식별합니다
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      true
node_A_2-FC      false
node_A_1-IP      false
node_A_2-IP      false
4 entries were displayed.
....
.. MetroCluster FC 노드(node_A_1-FC)에서 epsilon을 FALSE로 설정합니다. "cluster modify -node fc -node -epsilon FALSE
.. MetroCluster IP 노드(node_a_1-ip)에서 epsilon을 TRUE로 설정합니다. "cluster modify -node ip-node -epsilon TRUE
.. epsilon이 올바른 노드인 '클러스터 표시-필드 epsilon'로 이동했는지 확인합니다
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      false
node_A_2-FC      false
node_A_1-IP      true
node_A_2-IP      false
4 entries were displayed.
....


. 각 클러스터에서 이전 노드가 포함된 DR 그룹을 MetroCluster FC 구성에서 제거합니다.
+
두 클러스터 모두에서 한 번에 하나씩 이 단계를 수행해야 합니다.

+
....
cluster_B::> metrocluster remove-dr-group -dr-group-id 1

Warning: Nodes in the DR group that are removed from the MetroCluster
         configuration will lose their disaster recovery protection.

         Local nodes "node_A_1-FC, node_A_2-FC" will be removed from the
         MetroCluster configuration. You must repeat the operation on the
         partner cluster "cluster_B" to remove the remote nodes in the DR group.
Do you want to continue? {y|n}: y

Info: The following preparation steps must be completed on the local and partner
      clusters before removing a DR group.

      1. Move all data volumes to another DR group.
      2. Move all MDV_CRS metadata volumes to another DR group.
      3. Delete all MDV_aud metadata volumes that may exist in the DR group to
      be removed.
      4. Delete all data aggregates in the DR group to be removed. Root
      aggregates are not deleted.
      5. Migrate all data LIFs to home nodes in another DR group.
      6. Migrate the cluster management LIF to a home node in another DR group.
      Node management and inter-cluster LIFs are not migrated.
      7. Transfer epsilon to a node in another DR group.

      The command is vetoed ifthe preparation steps are not completed on the
      local and partner clusters.
Do you want to continue? {y|n}: y
[Job 513] Job succeeded: Remove DR Group is successful.

cluster_B::>
....
. 클러스터에서 노드를 제거할 준비가 되었는지 확인합니다.
+
두 클러스터 모두에서 이 단계를 수행해야 합니다.

+

NOTE: 이때 MetroCluster node show 명령은 로컬 MetroCluster FC 노드만 표시하며 더 이상 파트너 클러스터의 일부인 노드를 표시하지 않습니다.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        ready to configure
                                                -         -
              node_A_2-FC        ready to configure
                                                -         -
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_4-IP        configured     enabled   normal
6 entries were displayed.

cluster_B::>
....
. MetroCluster FC 노드에 대해 스토리지 페일오버를 해제합니다.
+
각 노드에서 이 단계를 수행해야 합니다.

+
....
cluster_A::> storage failover modify -node node_A_1-FC -enabled false
cluster_A::> storage failover modify -node node_A_2-FC -enabled false
cluster_A::>
....
. 클러스터에서 MetroCluster FC 노드의 연결을 해제합니다. 'cluster unjoin-node-name'
+
각 노드에서 이 단계를 수행해야 합니다.

+
....
cluster_A::> cluster unjoin -node node_A_1-FC

Warning: This command will remove node "node_A_1-FC"from the cluster. You must
         remove the failover partner as well. After the node is removed, erase
         its configuration and initialize all disks by usingthe "Clean
         configuration and initialize all disks (4)" option from the boot menu.
Do you want to continue? {y|n}: y
[Job 553] Job is queued: Cluster remove-node of Node:node_A_1-FC with UUID:6c87de7e-ff54-11e9-8371
[Job 553] Checking prerequisites
[Job 553] Cleaning cluster database
[Job 553] Job succeeded: Node remove succeeded
If applicable, also remove the node's HA partner, and then clean its configuration and initialize all disks with the boot menu.
Run "debug vreport show" to address remaining aggregate or volume issues.

cluster_B::>
....
. MetroCluster FC 컨트롤러 모듈 및 스토리지 쉘프의 전원을 끕니다.
. MetroCluster FC 컨트롤러 모듈 및 스토리지 쉘프를 분리하고 제거합니다.

