---
permalink: transition/task_prepare_ip_controllers_4n_transition.html 
sidebar: sidebar 
keywords: Transitioning from MetroCluster FC to MetroCluster IP configurations, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: 새로운 MetroCluster IP 노드 4개를 준비하고 올바른 ONTAP 버전을 설치해야 합니다. 
---
= MetroCluster IP 컨트롤러 준비
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 MetroCluster IP 노드 4개를 준비하고 올바른 ONTAP 버전을 설치해야 합니다.

이 작업은 새 노드 각각에 대해 수행해야 합니다.

* Node_A_1 - IP
* Node_A_2 - IP
* Node_B_1 - IP
* Node_B_2 - IP


다음 단계에서는 노드의 구성을 지우고 새 드라이브의 메일박스 영역을 지웁니다.

. MetroCluster IP 구성을 위해 새 컨트롤러를 랙에 장착했습니다.
+
MetroCluster FC 노드(node_A_x-FC 및 node_B_x-FC)는 현재 케이블로 연결되어 있습니다.

. 에 나와 있는 것처럼 MetroCluster IP 노드를 IP 스위치에 케이블로 연결합니다 link:../install-ip/using_rcf_generator.html["IP 스위치 케이블 연결"].
. 다음 섹션을 사용하여 MetroCluster IP 노드를 구성합니다.
+
.. link:../install-ip/task_sw_config_gather_info.html["필요한 정보를 수집하는 중입니다"]
.. link:../install-ip/task_sw_config_restore_defaults.html["컨트롤러 모듈의 구성 지우기"]
.. link:../install-ip/task_sw_config_verify_haconfig.html["구성 요소의 ha-config 상태 확인"]
.. link:../install-ip/task_sw_config_assign_pool0.html["풀 0에 드라이브 수동 할당(ONTAP 9.4 이상)"]


. 유지보수 모드에서 halt 명령을 실행하여 유지보수 모드를 종료한 다음 boot_ONTAP 명령을 실행하여 시스템을 부팅하고 클러스터 설정으로 이동합니다.
+
지금은 클러스터 마법사 또는 노드 마법사를 완료하지 마십시오.

. 다른 MetroCluster IP 노드에서 이 단계를 반복합니다.

