---
permalink: transition/task_apply_rcfs.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: MetroCluster IP 구성에 새로운 IP 스위치를 사용하는 경우 사용자 지정 RCF 파일을 사용하여 스위치를 구성해야 합니다. 
---
= 새 IP 스위치에 RCF 생성 및 적용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 구성에 새로운 IP 스위치를 사용하는 경우 사용자 지정 RCF 파일을 사용하여 스위치를 구성해야 합니다.

새 스위치를 사용하는 경우 이 작업이 필요합니다.

기존 스위치를 사용하는 경우 로 진행합니다 link:task_move_cluster_connections.html["로컬 클러스터 연결 이동"].

. 새 IP 스위치를 설치하고 랙에 설치합니다.
. 새로운 RCF 파일 적용을 위한 IP 스위치를 준비합니다.
+
해당 스위치 공급업체에 대한 섹션의 단계를 따릅니다.

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Broadcom IP 스위치를 출하 시 기본값으로 재설정합니다"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Cisco IP 스위치를 출하 시 기본값으로 재설정합니다"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["NVIDIA IP SN2100 스위치를 출하 시 기본값으로 재설정합니다"]


. 필요한 경우 스위치의 펌웨어를 지원되는 버전으로 업데이트합니다.
. RCF 생성기 툴을 사용하여 스위치 공급업체와 플랫폼 모델에 따라 RCF 파일을 생성한 다음 스위치를 파일로 업데이트합니다.
+
해당 스위치 공급업체에 대한 섹션의 단계를 따릅니다.

+
** link:../install-ip/task_switch_config_broadcom.html["Broadcom IP RCF 파일을 다운로드하여 설치합니다"]
** link:../install-ip/task_switch_config_cisco.html["Cisco IP RCF 파일을 다운로드하고 설치합니다"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["NVIDIA RCF 파일을 다운로드하고 설치합니다"]



