---
permalink: transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html 
sidebar: sidebar 
keywords: transition, metrocluster, node, fc, ip, iscsi, host, connection, moving, move, linux, set, up, add, report, removing, remove, rescan, path 
summary: MetroCluster 노드를 FC에서 IP로 전환한 후 iSCSI 호스트 연결을 새 노드로 이동해야 할 수 있습니다. 
---
= Linux iSCSI 호스트를 MetroCluster FC에서 MetroCluster IP 노드로 이동합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 노드를 FC에서 IP로 전환한 후 iSCSI 호스트 연결을 새 노드로 이동해야 할 수 있습니다.

.이 작업에 대해
* IPv4 인터페이스는 새 iSCSI 연결을 설정할 때 생성됩니다.
* 호스트 명령과 예는 Linux 운영 체제에만 해당됩니다.
* MetroCluster FC 노드를 이전 노드라고 하고, MetroCluster IP 노드를 새 노드라고 합니다.




== 1단계: 새 iSCSI 연결을 설정합니다

iSCSI 연결을 이동하려면 새 노드에 대한 새 iSCSI 연결을 설정합니다.

.단계
. 새 노드에서 iSCSI 인터페이스를 생성하고 iSCSI 호스트에서 새 노드의 새 인터페이스로의 ping 연결을 확인합니다.
+
https://docs.netapp.com/us-en/ontap/networking/create_a_lif.html["네트워크 인터페이스를 생성합니다"^]

+
SVM의 모든 iSCSI 인터페이스에 iSCSI 호스트에 연결할 수 있어야 합니다.

. iSCSI 호스트에서 호스트에서 호스트에서 이전 노드로의 기존 iSCSI 접속을 식별합니다.
+
[source, cli]
----
iscsiadm -m session
----
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session
tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. 새 노드에서 새 노드로부터의 연결을 확인합니다.
+
[source, cli]
----
iscsi session show -vserver <svm-name>
----
+
[listing]
----
node_A_1-new::*> iscsi session show -vserver vsa_1
 Tpgroup Initiator Initiator
Vserver Name TSIH Name ISID Alias
--------- ------- ---- ------------------------ --------- ---------------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 scspr1789621001.gdl.englab.netapp.com
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 scspr1789621001.gdl.englab.netapp.com
2 entries were displayed.
----
. 새 노드에서 인터페이스가 포함된 SVM용 ONTAP의 iSCSI 인터페이스를 나열합니다.
+
[source, cli]
----
iscsi interface show -vserver <svm-name>
----
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi interface show -vserver vsa_1
 Logical Status Curr Curr
Vserver Interface  TPGT Admin/Oper IP Address Node Port Enabled
------- ---------- ---- ---------- --------------- ----------- ---- -------
vsa_1 iscsi_lf__n1_p1_ 1156 up/up 10.230.68.236 sti8200mcc-htp-001 e0g true
vsa_1 iscsi_lf__n1_p2_ 1157 up/up fd20:8b1e:b255:805e::78c9 sti8200mcc-htp-001 e0h true
vsa_1 iscsi_lf__n2_p1_ 1158 up/up 10.230.68.237 sti8200mcc-htp-002 e0g true
vsa_1 iscsi_lf__n2_p2_ 1159 up/up fd20:8b1e:b255:805e::78ca sti8200mcc-htp-002 e0h true
vsa_1 iscsi_lf__n3_p1_ 1183 up/up 10.226.43.134 sti8200mccip-htp-005 e0c true
vsa_1 iscsi_lf__n4_p1_ 1188 up/up 10.226.43.142 sti8200mccip-htp-006 e0c true
6 entries were displayed.
----
. iSCSI 호스트에서 SVM의 iSCSI IP 주소 중 하나에서 검색을 실행하여 새 타겟을 검색합니다.
+
[source, cli]
----
iscsiadm -m discovery -t sendtargets -p iscsi-ip-address
----
+
비 iSCSI 인터페이스를 포함하여 SVM의 모든 IP 주소에서 검색을 실행할 수 있습니다.

+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m discovery -t sendtargets -p 10.230.68.236:3260
10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.134:3260,1183 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
----
. iSCSI 호스트에서 검색된 모든 주소에 로그인합니다.
+
[source, cli]
----
iscsiadm -m node -L all -T node-address -p portal-address -l
----
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m node -L all -T iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 -p 10.230.68.236:3260 -l
Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] (multiple)
Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] (multiple)
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] successful.
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] successful.
----
. iSCSI 호스트에서 로그인 및 접속을 확인합니다.
+
[source, cli]
----
iscsiadm -m session
----
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session
tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [3] 10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. 새 노드에서 호스트에 대한 로그인 및 연결을 확인합니다.
+
[source, cli]
----
iscsi initiator show -vserver <svm-name>
----
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi initiator show -vserver vsa_1
 Tpgroup Initiator
Vserver Name             TSIH Name                  ISID              Igroup Name
------- --------         ---- --------------------- ----------------- -----------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 igroup_linux
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 igroup_linux
vsa_1 iscsi_lf__n3_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:04 igroup_linux
vsa_1 iscsi_lf__n4_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:03 igroup_linux
4 entries were displayed.
----


.결과
이 작업이 끝나면 호스트는 이전 노드와 새 노드에 있는 모든 iSCSI 인터페이스를 볼 수 있으며 이러한 모든 인터페이스에 로그인됩니다.

LUN 및 볼륨은 이전 노드에서 물리적으로 호스팅됩니다. LUN은 이전 노드 인터페이스에서만 보고되기 때문에 호스트는 이전 노드에 대한 경로만 표시합니다. 이를 보려면 를 실행합니다 `sanlun lun show -p` 및 `multipath -ll -d` 호스트에 대한 명령을 실행하고 명령 출력을 검사합니다.

[listing]
----
[root@scspr1789621001 ~]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ -------------------
host vserver
path path /dev/ host vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ -------------------
up        primary    sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_
[root@scspr1789621001 ~]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


== 2단계: 새 노드를 보고 노드로 추가합니다

새 노드에 대한 연결을 설정한 후 새 노드를 보고 노드로 추가합니다.

.단계
. 새 노드에서 SVM에 있는 LUN에 대한 보고 노드를 나열합니다.
+
[source, cli]
----
lun mapping show -vserver <svm-name> -fields reporting-nodes -ostype linux
----
+
LUN이 물리적으로 이전 node_A_1-old 및 node_A_2-old에 있으므로 다음 보고 노드는 로컬 노드입니다.

+
[listing]
----
node_A_1-new::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux
vserver path                         igroup       reporting-nodes
------- ---------------------------- ------------ ---------------------------
vsa_1   /vol/vsa_1_vol1/lun_linux_2  igroup_linux node_A_1-old,node_A_2-old
.
.
.
vsa_1   /vol/vsa_1_vol9/lun_linux_19 igroup_linux node_A_1-old,node_A_2-old
12 entries were displayed.
----
. 새 노드에서 보고 노드를 추가합니다.
+
[source, cli]
----
lun mapping add-reporting-nodes -vserver <svm-name> -path /vol/vsa_1_vol*/lun_linux_* -nodes node1,node2 -igroup <igroup_name>
----
+
[listing]
----
node_A_1-new::*> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes node_A_1-new,node_A_2-new
-igroup igroup_linux
12 entries were acted on.
----
. 새 노드에서 새로 추가된 노드가 있는지 확인합니다.
+
[source, cli]
----
lun mapping show -vserver <svm-name> -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes
----
+
[listing]
----
node_A_1-new::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes
------- --------------------------- ------------ -------------------------------------------------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux node_A_1-old,node_A_2-old,node_A_1-new,node_A_2-new
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux node_A_1-old,node_A_2-old,node_A_1-new,node_A_2-new
.
.
.
12 entries were displayed.
----
. 를 클릭합니다 `sg3-utils` Linux 호스트에 패키지가 설치되어 있어야 합니다. 이를 통해 가 방지됩니다 `rescan-scsi-bus.sh utility not found` 를 사용하여 새로 매핑된 LUN에 대해 Linux 호스트를 다시 검색할 때 오류가 발생했습니다 `rescan-scsi-bus` 명령.
+
호스트에서 를 확인합니다 `sg3-utils` 패키지가 설치됨:

+
--
** 데비안 기반 배포판의 경우:
+
[source, cli]
----
dpkg -l | grep sg3-utils
----
** Red Hat 기반 배포판의 경우:
+
[source, cli]
----
rpm -qa | grep sg3-utils
----


--
+
필요한 경우 를 설치합니다 `sg3-utils` Linux 호스트의 패키지:

+
[source, cli]
----
sudo apt-get install sg3-utils
----
. 호스트에서 호스트의 SCSI 버스를 다시 검색하여 새로 추가된 경로를 찾습니다.
+
[source, cli]
----
/usr/bin/rescan-scsi-bus.sh -a
----
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
. iSCSI 호스트에서 새로 추가된 경로를 나열합니다.
+
[source, cli]
----
sanlun lun show -p
----
+
각 LUN에 대해 4개의 경로가 표시됩니다.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
------- ---------- ------- ----------- ---------------------
host vserver
path path /dev/ host vserver
state   type       node    adapter     LIF
------  ---------- ------- ----------- ---------------------
up      primary    sdk      host3      iscsi_lf__n2_p1_
up      secondary  sdh     host2       iscsi_lf__n1_p1_
up      secondary  sdag    host4       iscsi_lf__n4_p1_
up      secondary  sdah    host5       iscsi_lf__n3_p1_
----
. 새 노드의 경우 LUN이 포함된 볼륨/볼륨을 이전 노드에서 새 노드로 이동합니다.
+
[listing]
----
node_A_1-new::*> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate sti8200mccip_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "sti8200mccip_htp_005_aggr1". Use the "volume move show -vserver
vsa_1 -volume vsa_1_vol1" command to view the status of this operation.
node_A_1-new::*> vol move show
Vserver  Volume      State       Move       Phase            Percent-Complete  Time-To-Complete
-------- ----------  --------    ---------- ---------------- ----------------  ----------------
vsa_1    vsa_1_vol1  healthy                initializing     -                 -
----
. 볼륨을 새 노드로 이동한 후 볼륨이 온라인 상태인지 확인합니다.
+
[source, cli]
----
volume show -state
----
. 이제 LUN이 상주하는 새 노드의 iSCSI 인터페이스가 기본 경로로 업데이트됩니다. 볼륨 이동 후 기본 경로가 업데이트되지 않은 경우 를 실행합니다 `/usr/bin/rescan-scsi-bus.sh -a` 및 `multipath -v3` 호스트에서 또는 단순히 다중 경로 재검색이 수행될 때까지 기다립니다.
+
다음 예제에서 기본 경로는 새 노드의 LIF입니다.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ -----------------------
host vserver
path path /dev/ host vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ------------------------
up        primary    sdag    host4        iscsi_lf__n4_p1_
up        secondary  sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_
up        secondary  sdah    host5        iscsi_lf__n3_p1_
----




== 3단계: 보고 노드를 제거하고 경로를 다시 검색합니다

보고 노드를 제거하고 경로를 다시 검색해야 합니다.

.단계
. 새 노드에서 Linux LUN에 대한 원격 보고 노드(새 노드)를 제거합니다.
+
[source, cli]
----
lun mapping remove-reporting-nodes -vserver <svm-name> -path * -igroup <igroup_name> -remote-nodes true
----
+
이 경우 원격 노드가 이전 노드입니다.

+
[listing]
----
node_A_1-new::*> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true
12 entries were acted on.
----
. 새 노드에서 LUN에 대한 보고 노드를 확인합니다.
+
[source, cli]
----
lun mapping show -vserver <svm-name> -fields reporting-nodes -ostype linux
----
+
[listing]
----
node_A_1-new::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux
vserver  path                         igroup        reporting-nodes
-------  ---------------------------  ------------  -------------------------
vsa_1    /vol/vsa_1_vol1/lun_linux_2  igroup_linux  node_A_1-new,node_A_2-new
vsa_1    /vol/vsa_1_vol1/lun_linux_3  igroup_linux  node_A_1-new,node_A_2-new
vsa_1    /vol/vsa_1_vol2/lun_linux_4  group_linux   node_A_1-new,node_A_2-new
.
.
.
12 entries were displayed.
----
. 를 클릭합니다 `sg3-utils` Linux 호스트에 패키지가 설치되어 있어야 합니다. 이를 통해 가 방지됩니다 `rescan-scsi-bus.sh utility not found` 를 사용하여 새로 매핑된 LUN에 대해 Linux 호스트를 다시 검색할 때 오류가 발생했습니다 `rescan-scsi-bus` 명령.
+
호스트에서 를 확인합니다 `sg3-utils` 패키지가 설치됨:

+
--
** 데비안 기반 배포판의 경우:
+
[source, cli]
----
dpkg -l | grep sg3-utils
----
** Red Hat 기반 배포판의 경우:
+
[source, cli]
----
rpm -qa | grep sg3-utils
----


--
+
필요한 경우 를 설치합니다 `sg3-utils` Linux 호스트의 패키지:

+
[source, cli]
----
sudo apt-get install sg3-utils
----
. iSCSI 호스트에서 SCSI 버스를 다시 검색합니다.
+
[source, cli]
----
/usr/bin/rescan-scsi-bus.sh -r
----
+
제거된 경로는 이전 노드의 경로입니다.

+
[listing]
----
[root@scspr1789621001 ~]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
.
.
.
----
. iSCSI 호스트에서 새 노드의 경로만 표시되는지 확인합니다.
+
[source, cli]
----
sanlun lun show -p
----
+
[source, cli]
----
multipath -ll -d
----

