---
permalink: transition/task_configure_the_new_nodes_and_complete_transition.html 
sidebar: sidebar 
keywords: node, complete, transition, configure, metrocluster, ip, node, configuring, disabling, disable, data, set, up, lif, bring, svm, moving, move, system, volume 
summary: 새 노드가 추가되면 전환 단계를 완료하고 MetroCluster IP 노드를 구성해야 합니다. 
---
= 새 노드 구성 및 전환 완료
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 노드가 추가되면 전환 단계를 완료하고 MetroCluster IP 노드를 구성해야 합니다.



== MetroCluster IP 노드 구성 및 전환 비활성화

MetroCluster IP 연결을 구현하고, MetroCluster 구성을 새로 고치고, 전환 모드를 비활성화해야 합니다.

. controller node_a_1-IP에서 다음 명령을 실행하여 DR 그룹으로 새 노드를 구성합니다.
+
'MetroCluster configuration-settings dr-group create-partner-cluster peer-cluster-name-local-node local-controller-name-remote-node remote-controller-name'

+
'MetroCluster configuration-settings dr-group show'를 선택합니다

. MetroCluster IP 인터페이스 생성(node_A_1-IP, node_A_2-IP, node_B_1-IP, node_B_2-IP) -- 컨트롤러당 2개의 인터페이스 생성 필요, 총 8개의 인터페이스:
+
MetroCluster configuration-settings interface create-cluster-name cluster-name-home-node controller-name-home-port port-address-netmask-vlan-id vlan-id ``metrocluster configuration-settings interface show’

+

NOTE: ONTAP 9.9.1부터 Layer 3 구성을 사용하는 경우 MetroCluster IP 인터페이스를 생성할 때 '-gateway' 매개변수도 지정해야 합니다. 을 참조하십시오 link:../install-ip/concept_considerations_layer_3.html["계층 3 광역 네트워크에 대한 고려 사항"].

+
기본 VLAN ID를 사용하지 않는 경우에만 -vlan-id 매개 변수가 필요합니다. 특정 시스템만 기본 VLAN ID가 아닌 VLAN ID를 지원합니다.

+
--
[NOTE]
====
** 특정 플랫폼은 MetroCluster IP 인터페이스에 VLAN을 사용합니다. 기본적으로 두 포트 각각은 서로 다른 VLAN을 사용합니다(10 및 20). 'MetroCluster configuration-settings interface create' 명령에서 '-vlan-id 매개 변수'를 사용하여 100보다 큰(기본 아님) VLAN을 지정할 수도 있습니다(101 ~ 4095 사이).
** ONTAP 9.9.1부터 Layer 3 구성을 사용하는 경우 MetroCluster IP 인터페이스를 생성할 때 '-gateway' 매개변수도 지정해야 합니다. 을 참조하십시오 link:../install-ip/concept_considerations_layer_3.html["계층 3 광역 네트워크에 대한 고려 사항"].


====
--
+
사용된 VLAN이 10/20 이상인 경우 기존 MetroCluster 구성에 다음 플랫폼 모델을 추가할 수 있습니다. 다른 VLAN을 사용하는 경우 MetroCluster 인터페이스를 구성할 수 없으므로 기존 구성에 이러한 플랫폼을 추가할 수 없습니다. 다른 플랫폼을 사용하는 경우 ONTAP에서는 필요하지 않으므로 VLAN 구성은 관련이 없습니다.

+
|===


| AFF 플랫폼 | FAS 플랫폼 


 a| 
** AFF A220
** AFF A250
** AFF A400

 a| 
** FAS2750
** 500f로 설정합니다
** FAS8300
** FAS8700


|===


. 컨트롤러 node_a_1-IP에서 MetroCluster 연결 작업을 수행하여 MetroCluster 사이트를 연결합니다. -- 이 작업을 완료하는 데 몇 분 정도 걸릴 수 있습니다.
+
'MetroCluster configuration-settings connection connect'를 선택합니다

. iSCSI 연결을 통해 각 컨트롤러에서 원격 클러스터 디스크가 표시되는지 확인합니다.
+
'디스크 쇼'

+
구성에 다른 노드에 속한 원격 디스크가 표시됩니다.

. node_A_1-IP 및 node_B_1-IP에 대한 루트 애그리게이트 미러링:
+
집계 미러 집계 루트 집계

. node_A_2-IP 및 node_B_2-IP에 대한 디스크를 할당합니다.
+
부팅 메뉴에서 boot_after_MCC_transition 명령이 실행될 때 node_A_1-IP 및 node_B_1-IP에 대해 이미 작성된 풀 1 디스크 할당.

+
.. node_a_2-ip에서 다음 명령을 실행합니다.
+
디스크 할당: disk1disk2disk3...diskn-sysid node_B_2-ip-controller-sysid-pool 1-force

.. node_B_2-IP에서 다음 명령을 실행합니다.
+
"디스크 할당 disk1disk2disk3...diskn-sysid node_a_2-ip-controller-sysid-pool 1-force"



. 원격 디스크에 대한 소유권이 업데이트되었는지 확인합니다.
+
'디스크 쇼'

. 필요한 경우 다음 명령을 사용하여 소유권 정보를 새로 고칩니다.
+
.. 고급 권한 모드로 이동하고 계속할 것인지 묻는 메시지가 표시되면 y를 입력합니다.
+
'et priv advanced'

.. 디스크 소유권 새로 고침:
+
디스크 리프레시-소유권 컨트롤러-이름

.. 관리자 모드로 돌아가기:
+
'et priv admin'



. node_A_2-IP 및 node_B_2-IP의 루트 애그리게이트를 미러링합니다.
+
집계 미러 집계 루트 집계

. 루트 및 데이터 애그리게이트에 대해 애그리게이트 재동기화가 완료되었는지 확인:
+
'어거 쇼' '어거 플렉스 쇼'

+
재동기화는 시간이 다소 걸릴 수 있지만 다음 단계를 진행하기 전에 완료해야 합니다.

. 새 노드를 통합하기 위해 MetroCluster 구성 새로 고침:
+
.. 고급 권한 모드로 이동하고 계속할 것인지 묻는 메시지가 표시되면 y를 입력합니다.
+
'et priv advanced'

.. 구성 새로 고침:
+
|===


| 을(를) 구성한 경우... | 이 명령 실행... 


 a| 
각 클러스터의 단일 애그리게이트:
 a| 
MetroCluster configure-refresh true-allow-with-one-aggregate true



 a| 
각 클러스터에 하나의 집합 이상
 a| 
MetroCluster 설정-새로 고침 참

|===
.. 관리자 모드로 돌아가기:
+
'et priv admin'



. MetroCluster 전환 모드 비활성화:
+
.. 고급 권한 모드로 진입하고 계속하라는 메시지가 나타나면 ""y""를 입력합니다.
+
'et priv advanced'

.. 전환 모드 비활성화:
+
MetroCluster 전환 비활성화

.. 관리자 모드로 돌아가기:
+
'et priv admin'







== 새 노드에서 데이터 LIF 설정

새 노드인 node_A_2-IP 및 node_B_2-IP에 데이터 LIF를 구성해야 합니다.

아직 할당되지 않은 경우 새 컨트롤러에서 사용할 수 있는 새 포트를 브로드캐스트 도메인에 추가해야 합니다. 필요한 경우 새 포트에 VLAN 또는 인터페이스 그룹을 생성합니다. 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/network-management/index.html["네트워크 관리"^]

. 현재 포트 사용 및 브로드캐스트 도메인 식별:
+
네트워크 포트쇼 네트워크 포트 브로드캐스트 도메인 쇼

. 필요에 따라 브로드캐스트 도메인 및 VLAN에 포트를 추가합니다.
+
.. IP 공간 보기:
+
네트워크 IPspace 쇼

.. IP 공간을 생성하고 필요에 따라 데이터 포트를 할당합니다.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-69120CF0-F188-434F-913E-33ACB8751A5D.html["IPspace 구성(클러스터 관리자만 해당)"^]

.. 브로드캐스트 도메인 보기:
+
네트워크 포트 브로드캐스트 도메인 쇼

.. 필요에 따라 브로드캐스트 도메인에 데이터 포트를 추가합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["브로드캐스트 도메인에서 포트 추가 또는 제거"^]

.. 필요에 따라 VLAN 및 인터페이스 그룹을 다시 생성합니다.
+
VLAN 및 인터페이스 그룹 멤버쉽은 이전 노드의 멤버쉽과 다를 수 있습니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["VLAN을 생성하는 중입니다"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["물리적 포트를 결합하여 인터페이스 그룹을 생성합니다"^]



. LIF가 필요에 따라 MetroCluster IP 노드(SVM with-mc vserver 포함)의 적절한 노드와 포트에서 호스팅되는지 확인합니다.
+
에서 수집한 정보를 참조하십시오 link:task_connect_the_mcc_ip_controller_modules_2n_mcc_transition_supertask.html["네트워크 구성을 만드는 중입니다"].

+
.. LIF의 홈 포트를 확인하십시오.
+
네트워크 인터페이스 show-field home-port

.. 필요한 경우 LIF 구성을 수정합니다.
+
'vserver config override -command' network interface modify -vserver vserver_name -home-port active_port_after_upgrade -lif lif_name -home-node new_node_name'

.. LIF를 홈 포트로 되돌리기:
+
'네트워크 인터페이스 되돌리기 * - vserver_vserver_name_'







== SVM을 가져오는 중입니다

LIF 구성의 변경 사항으로 인해 새 노드에서 SVM을 다시 시작해야 합니다.

.단계
. SVM 상태 확인:
+
'MetroCluster vserver show'

. ""-mc" 접미사가 없는 cluster_a에서 SVM을 다시 시작합니다.
+
'vserver start-vserver svm-name-force true'

. 파트너 클러스터에서 이전 단계를 반복합니다.
. 모든 SVM이 정상 상태인지 확인합니다.
+
'MetroCluster vserver show'

. 모든 데이터 LIF가 온라인 상태인지 확인합니다.
+
네트워크 인터페이스 쇼





== 시스템 볼륨을 새 노드로 이동

복원력을 향상시키려면 시스템 볼륨을 컨트롤러 노드_A_1-IP에서 컨트롤러 노드_A_2-IP로, 노드_B_1-IP에서 노드_B_2-IP로 이동해야 합니다. 시스템 볼륨의 대상 노드에 미러링된 애그리게이트를 생성해야 합니다.

.이 작업에 대해
시스템 볼륨에는 "mdv\_crs_*\_a" 또는 "mdv_crs_*\_B." 형식의 이름이 있습니다. ""_A" 및 ""_B" 지정은 이 섹션 전체에서 사용되는 site_A 및 site_B 참조와 관련이 없습니다. 예를 들어, MDV_CRS_ *_A는 site_A와 관련이 없습니다

.단계
. 필요한 경우 컨트롤러 node_A_2-IP 및 node_B_2-IP에 대해 풀 0 및 풀 1 디스크 3개를 각각 할당합니다.
. 디스크 자동 할당을 활성화합니다.
. site_A의 다음 단계를 사용하여 _B 시스템 볼륨을 node_A_1-IP에서 node_A_2-IP로 이동합니다
+
.. 컨트롤러 node_a_2-IP에 미러링된 애그리게이트를 만들어 시스템 볼륨을 유지합니다.
+
"aggr create-aggregate new_node_a_2-ip_aggr-diskcount 10-mirror true-node nodename_node_a_2-IP"를 나타냅니다

+
'어거 쇼'

+
미러링된 애그리게이트에는 컨트롤러 node_A_2-IP가 소유하는 풀 0 5개와 풀 1 스페어 디스크 5개가 필요합니다.

+
고급 옵션인 "'-force-small-aggregate true'"는 디스크가 부족한 경우 풀 0 3개와 풀 1 디스크 3개로 디스크 사용을 제한하는 데 사용할 수 있습니다.

.. 관리 SVM과 관련된 시스템 볼륨을 나열합니다.
+
'vserver show'

+
'volume show-vserver_admin-vserver-name_'

+
site_A가 소유한 Aggregate에 포함된 볼륨을 식별해야 합니다 site_B 시스템 볼륨도 표시됩니다.



. site_A의 MDV_CRS_ * _B 시스템 볼륨을 컨트롤러 node_A_2-IP에 생성된 미러링된 Aggregate로 이동합니다
+
.. 가능한 대상 애그리게이트 확인:
+
'volume move target-aggr show -vserver_admin -vserver-name_-volume system_vol_MDV_B'

+
node_a_2-ip에서 새로 생성된 애그리게이트를 나열해야 합니다.

.. node_A_2-IP에서 새로 생성된 Aggregate로 볼륨을 이동합니다.
+
진일진일보한 것

+
'volume move start-vserver_admin-vserver_-volume system_vol_MDV_B-destination-aggregate new_node_A_2-IP_aggr-cutover-window 40'

.. 이동 작업의 상태를 점검합니다.
+
'volume move show -vserver_admin -vserver-name_-volume system_vol_MDV_B'

.. 이동 작업이 완료되면, MDV_CRS_*_B 시스템이 node_A_2-IP의 새 집계에 포함되어 있는지 확인합니다.
+
'관리자 설정'을 선택합니다

+
'volume show-vserver_admin-vserver_'



. site_B(node_B_1-IP 및 node_B_2-IP)에서 위의 단계를 반복합니다.

