---
permalink: upgrade/concept_choosing_an_upgrade_method_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, choose, upgrade, refresh, method 
summary: 사용하는 업그레이드 또는 업데이트 절차는 플랫폼 모델, 업그레이드 범위 및 MetroCluster 구성 유형에 따라 다릅니다. 
---
= 여기서 컨트롤러 업그레이드, 시스템 업데이트 또는 확장 중 하나를 선택합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
장비 업그레이드의 범위에 따라 컨트롤러 업그레이드 절차, 시스템 새로 고침 절차 또는 확장 절차를 선택할 수 있습니다.

* 컨트롤러 업그레이드 절차는 컨트롤러 모듈에만 적용됩니다. 컨트롤러가 새 컨트롤러 모델로 교체됩니다.
+
스토리지 쉘프 모델은 업그레이드되지 않습니다.

+
** 스위치오버 및 스위치백 절차에서 MetroCluster 스위치오버 작동은 파트너 클러스터의 컨트롤러 모듈이 업그레이드되는 동안 클라이언트에 무중단 서비스를 제공하는 데 사용됩니다.
** ARL 기반 컨트롤러 업그레이드 절차에서는 애그리게이트 재배치 작업을 사용하여 데이터를 이전 구성에서 업그레이드된 새 구성으로 중단 없이 이동할 수 있습니다.


* 업데이트 절차는 컨트롤러 및 스토리지 쉘프에 적용됩니다.
+
새로 고침 절차에서는 MetroCluster 구성에 새 컨트롤러와 쉘프를 추가하여 두 번째 DR 그룹을 생성한 다음, 데이터가 새 노드로 중단 없이 마이그레이션됩니다.

+
그러면 원래 컨트롤러가 폐기됩니다.

* 확장 절차를 사용하면 컨트롤러 및 쉘프를 제거하지 않고 MetroCluster 구성에 추가할 수 있습니다.
+
사용하는 절차는 MetroCluster 유형과 기존 컨트롤러의 수에 따라 다릅니다.




CAUTION: SVM 마이그레이션이 진행 중인 경우 모든 마이그레이션 프로세스가 완료될 때까지 기다린 후 컨트롤러 업그레이드 또는 시스템 업데이트 절차를 시작하십시오. 업그레이드 또는 업데이트 프로세스 중에 새로운 SVM 마이그레이션 작업을 시작하지 마십시오.

[cols="2,5"]
|===


| 업그레이드 유형 | 이동... 


 a| 
컨트롤러 업그레이드
 a| 
link:../upgrade/concept_choosing_controller_upgrade_mcc.html["컨트롤러 업그레이드 절차를 선택합니다"]



 a| 
시스템 새로 고침
 a| 
link:../upgrade/concept_choosing_tech_refresh_mcc.html["시스템 새로 고침 절차를 선택합니다"]



 a| 
확장
 a| 
* link:../upgrade/task_expand_a_two_node_mcc_fc_configuration_to_a_four_node_fc_configuration_supertask.html["2노드 MetroCluster를 4개로 설정합니다"]
* link:../upgrade/task_expand_a_four_node_mcc_fc_configuration_to_an_eight_node_configuration.html["4노드 MetroCluster FC를 8개로 설정합니다"]
* link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["4노드 MetroCluster IP를 8로 설정합니다"]


|===