---
permalink: upgrade/task_configure_intercluster_lifs_to_share_data_ports.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, intercluster, lif, shared, data, ports 
summary: 데이터 네트워크와 공유하는 포트에 대한 인터클러스터 LIF를 구성할 수 있습니다. 이렇게 하면 인터클러스터 네트워킹에 필요한 포트 수가 줄어듭니다. 
---
= 공유 데이터 포트에 대한 인터클러스터 LIF 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 네트워크와 공유하는 포트에 대한 인터클러스터 LIF를 구성할 수 있습니다. 이렇게 하면 인터클러스터 네트워킹에 필요한 포트 수가 줄어듭니다.

.단계
. 클러스터의 포트 나열:
+
네트워크 포트 쇼

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예는 cluster01의 네트워크 포트를 보여줍니다.

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. 시스템 SVM에 대한 인터클러스터 LIF 생성:
+
|===


| * ONTAP 9.6 이상: * 


 a| 
'network interface create-vserver_system_SVM_-lif_LIF_name_-service-policy default-인터클러스터-home-node_node_-home-port_port_-address_port_ip_-netmask_mask_'



| * ONTAP 9.5 및 이전 버전의 경우: * 


 a| 
'network interface create-vserver_system_SVM_-lif_LIF_name_-role l인터클러스터-home-node_node_-home-port_port_-address_port_ip_-netmask_mask_'

|===
+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 인터클러스터 LIF 'cluster01_icl01'과 'cluster01_icl02'를 생성합니다.

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. 인터클러스터 LIF가 생성되었는지 확인합니다.
+
|===


| * ONTAP 9.6 이상: * 


 a| 
네트워크 인터페이스 show-service-policy default-인터클러스터



| * ONTAP 9.5 및 이전 버전의 경우: * 


 a| 
네트워크 인터페이스 show-role 인터클러스터(network interface show-role 인터클러스터)

|===
+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. 인터클러스터 LIF가 중복되는지 확인합니다.
+
|===


| * ONTAP 9.6 이상: * 


 a| 
'network interface show – service-policy default-인터클러스터-failover'



| * ONTAP 9.5 및 이전 버전의 경우: * 


 a| 
네트워크 인터페이스 show-role 인터클러스터-failover를 참조하십시오

|===
+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 "e0c" 포트의 인터클러스터 LIF "cluster01_icl01" 및 "cluster01_icl02"가 "e0d" 포트로 페일오버되는 것을 보여 줍니다.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

