---
permalink: upgrade/task_refresh_the_mcc_configuration_mcc_configure_refresh.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, refresh, configuration, new, controller 
summary: 2노드 구성에서 4노드 구성으로 확장할 경우 MetroCluster 구성을 새로 고쳐야 합니다. 
---
= 새 컨트롤러로 MetroCluster 구성 새로 고침
:icons: font
:imagesdir: ../media/


[role="lead"]
2노드 구성에서 4노드 구성으로 확장할 경우 MetroCluster 구성을 새로 고쳐야 합니다.

.단계
. MetroCluster 구성 새로 고침:
+
.. 고급 권한 모드: + 'Set-Privilege advanced'로 진입합니다
.. MetroCluster 설정 새로 고침: + 'MetroCluster configure-refresh true-allow-with-one-aggregate true'
+
다음 명령을 실행하면 controller_a_1이 포함된 DR 그룹의 모든 노드에서 MetroCluster 구성이 새로 고쳐집니다.

+
[listing]
----
controller_A_1::*> metrocluster configure -refresh true -allow-with-one-aggregate true

[Job 726] Job succeeded: Configure is successful.
----
.. 관리자 권한 모드로 돌아가기:
+
'Set-Privilege admin'입니다



. 사이트 A의 네트워킹 상태를 확인합니다.
+
네트워크 포트 쇼

+
다음 예는 4노드 MetroCluster 구성의 네트워크 포트 사용량을 보여 줍니다.

+
[listing]
----
cluster_A::> network port show
                                                          Speed (Mbps)
Node   Port      IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ --------- --------- ---------------- ----- ------- ------------
controller_A_1
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
controller_A_2
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
14 entries were displayed.
----
. MetroCluster 구성의 두 사이트에서 MetroCluster 구성을 확인합니다.
+
.. 사이트 A에서 구성을 확인합니다.
+
MetroCluster 쇼

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 사이트 B의 구성을 확인합니다.
+
MetroCluster 쇼

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. DR 관계가 올바르게 생성되었는지 확인:
+
'MetroCluster node show-fields dr-cluster, dr-auxiliary, node-object-limit, automatic-USO, ha-partner, dr-partner'

+
[listing]
----
metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner
dr-group-id cluster     node    ha-partner dr-cluster  dr-partner   dr-auxiliary  node-object-limit automatic-uso
----------- ---------   ----    ---------- ----------  ----------   ------------  ----------------- -------------
2           cluster_A   node_A_1 node_A_2    cluster_B  node_B_1     node_B_2      on                true
2           cluster_A   node_A_2 node_A_1    cluster_B  node_B_2     node_B_1      on                true
2           cluster_B   node_B_1 node_B_2    cluster_A  node_A_1     node_A_2      on                true
2           cluster_B   node_B_2 node_B_1    cluster_A  node_A_2     node_A_1      on                true
4 entries were displayed.
----



