---
permalink: upgrade/task_boot_the_new_controllers_and_join_them_to_the_cluster.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, boot, new, controller, join, cluster 
summary: 새 컨트롤러를 클러스터에 연결하려면 각 새 컨트롤러 모듈을 부팅하고 ONTAP 클러스터 설정 마법사를 사용하여 클러스터가 결합될 것을 식별해야 합니다. 
---
= 새 컨트롤러를 부팅하고 클러스터에 가입합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 컨트롤러를 클러스터에 연결하려면 각 새 컨트롤러 모듈을 부팅하고 ONTAP 클러스터 설정 마법사를 사용하여 클러스터가 결합될 것을 식별해야 합니다.

.시작하기 전에
MetroCluster 구성에 케이블로 연결되어 있어야 합니다.

이 작업을 수행하기 전에 서비스 프로세서를 구성하지 않아야 합니다.

.이 작업에 대해
이 작업은 MetroCluster 구성의 두 클러스터에 있는 각각의 새 컨트롤러에 대해 수행해야 합니다.

.단계
. 아직 수행하지 않은 경우 각 노드의 전원을 켜고 완전히 부팅하십시오.
+
시스템이 유지보수 모드인 경우 '중지' 명령을 실행하여 유지보수 모드를 종료한 다음 LOADER 프롬프트에서 다음 명령을 실행합니다.

+
부트 ONTAP

+
컨트롤러 모듈이 노드 설정 마법사를 시작합니다.

+
출력은 다음과 비슷해야 합니다.

+
[listing]
----
Welcome to node setup

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
				Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.
.
.
.
----
. 시스템에서 제공하는 지침에 따라 AutoSupport 도구를 활성화합니다.
. 프롬프트에 응답하여 노드 관리 인터페이스를 구성합니다.
+
프롬프트는 다음과 유사합니다.

+
[listing]
----
Enter the node management interface port: [e0M]:
Enter the node management interface IP address: 10.228.160.229
Enter the node management interface netmask: 225.225.252.0
Enter the node management interface default gateway: 10.228.160.1
----
. 노드가 고가용성 모드로 구성되었는지 확인합니다.
+
'스토리지 페일오버 표시 필드 모드'

+
그렇지 않은 경우 각 노드에서 다음 명령을 실행한 다음 노드를 재부팅해야 합니다.

+
'Storage failover modify-mode ha-node localhost'

+
이 명령은 고가용성 모드를 구성하지만 스토리지 페일오버를 사용하도록 설정하지는 않습니다. 구성 프로세스 후반부에 'MetroCluster configure' 명령을 실행하면 스토리지 페일오버가 자동으로 설정됩니다.

. 클러스터 인터커넥트에 4개의 포트가 구성되어 있는지 확인합니다.
+
네트워크 포트 쇼

+
다음 예에서는 cluster_A의 컨트롤러 2개에 대한 출력을 보여 줍니다 2노드 MetroCluster 구성인 경우 출력에는 하나의 노드만 표시됩니다.

+
[listing]
----
cluster_A::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node_A_1
       **e0a       Cluster      Cluster          up       1500  auto/1000
       e0b       Cluster      Cluster          up       1500  auto/1000**
       e0c       Default      Default          up       1500  auto/1000
       e0d       Default      Default          up       1500  auto/1000
       e0e       Default      Default          up       1500  auto/1000
       e0f       Default      Default          up       1500  auto/1000
       e0g       Default      Default          up       1500  auto/1000
node_A_2
       **e0a       Cluster      Cluster          up       1500  auto/1000
       e0b       Cluster      Cluster          up       1500  auto/1000**
       e0c       Default      Default          up       1500  auto/1000
       e0d       Default      Default          up       1500  auto/1000
       e0e       Default      Default          up       1500  auto/1000
       e0f       Default      Default          up       1500  auto/1000
       e0g       Default      Default          up       1500  auto/1000
14 entries were displayed.
----
. CLI를 사용하여 클러스터를 설정하기 때문에 노드 설정 마법사를 종료합니다.
+
종료

. admin 사용자 이름을 사용하여 admin 계정에 로그인합니다.
. 클러스터 설정 마법사를 시작한 다음 기존 클러스터를 결합합니다.
+
'클러스터 설정'

+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the cluster setup wizard.
     Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value.


Do you want to create a new cluster or join an existing cluster? {create, join}:`join`
----
. 클러스터 설정 * 마법사를 완료하고 종료한 후 클러스터가 활성 상태이고 노드가 정상 상태인지 확인합니다.
+
'클러스터 쇼'

+
다음 예에서는 첫 번째 노드(cluster1-01)가 정상이고 참여할 자격이 있는 클러스터를 보여 줍니다.

+
[listing]
----
cluster_A::> cluster show
Node               Health  Eligibility
------------------ ------- ------------
node_A_1           true    true
node_A_2           true    true
node_A_3           true    true
----
+
admin SVM 또는 node SVM에 대해 입력한 설정을 변경해야 하는 경우 "cluster setup 명령"을 사용하여 * 클러스터 설정 * 마법사에 액세스할 수 있습니다.


