---
permalink: upgrade/task_configure_the_fc_to_sas_bridges_for_health_monitor.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, fc, sas, bridges, health, monitoring 
summary: FiberBridge 브리지는 타사 SNMP 모니터링 도구를 지원하지 않습니다. ONTAP 9.8부터 FC-SAS 브리지는 기본적으로 대역내 연결을 통해 모니터링되며 추가 구성은 필요하지 않습니다. 
---
= 상태 모니터링을 위한 FC-to-SAS 브리지 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


.이 작업에 대해
* FiberBridge 브리지는 타사 SNMP 모니터링 도구를 지원하지 않습니다.
* ONTAP 9.8부터 FC-SAS 브리지는 기본적으로 대역내 연결을 통해 모니터링되며 추가 구성은 필요하지 않습니다.



NOTE: ONTAP 9.8부터 스토리지 브리지 명령이 시스템 브리지로 바뀌었습니다. 다음 단계에서는 'Storage bridge' 명령어를 보여주지만, ONTAP 9.8 이상을 실행 중인 경우에는 'system bridge' 명령어를 사용한다.

.단계
. ONTAP 클러스터 프롬프트에서 상태 모니터링에 브리지를 추가합니다.
+
.. 사용 중인 ONTAP 버전에 대한 명령을 사용하여 브리지를 추가합니다.
+
|===


| ONTAP 버전입니다 | 명령 


 a| 
9.5 이상
 a| 
스토리지 브리지 추가 주소 0.0.0.0 - 대역내 관리 이름_브리지-이름_



 a| 
9.4 이하
 a| 
'Storage bridge add-address_bridge-ip-address_-name_bridge-name_'

|===
.. 브리지가 추가되었으며 올바르게 구성되었는지 확인합니다.
+
'스토리지 브리지 쇼'

+
폴링 간격 때문에 모든 데이터가 반영되는 데 15분 정도 걸릴 수 있습니다. ONTAP 상태 모니터는 "상태" 열의 값이 "확인"이고 WWN(Worldwide Name)과 같은 기타 정보가 표시되는 경우 브리지에 연결하고 모니터링할 수 있습니다.

+
다음 예는 FC-to-SAS 브리지가 구성된 경우를 보여줍니다.

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----



