---
permalink: upgrade/task_create_a_mirrored_data_aggregate_on_each_node_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, mirrored, data, aggregate, node 
summary: DR 그룹의 각 노드에 미러링된 데이터 애그리게이트를 만들어야 합니다. 
---
= 각 노드에서 미러링된 데이터 애그리게이트 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DR 그룹의 각 노드에 미러링된 데이터 애그리게이트를 만들어야 합니다.

.이 작업에 대해
* 새 애그리게이트에 어떤 드라이브가 사용되는지 알아야 합니다.
* 시스템에 여러 드라이브 유형(이기종 스토리지)이 있는 경우 올바른 드라이브 유형을 선택할 수 있는 방법을 이해해야 합니다.
* 드라이브는 특정 노드에 의해 소유되며, 애그리게이트를 생성할 경우, 애그리게이트에 있는 모든 드라이브는 동일한 노드에 의해 소유되어야 하며, 이 노드는 해당 애그리게이트의 홈 노드가 됩니다.
+
ADP를 사용하는 시스템에서는 각 드라이브가 P1, P2, P3 파티션으로 분할되는 파티션을 사용하여 애그리게이트를 생성합니다.

* 애그리게이트 이름은 MetroCluster 구성을 계획할 때 지정한 명명 규칙에 따라야 합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"]



.단계
. 사용 가능한 스페어 목록을 표시합니다.
+
'storage disk show-spare-owner_node_name_'

. 애그리게이트 생성:
+
'스토리지 집계 생성 - 미러 true'

+
클러스터 관리 인터페이스에서 클러스터에 로그인한 경우 클러스터의 모든 노드에 대해 애그리게이트를 생성할 수 있습니다. Aggregate가 특정 노드에서 생성되도록 하려면 '-node' 매개 변수를 사용하거나 해당 노드가 소유하는 드라이브를 지정합니다.

+
다음 옵션을 지정할 수 있습니다.

+
** Aggregate의 홈 노드(즉, 정상 운영 시 Aggregate를 소유한 노드)
** Aggregate에 추가될 특정 드라이브 목록입니다
** 포함할 드라이브 수입니다
+

NOTE: 지원되는 최소 구성에서는 드라이브 수가 제한되어 있으므로, 디스크 RAID-DP Aggregate 3개를 만들 수 있도록 force-small-aggregate 옵션을 사용해야 합니다.

** 집계에 사용할 체크섬 스타일
** 사용할 드라이브 유형입니다
** 사용할 드라이브의 크기입니다
** 주행 속도를 사용하십시오
** Aggregate의 RAID 그룹에 적합한 RAID 유형입니다
** RAID 그룹에 포함될 수 있는 최대 드라이브 수입니다
** RPM이 다른 드라이브가 허용되는지 여부
+
이러한 옵션에 대한 자세한 내용은 '저장소 집계 만들기' man 페이지를 참조하십시오.

+
다음 명령을 실행하면 10개의 디스크로 미러링된 Aggregate가 생성됩니다.

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. 새 애그리게이트의 RAID 그룹 및 드라이브를 확인합니다.
+
'Storage aggregate show-status-aggregate_aggregate-name_'


