---
permalink: upgrade/task_prepare_for_the_upgrade_add_2nd_controller_to_create_ha_pair.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, prepare, upgrade 
summary: HA 쌍으로 업그레이드하기 전에 시스템이 모든 요구사항을 충족하는지, 그리고 모든 필요한 정보를 갖추고 있는지 확인해야 합니다. 
---
= 업그레이드를 준비하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
HA 쌍으로 업그레이드하기 전에 시스템이 모든 요구사항을 충족하는지, 그리고 모든 필요한 정보를 갖추고 있는지 확인해야 합니다.

.단계
. 새 컨트롤러 모듈에 할당할 수 있는 할당되지 않은 디스크 또는 스페어 디스크를 식별해야 합니다.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2427462["물리적 스토리지 관리 가이드"]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"]

. 이전 단계의 결과에 따라 다음 중 하나를 수행합니다.
+
|===


| 결과가 다음과 같은 경우... | 그러면... 


 a| 
루트 데이터 파티셔닝 없이 시스템의 새 컨트롤러 모듈에 사용 가능한 스페어 디스크가 충분하지 않습니다
 a| 
자세한 내용은 기술 지원 부서에 문의하십시오.



 a| 
기타 결과
 a| 
다음 하위 단계를 완료합니다.

.. 기존 노드의 Aggregate가 위치한 위치를 확인합니다.
+
'스토리지 집계 쇼'

.. 디스크 소유권 자동 할당이 켜져 있으면 다음과 같이 끕니다.
+
'storage disk option modify -node_node_name_-autoassign off'

.. Aggregate가 없는 디스크의 소유권을 제거합니다.
+
'Storage disk removeowner_disk_name_'

.. 새 노드에 필요한 만큼 디스크에 대해 이전 단계를 반복합니다.


|===
. 다음 연결에 사용할 수 있는 케이블이 있는지 확인합니다.
+
** 클러스터 연결
+
스위치가 없는 2노드 클러스터를 생성하는 경우 컨트롤러 모듈을 연결하는 데 2개의 케이블이 필요합니다. 그렇지 않으면 클러스터 네트워크 스위치에 대한 컨트롤러 모듈 연결당 2개씩, 최소 4개의 케이블이 필요합니다. 다른 시스템(예: 80xx 시리즈)에는 기본적으로 4개 또는 6개의 클러스터 연결이 있습니다.

** 시스템이 이중 섀시 HA 쌍인 경우 HA 인터커넥트 연결


. 컨트롤러 모듈에 사용할 수 있는 직렬 포트 콘솔이 있는지 확인합니다.
. 사용 환경이 사이트 및 시스템 요구 사항을 충족하는지 확인합니다.
+
https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]

. 새 컨트롤러 모듈에 대한 모든 IP 주소 및 기타 네트워크 매개 변수를 수집합니다.

