---
permalink: upgrade/task_install_and_cable_the_new_controller.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, install, cable, new, controller, module 
summary: 섀시에 새 컨트롤러 모듈을 물리적으로 설치한 다음 케이블을 연결해야 합니다. 
---
= 새 컨트롤러 모듈 설치 및 케이블 연결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
섀시에 새 컨트롤러 모듈을 물리적으로 설치한 다음 케이블을 연결해야 합니다.

.단계
. 시스템에 I/O 확장 모듈(IOXM)이 있고 단일 섀시 HA 쌍을 생성하는 경우, IOXM을 분리하고 케이블을 분리해야 합니다.
+
그런 다음 새 컨트롤러 모듈에 빈 베이를 사용할 수 있습니다. 하지만 새 구성에는 IOXM이 제공하는 추가 I/O가 포함되지 않습니다.

. 새 컨트롤러 모듈을 물리적으로 설치하고 필요한 경우 추가 팬을 설치합니다.
+
|===


| 컨트롤러 모듈을 추가하는 경우... | 그런 다음 다음 다음 단계를 수행하십시오. 


 a| 
빈 베이에 단일 섀시 HA 쌍을 생성하고 시스템이 다음 플랫폼 중 하나에 속합니다.
 a| 
.. 새 컨트롤러 모듈이 들어 있는 빈 베이를 덮고 있는 섀시 후면의 블랭크 플레이트를 분리합니다.
.. 컨트롤러 모듈을 반쯤 섀시에 밀어 넣습니다.
+
컨트롤러 모듈이 자동으로 부팅되는 것을 방지하려면 이 절차의 뒷부분에서 완전히 장착하지 마십시오.





 a| 
기존 구성이 컨트롤러-IOX 모듈 구성에 있을 때 이중 섀시 HA 쌍을 생성하기 위해 HA 파트너와 별도의 섀시.

** FAS8200
** 80xx

 a| 
랙 또는 시스템 캐비닛에 새 시스템을 설치합니다.

|===
. 필요에 따라 클러스터 네트워크 연결을 케이블로 연결합니다.
+
.. 클러스터 연결을 위한 컨트롤러 모듈의 포트를 식별합니다.
+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["AFF A320 시스템: 설치 및 설정"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["AFF A220/FAS2700 시스템 설치 및 설정 지침"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["AFF A800 시스템 설치 및 설정 지침"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["AFF A300 시스템 설치 및 설정 지침"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["FAS8200 시스템 설치 및 설정 지침"^]

.. 스위치 클러스터를 구성하는 경우 클러스터 네트워크 스위치에서 사용할 포트를 식별합니다.
+
사용 중인 스위치에 따라 Cisco 스위치_,_NetApp 10G 클러스터 모드 스위치 설치 가이드_또는_NetApp 1G 클러스터 모드 스위치 설치 가이드_에 대한 _Data ONTAP 스위치 설정 가이드를 참조하십시오.

.. 클러스터 포트에 케이블 연결:


+
|===


| 클러스터가... | 그러면... 


 a| 
스위치가 없는 2노드 클러스터
 a| 
기존 컨트롤러 모듈의 클러스터 포트를 새 컨트롤러 모듈의 해당 클러스터 포트에 직접 연결합니다.



 a| 
스위치 클러스터
 a| 
Substep b에 나와 있는 클러스터 네트워크 스위치의 포트에 각 컨트롤러의 클러스터 포트를 연결합니다

|===

