---
permalink: upgrade/task_create_unmirrored_data_aggregates_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, unmirrored, data, aggregates 
summary: 선택적으로 MetroCluster 구성에서 제공되는 이중 미러링이 필요하지 않은 데이터에 대해 미러링되지 않은 데이터 애그리게이트를 만들 수 있습니다. 
---
= 미러링되지 않은 데이터 애그리게이트를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
선택적으로 MetroCluster 구성에서 제공되는 이중 미러링이 필요하지 않은 데이터에 대해 미러링되지 않은 데이터 애그리게이트를 만들 수 있습니다.

.이 작업에 대해
* 새 애그리게이트에 어떤 드라이브 또는 어레이 LUN을 사용할 것인지 알아야 합니다.
* 시스템에 여러 드라이브 유형(이기종 스토리지)이 있는 경우 올바른 드라이브 유형이 선택되었는지 확인하는 방법을 이해해야 합니다.



IMPORTANT: MetroCluster IP 구성에서는 전환 후 원격 미러링되지 않은 애그리게이트에 액세스할 수 없습니다


NOTE: 미러링되지 않은 애그리게이트는 해당 애그리게이트를 소유하는 노드에 로컬이어야 합니다.

* 드라이브 및 어레이 LUN은 특정 노드에 의해 소유되며, 애그리게이트를 생성할 경우, 애그리게이트에 있는 모든 드라이브가 동일한 노드에 소유되어야 하며, 이 노드가 해당 애그리게이트의 홈 노드가 됩니다.
* 애그리게이트 이름은 MetroCluster 구성을 계획할 때 지정한 명명 규칙에 따라야 합니다.
* _ 디스크 및 애그리게이트 관리 _ 는 미러링 Aggregate에 대한 자세한 정보를 포함합니다.


.단계
. 미러링되지 않은 애그리게이트를 포함할 디스크 쉘프를 설치 및 케이블로 연결합니다.
+
플랫폼 및 디스크 쉘프에 대한 _Installation 및 Setup_설명서의 절차를 사용할 수 있습니다.

+
https://docs.netapp.com/platstor/index.jsp["ONTAP 하드웨어 시스템 설명서"^]

. 새 쉘프의 모든 디스크를 적절한 노드에 수동으로 할당합니다.
+
디스크 할당 - disk_disk -id_-owner_owner -node -name _

. 애그리게이트 생성:
+
'스토리지 애그리게이트 생성'

+
클러스터 관리 인터페이스에서 클러스터에 로그인한 경우 클러스터의 모든 노드에 대해 애그리게이트를 생성할 수 있습니다. Aggregate가 특정 노드에 생성되었는지 확인하려면 '-node' 매개 변수를 사용하거나 해당 노드가 소유하는 드라이브를 지정해야 합니다.

+
또한 미러링되지 않은 쉘프의 드라이브만 애그리게이트에 포함되어 있는지 확인해야 합니다.

+
다음 옵션을 지정할 수 있습니다.

+
** Aggregate의 홈 노드(즉, 정상 운영 시 Aggregate를 소유한 노드)
** 애그리게이트에 추가될 특정 드라이브 또는 어레이 LUN의 목록입니다
** 포함할 드라이브 수입니다
** 집계에 사용할 체크섬 스타일
** 사용할 드라이브 유형입니다
** 사용할 드라이브의 크기입니다
** 주행 속도를 사용하십시오
** Aggregate의 RAID 그룹에 적합한 RAID 유형입니다
** RAID 그룹에 포함될 수 있는 최대 드라이브 또는 어레이 LUN 수
** RPM이 다른 드라이브가 허용되는지 여부
+
이러한 옵션에 대한 자세한 내용은 '저장소 집계 만들기' man 페이지를 참조하십시오.

+
다음 명령을 실행하면 10개의 디스크로 구성된 미러링되지 않은 Aggregate가 생성됩니다.

+
[listing]
----
controller_A_1::> storage aggregate create aggr1_controller_A_1 -diskcount 10 -node controller_A_1
[Job 15] Job is queued: Create aggr1_controller_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. 새 애그리게이트의 RAID 그룹 및 드라이브를 확인합니다.
+
'Storage aggregate show-status-aggregate_aggregate-name_'



.관련 정보
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"]
