---
permalink: upgrade/task_prepare_the_netboot_server_cluster_mode.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, prepare, netboot, server, download, image 
summary: netboot 서버를 준비할 준비가 되면 NetApp Support 사이트에서 netboot 서버로 올바른 ONTAP netboot 이미지를 다운로드하고 IP 주소를 메모해야 합니다. 
---
= 이미지를 다운로드하기 위해 netboot 서버를 준비하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
netboot 서버를 준비할 준비가 되면 NetApp Support 사이트에서 netboot 서버로 올바른 ONTAP netboot 이미지를 다운로드하고 IP 주소를 메모해야 합니다.

.이 작업에 대해
* 새 컨트롤러 모듈을 추가하기 전과 추가한 후에 시스템에서 HTTP 서버에 액세스할 수 있어야 합니다.
* 플랫폼과 ONTAP 버전에 필요한 시스템 파일을 다운로드하려면 NetApp Support 사이트에 액세스할 수 있어야 합니다.
+
https://mysupport.netapp.com/site/global/dashboard["NetApp Support 사이트"]

* HA 쌍의 두 컨트롤러 모듈은 같은 버전의 ONTAP를 실행해야 합니다.


.단계
. NetApp Support 사이트의 소프트웨어 다운로드 섹션에서 해당 ONTAP 소프트웨어를 다운로드하고 웹 액세스 가능한 디렉토리에 '<ONTAP_version>_image.tgz' 파일을 저장합니다.
+
"<ONTAP_VERSION>_IMAGE.tgz" 파일은 시스템의 netboot를 수행하는 데 사용됩니다.

. 웹 액세스 가능 디렉토리로 변경하고 필요한 파일을 사용할 수 있는지 확인합니다.
+
|===


| 대상... | 그러면... 


 a| 
FAS2200, FAS2500, FAS3200, FAS6200, FAS/AFF8000 시리즈 시스템
 a| 
ONTAP_VERSION>_IMAGE.tgz 파일의 내용을 타겟 디렉토리에 풉니다.

'tar-zxvf<ONTAP_version>_image.tgz'


NOTE: Windows에서 내용을 추출하는 경우 7-Zip 또는 WinRAR을 사용하여 netboot 이미지를 추출합니다.

디렉토리 목록에는 커널 파일이 있는 netboot 폴더가 포함되어야 합니다.

넷부트/커널



 a| 
기타 모든 시스템
 a| 
디렉토리 목록에는 다음 파일이 포함되어야 합니다.

'<ONTAP_VERSION>_IMAGE.tgz'


NOTE: 파일 내용을 추출할 필요가 없습니다.

|===
. 기존 컨트롤러 모듈의 IP 주소를 확인합니다.
+
이 주소는 이 절차의 후반부에서 '_ip-address-of-existing controller_'로 참조됩니다.

. IP 주소에 연결할 수 있는지 확인하기 위해 기존 컨트롤러의 IP 주소(_IP-address-of-existing controller_)를 ping합니다.

