---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-prepare-network-configuration.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 정보를 수집하고 작업을 재개하면 자동화 작업이 전환을 진행합니다. 
---
= 이전 MetroCluster IP 컨트롤러의 네트워크 구성을 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정보를 수집하고 작업을 재개하면 자동화 작업이 전환을 진행합니다.

.시작하기 전에
전환을 시작하기 전에 자동화 작업이 일시 중지되므로 사이트 B에서 모든 LIF가 ""가동""인지 수동으로 확인할 수 있습니다 필요한 경우 'down'인 LIF를 'up'으로 가져가 'system controller replace resume' 명령을 사용하여 자동화 작업을 다시 시작합니다.

자동화 작업이 전환 작업을 시작합니다. 이러한 작업이 완료되면 사용자 개입을 위해 * 일시 중지 * 시 작업이 일시 중지되므로 컨트롤러를 랙에 설치하고 설치하고, 파트너 컨트롤러를 부팅하고, 앞서 수집한 를 사용하여 플래시 백업에서 루트 애그리게이트 디스크를 새 컨트롤러 모듈에 재할당할 수 있습니다 `sysids`.

.이 작업에 대해
* 이 작업은 각 이전 노드에서 수행해야 합니다.
* 에서 수집한 정보를 link:upgrade-mcc-ip-system-controller-replace-prechecks.html#gather-information-before-the-upgrade["업그레이드하기 전에 정보를 수집합니다"]사용합니다.


.단계
. 이전 노드를 부팅하고 노드에 로그인합니다.
+
부트 ONTAP

. 업그레이드 대상 시스템에서 * 공유 클러스터/HA 포트 * 를 사용하는 경우 MetroCluster IP 인터페이스에서 지원되는 IP 주소를 사용하고 있는지 확인하십시오.
+
다음 정보를 사용하여 새 시스템에서 공유 클러스터/HA 포트를 사용하는지 여부를 확인하십시오.

+
[role="tabbed-block"]
====
.공유 클러스터/HA 포트
--
다음 표에 나열된 시스템은 공유 클러스터/HA 포트를 사용합니다.

[cols="2*"]
|===
| AFF 및 ASA 시스템 | FAS 시스템 


 a| 
** AFF A20 를 참조하십시오
** AFF A30
** AFF C30
** AFF A50 를 참조하십시오
** AFF C60
** AFF C80 를 참조하십시오
** AFF A70 를 참조하십시오
** AFF A90 를 참조하십시오
** AFF A1K 를 참조하십시오

 a| 
** FAS50를 참조하십시오
** FAS70를 참조하십시오
** FAS90를 참조하십시오


|===
--
.공유 MetroCluster/HA 포트
--
다음 표에 나열된 시스템은 공유 MetroCluster/HA 포트를 사용합니다.

[cols="2*"]
|===
| AFF 및 ASA 시스템 | FAS 시스템 


 a| 
** AFF A150, ASA A150
** AFF A220
** AFF C250, ASA C250
** AFF A250, ASA A250
** AFF A300
** AFF A320
** AFF C400, ASA C400
** AFF A400, ASA A400
** AFF A700
** AFF C800, ASA C800
** AFF A800, ASA A800
** AFF A900, ASA A900

 a| 
** FAS2750
** 500f로 설정합니다
** FAS8200
** FAS8300
** FAS8700
** FAS9000
** FAS9500


|===
--
====
+
.. 이전 컨트롤러에서 MetroCluster 인터페이스의 IP 주소를 확인합니다.
+
'MetroCluster configuration-settings interface show'를 선택합니다

.. MetroCluster 인터페이스에서 169.254.17.x 또는 169.254.18.x IP 주소를 사용하는 경우, 업그레이드를 진행하기 전에 인터페이스 IP 주소를 수정하려면 을 참조하십시오.link:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/How_to_modify_the_properties_of_a_MetroCluster_IP_interface["기술 문서 "MetroCluster IP 인터페이스의 속성을 수정하는 방법""^]
+

CAUTION: MetroCluster 인터페이스가 169.254.17.x 또는 169.254.18.x IP 주소로 구성된 경우 * 공유 클러스터/HA 포트 * 를 사용하는 시스템으로의 업그레이드는 지원되지 않습니다.



. 새 컨트롤러의 HA 인터커넥트 또는 MetroCluster IP DR 인터커넥트에 사용되는 포트와 다른 홈 포트를 사용하도록 이전 컨트롤러의 인터클러스터 LIF를 수정합니다.
+

NOTE: 이 단계는 성공적인 업그레이드를 위해 필요합니다.

+
이전 컨트롤러의 인터클러스터 LIF는 새 컨트롤러의 HA 인터커넥트 또는 MetroCluster IP DR 인터커넥트에 사용되는 포트와 다른 홈 포트를 사용해야 합니다. 예를 들어, AFF A90 컨트롤러로 업그레이드할 때 HA 인터커넥트 포트는 e1A와 e7a이고, MetroCluster IP DR 인터커넥트 포트는 e2b와 e3b입니다. 이전 컨트롤러가 포트 E1A, e7a, e2b 또는 e3b에서 호스팅되는 경우 인터클러스터 LIF를 이동해야 합니다.

+
새 노드에서의 포트 분배 및 할당은 를 https://hwu.netapp.com["Hardware Universe"]참조하십시오.

+
.. 이전 컨트롤러에서 인터클러스터 LIF를 확인하십시오.
+
`network interface show  -role intercluster`

+
이전 컨트롤러의 인터클러스터 LIF가 새 컨트롤러의 MetroCluster IP DR 인터커넥트에 사용되는 포트와 동일한 포트를 사용하는지 여부에 따라 다음 작업 중 하나를 수행합니다.

+
[cols="2*"]
|===
| 클러스터 간 LIF가 필요한 경우... | 이동... 


| 동일한 홈 포트를 사용합니다 | <<controller_replace_upgrade_prepare_network_ports_2b,하위 단계 b>> 


| 다른 홈 포트를 사용합니다 | <<controller_replace_upgrade_prepare_network_ports_3,4단계>> 
|===
.. [[controller_replace_upgrade_prepare_network_ports_2b]] 다른 홈 포트를 사용하도록 인터클러스터 LIF를 수정합니다.
+
`network interface modify -vserver <vserver> -lif <intercluster_lif> -home-port <port-not-used-for-ha-interconnect-or-mcc-ip-dr-interconnect-on-new-nodes>`

.. 모든 인터클러스터 LIF가 새 홈 포트에 설정되었는지 확인합니다.
+
`network interface show -role intercluster -is-home  false`

+
명령 출력은 모든 인터클러스터 LIF가 각 홈 포트에 있어야 한다는 것을 나타내는 비워 두어야 합니다.

.. 홈 포트에 없는 LIF를 되돌립니다.
+
`network interface revert -lif <intercluster_lif>`

+
홈 포트에 있지 않은 각 인터클러스터 LIF에 대해 명령을 반복하십시오.



. [[controller_replace_upgrade_prepare_network_ports_3]] 이전 컨트롤러에 있는 모든 데이터 LIF의 홈 포트를 이전 컨트롤러 모듈과 새 컨트롤러 모듈에서 모두 동일한 공통 포트에 할당합니다.
+

CAUTION: 이전 컨트롤러와 새 컨트롤러에 공통 포트가 없는 경우 데이터 LIF를 수정할 필요가 없습니다. 이 단계를 건너뛰고 바로 로 이동합니다<<upgrades_assisted_without_matching_ports,5단계>>.

+
.. LIF 표시:
+
네트워크 인터페이스 쇼

+
SAN 및 NAS를 포함한 모든 데이터 LIF는 스위치오버 사이트(cluster_A)에 있기 때문에 관리 ""업""과 운영 "'다운""이 될 것입니다.

.. 출력을 검토하여 클러스터 포트로 사용되지 않는 이전 컨트롤러와 새 컨트롤러 모두에서 동일한 일반적인 물리적 네트워크 포트를 찾습니다.
+
예를 들어, ""e0d""는 이전 컨트롤러의 물리적 포트이며 새 컨트롤러에도 존재합니다. ""e0d""는 클러스터 포트로 사용하거나 새 컨트롤러에서 사용되지 않습니다.

+
각 플랫폼 모델의 포트 사용법은 를 link:https://hwu.netapp.com/["Hardware Universe"^]참조하십시오.

.. 공통 포트를 홈 포트로 사용하도록 모든 데이터 LIF를 수정합니다.
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
다음 예에서는 ""e0d""입니다.

+
예를 들면 다음과 같습니다.

+
[listing]
----
network interface modify -vserver vs0 -lif datalif1 -home-port e0d
----


. [[upgrades_assisted_without_matching_ports]] 브로드캐스트 도메인을 수정하여 삭제해야 하는 VLAN 및 물리적 포트를 제거합니다.
+
`broadcast-domain remove-ports -broadcast-domain <broadcast-domain-name>-ports <node-name:port-id>`

+
모든 VLAN 및 물리적 포트에 대해 이 단계를 반복합니다.

. 클러스터 포트를 구성원 포트로 사용하고 클러스터 포트를 구성원 포트로 사용하는 인터페이스 그룹을 사용하여 VLAN 포트를 제거합니다.
+
.. VLAN 포트 삭제:
+
`network port vlan delete -node <node-name> -vlan-name <portid-vlandid>`

+
예를 들면 다음과 같습니다.

+
[listing]
----
network port vlan delete -node node1 -vlan-name e1c-80
----
.. 인터페이스 그룹에서 물리적 포트를 제거합니다.
+
`network port ifgrp remove-port -node <node-name> -ifgrp <interface-group-name> -port <portid>`

+
예를 들면 다음과 같습니다.

+
[listing]
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----
.. 브로드캐스트 도메인에서 VLAN 및 인터페이스 그룹 포트 제거:
+
`network port broadcast-domain remove-ports -ipspace <ipspace> -broadcast-domain <broadcast-domain-name>-ports <nodename:portname,nodename:portname>,..`

.. 필요에 따라 다른 물리적 포트를 구성원으로 사용하도록 인터페이스 그룹 포트를 수정합니다.
+
`ifgrp add-port -node <node-name> -ifgrp <interface-group-name> -port <port-id>`



. 노드 중단:
+
`halt -inhibit-takeover true -node <node-name>`

+
이 단계는 두 노드에서 모두 수행해야 합니다.

. 노드가 프롬프트에 있는지 `LOADER` 확인하고 현재 환경 변수를 수집 및 유지합니다.
. bootarg 값을 수집합니다.
+
'printenv'

. 컨트롤러가 업그레이드되는 사이트에서 노드 및 쉘프의 전원을 끕니다.


.다음 단계
link:upgrade-mcc-ip-system-controller-replace-setup-new-controllers.html["새 컨트롤러를 설정하고 NetBoot합니다"]..
