---
permalink: upgrade/upgrade-mcc-ip-manual-boot-new-controllers.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 새로운 컨트롤러를 부팅하고 LIF가 적절한 노드 및 포트에서 호스팅되는지 확인합니다. 
---
= 새 MetroCluster IP 컨트롤러를 부팅하고 LIF 구성을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 컨트롤러를 부팅하고 LIF가 적절한 노드 및 포트에서 호스팅되는지 확인합니다.



== 새 컨트롤러를 부팅합니다

bootarg 변수가 올바른지 확인하고 필요한 경우 암호화 복구 단계를 수행하기 위해 새 컨트롤러를 부팅해야 합니다.

.단계
. 새 노드를 중단합니다.
+
"중지"

. 외부 키 관리자가 구성된 경우 관련 boots를 설정합니다.
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`

+
`setenv bootarg.kmip.init.netmask <netmask>`

+
`setenv bootarg.kmip.init.gateway <gateway-addres>`

+
`setenv bootarg.kmip.init.interface <interface-id>`

. partner-sysid가 현재인지 확인합니다.
+
'printenv partner-sysid

+
partner-sysid가 올바르지 않으면 다음을 설정합니다.

+
`setenv partner-sysid <partner-sysID>`

. ONTAP 부팅 메뉴를 표시합니다.
+
boot_ontap 메뉴

. 루트 암호화를 사용하는 경우 키 관리 구성에 대한 부팅 메뉴 옵션을 선택합니다.
+
|===


| 사용 중인 경우... | 이 부팅 메뉴 옵션을 선택합니다... 


 a| 
온보드 키 관리
 a| 
옵션 '10'

프롬프트에 따라 키 관리자 구성을 복구 및 복원하는 데 필요한 입력을 제공합니다.



 a| 
외부 키 관리
 a| 
옵션 '11'

프롬프트에 따라 키 관리자 구성을 복구 및 복원하는 데 필요한 입력을 제공합니다.

|===
. 부팅 메뉴에서 ""(6) Update flash from backup config"(백업 구성에서 플래시 업데이트)를 선택합니다.
+

NOTE: 옵션 6은 프로세스가 완료되기 전에 노드를 두 번 재부팅합니다.

+
시스템 ID 변경 프롬프트에 ""y""로 응답합니다. 두 번째 재부팅 메시지가 나타날 때까지 기다립니다.

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
.  `LOADER`프롬프트에서 bootarg 값을 확인하고 필요에 따라 값을 업데이트합니다.
+
의 단계를 link:upgrade-mcc-ip-manual-apply-rcf-set-bootarg.html#set-the-metrocluster-ip-bootarg-variables["MetroCluster IP bootarg 변수를 설정합니다"]사용합니다.

. partner-sysid가 올바른지 확인합니다.
+
'printenv partner-sysid

+
partner-sysid가 올바르지 않으면 다음을 설정합니다.

+
`setenv partner-sysid <partner-sysID>`

. 루트 암호화를 사용하는 경우 키 관리 구성에 대해 부팅 메뉴 옵션을 다시 선택합니다.
+
|===


| 사용 중인 경우... | 이 부팅 메뉴 옵션을 선택합니다... 


 a| 
온보드 키 관리
 a| 
옵션 '10'

프롬프트에 따라 키 관리자 구성을 복구 및 복원하는 데 필요한 입력을 제공합니다.



 a| 
외부 키 관리
 a| 
옵션 "'11'"

프롬프트에 따라 키 관리자 구성을 복구 및 복원하는 데 필요한 입력을 제공합니다.

|===
+
키 관리자 설정에 따라 첫 번째 부팅 메뉴 프롬프트에서 옵션 ""10"" 또는 옵션 ""11", 옵션 "6"을 차례로 선택하여 복구 절차를 수행합니다. 노드를 완전히 부팅하려면 옵션 ""1"(일반 부팅)에서 계속 진행하는 복구 절차를 반복해야 할 수 있습니다.

. 교체된 노드가 부팅될 때까지 기다립니다.
+
두 노드 중 하나가 Takeover 모드에 있으면 'storage failover 반환' 명령을 사용하여 Giveback을 수행합니다.

. 암호화가 사용되는 경우 키 관리 구성에 맞는 명령을 사용하여 키를 복원합니다.
+
|===


| 사용 중인 경우... | 이 명령 사용... 


 a| 
온보드 키 관리
 a| 
보안 키매니저 온보드 동기화

자세한 내용은 을 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["온보드 키 관리 암호화 키를 복원합니다"^]참조하십시오.



 a| 
외부 키 관리
 a| 
`security key-manager external restore -vserver <SVM> -node <node> -key-server <host_name|IP_address:port> -key-id key_id -key-tag key_tag <node_name>`

자세한 내용은 을 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["외부 키 관리 암호화 키를 복원합니다"^]참조하십시오.

|===
. 모든 포트가 브로드캐스트 도메인에 있는지 확인합니다.
+
.. 브로드캐스트 도메인 보기:
+
네트워크 포트 브로드캐스트 도메인 쇼

.. 새로 업그레이드된 컨트롤러의 데이터 포트에 대해 새 브로드캐스트 도메인이 생성된 경우 브로드캐스트 도메인을 삭제합니다.
+

NOTE: 새 브로드캐스트 도메인만 삭제합니다. 업그레이드를 시작하기 전에 있던 브로드캐스트 도메인을 삭제하지 마십시오.

+
`broadcast-domain delete -broadcast-domain <broadcast_domain_name>`

.. 필요에 따라 브로드캐스트 도메인에 포트를 추가합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["브로드캐스트 도메인에서 포트를 추가하거나 제거합니다"^]

.. 필요에 따라 VLAN 및 인터페이스 그룹을 다시 생성합니다.
+
VLAN 및 인터페이스 그룹 구성원 자격은 이전 노드와 다를 수 있습니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["VLAN을 생성합니다"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["물리적 포트를 결합하여 인터페이스 그룹을 생성합니다"^]







== LIF 구성을 확인 및 복원합니다

업그레이드 절차를 시작할 때 LIF가 적절한 노드 및 포트에 매핑되어 있는지 확인합니다.

.이 작업에 대해
* 이 작업은 site_B에서 수행됩니다
* 에서 생성한 포트 매핑 계획을 link:upgrade-mcc-ip-prepare-system.html#map-ports-from-the-old-nodes-to-the-new-nodes["이전 노드의 포트를 새 노드로 매핑합니다"]참조하십시오.



CAUTION: 스위치백을 수행하기 전에 데이터 LIF 위치가 새 노드에서 올바른지 확인해야 합니다. 구성을 다시 전환하면 ONTAP은 LIF에서 사용하는 홈 포트에서 트래픽을 다시 시작하려고 합니다. 스위치 포트 및 VLAN에 대한 홈 포트 연결이 잘못되면 I/O 장애가 발생할 수 있습니다.

.단계
. 스위치백 전에 LIF가 적절한 노드 및 포트에서 호스팅되는지 확인합니다.
+
.. 고급 권한 레벨로 변경:
+
세트 프리빌리지 고급

.. LIF를 표시하고 각 데이터 LIF가 올바른 홈 포트를 사용 중인지 확인합니다.
+
네트워크 인터페이스 쇼

.. 올바른 홈 포트를 사용하고 있지 않은 LIF를 수정합니다.
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
명령에서 오류가 반환되면 포트 구성을 재정의할 수 있습니다.

+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>"`

+
'vserver config override' 명령 내에서 network interface modify 명령을 입력할 때는 tab autotcomplete 기능을 사용할 수 없습니다. 자동 완성 기능을 사용하여 네트워크 'interface modify'를 만든 다음 'vserver config override' 명령에 포함할 수 있습니다.

.. 모든 데이터 LIF가 이제 올바른 홈 포트에 있는지 확인합니다.
+
네트워크 인터페이스 쇼

.. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다



. 인터페이스를 홈 노드로 되돌리기:
+
`network interface revert * -vserver <svm-name>`

+
필요에 따라 모든 SVM에서 이 단계를 수행합니다.



.다음 단계
link:upgrade-mcc-ip-manual-switchback.html["MetroCluster 구성을 다시 전환합니다"]..
