---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: ONTAP 9.15.1 이상에서 도입된 시스템을 업그레이드하려면 업그레이드를 진행하기 전에 bootarg를 설정해야 합니다. 
---
= 필요한 bootarg 설정(ONTAP 9.15.1 이상에서 도입된 시스템으로 MetroCluster IP 업그레이드)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.15.1 이상에서 도입된 시스템으로 업그레이드하는 경우 일반적으로 업그레이드를 시작하기 전에 이전 컨트롤러에 bootarg를 설정해야 합니다.


NOTE: 업그레이드 조합이 영향을 받는 경우, 성공적인 업그레이드를 위해 모든 이전 컨트롤러에 bootarg를 설정해야 합니다.  업그레이드 조합에 bootarg 설정이 필요한지, 그리고 조합에 맞는 올바른 bootarg를 설정하는 방법을 확인하려면 이 섹션의 정보를 주의 깊게 검토하세요.



== 1단계: 이전 컨트롤러에 bootarg를 설정해야 하는지 확인

업그레이드를 시작하기 전에 다음 정보를 사용하여 이전 컨트롤러에 bootarg를 설정해야 하는지 확인하십시오.

* 다음 시스템에 지원되는 업그레이드를 위해서는 달리 명시되지 않는 한 이전 컨트롤러에 bootarg를 설정해야 합니다.
+
** AFF A70, AFF A90, AFF A1K
** FAS70, FAS90
** AFF C80 를 참조하십시오
** AFF A50, AFF A20, AFF A30
** AFF C30, AFF C60
** FAS50를 참조하십시오


* 업그레이드가 다음 조합 중 하나인 경우 이전 컨트롤러에 bootarg를 설정할 필요가 *없습니다*.
+
** AFF A70 시스템에서 AFF A90 시스템으로
** FAS70 시스템에서 FAS90 시스템으로





CAUTION: 업그레이드에 bootarg를 설정할 필요가 없는 경우 이 작업을 건너뛰고 link:upgrade-mcc-ip-system-controller-replace-prechecks.html["업그레이드를 위해 시스템을 준비합니다"]로 바로 이동할 수 있습니다.



== 2단계: 이전 컨트롤러에 설정해야 하는 bootarg를 결정합니다.

영향을 받는 대부분의 업그레이드에는 다음을 설정해야 합니다. `hw.cxgbe.toe_keepalive_disable` 이전 컨트롤러의 bootarg.  그러나 특정 업그레이드 경로에서는 다음을 설정해야 합니다. `bootarg.siw.interop_enabled` 대신 bootarg를 사용하세요.

다음 표를 사용하여 특정 업그레이드 조합에 대해 설정해야 하는 부트카를 결정합니다.

[cols="2*"]
|===
| 업그레이드 대상... | bootarg 설정... 


| AFF A250에서 AFF A30까지 | `bootarg.siw.interop_enabled` 


| AFF C250에서 AFF C30까지 | `bootarg.siw.interop_enabled` 


| AFF A150에서 AFF A20까지 | `bootarg.siw.interop_enabled` 


| AFF A220에서 AFF A20까지 | `bootarg.siw.interop_enabled` 


 a| 
AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A30, AFF C30, AFF C60 또는 FAS50 시스템에 대한 기타 모든 업그레이드

*참고:* AFF A70 에서 AFF A90 시스템으로, 또는 FAS70에서 FAS90 시스템으로 업그레이드하는 경우 bootarg를 설정할 필요가 없습니다.
| `hw.cxgbe.toe_keepalive_disable` 
|===


== 3단계: 이전 컨트롤러에 필요한 bootarg 설정

업그레이드 조합에 필요한 bootarg를 확인한 후에는 이전 컨트롤러에서 bootarg를 설정하는 단계를 따르십시오.


NOTE: 업그레이드를 시작하기 전에 두 사이트의 모든 이전 노드에서 bootarg를 설정해야 합니다.

.단계
. 두 사이트에서 하나의 노드를 중지하고 HA 파트너가 노드의 스토리지 인수를 수행하도록 합니다.
+
`halt  -node <node_name>`

. 업그레이드 조합에 필요한 bootarg를 설정합니다. 의 테이블을 사용하여 <<upgrade_paths_bootarg_assisted,설정할 부트문자를 결정합니다>>설정해야 하는 부트아그를 이미 확인했습니다.
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable을 선택합니다
--
..  `LOADER`중지된 노드의 프롬프트에서 다음을 입력합니다.
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
'사베에프'

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
..  `LOADER`중지된 노드의 프롬프트에서 다음을 입력합니다.
+
`setenv bootarg.siw.interop_enabled 1`

+
'사베에프'

+
`printenv bootarg.siw.interop_enabled`



--
====
. 노드를 부팅합니다.
+
부트 ONTAP

. 노드가 부팅되면 프롬프트에서 노드에 대해 반환 작업을 수행합니다.
+
`storage failover giveback -ofnode <node_name>`

. 업그레이드 중인 DR 그룹의 4개 노드 모두에 대해 이 단계를 반복합니다.


.다음 단계
link:upgrade-mcc-ip-system-controller-replace-prechecks.html["업그레이드를 위해 시스템을 준비합니다"]..
