---
permalink: tiebreaker/concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html 
sidebar: sidebar 
keywords: switchover, upon, detection, site, failure, automatic, metrocluster, tiebreaker, active, mode, supplement, ontap, fas, capability, risk, limitation 
summary: MetroCluster Tiebreaker가 활성 모드에 있을 때 사이트 장애 감지 시 자동으로 전환됩니다. 이 모드는 ONTAP/FAS 자동 전환 기능을 보완하는 데 사용할 수 있습니다. 
---
= 활성 모드에서 MetroCluster Tiebreaker를 사용할 때의 위험 및 제한 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster Tiebreaker가 활성 모드에 있을 때 사이트 장애 감지 시 자동으로 전환됩니다. 이 모드는 ONTAP/FAS 자동 전환 기능을 보완하는 데 사용할 수 있습니다.

활성 모드에서 MetroCluster Tiebreaker를 구현할 때 다음과 같은 알려진 문제로 인해 데이터가 손실될 수 있습니다.

* 사이트 간 링크에 오류가 발생하면 각 사이트의 컨트롤러가 계속해서 클라이언트를 제공합니다. 그러나 컨트롤러는 미러링되지 않습니다. 한 사이트에서 컨트롤러 장애가 발생하면 사이트 장애로 식별되고 MetroCluster Tiebreaker가 전환을 시작합니다. 원격 사이트와의 사이트 간 링크 장애 후 미러링되지 않은 데이터는 손실됩니다.
* 원격 사이트의 애그리게이트가 성능 저하 상태일 때 스위치오버가 발생합니다. 애그리게이트 재동기화 전에 스위치오버가 발생한 경우에는 데이터가 복제되지 않습니다.
* 절체가 진행 중일 때 원격 스토리지 장애가 발생합니다.
* 스토리지 컨트롤러의 비휘발성 메모리(플랫폼 모델에 따라 NVRAM 또는 NVMEM)가 파트너 사이트의 원격 DR(재해 복구) 파트너에 미러링되지 않습니다.
* 클러스터 피어링 네트워크가 오랜 기간 동안 중단되었고 메타데이터 볼륨이 전환 후 온라인 상태가 아닌 경우 메타데이터가 손실됩니다.



NOTE: 언급되지 않은 시나리오가 있을 수 있습니다. NetApp은 액티브 모드에서 MetroCluster Tiebreaker를 사용하지 않을 경우 발생할 수 있는 어떠한 손상에도 책임을 지지 않습니다. 위험 및 제한이 허용되지 않는 경우 MetroCluster Tiebreaker를 활성 모드에서 사용하지 마십시오.
