---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing 
summary: Tiebreaker 소프트웨어를 설치한 후 MetroCluster 구성을 추가 또는 수정하거나 Tiebreaker 소프트웨어에서 제거할 수 있습니다. 
---
= MetroCluster Tiebreaker 소프트웨어 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tiebreaker 소프트웨어를 설치한 후 MetroCluster 구성을 추가 또는 수정하거나 Tiebreaker 소프트웨어에서 제거할 수 있습니다.



== Tiebreaker 소프트웨어 CLI를 실행합니다.

Tiebreaker 소프트웨어를 설치한 후 소프트웨어를 구성하려면 CLI를 시작해야 합니다.

. 소프트웨어를 설치한 호스트의 프롬프트에서 CLI를 시작합니다.
+
'NetApp-MetroCluster-Tiebreaker-software-CLI'

. 설치 후 처음 시작하는 동안 데이터베이스에 액세스하려면 Tiebreaker 사용자의 암호를 입력합니다. 설치하는 동안 데이터베이스 사용자에 대해 지정한 암호입니다.




== MetroCluster 구성 추가

NetApp MetroCluster Tiebreaker 소프트웨어를 설치한 후 한 번에 하나씩 더 많은 MetroCluster 구성을 추가할 수 있습니다.

.이 작업에 대해
* ONTAP 환경에 MetroCluster 구성을 설치하고 소프트웨어에서 설정을 활성화해야 합니다.
* 단계별 절차와 예상되는 명령 출력은 사용 중인 Tiebreaker 버전에 따라 다릅니다.


[role="tabbed-block"]
====
.동점자 처리 1.5 또는 이전
--
.단계
. MetroCluster 구성을 추가하려면 tiebreaker CLI(Command-line Interface) monitor add 명령을 사용합니다.
+
호스트 이름을 사용하는 경우 FQDN(정규화된 도메인 이름)이어야 합니다.

+
다음 예에서는 cluster_a의 구성을 보여 줍니다.

+
.예
[%collapsible]
=====
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: <monitor_name>
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----
=====
. tiebreaker CLI monitor show-status 명령을 사용하여 MetroCluster 구성이 올바르게 추가되었는지 확인합니다.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Tiebreaker 소프트웨어가 사이트 장애를 감지한 후 자동으로 전환을 시작하려면 observer 모드를 비활성화합니다.
+
`monitor modify -monitor-name <monitor_name> -observer-mode false`

+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----


--
.타이브레이커 1.6 이상
--
.단계
. MetroCluster 구성을 추가하려면 tiebreaker CLI(Command-line Interface) monitor add 명령을 사용합니다.
+
호스트 이름을 사용하는 경우 FQDN(정규화된 도메인 이름)이어야 합니다.

+
다음 예에서는 cluster_a의 구성을 보여 줍니다.

+
.예
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter Monitor Name: cluster_A
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:

 NOTE: Before enabling automatic switchover capability, make sure to review the 'risks and limitations' as described in the MetroCluster Tiebreaker Installation and Configuration Guide.

Do you want to enable automatic switchover capability for monitor(Y/N): y
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
Verifying SSL certificate chain from cluster_A...

===============================================
Warning missing SSL certificates
===============================================

Cluster: cluster_A

IP Address: <cluster_ip_value>

Result:

The MetroCluster Tiebreaker is unable to verify the SSL certificate chain.

Recommended Actions:

Run the following command to identify missing certificates:

monitor switchover-simulate

Import any missing certificates as indicated by the command output.

For detailed instructions, please refer to the MetroCluster Tiebreaker documentation, or contact NetApp Support for assistance.

Note:

Missing certificates will prevent the MetroCluster Tiebreaker from issuing a switchover request in the event of a site failure.

================================================================================================================================
Verifying SSL certificate chain from cluster_B...

SSL certificate chain is valid
----
=====
. tiebreaker CLI monitor show-status 명령을 사용하여 MetroCluster 구성이 올바르게 추가되었는지 확인합니다.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Tiebreaker 버전에 맞는 단계를 수행하여 누락된 인증서를 가져오세요.<<import-certificates-tb17,수입증명서>> .


--
====
.관련 정보
link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["활성 모드에서 MetroCluster Tiebreaker를 사용할 때의 위험 및 제한 사항"]



== 수입증명서

Tiebreaker 1.6 이상에서 원활한 모니터링을 활성화하려면 ONTAP 에서 서버 SSL(Secure Sockets Layer) 인증서, 중간 인증서(있는 경우), 루트 인증서를 Java Virtual Machine(JVM)의 키 저장소로 가져와야 합니다.

.이 작업에 대해
* 이 작업은 Tiebreaker 1.6 이상에서 필요합니다.
* Tiebreaker에 MetroCluster 구성을 성공적으로 추가한 후 또는 인증서가 만료된 경우 이 작업을 수행합니다.
* Tiebreaker 1.7 이상 버전에서는 전환 시뮬레이션을 수행하여 인증서를 가져와야 하는지 여부를 확인할 수 있습니다.  전환 시뮬레이션이 실패하면 ONTAP 에서 Java 가상 머신(JVM)의 키 저장소로 인증서를 가져와야 합니다.


[role="tabbed-block"]
====
.동점자 처리 1.7 이상
--
.단계
. 인증서를 가져와야 하는지 확인하려면 전환 시뮬레이션을 실행하세요.
+
.. 타이브레이커 모니터링 상태를 확인하세요:
`monitor show -status`
+
.예
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 전환 시뮬레이션을 시작하세요:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
JVM에 인증서를 가져와야 하는 경우 해당 명령은 다음과 같은 출력을 반환합니다.

+
[listing]
----
Failed to trigger Switchover Simulation. Please check Metrocluster Tiebreaker logs for further information or contact NetApp support.
----


. 가져와야 하는 각 인증서(SSL 서버, 중간 인증서 또는 루트 인증서)에 대해 다음 명령을 실행합니다.
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** 그만큼 `<certificate_file_name>` value는 가져오려는 인증서의 파일 이름을 지정합니다.
** 그만큼 `-alias <certificate>` value는 인증서를 JVM으로 가져온 후 저장할 이름을 지정합니다.
+
다음 예제에서는 파일 이름으로 루트 인증서를 가져오는 방법을 보여줍니다. `root.crt` 그리고 파일 이름이 포함된 SSL 서버 인증서 `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. 타이브레이커 소프트웨어를 다시 시작하세요:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. 전환 시뮬레이션 점검을 다시 수행하십시오.
+
.. 타이브레이커 모니터링 상태를 확인하세요:
`monitor show -status`
+
.예
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 전환 시뮬레이션을 시작하세요:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
[listing]
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----




--
.동점자 처리 규칙 1.6 또는 1.6P1
--
.단계
. ONTAP 에서 모든 인증서를 가져옵니다. 가져와야 하는 각 인증서(SSL 서버, 중간 인증서 또는 루트 인증서)에 대해 다음 명령을 실행합니다.
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** 그만큼 `<certificate_file_name>` value는 가져오려는 인증서의 파일 이름을 지정합니다.
** 그만큼 `-alias <certificate>` value는 인증서를 JVM으로 가져온 후 저장할 이름을 지정합니다.
+
다음 예제에서는 파일 이름으로 루트 인증서를 가져오는 방법을 보여줍니다. `root.crt` 그리고 파일 이름이 포함된 SSL 서버 인증서 `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. 타이브레이커 소프트웨어를 다시 시작하세요:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`



--
====


== MetroCluster Tiebreaker 구성을 수정하는 명령입니다

설정을 변경해야 할 때마다 MetroCluster 구성을 수정할 수 있습니다.

Tiebreaker CLI monitor modify 명령은 다음 옵션 중 하나를 사용할 수 있습니다. MONITOR SHOW-STATUS 명령으로 변경 사항을 확인할 수 있습니다.

[cols="30,70"]
|===


| 옵션을 선택합니다 | 설명 


 a| 
-monitor-name
 a| 
MetroCluster 구성의 이름입니다



 a| 
-enable-monitor
 a| 
MetroCluster 구성 모니터링을 활성화 및 비활성화합니다



 a| 
무음 기간
 a| 
MetroCluster Tiebreaker 소프트웨어가 감지 후 사이트 장애 확인을 대기하는 시간(초)입니다



 a| 
관찰자 모드
 a| 
관찰자 모드(참)는 모니터링만 제공하며 사이트 재해가 발생할 경우 전환을 트리거하지 않습니다. 온라인 모드(false)는 사이트 재해가 발생할 경우 전환을 트리거합니다.

* link:concept_overview_of_the_tiebreaker_software.html["Tiebreaker 소프트웨어가 사이트 장애를 감지하는 방식"]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["활성 모드에서 MetroCluster Tiebreaker를 사용할 때의 위험 및 제한 사항"]


|===
다음 예제에서는 구성에 대한 자동 기간을 변경합니다.

[listing]
----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----
tiebreaker CLI debug 명령을 사용하여 로깅 모드를 변경할 수 있습니다.

[cols="30,70"]
|===


| 명령 | 설명 


 a| 
디버그 상태
 a| 
디버그 모드의 상태를 표시합니다



 a| 
디버그 활성화
 a| 
로깅을 위한 디버그 모드를 활성화합니다



 a| 
디버그 비활성화
 a| 
로깅에 대한 디버그 모드를 비활성화합니다

|===
Tiebreaker 1.4 이하를 실행하는 시스템에서는 Tiebreaker CLI를 사용합니다 `update-mcctb-password` 명령을 사용하여 사용자 암호를 업데이트할 수 있습니다. 이 명령은 Tiebreaker 1.5 이상에서 더 이상 사용되지 않습니다.

[cols="30,70"]
|===


| 명령 | 설명 


 a| 
update-mctb-password(업데이트-mctb-암호)
 a| 
사용자 암호가 성공적으로 업데이트되었습니다

|===


== MetroCluster 구성을 제거합니다

MetroCluster 구성을 더 이상 모니터링하지 않으려는 경우 Tiebreaker 소프트웨어에서 모니터링하는 MetroCluster 구성을 제거할 수 있습니다.

. MetroCluster 구성을 제거하려면 tiebreaker CLI monitor remove 명령을 사용합니다.
+
다음 예에서는 ""cluster_a""가 소프트웨어에서 제거됩니다.

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----
. tiebreaker CLI monitor show-status 명령을 사용하여 MetroCluster 구성이 올바르게 제거되었는지 확인합니다.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

