---
permalink: tiebreaker/reference_where_to_find_additional_information_tb_icg.html 
sidebar: sidebar 
keywords: metrocluster, configuration, operation, netapp, documentation, additional, information, miscellaneous, guide 
summary: MetroCluster 구성 및 작동에 대해 자세히 알아볼 수 있습니다. 
---
= 추가 정보를 찾을 수 있는 위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성 및 작동에 대해 자세히 알아볼 수 있습니다.



== MetroCluster 및 기타 정보

|===


| 정보 | 제목 


 a| 
link:../index.html["MetroCluster 문서"]
 a| 
* 모든 MetroCluster 정보




 a| 
https://www.netapp.com/pdf.html?item=/media/13482-tr4375pdf.pdf["NetApp 기술 보고서 4375: ONTAP 9.3을 위한 NetApp MetroCluster"^]
 a| 
* MetroCluster 구성 및 작동에 대한 기술적 개요
* MetroCluster 구성에 대한 모범 사례




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["패브릭 연결 MetroCluster 설치 및 구성"]
 a| 
* 패브릭 연결 MetroCluster 아키텍처
* 구성 케이블 연결
* FC-to-SAS 브릿지 구성
* FC 스위치 구성
* ONTAP에서 MetroCluster 구성




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["스트레치 MetroCluster 설치 및 구성"]
 a| 
* MetroCluster 아키텍처 확장
* 구성 케이블 연결
* FC-to-SAS 브릿지 구성
* ONTAP에서 MetroCluster 구성




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["MetroCluster IP 설치 및 구성"]
 a| 
* MetroCluster IP 아키텍처
* MetroCluster IP 구성 케이블 연결
* ONTAP에서 MetroCluster 구성




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["MetroCluster 구성 요소를 유지보수하십시오"]
 a| 
* MetroCluster 구성 유지 관리 지침
* FC-to-SAS 브리지 및 FC 스위치에 대한 하드웨어 교체 또는 업그레이드 및 펌웨어 업그레이드 절차
* 패브릭 연결 또는 확장 MetroCluster 구성에서 디스크 쉘프 핫 추가
* 패브릭 연결 또는 확장 MetroCluster 구성에서 디스크 쉘프 핫 제거
* 패브릭 연결 또는 확장 MetroCluster 구성의 재해 사이트에서 하드웨어 교체
* 2노드 패브릭 연결 또는 확장 MetroCluster 구성을 4노드 MetroCluster 구성으로 확장
* 4노드 패브릭 연결 또는 확장 MetroCluster 구성을 8노드 MetroCluster 구성으로 확장




 a| 
Active IQ Unified Manager 설명서

https://docs.netapp.com["NetApp 설명서: 제품 가이드 및 리소스"^]
 a| 
* MetroCluster 구성 및 성능 모니터링




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["복사 기반 전환"]
 a| 
* 7-Mode 스토리지 시스템에서 클러스터 스토리지 시스템으로 데이터 전환


|===