---
permalink: install-fc/concept_considerations_8510.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: MetroCluster 설치를 준비할 때 MetroCluster 하드웨어 아키텍처와 필수 구성 요소를 이해해야 합니다. 
---
= Brocade DCX 8510-8 스위치 사용에 대한 요구 사항


* MetroCluster 구성에 사용되는 DCX 8510-8 스위치는 NetApp에서 구입해야 합니다.
* 확장성을 위해 4x48 포트 모듈에서 2개의 MetroClusters만 케이블로 연결하는 경우 MetroCluster 구성 간에 포트-청크를 하나만 남겨두어야 합니다. 이를 통해 MetroCluster 구성에서 포트 사용을 재설정하지 않고 확장할 수 있습니다.
* MetroCluster 구성의 각 Brocade DCX 8510-8 스위치는 ISL 포트 및 스토리지 연결에 대해 올바르게 구성되어야 합니다. 포트 사용에 대한 자세한 내용은 다음 섹션을 참조하십시오. link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["ONTAP 9.1 이상을 사용할 경우 FC 스위치에 대한 포트 할당"].
* ISL은 공유할 수 없으며 각 MetroCluster에는 각 Fabric에 두 개의 ISL이 필요합니다.
* 백엔드 MetroCluster 연결에 사용되는 DCX 8510-8 스위치는 다른 연결에 사용해서는 안 됩니다.
+
비 MetroCluster 장치는 이러한 스위치에 연결하면 안 되며, 비 MetroCluster 트래픽은 DCX 8510-8 스위치를 통해 흐르지 않습니다.

* ONTAP MetroClusters * 또는 * ONTAP 7-Mode MetroClusters에 하나의 라인 카드를 연결할 수 있습니다.



NOTE: RCF 파일은 이 스위치에 사용할 수 없습니다.

Brocade DCX 8510-8 스위치 2개를 사용하기 위한 요구 사항은 다음과 같습니다.

* 각 사이트에 DCX 8510-8 스위치가 하나 있어야 합니다.
* 각 스위치에 16Gb SFP가 포함된 최소 2개의 48포트 블레이드를 사용해야 합니다.


다음은 MetroCluster 구성에서 각 사이트에 DCX 8510-8 스위치 4개를 사용하기 위한 요구 사항입니다.

* 각 사이트에 DCX 8510-8 스위치가 2개 있어야 합니다.
* 각 DCX 8510-8 스위치당 48포트 블레이드를 하나 이상 사용해야 합니다.
* 각 블레이드는 가상 패브릭을 사용하여 가상 스위치로 구성됩니다.


다음 NetApp 제품은 Brocade DCX 8510-8 스위치에서 지원되지 않습니다.

* Config Advisor
* Fabric 상태 모니터
* MyAutoSupport(시스템 위험이 오탐 표시 가능)
* Active IQ Unified Manager(이전의 OnCommand Unified Manager)



NOTE: 이 설정에 필요한 모든 구성 요소가 에 있는지 확인합니다 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]. 지원되는 구성에 대한 자세한 내용은 상호 운용성 매트릭스 툴의 참고 섹션을 참조하십시오.
