---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns 
summary: 디스크 및 어레이 LUN에 사용할 MetroCluster 구성을 계획할 때는 스토리지 액세스 설정 순서, 루트 애그리게이트 위치, FC 이니시에이터 포트, 스위치 및 FC-to-SAS 브릿지 사용 등과 같은 다양한 요소를 고려해야 합니다. 
---
= 디스크 및 스토리지 LUN을 사용하여 MetroCluster 구성을 구축할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
디스크 및 어레이 LUN에 사용할 MetroCluster 구성을 계획할 때는 스토리지 액세스 설정 순서, 루트 애그리게이트 위치, FC 이니시에이터 포트, 스위치 및 FC-to-SAS 브릿지 사용 등과 같은 다양한 요소를 고려해야 합니다.

구성을 계획할 때 다음 표의 정보를 고려하십시오.

|===


| 고려 사항 | 지침 


 a| 
스토리지에 대한 액세스를 설정하는 순서입니다
 a| 
먼저 디스크 또는 어레이 LUN에 대한 액세스를 설정할 수 있습니다. 다른 유형의 스토리지를 설정하기 전에 해당 스토리지 유형에 대한 모든 설정을 완료하고 올바르게 설정되었는지 확인해야 합니다.



 a| 
루트 애그리게이트의 위치입니다
 a| 
* 디스크와 어레이 LUN을 모두 사용하여 _new_MetroCluster 구축을 설정하는 경우 네이티브 디스크에 루트 애그리게이트를 생성해야 합니다.
+
이렇게 하려면 각 사이트에 _디스크 쉘프(디스크 드라이브 24개 포함)가 하나 이상 설정되어 있어야 합니다.

* 어레이 LUN을 사용하는 _existing_MetroCluster 구성에 네이티브 디스크를 추가하는 경우 루트 애그리게이트는 어레이 LUN에 남아 있을 수 있습니다.




 a| 
스위치 및 FC-to-SAS 브릿지 사용
 a| 
FC-to-SAS 브릿지는 4노드 구성과 2노드 패브릭 연결 구성에서 ONTAP 시스템을 스위치를 통해 디스크 쉘프에 연결하는 데 필요합니다.

동일한 스위치를 사용하여 스토리지 어레이와 FC-to-SAS 브리지에 연결해야 합니다.



 a| 
FC 이니시에이터 포트 사용
 a| 
FC-to-SAS 브리지에 연결하는 데 사용되는 이니시에이터 포트는 스토리지 어레이에 연결하는 스위치에 연결하는 데 사용되는 포트와 달라야 합니다.

ONTAP 시스템을 디스크 및 어레이 LUN 모두에 연결하려면 최소 8개의 이니시에이터 포트가 필요합니다.

|===
.관련 정보
* 스위치 구성 절차와 명령은 스위치 공급업체에 따라 다릅니다.
+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade FC 스위치를 수동으로 구성합니다"]

+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Cisco FC 스위치를 수동으로 구성합니다"]

* 구성에 새 스토리지를 추가할 때 ATTO FiberBridge 브리지 및 SAS 디스크 쉘프를 설치하고 케이블을 연결합니다.
+
link:task_fb_new_install.html["FC-to-SAS 브릿지 및 SAS 디스크 쉘프 설치"]

* 스위치 조닝은 연결된 노드 간 경로를 정의합니다. 조닝을 구성하면 특정 ONTAP 시스템에서 볼 수 있는 어레이 LUN을 정의할 수 있습니다.
+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["어레이 LUN이 있는 4노드 MetroCluster 구성의 스위치 조닝의 예"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["어레이 LUN이 있는 8노드 MetroCluster 구성의 스위치 조닝의 예"]

* https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]

