---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: 각 패브릭에 대해 단일 이니시에이터 포트와 각 컨트롤러에 대한 2개의 이니시에이터 포트를 사용하여 FAS8020, AFF8020, FAS8200 및 AFF A300 시스템을 구성할 수 있습니다. 
---
= 이니시에이터 포트 2개를 사용하는 시스템의 포트 할당
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 패브릭에 대해 하나의 이니시에이터 포트를 사용하고 각 컨트롤러에 대해 두 개의 이니시에이터 포트를 사용하여 FAS8200 및 AFF A300 시스템을 구성할 수 있습니다.

FibreBridge 7600N 브리지 케이블 연결은 FC 포트(FC1 또는 FC2) 하나만 사용하여 수행할 수 있습니다. 이니시에이터 네 개를 사용하는 대신, 이니시에이터 두 개만 연결하고 스위치 포트에 연결된 나머지 두 개는 비워 두세요.

수동으로 구역 설정을 수행하는 경우, FC 포트 하나(FC1 또는 FC2)를 사용하는 FibreBridge 7600N 브리지에 사용된 구역 설정을 따릅니다. 이 경우 패브릭당 각 구역 멤버에 두 개가 아닌 하나의 이니시에이터 포트가 추가됩니다.

의 절차에 따라 조닝을 변경하거나 FiberBridge 6500N에서 FiberBridge 7500N으로 업그레이드할 수 있습니다 link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["FiberBridge 7600N 브리지를 FiberBridge 7600N 또는 7500N 브리지로 핫 스와핑합니다"].

다음 표는 각 패브릭에 대해 단일 이니시에이터 포트를 사용하고 각 컨트롤러에 대해 두 개의 이니시에이터 포트를 사용할 때 Brocade FC 스위치의 포트 할당을 보여줍니다.

[cols="2a,2a,2a,2a"]
|===
4+| FC 포트(FC1 또는 FC2)를 사용한 FiberBridge 7500N 또는 7600N을 사용한 구성 


 a| 
* MetroCluster 1 또는 DR 그룹 1 *



 a| 
* 구성 요소 *
 a| 
* 포트 *
 a| 
*6505, 6510, 6520, 7840, G620, G630, G610, G710, G720, G730 및 DCX 8510-8*



 a| 
* FC 스위치에 연결... *
 a| 
* 스위치 포트에 연결합니다... *



 a| 
컨트롤러_x_1
 a| 
FC-VI 포트 A
 a| 
1
 a| 
0



 a| 
FC-VI 포트 b
 a| 
2
 a| 
0



 a| 
FC-VI 포트 c
 a| 
1
 a| 
1



 a| 
FC-VI 포트 d
 a| 
2
 a| 
1



 a| 
HBA 포트 A
 a| 
1
 a| 
2



 a| 
HBA 포트 b
 a| 
2
 a| 
2



 a| 
HBA 포트 c
 a| 
-
 a| 
-



 a| 
HBA 포트 d
 a| 
-
 a| 
-



 a| 
스택 1
 a| 
Bridge_x_1a
 a| 
1
 a| 
8



 a| 
Bridge_x_1b
 a| 
2
 a| 
8



 a| 
스택 y
 a| 
브리지 x _ 야
 a| 
1
 a| 
11



 a| 
Bridge_x_yb입니다
 a| 
2
 a| 
11

|===