---
permalink: install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html 
sidebar: sidebar 
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster 
summary: ONTAP 9.1 이상을 사용할 때 FC 스위치에 케이블을 연결할 때 지정한 포트 할당을 사용하고 있는지 확인해야 합니다. 
---
= AFF A900 또는 FAS9500 시스템 사용 시 FC 스위치에 대한 포트 할당
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


ONTAP 9.10.1 이상을 사용하는 경우 FC 스위치에 케이블을 연결할 때 지정된 포트 할당을 사용하고 있는지 확인해야 합니다.

이니시에이터 포트, FC-VI 포트 또는 ISL을 연결하는 데 사용되지 않는 포트를 스토리지 포트로 재구성할 수 있습니다. 그러나 지원되는 RCFs를 사용하는 경우에는 그에 따라 조닝을 변경해야 합니다.

지원되는 RCF를 사용하는 경우 ISL 포트가 표시된 동일한 포트에 연결되지 않을 수 있으므로 수동으로 다시 구성해야 할 수 있습니다.

ONTAP 9에 대한 포트 할당을 사용하여 스위치를 구성한 경우 이전 할당을 계속 사용할 수 있습니다. 그러나 ONTAP 9.1 이상 릴리즈를 실행하는 새 구성에서는 여기에 표시된 포트 할당을 사용해야 합니다.



== 전반적인 케이블 연결 지침

케이블 연결 테이블을 사용할 때 다음 지침을 숙지해야 합니다.

* AFF A900 또는 FAS9500 스토리지 시스템에는 8개의 FC-VI 포트가 필요합니다. AFF A900 또는 FAS9500을 사용하는 경우 8포트 구성을 사용해야 합니다. 구성에 다른 스토리지 시스템 모델이 포함된 경우, 표에 표시된 케이블을 사용하되 불필요한 FC-VI 포트의 케이블은 무시합니다.
* ISL을 공유하는 MetroCluster 구성이 2개인 경우 8노드 MetroCluster 케이블 연결과 동일한 포트 할당을 사용합니다.
* 케이블 연결 ISL 수는 사이트의 요구 사항에 따라 다를 수 있습니다.
* ISL 고려 사항에 대한 섹션을 참조하십시오.
+
link:concept_considerations_isls_mcfc.html["ISL에 대한 고려 사항"]


