---
permalink: install-fc/concept_required_mcc_components_and_naming_conventions_fabric_mcc.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, required, fc, components, naming, conventions 
summary: MetroCluster FC 구성을 계획할 때 반드시 필요한 하드웨어 및 소프트웨어 구성 요소와 지원되는 소프트웨어 구성 요소를 이해해야 합니다. 또한 설명서 전체에서 구성 요소에 사용되는 명명 규칙을 예제로 이해해야 합니다. 예를 들어 사이트 A는 사이트 A라고 하며 다른 사이트는 사이트 B라고 합니다 
---
= MetroCluster FC 구성 요소 및 명명 규칙이 필요합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster FC 구성을 계획할 때 반드시 필요한 하드웨어 및 소프트웨어 구성 요소와 지원되는 소프트웨어 구성 요소를 이해해야 합니다. 또한 설명서 전체에서 구성 요소에 사용되는 명명 규칙을 예제로 이해해야 합니다. 예를 들어 사이트 A는 사이트 A라고 하며 다른 사이트는 사이트 B라고 합니다



== 지원되는 소프트웨어 및 하드웨어

MetroCluster FC 구성의 경우 하드웨어 및 소프트웨어가 지원되어야 합니다.

https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]

AFF 시스템을 사용하는 경우 MetroCluster 구성의 모든 컨트롤러 모듈을 AFF 시스템으로 구성해야 합니다.


NOTE: MetroCluster 스토리지 스위치에서는 장파 SFP가 지원되지 않습니다. 지원되는 SPF 테이블은 MetroCluster 기술 보고서를 참조하십시오.



== MetroCluster FC 구성의 하드웨어 이중화

MetroCluster FC 구성의 하드웨어 이중화 때문에 각 사이트에는 2개의 구성 요소가 있습니다. 사이트는 문자 A와 B를 임의로 할당하며, 개별 구성 요소에는 숫자 1과 2가 임의로 할당됩니다.



== 2개의 ONTAP 클러스터 필요

패브릭 연결 MetroCluster FC 구성에는 각 MetroCluster 사이트에 하나씩 있는 2개의 ONTAP 클러스터가 필요합니다.

이름은 MetroCluster 구성 내에서 고유해야 합니다.

예제 이름:

* 사이트 A: cluster_a
* 사이트 B: cluster_B




== FC 스위치 4개 필요

패브릭 연결 MetroCluster FC 구성에는 4개의 FC 스위치(지원되는 Brocade 또는 Cisco 모델)가 필요합니다.

4개의 스위치는 MetroCluster FC 구성의 각 클러스터 간에 ISL을 제공하는 2개의 스위치 스토리지 패브릭을 형성합니다.

이름은 MetroCluster 구성 내에서 고유해야 합니다.



== 2개, 4개 또는 8개의 컨트롤러 모듈에 대한 요구사항

패브릭 연결 MetroCluster FC 구성에는 2개, 4개 또는 8개의 컨트롤러 모듈이 필요합니다.

4노드 또는 8노드 MetroCluster 구성에서는 각 사이트의 컨트롤러 모듈이 1쌍 또는 2개의 HA 쌍을 형성합니다. 각 컨트롤러 모듈에는 다른 사이트에 DR 파트너가 있습니다.

컨트롤러 모듈은 다음 요구 사항을 충족해야 합니다.

* 이름은 MetroCluster 구성 내에서 고유해야 합니다.
* MetroCluster 구성의 모든 컨트롤러 모듈이 동일한 버전의 ONTAP를 실행해야 합니다.
* DR 그룹의 모든 컨트롤러 모듈은 동일한 모델이어야 합니다.
+
하지만 2개의 DR 그룹이 있는 구성에서는 각 DR 그룹이 서로 다른 컨트롤러 모듈 모델로 구성될 수 있습니다.

* DR 그룹의 모든 컨트롤러 모듈은 동일한 FC-VI 구성을 사용해야 합니다.
+
일부 컨트롤러 모듈은 FC-VI 연결을 위한 두 가지 옵션을 지원합니다.

+
** 온보드 FC-VI 포트
** 슬롯 1의 FC-VI 카드 온보드 FC-VI 포트를 사용하는 컨트롤러 모듈과 애드온 FC-VI 카드를 사용하는 컨트롤러 모듈의 혼합은 지원되지 않습니다. 예를 들어, 한 노드에서 온보드 FC-VI 구성을 사용하는 경우 DR 그룹의 다른 모든 노드는 온보드 FC-VI 구성을 사용해야 합니다.




예제 이름:

* 사이트 A: controller_a_1
* 사이트 B: controller_B_1




== 4개의 클러스터 인터커넥트 스위치에 대한 요구사항

패브릭 연결 MetroCluster FC 구성에는 클러스터 인터커넥트 스위치 4개가 필요합니다(스위치가 없는 2노드 클러스터를 사용하지 않는 경우).

이러한 스위치는 각 클러스터의 컨트롤러 모듈 간에 클러스터 통신을 제공합니다. 각 사이트의 컨트롤러 모듈이 스위치가 없는 2노드 클러스터로 구성된 경우에는 스위치가 필요하지 않습니다.



== FC-to-SAS 브릿지 요구 사항

패브릭 연결 MetroCluster FC 구성에서는 SAS 쉘프의 각 스택 그룹에 대해 한 쌍의 FC-SAS 브리지가 필요합니다.


NOTE: FiberBridge 6500N 브리지는 ONTAP 9.8 이상을 실행하는 구성에서는 지원되지 않습니다.

* FiberBridge 7600N 또는 7500N 브리지는 최대 4개의 SAS 스택을 지원합니다.
* FiberBridge 6500N 브리지는 하나의 SAS 스택만 지원합니다.
* 각 스택은 IOM의 다양한 모델을 사용할 수 있습니다.
+
IOM12 모듈과 IOM3 모듈의 혼합은 동일한 스토리지 스택 내에서 지원되지 않습니다. 시스템에서 지원되는 ONTAP 버전을 실행 중인 경우 동일한 스토리지 스택 내에서 IOM12 모듈과 IOM6 모듈의 조합이 지원됩니다.

+
지원되는 IOM 모듈은 실행 중인 ONTAP 버전에 따라 다릅니다.

* 이름은 MetroCluster 구성 내에서 고유해야 합니다.


이 설명서의 예제로 사용된 제안된 이름은 아래와 같이 브리지가 연결되는 컨트롤러 모듈과 스택을 식별합니다.



== 풀 및 드라이브 요구 사항(최소 지원)

쉘프당 디스크 소유권을 허용하려면 SAS 디스크 쉘프 8개(각 사이트에 쉘프 4개)가 권장됩니다.

MetroCluster 구성에는 각 사이트에서 최소 구성이 필요합니다.

* 각 노드에는 사이트에 하나 이상의 로컬 풀과 하나의 원격 풀이 있습니다.
+
예를 들어 4노드 MetroCluster 구성에서는 각 사이트에 2개의 노드가 있고 각 사이트에 4개의 풀이 필요합니다.

* 각 풀에 최소 7개의 드라이브가 있습니다.
+
노드당 단일 미러링된 데이터 애그리게이트를 사용하는 4노드 MetroCluster 구성에서는 사이트에 24개의 디스크가 필요합니다.



지원되는 최소 구성에서는 각 풀에 다음과 같은 드라이브 레이아웃이 있습니다.

* 3개의 루트 드라이브
* 데이터 드라이브 3개
* 스페어 드라이브 1개


지원되는 최소 구성에서는 사이트당 쉘프가 하나 이상 필요합니다.

MetroCluster 구성은 RAID-DP 및 RAID4를 지원합니다.



== 부분적으로 채워진 셸프에 대한 드라이브 위치 고려 사항

절반으로 채워진 쉘프를 사용하는 경우(24-드라이브 쉘프의 드라이브 12개) 드라이브 자동 할당을 올바로 위해서는 드라이브가 슬롯 0-5 및 18-23에 있어야 합니다.

쉘프가 부분적으로 채워진 구성에서 드라이브는 쉘프의 4사분면 에 균등하게 분산되어야 합니다.



== 스택에서 IOM12와 IOM 6 모듈 혼합

사용 중인 ONTAP 버전은 쉘프 혼합을 지원해야 합니다. 사용 중인 ONTAP 버전이 쉘프 혼합을 지원하는지 확인하려면 상호 운용성 매트릭스 툴(IMT) 을 참조하십시오. https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성"]

쉘프 혼합에 대한 자세한 내용은 다음을 참조하십시오. https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["IOM6 모듈을 사용해 쉘프 스택에 IOM12 모듈을 장착한 상태로 쉘프 추가"]



== 브리지 명명 규칙

브리지는 다음 이름 지정을 사용합니다.

'bridge_site_stack 그루플위치(쌍)'

|===


| 이름의 이 부분은... | 다음을 식별합니다... | 가능한 값... 


 a| 
사이트
 a| 
브리지 쌍이 물리적으로 상주하는 사이트입니다.
 a| 
A 또는 B입니다



 a| 
스택 그룹
 a| 
브리지 쌍이 연결되는 스택 그룹의 수입니다.

* FiberBridge 7600N 또는 7500N 브리지는 스택 그룹에서 최대 4개의 스택을 지원합니다.
+
스택 그룹은 10개 이상의 스토리지 쉘프를 포함할 수 없습니다.

* FiberBridge 6500N 브리지는 스택 그룹에서 단일 스택만 지원합니다.

 a| 
1, 2 등



 a| 
한 쌍의 위치
 a| 
브리지 쌍 내의 브리지. 한 쌍의 브리지는 특정 스택 그룹에 연결됩니다.
 a| 
a 또는 b

|===
각 사이트의 스택 그룹 하나에 대한 브리지 이름 예:

* Bridge_A_1a
* Bridge_a_1b
* Bridge_B_1a
* Bridge_B_1b

