---
permalink: install-fc/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: 구성에 미러링되지 않은 애그리게이트가 포함된 경우, 전환 작업 후 잠재적 액세스 문제를 알고 있어야 합니다. 
---
= 미러링되지 않은 애그리게이트를 사용할 때의 고려 사항




== 미러링되지 않은 애그리게이트를 사용할 때의 고려 사항

구성에 미러링되지 않은 애그리게이트가 포함된 경우 전환 작업 후 발생할 수 있는 액세스 문제를 알고 있어야 합니다.



== 전원 종료가 필요한 유지 관리 수행 시 미러링되지 않은 애그리게이트의 고려 사항

사이트 전체의 전원을 차단해야 하는 유지 관리 이유로 협상된 전환을 수행하는 경우, 먼저 재해 사이트에서 소유한 미러링되지 않은 애그리게이트를 수동으로 오프라인으로 전환해야 합니다.

미러링되지 않은 애그리게이트를 오프라인으로 전환하지 않으면 다중 디스크 패닉이 발생하여 나머지 사이트의 노드가 다운될 수 있습니다. 이 문제는 재해 사이트에서 스토리지에 대한 연결이 손실되어 미러링되지 않은 애그리게이트를 통한 전환이 오프라인 상태가 되거나 누락될 경우 발생할 수 있습니다. 이는 전원 종료 또는 ISL 손실로 인한 결과입니다.



== 미러링되지 않은 애그리게이트 및 계층적 네임스페이스에 대한 고려 사항

계층적 네임스페이스를 사용하는 경우 해당 경로의 모든 볼륨이 미러링된 애그리게이트에만 있거나 미러링되지 않은 애그리게이트에만 있도록 접합 경로를 구성해야 합니다. 접합 경로에 미러링되지 않은 애그리게이트와 미러링된 애그리게이트를 혼합하여 구성할 경우, 전환 작업 후 미러링되지 않은 애그리게이트에 액세스하지 못할 수 있습니다.



== 미러링되지 않은 애그리게이트 및 CRS 메타데이터 볼륨과 데이터 SVM 루트 볼륨의 고려 사항

CRS(구성 복제 서비스) 메타데이터 볼륨 및 데이터 SVM 루트 볼륨은 미러링된 Aggregate에 있어야 합니다. 이러한 볼륨을 미러링되지 않은 애그리게이트로 이동할 수 없습니다. 미러링되지 않은 애그리게이트에 있는 경우 협상된 전환 및 스위치백 작업에 대한 거부가 표시됩니다. 이 경우 MetroCluster check 명령을 실행하면 경고가 표시됩니다.



== 미러링되지 않은 애그리게이트 및 SVM에 대한 고려사항

SVM은 미러링된 애그리게이트에만 구성하거나 미러링되지 않은 애그리게이트에만 구성해야 합니다. 미러링되지 않은 애그리게이트와 미러링된 애그리게이트를 혼합하여 구성하면 스위치오버 작업이 120초 이상 수행되어 미러링되지 않은 애그리게이트가 온라인 상태가 아닌 경우 데이터 중단이 발생할 수 있습니다.



== 미러링되지 않은 애그리게이트 및 SAN에 대한 고려사항

9.9.1 이전의 ONTAP 버전에서는 LUN이 미러링되지 않은 애그리게이트에 있어서는 안 됩니다. 미러링되지 않은 애그리게이트에 LUN을 구성하면 스위치오버 작업이 120초를 초과하고 데이터 중단이 발생할 수 있습니다.
