---
permalink: install-fc/fc-switch-port-assignment-overview.html 
sidebar: sidebar 
keywords: ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster, switch, cabling, port, assignment 
summary: FC 스위치에 케이블을 연결할 때 지정된 포트 할당을 사용하고 있는지 확인해야 합니다. 
---
= MetroCluster FC 스위치에 대한 포트 할당
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FC 스위치에 케이블을 연결할 때 지정된 포트 할당을 사용하고 있는지 확인해야 합니다.

이니시에이터 포트, FC-VI 포트 또는 ISL 연결에 사용되지 않는 포트를 스토리지 포트로 재구성할 수 있습니다. 단, 지원되는 RCF를 사용하는 경우 조닝을 그에 맞게 변경해야 합니다.

지원되는 RCF를 사용하는 경우 ISL 포트가 표시된 동일한 포트에 연결되지 않을 수 있으며 수동으로 재구성해야 할 수도 있습니다.

ONTAP 9용 포트 할당을 사용하여 스위치를 구성한 경우 이전 할당을 계속 사용할 수 있습니다. 그러나 ONTAP 9.1 이상을 실행하는 새로운 구성에서는 여기에 표시된 포트 할당을 사용해야 합니다.



== 전반적인 케이블 연결 지침

케이블 연결 테이블을 사용할 때 다음 지침을 숙지해야 합니다.

* Brocade 및 Cisco 스위치는 다른 포트 번호를 사용합니다.
+
** Brocade 스위치에서 첫 번째 포트는 0으로 번호가 지정됩니다.
** Cisco 스위치에서 첫 번째 포트의 번호는 1입니다.


* 케이블 연결은 스위치 패브릭의 각 FC 스위치에 대해 동일합니다.
* FC-VI 연결을 위한 2가지 옵션 중 하나로 AFF A300 및 FAS8200 스토리지 시스템을 주문할 수 있습니다.
+
** FC-VI 모드로 구성된 온보드 포트 0e 및 0f
** 슬롯 1의 FC-VI 카드에 있는 포트 1a 및 1b


* AFF A700 및 FAS9000 스토리지 시스템에는 FC-VI 포트 4개가 필요합니다. 다음 표는 Cisco 9250i 스위치를 제외하고 각 컨트롤러에 FC-VI 포트 4개가 있는 FC 스위치의 케이블 연결을 보여줍니다.
+
다른 스토리지 시스템의 경우, 표에 표시된 케이블을 사용하지만 FC-VI 포트 c 및 d의 케이블은 무시합니다

+
이러한 포트는 비워 둘 수 있습니다.

* AFF A400 및 FAS8300 스토리지 시스템은 FC-VI 연결에 포트 2a 및 2b를 사용합니다.
* ISL을 공유하는 MetroCluster 구성이 2개인 경우 8노드 MetroCluster 케이블 연결과 동일한 포트 할당을 사용합니다.
* 케이블로 연결하는 ISL의 수는 현장 요구 사항에 따라 달라질 수 있습니다.
* ISL 고려 사항에 대한 섹션을 참조하십시오.
+
link:concept_considerations_isls_mcfc.html["ISL에 대한 고려 사항"]





== AFF A900 및 FAS9500 케이블링 지침

* AFF A900 또는 FAS9500 스토리지 시스템에는 8개의 FC-VI 포트가 필요합니다. AFF A900 또는 FAS9500을 사용하는 경우 8포트 구성을 사용해야 합니다. 구성에 다른 스토리지 시스템 모델이 포함된 경우, 표에 표시된 케이블을 사용하되 불필요한 FC-VI 포트의 케이블은 무시합니다.

