---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, requirements, array, luns, mcc 
summary: MetroCluster 구성에 사용되는 ONTAP 시스템, 스토리지 어레이 및 FC 스위치는 이러한 유형의 구성에 대한 요구사항을 충족해야 합니다. 또한 어레이 LUN을 사용하는 MetroCluster 구성에 대한 SyncMirror 요구 사항도 고려해야 합니다. 
---
= 스토리지 LUN이 포함된 MetroCluster 구성 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성에 사용되는 ONTAP 시스템, 스토리지 어레이 및 FC 스위치는 이러한 유형의 구성에 대한 요구사항을 충족해야 합니다. 또한 어레이 LUN을 사용하는 MetroCluster 구성에 대한 SyncMirror 요구 사항도 고려해야 합니다.



== ONTAP 시스템에 대한 요구 사항

* ONTAP 시스템은 MetroCluster 구성에서 지원되는 것으로 식별되어야 합니다.
+
에 있습니다 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴(IMT)"]에서 스토리지 솔루션 필드를 사용하여 MetroCluster 솔루션을 선택할 수 있습니다. 부품 탐색기 * 를 사용하여 부품 및 ONTAP 버전을 선택하여 검색을 구체화합니다. 결과 표시 * 를 클릭하여 조건에 맞는 지원되는 설정 목록을 표시할 수 있습니다.

+

NOTE: 상호 운용성 매트릭스 에서 선택한 구성과 관련된 경고 세부 정보를 참조해야 합니다.

* MetroCluster 구성의 모든 ONTAP 시스템은 동일한 모델이어야 합니다.
* FC-VI 어댑터는 모델에 따라 각 ONTAP 시스템의 적절한 슬롯에 설치해야 합니다.
+
https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]





== 요구사항을 충족해야 합니다

* 스토리지 어레이는 MetroCluster 구성에서 지원되는 것으로 식별되어야 합니다.
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]

* MetroCluster 구성의 스토리지 어레이는 대칭이어야 합니다.
+
** 두 스토리지 어레이는 동일한 지원되는 공급업체 제품군에서 가져온 것이어야 하며 동일한 펌웨어 버전이 설치되어 있어야 합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html["NetApp E-Series 스토리지를 위한 FlexArray 가상화 구축"]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html["타사 스토리지를 위한 FlexArray 가상화 구축"]

** 미러링된 스토리지에 사용되는 디스크 유형(예: SATA, SSD 또는 SAS)은 두 스토리지 어레이에서 동일해야 합니다.
** RAID 유형 및 계층화와 같은 스토리지 배열 구성에 대한 매개 변수는 두 사이트 간에 동일해야 합니다.






== FC 스위치 요구 사항

* 스위치 및 스위치 펌웨어는 MetroCluster 구성에서 지원되는 것으로 식별되어야 합니다.
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]

* 각 Fabric에는 2개의 FC 스위치가 있어야 합니다.
* 각 ONTAP 시스템은 중복 구성 요소를 사용하여 스토리지에 연결해야 장치 및 경로 장애가 발생할 경우 이중화가 가능합니다.
* AFF A700, FAS9000, AFF A900 및 FAS9500 스토리지 시스템은 패브릭당 최대 8개의 ISL을 지원합니다. 다른 스토리지 시스템 모델은 Fabric당 최대 4개의 ISL을 지원합니다.


스위치는 MetroCluster 기본 스위치 구성, ISL 설정 및 FC-VI 구성을 사용해야 합니다.

link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Cisco 또는 Brocade FC 스위치를 수동으로 구성합니다"]



== SyncMirror 요구 사항

* MetroCluster를 구성하려면 SyncMirror가 필요합니다.
* 미러링된 스토리지를 사용하려면 각 사이트에 하나씩 두 개의 개별 스토리지 어레이가 필요합니다.
* 두 세트의 스토리지 LUN이 필요합니다.
+
로컬 스토리지 어레이(pool0)의 Aggregate에 한 세트가 필요하고 원격 스토리지 어레이에서 애그리게이트의 미러에 대한 다른 세트(pool1)가 필요합니다.

+
어레이 LUN의 크기는 애그리게이트를 미러링할 때 동일해야 합니다.

* 미러링되지 않은 애그리게이트는 MetroCluster 구성에서도 지원됩니다.
+
사이트 재해 발생 시 보호되지 않습니다.




NOTE: 최적의 스토리지 성능과 가용성을 위해 미러링된 애그리게이트에 대해 최소 20%의 여유 공간을 유지하는 것이 좋습니다. 미러링되지 않은 애그리게이트의 권장사항은 10%이지만, 파일 시스템이 증분 변경을 흡수하기 위해 추가 10%의 공간을 사용할 수 있습니다. 증분식으로 변경하면 ONTAP의 COW Snapshot 기반 아키텍처로 인해 미러링된 애그리게이트의 공간 활용률이 증가합니다. 이러한 모범 사례를 준수하지 않을 경우 성능에 부정적인 영향을 미칠 수 있습니다.
