---
permalink: install-fc/reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, switch, zoning, array, luns, requirements 
summary: 어레이 LUN이 있는 MetroCluster 구성에서 스위치 조닝을 사용하는 경우 특정 기본 요구사항을 준수해야 합니다. 
---
= 어레이 LUN이 있는 MetroCluster 구성의 스위치 조닝에 대한 요구사항
:icons: font
:imagesdir: ../media/


[role="lead"]
어레이 LUN이 있는 MetroCluster 구성에서 스위치 조닝을 사용하는 경우 특정 기본 요구사항을 준수해야 합니다.

어레이 LUN이 있는 MetroCluster 구성에서 스위치 조닝에 대한 요구 사항은 다음과 같습니다.

* MetroCluster 구성은 단일 이니시에이터에서 단일 타겟 조닝(zoning) 방식을 따라야 합니다.
+
단일 이니시에이터에서 단일 타겟 조닝으로 인해 각 존이 단일 FC 이니시에이터 포트 및 단일 타겟 포트로 제한됩니다.

* FC-VI 포트는 패브릭 전체에서 엔드 투 엔드 조닝되어야 합니다.
* 여러 이니시에이터 포트를 단일 타겟 포트와 공유하면 성능 문제가 발생할 수 있습니다.
+
마찬가지로, 여러 타겟 포트를 단일 이니시에이터 포트와 공유하면 성능 문제가 발생할 수 있습니다.

* MetroCluster 구성에 사용되는 FC 스위치의 기본 구성을 수행해야 합니다.
+
link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Cisco 또는 Brocade FC 스위치를 수동으로 구성합니다"]





== 스토리지 LUN이 있는 MetroCluster 구성에 대한 공유 이니시에이터 및 공유 타겟 지원

지정된 FC 이니시에이터 포트 또는 타겟 포트를 공유할 수 있으면 사용되는 이니시에이터 또는 타겟 포트의 수를 최소화하려는 조직에 유용합니다. 예를 들어, FC 이니시에이터 포트 또는 타겟 포트에서 낮은 I/O 사용량을 기대하는 조직은 각 FC 이니시에이터 포트를 단일 타겟 포트에 할당하는 대신 FC 이니시에이터 포트 또는 타겟 포트를 공유하는 것을 선호할 수 있습니다.

그러나 이니시에이터 또는 타겟 포트를 공유하면 성능에 부정적인 영향을 미칠 수 있습니다.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_support_Shared_Initiator_and_Shared_Target_configuration_with_Array_LUNs_in_a_MetroCluster_environment["MetroCluster 환경에서 스토리지 LUN과 공유 이니시에이터 및 공유 타겟 구성을 지원하는 방법"]

* 스위치 조닝은 연결된 노드 간 경로를 정의합니다. 조닝을 구성하면 특정 ONTAP 시스템에서 볼 수 있는 어레이 LUN을 정의할 수 있습니다.
+
link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html["어레이 LUN이 있는 2노드 MetroCluster 구성에서 스위치 조닝의 예"]

+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["어레이 LUN이 있는 4노드 MetroCluster 구성의 스위치 조닝의 예"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["어레이 LUN이 있는 8노드 MetroCluster 구성의 스위치 조닝의 예"]


