---
permalink: install-fc/reference_where_to_find_additional_information_icg.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, additional, information 
summary: MetroCluster 구성 및 작동에 대한 자세한 내용은 NetApp 설명서를 참조하십시오. 
---
= 추가 정보를 찾을 수 있는 위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성 및 작동에 대해 자세히 알아볼 수 있습니다.



== MetroCluster 및 기타 정보

|===


| 정보 | 제목 


 a| 
link:https://docs.netapp.com/us-en/ontap/index.html["ONTAP 9 설명서"^]
 a| 
* 모든 MetroCluster 정보




| link:https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["NetApp MetroCluster 솔루션 아키텍처 및 설계, TR-4705"^]  a| 
* MetroCluster FC 구성 및 작동에 대한 기술적 개요
* MetroCluster FC 구성의 모범 사례




| link:https://www.netapp.com/pdf.html?item=/media/13481-tr4689.pdf["MetroCluster IP 솔루션 아키텍처 및 설계, TR-4689"^]  a| 
* MetroCluster IP 구성 및 작동에 대한 기술적 개요
* MetroCluster IP 구성의 모범 사례




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["스트레치 MetroCluster 설치 및 구성"]
 a| 
* MetroCluster 아키텍처 확장
* 구성 케이블 연결
* FC-to-SAS 브릿지 구성
* ONTAP에서 MetroCluster 구성




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["MetroCluster IP 설치 및 구성: ONTAP MetroCluster 구성 간의 차이점"]
 a| 
* MetroCluster IP 아키텍처
* 구성 케이블 연결
* ONTAP에서 MetroCluster 구성




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html["MetroCluster 관리 및 재해 복구"]
 a| 
* MetroCluster 구성 이해
* 전환, 복구, 스위치백
* 재해 복구




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["MetroCluster 구성 요소를 유지보수하십시오"]
 a| 
* MetroCluster FC 구성의 유지 관리 지침
* FC-to-SAS 브리지 및 FC 스위치에 대한 하드웨어 교체 또는 업그레이드 및 펌웨어 업그레이드 절차
* 패브릭 연결 또는 확장 MetroCluster FC 구성에서 디스크 쉘프 핫 추가
* 패브릭 연결 또는 확장 MetroCluster FC 구성에서 디스크 쉘프 핫 제거
* 패브릭 연결 또는 확장 MetroCluster FC 구성의 재해 사이트에서 하드웨어 교체
* 2노드 패브릭 연결 또는 확장 MetroCluster FC 구성을 4노드 MetroCluster 구성으로 확장
* 4노드 패브릭 연결 또는 확장 MetroCluster FC 구성을 8노드 MetroCluster FC 구성으로 확장




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html["MetroCluster FC에서 MetroCluster IP로 전환합니다"]

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster 업그레이드 및 확장 가이드"]
 a| 
* MetroCluster 구성 업그레이드 또는 새로 고침
* MetroCluster FC 구성에서 MetroCluster IP 구성으로 전환
* 노드를 추가하여 MetroCluster 구성 확장




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html["MetroCluster Tiebreaker 소프트웨어 설치 및 구성"]
 a| 
* MetroCluster Tiebreaker 소프트웨어로 MetroCluster 구성 모니터링




 a| 
Active IQ 디지털 자문 문서

https://www.netapp.com/support-and-training/documentation/["NetApp 설명서: 제품 가이드 및 리소스"^]
 a| 
* MetroCluster 구성 및 성능 모니터링




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["복사 기반 전환"^]
 a| 
* 7-Mode 스토리지 시스템에서 클러스터 스토리지 시스템으로 데이터 전환




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["ONTAP 개념"^]
 a| 
* 미러링된 데이터의 작동 방식


|===