---
permalink: install-fc/task_rack_the_hardware_components_mcc_fabric_and_ip.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, rack, hardware, components 
summary: 캐비닛에 이미 설치된 장비를 받지 못한 경우 구성 요소를 랙에 장착해야 합니다. 
---
= 하드웨어 구성 요소 장착
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
캐비닛에 이미 설치된 장비를 받지 못한 경우 구성 요소를 랙에 장착해야 합니다.

.이 작업에 대해
이 작업은 두 MetroCluster 사이트 모두에서 수행해야 합니다.

.단계
. MetroCluster 구성 요소의 포지셔닝을 계획합니다.
+
랙 공간은 컨트롤러 모듈의 플랫폼 모델, 스위치 유형 및 구성의 디스크 쉘프 스택 수에 따라 달라집니다.

. 적절하게 접지합니다.
. 랙 또는 캐비닛에 컨트롤러 모듈을 설치합니다.
+
https://docs.netapp.com/platstor/index.jsp["AFF and FAS 문서 센터 를 참조하십시오"]

. 랙 또는 캐비닛에 FC 스위치를 설치합니다.
. 디스크 쉘프를 설치하고 전원을 켠 다음 쉘프 ID를 설정합니다.
+
** 각 디스크 쉘프의 전원을 껐다가 다시 켜야 합니다.
** 쉘프 ID는 각 MetroCluster DR 그룹(두 사이트 포함)의 각 SAS 디스크 쉘프에 대해 고유해야 합니다.


. 각 FC-to-SAS 브리지를 설치합니다.
+
.. 4개의 나사로 브리지 전면의 ""L"" 브래킷을 랙 전면(플러시 마운트)에 고정합니다.
+
브리지 ""L"" 브래킷의 개구부는 19인치(482.6mm) 랙에 대한 랙 표준 ETA-310-X를 준수합니다.

+
브리지 모델의 _ATTO FiberBridge 설치 및 작동 설명서_ 에는 자세한 정보와 설치 그림이 포함되어 있습니다.

+

NOTE: 적절한 포트 공간 액세스 및 FRU 서비스 가능성을 위해 브리지 쌍 아래에 1U 공간을 두고 공구가 필요 없는 블랭킹 패널을 사용하여 이 공간을 덮어야 합니다.

.. 각 브리지를 적절한 접지를 제공하는 전원에 연결합니다.
.. 각 브리지의 전원을 켭니다.
+

NOTE: 복원력을 극대화하려면 동일한 디스크 쉘프 스택에 연결된 브리지를 다른 전원에 연결해야 합니다.

+
브리지 준비 LED가 켜지려면 최대 30초가 걸릴 수 있으며 이는 브리지가 전원 공급 자체 테스트 시퀀스를 완료했음을 나타냅니다.




