---
permalink: install-fc/task_verify_the_ha_state_of_components_is_mcc_or_mcc_2n_in_maintenance_mode.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, verify, ha, state, components, maintenance, mode 
summary: 'MetroCluster 구성에서 스토리지 시스템을 구성할 때는 컨트롤러 모듈 및 섀시 구성 요소의 고가용성 \(HA\) 상태가 MCC 또는 MCC-2n인지 확인해야 구성 요소가 제대로 부팅됩니다.' 
---
= 유지보수 모드에서 구성요소의 HA 상태 확인 및 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성에서 스토리지 시스템을 구성할 때는 컨트롤러 모듈 및 섀시 구성 요소의 고가용성(HA) 상태가 "MCC" 또는 "MCC-2n"인지 확인해야 합니다.

시스템이 유지보수 모드여야 합니다.

이 작업은 공장에서 입고된 시스템에는 필요하지 않습니다.

.단계
. 유지보수 모드에서 컨트롤러 모듈 및 섀시의 HA 상태를 표시합니다.
+
하구성 쇼

+
올바른 HA 상태는 MetroCluster 구성에 따라 다릅니다.

+
|===


| MetroCluster 구성의 컨트롤러 수입니다 | 모든 구성요소의 HA 상태는... 


 a| 
8노드 또는 4노드 MetroCluster FC 구성
 a| 
MCC



 a| 
2노드 MetroCluster FC 구성
 a| 
MCC - 2n



 a| 
MetroCluster IP 구성
 a| 
mcip

|===
. 표시된 컨트롤러 시스템 상태가 정확하지 않은 경우 컨트롤러 모듈에 대한 HA 상태를 설정합니다.
+
|===


| MetroCluster 구성의 컨트롤러 수입니다 | 명령 


 a| 
8노드 또는 4노드 MetroCluster FC 구성
 a| 
하구성 수정 컨트롤러 MCC



 a| 
2노드 MetroCluster FC 구성
 a| 
ha-config modify controller MCC-2n



 a| 
MetroCluster IP 구성
 a| 
ha-config modify controller mcip.(컨트롤러 mccip 수정

|===
. 표시된 섀시 시스템 상태가 올바르지 않으면 섀시의 HA 상태를 설정합니다.
+
|===


| MetroCluster 구성의 컨트롤러 수입니다 | 명령 


 a| 
8노드 또는 4노드 MetroCluster FC 구성
 a| 
하구성 수정 새시 MCC



 a| 
2노드 MetroCluster FC 구성
 a| 
ha-config modify chassis MCC-2n



 a| 
MetroCluster IP 구성
 a| 
ha-config modify chassis mccip.(섀시 mcip 수정

|===
. 노드를 ONTAP로 부팅합니다.
+
부트 ONTAP

. MetroCluster 구성의 각 노드에서 이 단계를 반복합니다.

