---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: 'ISL(Inter-Switch Link)\)이 동일한 포트 그룹에 있는지 확인하고 MetroCluster 구성이 스위치 패브릭을 성공적으로 공유할 수 있도록 조닝을 구성해야 합니다.' 
---
= ISL이 동일한 포트 그룹에 있는지 확인하고 조닝을 구성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ISL(Inter-Switch Link)이 동일한 포트 그룹에 있는지 확인하고 MetroCluster 구성이 스위치 패브릭을 성공적으로 공유할 수 있도록 조닝을 구성해야 합니다.

.단계
. ISL이 동일한 포트 그룹에 없으면 ISL 포트 중 하나를 다른 포트와 동일한 포트 그룹으로 이동합니다.
+
새 MetroCluster 구성에 사용되는 32-45를 제외한 모든 사용 가능한 포트를 사용할 수 있습니다. 권장 ISL 포트는 46 및 47입니다.

. 의 단계를 따릅니다 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade FC 스위치에서 조닝 구성"] 섹션을 참조하십시오.
+
Fabric을 공유할 때의 포트 번호는 섹션에 나와 있는 포트 번호와 다릅니다. 공유할 때는 ISL 포트에 대해 포트 46과 47을 사용합니다. ISL 포트를 이동한 경우 의 절차를 사용해야 합니다 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade FC 스위치에서 E-포트(ISL 포트)를 구성합니다"] 섹션을 참조하십시오.

. [[step3_zones]]의 단계를 따릅니다 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade 스위치에서 비 E 포트 구성"] 섹션을 참조하여 비 E 포트를 구성합니다.
. 의 TI(트래픽 격리) 영역을 제외하고 백엔드 스위치(7-Mode 패브릭 MetroCluster용)에 이미 있는 영역 또는 영역 세트를 삭제하지 마십시오 <<step3_zones,3단계>>.
. 의 단계를 따릅니다 link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade FC 스위치에서 E-포트(ISL 포트)를 구성합니다"] 섹션을 클릭하여 새 MetroCluster에 필요한 영역을 기존 영역 집합에 추가합니다.
+
다음 예는 영역을 생성하기 위한 명령 및 시스템 출력을 보여줍니다.

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

