---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_rcf_files.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, install, cisco, fc, rcf, files 
summary: RCF 파일은 MetroCluster 패브릭 구성의 각 스위치에 다운로드해야 합니다. 
---
= Cisco FC RCF 파일 다운로드 및 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RCF 파일은 MetroCluster 패브릭 구성의 각 스위치에 다운로드해야 합니다.

.시작하기 전에
이 작업을 수행하려면 FTP, TFTP(Trivial File Transfer Protocol), SFTP 또는 SCP(Secure Copy Protocol)와 같은 파일 전송 소프트웨어가 필요합니다.

.이 작업에 대해
이러한 단계는 MetroCluster 패브릭 구성의 각 Cisco FC 스위치에서 반복해야 합니다.

지원되는 스위치 소프트웨어 버전을 사용해야 합니다.

https://["NetApp Hardware Universe를 참조하십시오"]

RCF 파일은 MetroCluster 패브릭 구성에서 4개 스위치당 하나씩 4개의 RCF 파일로 구성됩니다. 사용 중인 스위치 모델에 적합한 RCF 파일을 사용해야 합니다.

|===


| 스위치 | RCF 파일 


 a| 
fc_switch_a_1
 a| 
'NX3232_v1.80_Switch-A1.txt'



 a| 
fc_switch_a_2
 a| 
'NX3232_v1.80_Switch-A2.txt'



 a| 
fc_switch_B_1
 a| 
'NX3232_v1.80_Switch-B1.txt'



 a| 
fc_switch_B_2
 a| 
'NX3232_v1.80_Switch-B2.txt'

|===

NOTE: 표시된 출력은 Cisco IP 스위치용으로 표시되지만 Cisco FC 스위치에도 적용할 수 있습니다.

.단계
. 에서 Cisco FC RCF 파일을 다운로드합니다 https://["MetroCluster RCF 다운로드 페이지"].
. RCF 파일을 스위치에 복사합니다.
+
.. RCF 파일을 첫 번째 스위치에 복사합니다.
+
'복사 sftp://__root@ftp-server-ip-address/tftpboot/switch-specific-RCF__bootflash:vrf management'

+
이 예에서는 NX3232_v1.80_Switch-A1.txt의 RCF 파일이 SFTP 서버(10.10.99.99)에서 로컬 bootflash로 복사됩니다. TFTP/SFTP 서버의 IP 주소와 설치해야 하는 RCF 파일의 파일 이름을 사용해야 합니다.

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/NX3232_v1.8T-X1_Switch-A1.txt bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/NX3232_v1.80_Switch-A1.txt /bootflash/NX3232_v1.80_Switch-A1.txt
Fetching /tftpboot/NX3232_v1.80_Switch-A1.txt to /bootflash/NX3232_v1.80_Switch-A1.txt
/tftpboot/NX3232_v1.80_Switch-A1.txt          100% 5141     5.0KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
IP_switch_A_1#
----
.. 일치하는 RCF 파일을 해당 스위치에 복사하도록 나머지 세 스위치 각각에 대해 이전 하위 단계를 반복합니다.


. 각 스위치에서 RCF 파일이 각 스위치의 'bootflash' 디렉토리에 있는지 확인합니다.
+
'dir bootflash:'

+
다음 예제는 파일이 IP_SWITCH_A_1에 있음을 보여줍니다.

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
       5514    Jun 13 22:09:05 2017  NX3232_v1.80_Switch-A1.txt
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. 로컬 bootflash에서 각 스위치의 실행 구성으로 일치하는 RCF 파일을 복사합니다.
+
bootflash: __switch-specific-RCF__.txt running-config를 복사합니다

. RCF 파일을 실행 중인 구성에서 각 스위치의 시작 구성으로 복사합니다.
+
'copy running-config startup-config'를 선택합니다

+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
IP_switch_A_1# copy bootflash:NX3232_v1.80_Switch-A1.txt running-config
IP_switch_A_1# copy running-config startup-config
----
. 스위치를 다시 로드하십시오.
+
다시 로드

+
[listing]
----
IP_switch_A_1# reload
----
. MetroCluster IP 구성의 다른 3개 스위치에 대해 이전 단계를 반복합니다.

