---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: ONTAP 중재자의 새로운 기능은 각 릴리스에 제공됩니다.  새로운 기능 
---
= MetroCluster 에 대한 ONTAP Mediator 지원의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Mediator 지원을 위한 새로운 MetroCluster 기능과 향상된 기능에 대해 알아보세요.

ONTAP Mediator의 각 릴리스에 대한 기능 및 향상된 기능에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["ONTAP Mediator의 새로운 기능"^] .

[cols="4,2"]
|===
| ONTAP 중재자 기능 | 처음부터 사용할 수 있습니다 


 a| 
IPv6는 MetroCluster IP 구성의 ONTAP Mediator 1.11 이상에서 지원됩니다.

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["MetroCluster IP 구성을 위한 ONTAP Mediator 설정"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11에서는 단일 ONTAP Mediator 인스턴스를 사용하여 최대 10개의 MetroCluster IP 구성을 관리할 수 있는 지원 기능이 추가되었습니다.

link:../install-ip/concept_mediator_requirements.html["MetroCluster IP 구성에 ONTAP Mediator를 설치할 준비를 합니다."]
 a| 
ONTAP 9.18.1



 a| 
환경 종료 시 중재자 지원 자동 계획되지 않은 전환(MAUSO)이 지원됩니다.

환경 가동 중단으로 인해 한 사이트가 정상적으로 종료되면 MAUSO가 트리거됩니다.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP Mediator가 자동 계획되지 않은 전환을 지원하는 방식"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
MetroCluster IP 구성에서 ONTAP Mediator에 대한 초기 지원
 a| 
ONTAP 9.7 을 참조하십시오

|===