---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= ONTAP 기능에 대한 MetroCluster 구성의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAP 9 데이터 관리 소프트웨어가 릴리즈될 때마다 ONTAP MetroCluster 구성의 기능, 관리 효율 및 성능을 개선하는 새롭고 향상된 기능을 제공합니다.

ONTAP MetroCluster 구성에 영향을 주는 알려진 문제, 제한 사항 및 업그레이드 주의 사항에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"^]. 릴리스 정보에 액세스하려면 NetApp 계정으로 로그인하거나 계정을 만들어야 합니다.

[cols="20,65,15"]
|===
| MetroCluster 구성에서 지원되는 기능 | 설명 | 처음부터 사용할 수 있습니다 


 a| 
NVMe에 대한 MetroCluster IP 지원
 a| 
NVMe/TCP 프런트 엔드 호스트 프로토콜은 4노드 MetroCluster IP 구성에서 지원됩니다.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 환경의 SAN 구성입니다"^]
 a| 
ONTAP 9.15.1



 a| 
미러링된 및 미러링되지 않은 애그리게이트에서 S3 오브젝트 스토리지 지원
 a| 
MetroCluster IP 및 FC 구성의 경우, 미러링되거나 미러링되지 않은 애그리게이트의 SVM에서 S3 오브젝트 스토리지 서버를 사용하도록 설정할 수 있습니다.

https://docs.netapp.com/us-en/ontap/s3-config/index.html["S3 구성 개요"]
 a| 
ONTAP 9.14.1



 a| 
MetroCluster 클러스터의 미러링된 애그리게이트 및 미러링되지 않은 애그리게이트에서 S3 버킷을 프로비저닝할 수 있습니다
 a| 
MetroCluster 구성의 경우 미러링된 또는 미러링되지 않은 애그리게이트에 버킷을 생성할 수 있습니다.

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["MetroCluster 구성의 경우 미러링된 또는 미러링되지 않은 애그리게이트에 버킷을 생성합니다"]
 a| 
ONTAP 9.12.1



 a| 
NVMe에 대한 MetroCluster IP 지원
 a| 
NVMe/FC 프로토콜은 4노드 MetroCluster IP 구성에서 지원됩니다.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 환경의 SAN 구성입니다"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP 및 MetroCluster 패브릭 연결 구성에서 프런트 엔드 호스트 프로토콜에 대한 IPsec 지원
 a| 
MetroCluster IP 및 MetroCluster 패브릭 연결 구성에서 프런트 엔드 호스트 프로토콜(예: NFS 및 iSCSI)에 대한 IPsec 지원을 사용할 수 있습니다.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["유선 암호화를 통해 IP 보안(IPsec)을 구성합니다"]
 a| 
ONTAP 9.11.1



 a| 
정합성 보장 그룹
 a| 
정합성 보장 그룹은 MetroCluster 구성에서 지원됩니다.
 a| 
ONTAP 9.7 을 참조하십시오



 a| 
MetroCluster 구성의 FabricPool 미러
 a| 
MetroCluster 구성에서 미러링된 FabricPool를 설정하여 콜드 데이터를 두 개의 서로 다른 장애 영역으로 계층화할 수 있습니다.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["MetroCluster 구성에서 FabricPool에 대한 오브젝트 저장소 설정"]
 a| 
ONTAP 9.7 을 참조하십시오



 a| 
SVM 재해 복구
 a| 
MetroCluster 구성에서 액티브 스토리지 가상 머신(SVM)을 SnapMirror SVM 재해 복구 기능의 소스로 사용할 수 있습니다.
 a| 
ONTAP 9.5 를 참조하십시오

|===