---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= MetroCluster의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 데이터 관리 소프트웨어가 릴리즈될 때마다 ONTAP MetroCluster 구성의 기능, 관리 효율 및 성능을 개선하는 새롭고 향상된 기능을 제공합니다.

ONTAP MetroCluster 구성에 영향을 주는 알려진 문제, 제한 사항 및 업그레이드 주의 사항에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"^]. 릴리스 정보에 액세스하려면 NetApp 계정으로 로그인하거나 계정을 만들어야 합니다.

[cols="20,65,15"]
|===
| MetroCluster 구성에서 지원되는 기능 | 설명 및 자세한 내용 | 처음부터 사용할 수 있습니다 


 a| 
MetroCluster IP 구성의 FAS50 시스템에 대한 Flash Cache 지원
 a| 
Flash Cache는 MetroCluster IP 구성의 FAS50 시스템에서 지원됩니다.

link:../install-ip/concept_considerations_drive_assignment.html#disk-assignment-on-fas50-systems-with-flash-cache["Flash Cache를 사용하는 FAS50 시스템의 디스크 할당"]
 a| 
ONTAP 9.18.1



 a| 
MetroCluster IP는 엔드 투 엔드 암호화를 지원합니다
 a| 
MetroCluster IP 구성의 사이트 간 백엔드 트래픽(예: NVlog 및 스토리지 복제 데이터)을 암호화하기 위해 다음 시스템에서는 엔드투엔드 암호화가 지원됩니다.

* AFF A800, AFF C800
* AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
* AFF A70, AFF A90, AFF A1K, AFF C80의 약어입니다
* FAS50, FAS70, FAS90


link:../maintain/task-configure-encryption.html["MetroCluster IP 구성에서 엔드 투 엔드 암호화를 구성합니다"]
 a| 
ONTAP 9.17.1



 a| 
MetroCluster IP 구성에 대한 변경 제한
 a| 
ONTAP 9.17.1에는 4노드 MetroCluster IP 구성에 대한 다음과 같은 제한 업데이트가 포함되어 있습니다.

* AFF C800, AFF A800, AFF A900, AFF A90 및 AFF A1K 시스템에는 다음과 같은 업데이트된 제한이 있습니다.
+
** 노드당 FlexVol volume 제한: 1250
** SVM 제한: 클러스터당 64개 SVM
** LIF 수: 클러스터당 256개 LIF


* AFF A400, AFF C400, ASA A400, ASA C400, AFF C80, AFF A70 및 AFF A50 시스템에는 다음과 같은 업데이트된 제한이 있습니다.
+
** 집계당 FlexVol volume 제한(단일 또는 다중): 625
** 노드당 FlexVol volume 제한: 1250
** 고가용성(HA) 쌍당 FlexVol volume 제한: 2500
** 클러스터당 FlexVol volume 제한: 5000
** SVM 제한: 클러스터당 64개 SVM
** LIF 수: 클러스터당 256개 LIF




를 참조하세요 link:https://hwu.netapp.com["Hardware Universe"^] 자세한 내용은.
 a| 
ONTAP 9.17.1



 a| 
자격 증명을 사용한 FibreBridge 펌웨어 업데이트
 a| 
서버에서 펌웨어 패키지를 다운로드하는 데 필요한 경우 자격 증명을 사용하여 FibreBridge 브리지의 펌웨어를 업데이트할 수 있습니다.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["FiberBridge 브리지에서 펌웨어를 업데이트합니다"]
 a| 
ONTAP 9.16.1



 a| 
MetroCluster 구성 마이그레이션에 대한 SVM 데이터 이동성 지원
 a| 
ONTAP은 다음 MetroCluster SVM 마이그레이션을 지원합니다.

* 비 MetroCluster HA 쌍 및 MetroCluster IP 구성 간에 SVM 마이그레이션
* 2개의 MetroCluster IP 구성 간에 SVM 마이그레이션
* MetroCluster FC 구성과 MetroCluster IP 구성 간에 SVM 마이그레이션


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["SVM 데이터 이동성"^]
 a| 
ONTAP 9.16.1



 a| 
BGP 피어 그룹에 대한 MD5 인증 지원
 a| 
ONTAP는 BGP 피어 그룹에서 MD5 인증을 지원하여 BGP 세션을 보호합니다. MD5가 활성화되면 승인된 피어 사이에서만 BGP 세션을 설정 및 처리할 수 있으므로 권한이 없는 행위자에 의한 세션 중단을 방지할 수 있습니다.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["가상 IP(VIP) LIF를 구성합니다"^]
 a| 
ONTAP 9.16.1



 a| 
MetroCluster IP는 엔드 투 엔드 암호화를 지원합니다
 a| 
AFF A400, AFF C400, FAS8300 및 FAS8700 시스템은 MetroCluster IP 구성의 사이트 간 NVlog 및 스토리지 복제 데이터와 같은 백엔드 트래픽을 암호화하기 위해 종단 간 암호화를 지원합니다.

link:../maintain/task-configure-encryption.html["MetroCluster IP 구성에서 엔드 투 엔드 암호화를 구성합니다"]
 a| 
ONTAP 9.15.1



 a| 
AFF A800 및 AFF C800 시스템에서 4노드 MetroCluster IP 구성의 볼륨 제한 증가
 a| 
4노드 MetroCluster IP 구성에서 AFF A800 및 AFF C800 시스템에 대한 다음 볼륨 제한이 증가했습니다.

* 애그리게이트당 최대 FlexVol 볼륨 수가 200개에서 625개로 증가했습니다.
* 노드당 최대 FlexVol 볼륨 수가 800개에서 1250개로 증가했습니다.
* HA 쌍당 FlexVol 볼륨의 최대 수가 1600에서 2500으로 증가했습니다.

 a| 
ONTAP 9.15.1



 a| 
NVMe에 대한 MetroCluster IP 지원
 a| 
NVMe/TCP 프런트 엔드 호스트 프로토콜은 4노드 MetroCluster IP 구성에서 지원됩니다.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 환경의 SAN 구성입니다"^]
 a| 
ONTAP 9.15.1



 a| 
AFF A900 시스템에서 4노드 MetroCluster IP 구성의 볼륨 제한 인상
 a| 
4노드 MetroCluster IP 구성에서는 AFF A900 시스템에 대한 다음 볼륨 제한이 증가했습니다.

* 애그리게이트당 최대 FlexVol 볼륨 수가 200개에서 625개로 증가했습니다.
* 노드당 최대 FlexVol 볼륨 수가 800개에서 1250개로 증가했습니다.
* HA 쌍당 FlexVol 볼륨의 최대 수가 1600에서 2500으로 증가했습니다.

 a| 
ONTAP 9.14.1



 a| 
미러링된 및 미러링되지 않은 애그리게이트에서 S3 오브젝트 스토리지 지원
 a| 
MetroCluster IP 및 FC 구성의 경우, 미러링되거나 미러링되지 않은 애그리게이트의 SVM에서 S3 오브젝트 스토리지 서버를 사용하도록 설정할 수 있습니다.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["MetroCluster를 통해 S3 지원"^]
 a| 
ONTAP 9.14.1



 a| 
MetroCluster 클러스터의 미러링된 애그리게이트 및 미러링되지 않은 애그리게이트에서 S3 버킷을 프로비저닝할 수 있습니다
 a| 
MetroCluster 구성의 경우 미러링된 또는 미러링되지 않은 애그리게이트에 버킷을 생성할 수 있습니다.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["MetroCluster 구성의 경우 미러링된 또는 미러링되지 않은 애그리게이트에 ONTAP S3 버킷을 생성합니다"^]
 a| 
ONTAP 9.14.1



 a| 
MetroCluster IP 및 이더넷 연결 스토리지의 공유 스위치를 사용하여 MetroCluster FC에서 MetroCluster IP로 전환합니다
 a| 
공유 스토리지 스위치를 사용하여 MetroCluster FC에서 MetroCluster IP 구성으로 중단 없이 전환할 수 있습니다.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["MetroCluster FC에서 MetroCluster IP 구성으로 중단 없이 전환(ONTAP 9.8 이상)"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
8노드 MetroCluster FC 구성에서 MetroCluster IP 구성으로 무중단 전환
 a| 
기존 8노드 MetroCluster FC 구성에서 새 MetroCluster IP 구성으로 중단 없이 워크로드와 데이터를 전환할 수 있습니다.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["MetroCluster FC에서 MetroCluster IP 구성으로 중단 없이 전환합니다"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
스위치오버 및 스위치백을 사용한 4노드 MetroCluster IP 구성 업그레이드
 a| 
스위치오버 및 스위치백을 사용하여 4노드 MetroCluster IP 구성에서 컨트롤러를 업그레이드할 수 있습니다 `system controller replace` 명령.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["4노드 MetroCluster IP 구성에서 컨트롤러를 업그레이드합니다"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
환경 종료를 위해 중재자 지원 자동 계획되지 않은 전환(MAUSO)이 트리거됩니다
 a| 
환경 가동 중단으로 인해 한 사이트가 정상적으로 종료되면 MAUSO가 트리거됩니다.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP 중재자가 자동 계획되지 않은 전환을 지원하는 방법"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
8노드 MetroCluster IP 구성 지원
 a| 
8노드 MetroCluster IP 구성에서 컨트롤러 및 스토리지를 업그레이드할 수 있도록 구성을 임시 12노드 구성으로 확장한 다음 이전 DR 그룹을 제거하면 됩니다.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["4노드 MetroCluster IP 구성을 업데이트합니다"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
공유 스토리지 MetroCluster 스위치 구성으로 MetroCluster IP 구성 변환
 a| 
MetroCluster IP 구성을 공유 스토리지 MetroCluster 스위치 구성으로 변환할 수 있습니다.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["IP 스위치를 교체합니다"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
MetroCluster IP 구성의 MetroCluster 자동 강제 전환 기능
 a| 
MetroCluster IP 구성에서 MetroCluster 자동 강제 전환 기능을 활성화할 수 있습니다. 이 기능은 중재자 지원 계획되지 않은 전환(MAUSO) 기능의 확장입니다.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["자동 전환 제한"]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP 구성의 미러링되지 않은 애그리게이트에서 SVM에 S3가 지원됩니다
 a| 
MetroCluster IP 구성의 미러링되지 않은 애그리게이트의 SVM에서 ONTAP S3(Simple Storage Service) 오브젝트 스토리지 서버를 사용하도록 설정할 수 있습니다.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["MetroCluster를 통해 S3 지원"^]
 a| 
ONTAP 9.12.1



 a| 
NVMe에 대한 MetroCluster IP 지원
 a| 
NVMe/FC 프로토콜은 4노드 MetroCluster IP 구성에서 지원됩니다.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 환경의 SAN 구성입니다"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP 및 MetroCluster 패브릭 연결 구성에서 프런트 엔드 호스트 프로토콜에 대한 IPsec 지원
 a| 
MetroCluster IP 및 MetroCluster 패브릭 연결 구성에서 프런트 엔드 호스트 프로토콜(예: NFS 및 iSCSI)에 대한 IPsec 지원을 사용할 수 있습니다.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["유선 암호화를 통해 IP 보안(IPsec)을 구성합니다"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster FC 구성에서 AFF A250 또는 FAS500f MetroCluster IP 구성으로 전환합니다
 a| 
MetroCluster FC 구성에서 AFF A250 또는 FAS500f MetroCluster IP 구성으로 전환할 수 있습니다.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["로컬 클러스터 연결을 이동합니다"]
 a| 
ONTAP 9.11.1



 a| 
정합성 보장 그룹
 a| 
정합성 보장 그룹은 MetroCluster 구성에서 지원됩니다.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["MetroCluster 구성의 일관성 그룹"^]
 a| 
ONTAP 9.11.1



 a| 
MetroCluster FC 구성에서 노드에 대한 컨트롤러 업그레이드를 간소화합니다
 a| 
스위치오버와 스위치백을 사용한 업그레이드 프로세스의 업그레이드 절차가 간소화되었습니다.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["스위치오버 및 스위치백을 사용하여 MetroCluster FC 구성에서 컨트롤러를 업그레이드합니다"]
 a| 
ONTAP 9.10.1



 a| 
계층 3에서 공유 링크에 대한 IP 지원
 a| 
MetroCluster IP 구성은 IP 라우팅(계층 3) 백엔드 연결을 통해 구현할 수 있습니다.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["계층 3 광역 네트워크에 대한 고려 사항"]
 a| 
ONTAP 9.9.1



 a| 
8노드 MetroCluster 구성 지원
 a| 
영구 8노드 클러스터는 IP 및 패브릭 연결 MetroCluster 구성으로 지원됩니다.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster 구성 요소를 설치하고 케이블을 연결합니다"]
 a| 
ONTAP 9.9.1

|===