---
permalink: maintain/concept_migrating_root_volumes_to_a_new_destination.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, migrate, root, volumes, new, destination 
summary: 2노드 또는 4노드 MetroCluster 구성 내에서 루트 볼륨을 다른 루트 애그리게이트로 이동해야 할 수 있습니다. 
---
= 루트 볼륨을 새 대상으로 마이그레이션하는 시기
:icons: font
:imagesdir: ../media/


[role="lead"]
2노드 또는 4노드 MetroCluster 구성 내에서 루트 볼륨을 다른 루트 애그리게이트로 이동해야 할 수 있습니다.



== 2노드 MetroCluster 구성 내에서 루트 볼륨 마이그레이션

2노드 MetroCluster 구성 내에서 루트 볼륨을 새 루트 애그리게이트로 마이그레이션하려면 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_move_mroot_to_a_new_root_aggregate_in_a_2-node_Clustered_MetroCluster_with_Switchover["Switchover를 사용하여 2노드 clustered MetroCluster에서 mroot를 새 루트 애그리게이트로 이동하는 방법"]. 이 절차에서는 MetroCluster 전환 작업 중에 루트 볼륨을 운영 중단 없이 마이그레이션하는 방법을 보여 줍니다. 이 절차는 4노드 구성에 사용되는 절차와 약간 다릅니다.



== 4노드 MetroCluster 구성 내에서 루트 볼륨 마이그레이션

4노드 MetroCluster 구성 내에서 루트 볼륨을 새 루트 애그리게이트로 마이그레이션하려면 를 사용할 수 있습니다 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/system%5F%5Fnode%5F%5Fmigrate-root.html["시스템 노드 migrate-root"] 다음 요구 사항을 충족하는 동안 명령을 내립니다.

* system node migrate-root를 사용하여 4노드 MetroCluster 구성 내에서 루트 애그리게이트를 이동할 수 있습니다.
* 모든 루트 애그리게이트를 미러링해야 합니다.
* 두 사이트 모두에서 더 작은 드라이브를 사용하여 새 쉘프를 추가하여 루트 애그리게이트를 호스팅할 수 있습니다.
* 새 드라이브를 연결하기 전에 플랫폼이 지원하는 드라이브 제한을 확인해야 합니다.
+
https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]

* 루트 애그리게이트를 더 작은 드라이브로 이동하는 경우, 모든 코어 파일이 저장되도록 플랫폼의 최소 루트 볼륨 크기를 수용해야 합니다.



NOTE: 4노드 절차는 8노드 구성에도 적용할 수 있습니다.
