---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: MetroCluster 하드웨어 유지보수 작업을 수행할 때는 올바른 절차를 선택해야 합니다. 
---
= MetroCluster 유지 관리 작업의 절차를 찾는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 하드웨어 유지보수 작업을 수행할 때는 올바른 절차를 선택해야 합니다.

.다양한 유형의 MetroCluster 구성에 대한 유지 관리 절차
* MetroCluster IP 구성을 사용하는 경우 의 절차를 link:task-modify-ip-netmask-properties.html["MetroCluster IP 구성에 대한 유지 관리 절차"]검토하십시오.
* MetroCluster FC 구성을 사용하는 경우 의 절차를 link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["MetroCluster FC 구성 유지 관리 절차"]검토하십시오.
* 구성에 대한 특정 섹션에서 절차를 찾을 수 없는 경우 의 절차를 검토하십시오link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["모든 MetroCluster 구성에 대한 유지 보수 절차"].


.기타 모든 유지보수 절차
다음 표에는 위에 나열된 세 섹션에 없는 MetroCluster 유지 보수 관련 절차에 대한 링크가 나와 있습니다.

|===


| 구성 요소 | MetroCluster 유형(FC 또는 IP) | 작업 | 절차를 참조하십시오 


 a| 
ONTAP 소프트웨어
 a| 
둘 다 해당되며
 a| 
ONTAP 소프트웨어 업그레이드
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["업그레이드, 되돌리기 또는 다운그레이드를 수행할 수 있습니다"^]



 a| 
컨트롤러 모듈
 a| 
둘 다 해당되며
 a| 
FRU 교체(컨트롤러 모듈, PCIe 카드, FC-VI 카드 등)


NOTE: MetroCluster 스토리지 시스템 간에 스토리지 컨트롤러 모듈 또는 NVRAM 카드를 이동하는 것은 지원되지 않습니다.
 a| 
https://docs.netapp.com/platstor/index.jsp["ONTAP 하드웨어 시스템 설명서"^]



 a| 
업그레이드 및 확장
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster 업그레이드 및 확장"]



 a| 
FC에서 IP 연결로 전환
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["MetroCluster FC에서 MetroCluster IP로 전환합니다"]



 a| 
드라이브 쉘프
 a| 
FC
 a| 
기타 모든 선반 정비 절차. 표준 절차를 사용할 수 있습니다.
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["DS460C DS224C 및 DS212C 디스크 쉘프를 유지합니다"^]



 a| 
IP
 a| 
모든 선반 정비 절차. 표준 절차를 사용할 수 있습니다.

미러링되지 않은 애그리게이트의 쉘프를 추가하는 경우 를 참조하십시오 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["미러링되지 않은 애그리게이트를 사용할 때의 고려 사항"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["DS460C DS224C 및 DS212C 디스크 쉘프를 유지합니다"^]



 a| 
둘 다 해당되며
 a| 
IOM6 쉘프 스택에 IOM12 쉘프를 핫 추가합니다
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["IOM6 모듈을 사용해 쉘프 스택에 IOM12 모듈을 장착한 상태로 쉘프 추가"^]

|===