---
permalink: maintain/reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, requirements, interfaces, fibrebridge, bridges, manage, configures 
summary: 직렬 포트, 텔넷 및 FTP의 조합을 사용하여 권장되는 관리 인터페이스 대신 FiberBridge 브리지를 관리할 수 있습니다. 브리지를 설치하기 전에 시스템이 해당 인터페이스의 요구 사항을 충족해야 합니다. 
---
= FiberBridge 브리지를 구성 및 관리하기 위한 다른 인터페이스 사용 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
직렬 포트, 텔넷 및 FTP의 조합을 사용하여 권장되는 관리 인터페이스 대신 FiberBridge 브리지를 관리할 수 있습니다. 브리지를 설치하기 전에 시스템이 해당 인터페이스의 요구 사항을 충족해야 합니다.

직렬 포트 또는 텔넷을 사용하여 브리지 및 이더넷 관리 1 포트를 구성하고 브리지를 관리할 수 있습니다. FTP를 사용하여 브리지 펌웨어를 업데이트할 수 있습니다.


NOTE: 모델 브리지의 _ATTO FiberBridge 설치 및 작동 설명서_에는 관리 인터페이스에 대한 자세한 정보가 나와 있습니다.

ATTO FibreBridge 설명 페이지에 제공된 링크를 사용하여 ATTO 웹 사이트에서 이 문서에 접근할 수 있습니다.



== 직렬 포트

직렬 포트를 사용하여 브리지를 구성 및 관리하고 이더넷 관리 1 포트를 구성하려면 시스템이 다음 요구 사항을 충족해야 합니다.

* 직렬 케이블(브리지 직렬 포트에서 설정에 사용하는 컴퓨터의 직렬(COM) 포트로 연결)
+
브리지 직렬 포트는 RJ-45이며 컨트롤러와 동일한 핀 아웃입니다.

* HyperTerminal, TeraTerm 또는 PuTTY와 같은 터미널 에뮬레이션 프로그램으로 콘솔에 액세스합니다
+
터미널 프로그램은 파일에 화면 출력을 기록할 수 있어야 합니다.





== 텔넷

텔넷을 사용하여 브리지를 구성 및 관리하는 경우 시스템은 다음 요구 사항을 충족해야 합니다.

* 직렬 케이블(브리지 직렬 포트에서 설정에 사용하는 컴퓨터의 직렬(COM) 포트로 연결)
+
브리지 직렬 포트는 RJ-45이며 컨트롤러와 동일한 핀 아웃입니다.

* (권장) 기본 사용자 이름과 암호가 아닌 사용자 이름 및 암호(브리지 액세스용)
* HyperTerminal, TeraTerm 또는 PuTTY와 같은 터미널 에뮬레이션 프로그램으로 콘솔에 액세스합니다
+
터미널 프로그램은 파일에 화면 출력을 기록할 수 있어야 합니다.

* 각 브리지의 이더넷 관리 1 포트에 대한 IP 주소, 서브넷 마스크 및 게이트웨이 정보




== FTP

FTP를 사용하여 브리지 펌웨어를 업데이트할 때 시스템은 다음 요구 사항을 충족해야 합니다.

* 표준 이더넷 케이블(브리지 이더넷 관리 1 포트에서 네트워크로 연결)
* (권장) 기본 사용자 이름과 암호가 아닌 사용자 이름 및 암호(브리지 액세스용)

