---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: MetroCluster IP 스위치에서 펌웨어 업그레이드 
---
= MetroCluster IP 스위치에서 펌웨어를 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 스위치에서 펌웨어를 업그레이드해야 할 수 있습니다.



== RCF가 지원되는지 확인합니다

ONTAP 버전 또는 스위치 펌웨어 버전을 변경하는 경우 해당 버전에 대해 지원되는 RCF(참조 구성 파일)가 있는지 확인해야 합니다. 이  도구를 사용하면 link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator 를 참조하십시오"^]구성에 맞는 올바른 RCF가 생성됩니다.

.단계
. 스위치에서 다음 명령을 사용하여 RCF 버전을 확인합니다.
+
[cols="30,70"]
|===


| 이 스위치에서... | 이 명령 실행... 


 a| 
Broadcom 스위치
 a| 
'(ip_switch_a_1)#show clibanner'



 a| 
Cisco 스위치
 a| 
'ip_switch_a_1#배너 mott'를 표시합니다



 a| 
NVIDIA SN2100 스위치
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
명령 출력에서 RCF 버전을 나타내는 줄을 찾습니다. 예를 들어, Cisco 스위치의 다음 출력은 RCF 버전이 "'v1.80'"임을 나타냅니다.

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. 특정 ONTAP 버전, 스위치 및 플랫폼에 대해 지원되는 파일을 확인하려면 를 link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["MetroCluster IP용 RcfFileGenerator입니다"^]사용합니다. 가지고 있거나 업그레이드하려는 구성에 대한 RCF를 생성할 수 있는 경우 지원됩니다.
. 스위치 펌웨어가 지원되는지 확인하려면 다음을 참조하십시오.
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^]






== 스위치 펌웨어를 업그레이드합니다

.이 작업에 대해
각 스위치에 대해 이 작업을 연속으로 반복해야 합니다.

link:enable-console-logging-before-maintenance.html["콘솔 로깅을 활성화합니다"] 이 작업을 수행하기 전에

[[step_1_fw_upgrade]]
.단계
. 구성 상태를 확인합니다.
+
.. 각 클러스터에서 MetroCluster가 정상 모드로 구성되어 있는지 확인합니다.
+
MetroCluster 쇼

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 각 노드에서 미러링이 활성화되어 있는지 확인합니다.
+
'MetroCluster node show'

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. MetroCluster 구성 요소가 정상인지 점검한다.
+
'MetroCluster check run

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
작업은 백그라운드에서 실행됩니다.

.. 를 누릅니다 `metrocluster check run` 작업이 완료되면 다음을 실행합니다.
+
MetroCluster 체크 쇼

+
약 5분 후 다음 결과가 표시됩니다.

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. 상태 경고가 없는지 확인합니다.
+
'시스템 상태 경고 표시



. 첫 번째 스위치에 소프트웨어를 설치합니다.
+

NOTE: 스위치에 스위치 소프트웨어를 설치하려면 switch_A_1, switch_B_1, switch_A_2, switch_B_2 순서로 설치해야 합니다.

+
스위치 유형이 Broadcom, Cisco 또는 NVIDIA인지 여부에 따라 관련 항목에서 스위치 소프트웨어 설치 단계를 따르십시오.

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["Broadcom 스위치 EFOS 소프트웨어를 다운로드하고 설치합니다"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["Cisco 스위치 NX-OS 소프트웨어를 다운로드하고 설치합니다"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["NVIDIA SN2100 스위치 Cumulus 소프트웨어를 다운로드하고 설치합니다"]


. 각 스위치에 대해 이전 단계를 반복합니다.
. 반복합니다 <<step_1_fw_upgrade,1단계>> 구성 상태를 확인합니다.

