---
permalink: maintain/task_add_remove_or_change_isl_ports_nondisruptively.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, remove, change, isl, ports, nondisruptively 
summary: ISL 포트를 추가, 제거 또는 변경해야 할 수 있습니다. 전용 ISL 포트를 공유 ISL 포트로 전환하거나 스위치에서 ISL 포트의 속도를 변경할 수 있습니다. 거리가 더 먼 ISL을 이동하는 경우 품질을 향상시키려면 속도가 더 빨라질 수 있습니다. 또한 하드웨어를 추가하거나 업그레이드하는 경우 ISL 포트의 속도를 높여 시스템 업그레이드를 활용하고 Cisco IP 스위치에 ISL을 추가해야 할 수 있습니다. 
---
= Cisco IP 스위치에서 ISL 포트를 중단 없이 추가, 제거 또는 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco IP 스위치에서 ISL 포트를 추가, 제거 또는 변경해야 할 수 있습니다. 전용 ISL 포트를 공유 ISL 포트로 변환하거나 Cisco IP 스위치에서 ISL 포트의 속도를 변경할 수 있습니다.

.이 작업에 대해
전용 ISL 포트를 공유 ISL 포트로 변환하는 경우 새 포트가 을 충족하는지 확인합니다 link:../install-ip/concept_considerations_layer_2.html["공유 ISL 포트에 대한 요구 사항"].

ISL 연결을 보장하려면 두 스위치 모두에서 모든 단계를 완료해야 합니다.

다음 절차에서는 스위치 포트 Eth1/24/1에 연결된 10Gb ISL을 스위치 포트 17 및 18에 연결된 두 개의 100-Gb ISL으로 교체하는 것으로 가정합니다.


NOTE: NS224 셸프를 연결하는 공유 구성에서 Cisco 9336C-FX2 스위치를 사용하는 경우 ISL을 변경하려면 새 RCF 파일이 필요할 수 있습니다. 현재 및 새 ISL 속도가 40Gbps 및 100Gbps인 경우에는 새 RCF 파일이 필요하지 않습니다. ISL 속도의 다른 모든 변경 사항에는 새 RCF 파일이 필요합니다. 예를 들어 ISL 속도를 40Gbps에서 100Gbps로 변경하는 경우 새 RCF 파일이 필요하지 않지만 ISL 속도를 10Gbps에서 40Gbps로 변경하려면 새 RCF 파일이 필요합니다.

.시작하기 전에
의 * 스위치 * 섹션을 참조하십시오 link:https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^] 지원되는 트랜시버를 확인합니다.

.단계
. 변경할 Fabric의 두 스위치 모두에서 ISL의 ISL 포트를 비활성화합니다.
+
--

NOTE: 다른 포트로 이동하거나 ISL의 속도가 변경되는 경우 현재 ISL 포트만 해제하면 됩니다. 기존 ISL과 속도가 동일한 ISL 포트를 추가하는 경우 3단계로 이동하십시오.

--
+
다음 예제와 같이 각 줄에 대해 하나의 구성 명령만 입력하고 모든 명령을 입력한 후 Ctrl-Z를 눌러야 합니다.

+
[listing]
----

switch_A_1# conf t
switch_A_1(config)# int eth1/24/1
switch_A_1(config-if)# shut
switch_A_1(config-if)#
switch_A_1#

switch_B_1# conf t
switch_B_1(config)# int eth1/24/1
switch_B_1(config-if)# shut
switch_B_1(config-if)#
switch_B_1#
----
. 기존 케이블 및 트랜시버를 제거합니다.
. 필요에 따라 ISL 포트를 변경합니다.
+

NOTE: NS224 셸프를 연결하는 공유 구성에서 Cisco 9336C-FX2 스위치를 사용하는 경우 RCF 파일을 업그레이드하고 새 ISL 포트에 대한 새 구성을 적용해야 하는 경우, 의 단계를 따릅니다 link:task_upgrade_rcf_files_on_mcc_ip_switches.html["MetroCluster IP 스위치에서 RCF 파일을 업그레이드합니다."]

+
[cols="30,70"]
|===


| 옵션을 선택합니다 | 단계 


 a| 
ISL 포트의 속도를 변경하려면...
 a| 
속도에 따라 새 ISL을 지정된 포트에 케이블로 연결합니다. 스위치의 ISL 포트가 _MetroCluster IP 설치 및 구성_에 나열되어 있는지 확인해야 합니다.



 a| 
ISL 추가...
 a| 
ISL 포트로 추가할 포트에 QFSP를 삽입합니다. MetroCluster IP 설치 및 구성_에 나열되어 있는지 확인하고 이에 따라 케이블을 연결합니다.

|===
. 다음 명령으로 시작되는 Fabric의 두 스위치 모두에서 모든 ISL 포트(활성화되지 않은 경우)를 설정합니다.
+
'스위치_A_1#설정 t'

+
모든 명령을 입력한 후 줄당 하나의 구성 명령만 입력하고 Ctrl-Z를 눌러야 합니다.

+
[listing]
----
switch_A_1# conf t
switch_A_1(config)# int eth1/17
switch_A_1(config-if)# no shut
switch_A_1(config-if)# int eth1/18
switch_A_1(config-if)# no shut
switch_A_1(config-if)#
switch_A_1#
switch_A_1# copy running-config startup-config

switch_B_1# conf t
switch_B_1(config)# int eth1/17
switch_B_1(config-if)# no shut
switch_B_1(config-if)# int eth1/18
switch_B_1(config-if)# no shut
switch_B_1(config-if)#
switch_B_1#
switch_B_1# copy running-config startup-config
----
. ISL과 ISL의 포트 채널이 두 스위치 간에 설정되었는지 확인합니다.
+
`switch_A_1# show int brief`

+
다음 예와 같이 명령 출력에 ISL 인터페이스가 표시되어야 합니다.

+
[listing]
----
Switch_A_1# show interface brief
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/17         1       eth  access down    XCVR not inserted        auto(D) --
Eth1/18         1       eth  access down    XCVR not inserted        auto(D) --

------------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                              Speed   Protocol
Interface
------------------------------------------------------------------------------------------
Po10         1       eth  trunk  up      none                                a-100G(D)  lacp
Po11         1       eth  trunk  up      none                                a-100G(D)  lacp
----
. 패브릭 2에 대해 이 절차를 반복합니다.

