---
permalink: maintain/task_fb_hot_add_a_disk_shelf_install_7500n.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, disk, shelf 
summary: 성능을 저하시키지 않고 스토리지를 증가하려는 경우 디스크 쉘프를 핫 추가할 수 있습니다. 
---
= 디스크 쉘프 핫 추가
:icons: font
:imagesdir: ../media/


[role="lead"]
성능을 저하시키지 않고 스토리지를 증가하려는 경우 디스크 쉘프를 핫 추가할 수 있습니다.

* 시스템은 의 모든 요구 사항을 충족해야 합니다 link:task_fb_hot_add_shelf_prepare_7500n.html["SAS 디스크 쉘프 핫 추가 준비"].
* 쉘프를 핫 애드할 경우 환경은 다음 시나리오 중 하나를 충족해야 합니다.
+
** 2개의 FiberBridge 7500N 브리지가 SAS 디스크 쉘프 스택에 연결되어 있습니다.
** 하나의 FiberBridge 7500N 브리지와 하나의 FiberBridge 6500N 브리지가 SAS 디스크 쉘프 스택에 연결되어 있습니다.
** 2개의 FiberBridge 6500N 브리지가 SAS 디스크 쉘프 스택에 연결되어 있습니다.


* 이 절차는 디스크 쉘프를 스택의 마지막 디스크 쉘프에 핫 추가하기 위한 것입니다.
+
이 절차는 스택의 마지막 디스크 쉘프가 IOM A에서 브리지 A로, IOM B에서 브리지 B로 연결된다고 가정하고 작성되었습니다

* 이는 무중단으로 수행할 수 있는 절차입니다.
* 각 사이트에서 동일한 수의 디스크 쉘프를 핫 추가해야 합니다.
* 둘 이상의 디스크 쉘프를 핫 추가할 경우, 한 번에 하나의 디스크 쉘프를 핫 추가해야 합니다.
+

NOTE: FiberBridge 7500N 또는 7600N 브리지의 각 쌍은 최대 4개의 스택을 지원할 수 있습니다.




IMPORTANT: 디스크 쉘프를 핫 추가하려면 고급 모드에서 '스토리지 디스크 펌웨어 업데이트' 명령을 실행하여 핫 추가 디스크 쉘프의 디스크 드라이브 펌웨어를 업데이트해야 합니다. 시스템의 기존 디스크 드라이브의 펌웨어가 이전 버전인 경우 이 명령을 실행하면 작업이 중단될 수 있습니다.


IMPORTANT: SAS 케이블을 잘못된 포트에 삽입한 경우 SAS 포트에서 케이블을 분리할 때 다른 SAS 포트에 케이블을 연결하기 전에 최소 120초 정도 기다려야 합니다. 그렇지 않으면 시스템이 케이블이 다른 포트로 이동되었음을 인식하지 못합니다.

.단계
. 적절하게 접지합니다.
. 다음 중 하나의 컨트롤러의 시스템 콘솔에서 디스크 쉘프의 연결을 확인합니다.
+
' * sysconfig-v * '

+
출력은 다음과 유사합니다.

+
** FiberBridge 7500N 브리지 세트에 디스크 쉘프를 핫 추가하면 다음과 같은 결과를 얻을 수 있습니다. 예를 들어, 개별 라인과 각 FC 포트 아래에 각 브리지가 표시됩니다.
+
[listing]
----
FC-to-SAS Bridge:
cisco_A_1-1:9.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100189
cisco_A_1-2:1.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100162
----
** 각 FC 포트 아래의 개별 행에 있는 각 디스크 쉘프:
+
[listing]
----
Shelf   0: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
Shelf   1: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
----
** 각 디스크 드라이브는 각 FC 포트 아래의 별도의 줄에 있으며 이 포트가 표시됩니다.
+
[listing]
----
cisco_A_1-1:9.126L1   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
cisco_A_1-1:9.126L2   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
----


. 시스템에 다음 중 하나의 컨트롤러의 콘솔에서 디스크 자동 할당이 활성화되었는지 확인합니다.
+
'* 스토리지 디스크 옵션 표시 *'

+
자동 할당 정책이 자동 할당 열에 표시됩니다.

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 시스템에 디스크 자동 할당이 설정되어 있지 않거나 동일한 스택에 있는 디스크 드라이브가 두 컨트롤러가 소유하는 경우 디스크 드라이브를 적절한 풀에 할당합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"]

+
[NOTE]
====
두 컨트롤러 사이에 단일 디스크 쉘프 스택을 분할하는 경우 디스크 소유권을 할당하기 전에 디스크 자동 할당을 비활성화해야 합니다. 그렇지 않으면 단일 디스크 드라이브를 할당할 때 나머지 디스크 드라이브가 동일한 컨트롤러 및 풀에 자동으로 할당될 수 있습니다.

'storage disk option modify -node_node -name_ -autoassign off' 명령은 디스크 자동 할당을 비활성화합니다.

====
+

NOTE: 디스크 드라이브 및 디스크 쉘프 펌웨어가 업데이트될 때까지 디스크 드라이브를 애그리게이트 또는 볼륨에 추가할 수 없습니다.

. 다운로드한 펌웨어의 지침을 사용하여 디스크 쉘프 펌웨어를 최신 버전으로 업데이트합니다.
+
두 컨트롤러의 시스템 콘솔에서 절차의 명령을 실행할 수 있습니다.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"]

. 디스크 쉘프 설치 및 케이블 연결:
+
다음 사항을 고려하십시오.

+
** FiberBridge 6500N 브리지의 경우:
+
포트를 연결하기 전에 10초 이상 기다립니다. SAS 케이블 커넥터는 SAS 포트에 올바르게 꽂으면 딸깍 소리가 나면서 제자리에 끼며 디스크 쉘프 SAS 포트 LNK LED가 녹색으로 켜집니다. 디스크 쉘프의 경우 풀 탭이 아래로 향하게 하여 커넥터 아래쪽에 있는 SAS 케이블 커넥터를 삽입합니다.

** FiberBridge 7500N 브리지의 경우:
+
커넥터를 포트에 억지로 밀어 넣지 마십시오. 미니 SAS 케이블은 SAS 포트에 올바르게 연결될 때 딸깍 소리가 나면서 제자리에 고정되며 디스크 쉘프 SAS 포트 LNK LED가 녹색으로 켜집니다. 디스크 쉘프의 경우 풀 탭이 위로 향하게 SAS 케이블 커넥터를 삽입합니다(커넥터 윗면에 있음).

+
... 디스크 쉘프를 설치하고 전원을 켠 다음 쉘프 ID를 설정합니다.
+
디스크 쉘프 설치에 대한 자세한 내용은 디스크 쉘프 모델의 _설치 가이드_를 참조하십시오.

+

NOTE: 디스크 쉘프의 전원을 껐다가 켠 후 전체 스토리지 시스템 내에서 각 SAS 디스크 쉘프의 쉘프 ID를 고유하게 유지해야 합니다.

... 스택의 마지막 쉘프 IOM B 포트에서 SAS 케이블을 분리한 다음 새 쉘프의 같은 포트에 다시 연결합니다.
+
이 케이블의 다른 쪽 끝은 브리지 B에 연결되어 있습니다

... IOM A 및 IOM B의 새 쉘프 IOM 포트(IOM A 및 IOM B)를 마지막 쉘프 IOM 포트(IOM A 및 IOM B)에 연결하여 새 디스크 쉘프를 데이지 체인 방식으로 연결합니다.




+
디스크 쉘프 모델의 _설치 가이드_에서 디스크 쉘프 데이지 체인 방식으로 연결되는 방법에 대한 자세한 정보를 얻을 수 있습니다.

. 시스템 콘솔에서 디스크 드라이브 펌웨어를 최신 버전으로 업데이트합니다.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"]

+
.. 고급 권한 수준으로 변경: + " * set-privilege advanced * "
+
고급 모드로 계속 진행하고 고급 모드 프롬프트(*>)를 보려면 "* y*"로 응답해야 합니다.

.. 시스템 콘솔에서 디스크 드라이브 펌웨어를 최신 버전으로 업데이트합니다: + " * 스토리지 디스크 펌웨어 업데이트 * "
.. 관리자 권한 수준(+' * set-privilege admin * ')으로 돌아갑니다
.. 다른 컨트롤러에서 이전 하위 단계를 반복합니다.


. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템에 다중 경로 가 있는지 확인합니다.
+
' * node run-node_node-name_sysconfig-a * '

.. 두 클러스터에 대한 상태 경고(+' * system health alert show * ')가 있는지 확인합니다
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 확인합니다. + " * MetroCluster show * "
.. MetroCluster check 수행: + ` * MetroCluster check run * '
.. MetroCluster 검사 결과를 표시합니다.
+
``MetroCluster CHOK SHOW *’’

.. 스위치에 대한 상태 경고를 확인합니다(있는 경우).
+
'* 스토리지 스위치 쇼 * '

.. Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.


. 디스크 쉘프를 하나 이상 핫 추가할 경우, 핫 추가할 각 디스크 쉘프에 대해 이전 단계를 반복합니다.

