---
permalink: maintain/task_move_a_metadata_volume_in_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, move, metadata, volume, configuration 
summary: MetroCluster 구성에서 메타데이터 볼륨을 한 Aggregate에서 다른 aggregate로 이동할 수 있습니다. 소스 애그리게이터가 사용 중지되거나 미러링되지 않은 경우 또는 애그리게이트에 적합하지 않은 다른 이유로 메타데이터 볼륨을 이동할 수 있습니다. 
---
= MetroCluster 구성에서 메타데이터 볼륨 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성에서 메타데이터 볼륨을 한 Aggregate에서 다른 aggregate로 이동할 수 있습니다. 소스 애그리게이터가 사용 중지되거나 미러링되지 않은 경우 또는 애그리게이트에 적합하지 않은 다른 이유로 메타데이터 볼륨을 이동할 수 있습니다.

* 이 작업을 수행하려면 클러스터 관리자 권한이 있어야 합니다.
* 대상 애그리게이트는 미러링되어야 하며 성능 저하 상태가 아니어야 합니다.
* 타겟 Aggregate의 사용 가능한 공간은 이동 중인 메타데이터 볼륨보다 커야 합니다.


.단계
. 권한 수준을 고급으로 설정합니다.
+
' * set-Privilege advanced * '

. 이동할 메타데이터 볼륨 식별:
+
'* 볼륨 표시 MDV_CRS**'

+
[listing]
----
Cluster_A::*> volume show MDV_CRS*
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
Cluster_A
          MDV_CRS_14c00d4ac9f311e7922800a0984395f1_A
                       Node_A_1_aggr1
                                    online     RW         10GB     9.50GB    5%
Cluster_A
          MDV_CRS_14c00d4ac9f311e7922800a0984395f1_B
                       Node_A_2_aggr1
                                    online     RW         10GB     9.50GB    5%
Cluster_A
          MDV_CRS_15035e66c9f311e7902700a098439625_A
                       Node_B_1_aggr1
                                    -          RW            -          -     -
Cluster_A
          MDV_CRS_15035e66c9f311e7902700a098439625_B
                       Node_B_2_aggr1
                                    -          RW            -          -     -
4 entries were displayed.

Cluster_A::>
----
. 적합한 대상 애그리게이트 식별:
+
`* MetroCluster check config-replication show-aggregate-eligibility * '

+
다음 명령을 실행하면 메타데이터 볼륨을 호스팅할 수 있는 cluster_A의 애그리게이트를 식별할 수 있습니다.

+
[listing]
----

Cluster_A::*> metrocluster check config-replication show-aggregate-eligibility

Aggregate Hosted Config Replication Vols Host Addl Vols Comments
------------ ------------------------------------------ -------------- --------
Node_A_1_aggr0 - false Root Aggregate
Node_A_2_aggr0 - false Root Aggregate
Node_A_1_aggr1 MDV_CRS_1bc7134a5ddf11e3b63f123478563412_A true -
Node_A_2_aggr1 MDV_CRS_1bc7134a5ddf11e3b63f123478563412_B true -
Node_A_1_aggr2 - true
Node_A_2_aggr2 - true
Node_A_1_Aggr3 - false Unable to determine available space of aggregate
Node_A_1_aggr5 - false Unable to determine mirror configuration
Node_A_2_aggr6 - false Mirror configuration does not match requirement
Node_B_1_aggr4 - false NonLocal Aggregate
----
+

NOTE: 이전 예에서는 Node_A_1_aggr2 및 Node_A_2_aggr2를 사용할 수 있습니다.

. 볼륨 이동 작업을 시작합니다.
+
'* volume move start -vserver_svm_name_-volume_metadata_volume_name_-destination-aggregate_destination_name_*'

+
다음 명령을 실행하면 메타데이터 볼륨 MDV_CRS_14c00d4ac9f311e7922800a0984395F1이 집계 Node_A_1_aggr1에서 집계 Node_A_1_aggr2로 이동합니다.

+
[listing]
----
Cluster_A::*> volume move start -vserver svm_cluster_A -volume MDV_CRS_14c00d4ac9f311e7922800a0984395f1
-destination-aggregate aggr_cluster_A_02_01

Warning: You are about to modify the system volume
         "MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A".  This may cause severe
         performance or stability problems.  Do not proceed unless directed to
         do so by support.  Do you want to proceed? {y|n}: y
[Job 109] Job is queued: Move "MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A" in Vserver
"svm_cluster_A" to aggregate "aggr_cluster_A_02_01".
Use the "volume move show -vserver svm_cluster_A -volume
MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A" command to view the status of this operation.
----
. 볼륨 이동 작업의 상태를 확인합니다.
+
' * volume move show -volume vol_f성분_이름 * '

. 관리자 권한 레벨로 돌아갑니다.
+
' * set-privilege admin * '


