---
permalink: maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, downgrade, firmware, brocade, fc, switch 
summary: Brocade FC 스위치에서 펌웨어를 업그레이드하거나 다운그레이드하려면 Brocade 관련 명령을 사용하여 스위치를 비활성화하고 펌웨어 변경을 수행 및 확인하고 스위치를 재부팅 및 다시 활성화해야 합니다. 
---
= Brocade FC 스위치에서 펌웨어 업그레이드 또는 다운그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Brocade FC 스위치에서 펌웨어를 업그레이드하거나 다운그레이드하려면 Brocade 관련 명령을 사용하여 스위치를 비활성화하고 펌웨어 변경을 수행 및 확인하고 스위치를 재부팅 및 다시 활성화해야 합니다.

* 펌웨어 파일이 있어야 합니다.
* 시스템의 케이블이 올바르게 연결되어 있어야 합니다.
* 스토리지 쉘프에 대한 모든 경로를 사용할 수 있어야 합니다.
* 디스크 쉘프 스택은 안정적이어야 합니다.
* FC 스위치 패브릭은 양호한 상태여야 합니다.
* 시스템에 장애가 발생한 구성 요소가 없을 수 있습니다.
* 시스템이 정상적으로 작동해야 합니다.
* FTP 또는 SCP 서버에 대한 관리자 암호 및 액세스 권한이 있어야 합니다.


펌웨어 업그레이드 또는 다운그레이드 중에는 스위치 패브릭을 사용할 수 없으며 MetroCluster 구성은 두 번째 Fabric에 의존하여 작업을 계속합니다.

이 작업은 모든 스위치가 동일한 펌웨어 버전을 실행할 수 있도록 각 스위치 Fabric에 대해 연속적으로 수행해야 합니다.


NOTE: 이 절차는 무중단으로 진행되며 완료까지 약 1시간이 소요됩니다.

.단계
. Fabric의 각 스위치에 로그인합니다.
+
다음 단계의 예에서는 스위치 FC_SWITCH_A_1을 사용합니다.

. Fabric의 각 스위치를 해제합니다.
+
'* switchCfgPersistentDisable*'

+
이 명령어를 사용할 수 없으면 'witchDisable' 명령어를 실행한다.

+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----
. 원하는 펌웨어 버전을 다운로드합니다.
+
'* firmwaredownload*'

+
파일 이름을 묻는 메시지가 나타나면 펌웨어 파일의 하위 디렉토리 또는 상대 경로를 지정해야 합니다.

+
두 스위치에서 "firmwaredownload" 명령을 동시에 실행할 수 있지만 다음 단계로 이동하기 전에 펌웨어를 제대로 다운로드하고 커밋하도록 허용해야 합니다.

+
[listing]
----
FC_switch_A_1:admin> firmwaredownload
Server Name or IP Address: 10.64.203.188
User Name: test
File Name: v7.3.1b
Network Protocol(1-auto-select, 2-FTP, 3-SCP, 4-SFTP) [1]: 2
Password:
Server IP: 10.64.203.188, Protocol IPv4
Checking system settings for firmwaredownload...
System settings check passed.
----
. 펌웨어가 다운로드되고 두 파티션에 커밋되었는지 확인합니다.
+
' * firmwareshweshwHow * '

+
다음 예에서는 두 이미지가 모두 업데이트되므로 펌웨어 다운로드가 완료되었음을 보여 줍니다.

+
[listing]
----
FC_switch_A_1:admin> firmwareShow
Appl     Primary/Secondary Versions

------------------------------------------

FOS      v7.3.1b

         v7.3.1b
----
. 스위치를 재부팅합니다.
+
'* 재부팅 * '

+
일부 펌웨어 버전은 펌웨어 다운로드가 완료된 후 haReboot 작업을 자동으로 수행합니다. haReboot를 수행한 경우에도 이 단계의 재부팅이 필요합니다.

+
[listing]
----
FC_switch_A_1:admin> reboot
----
. 새 펌웨어가 중간 펌웨어 버전인지 또는 최종 지정된 릴리스에 대한 펌웨어인지 확인합니다.
+
중간 펌웨어 버전용 다운로드인 경우, 지정된 릴리스가 설치될 때까지 이전 두 단계를 수행합니다.

. 스위치 활성화:
+
'* switchCfgPersistentEnable*'

+
이 명령어를 사용할 수 없는 경우 reboot 명령어가 실행된 후 스위치가 enabled 상태여야 한다.

+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentEnable
----
. 스위치가 온라인 상태이고 모든 장치가 제대로 로그인되었는지 확인합니다.
+
``switchshow *’’입니다

+
[listing]
----
FC_switch_A_1:admin> switchShow
----
. 포트 그룹 또는 스위치의 모든 포트 그룹에 대한 버퍼 사용 정보가 올바르게 표시되는지 확인합니다.
+
``포르피버쇼 *’

+
[listing]
----
FC_switch_A_1:admin> portbuffershow
----
. 포트의 현재 구성이 올바르게 표시되는지 확인합니다.
+
'* portcfgshow *'

+
[listing]
----
FC_switch_A_1:admin> portcfgshow
----
+
속도, 모드, 트렁킹, 암호화와 같은 포트 설정을 확인합니다. 그리고 ISL(Inter-Switch Link) 출력에 압축 기능이 포함되어 있습니다. 포트 설정이 펌웨어 다운로드의 영향을 받지 않았는지 확인합니다.

. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템이 다중 경로로 지정되었는지 확인합니다. + " * node run-node_node -name_sysconfig -a * "
.. 두 클러스터에 대한 상태 경고(+' * system health alert show * ')가 있는지 확인합니다
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 확인합니다. + " * MetroCluster show * "
.. MetroCluster check 수행: + ` * MetroCluster check run * '
.. MetroCluster check 결과 표시: + ` * MetroCluster check show * '
.. 스위치에 대한 상태 경고(있는 경우)가 있는지 확인합니다. + " * storage switch show * "
.. Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.


. 15분 후에 두 번째 스위치 패브릭에서 이 절차를 반복합니다.

