---
permalink: maintain/task_fb_hot_add_a_disk_shelf_install_7500n.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, disk, shelf 
summary: 성능을 저하시키지 않고 스토리지를 증가하려는 경우 디스크 쉘프를 핫 추가할 수 있습니다. 
---
= SAS 디스크 쉘프 스택에 SAS 디스크 쉘프를 핫 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능을 저하시키지 않고 스토리지를 증가하려는 경우 디스크 쉘프를 핫 추가할 수 있습니다.



== 1단계: SAS 디스크 쉘프를 핫 추가할 준비를 합니다

SAS 디스크 쉘프의 핫 추가를 준비하려면 디스크 드라이브 및 디스크 쉘프 펌웨어와 함께 문서를 다운로드해야 합니다.

.시작하기 전에
* 시스템이 지원되는 구성이고 지원되는 ONTAP 버전을 실행하고 있는지 확인합니다.
* 시스템의 모든 디스크 드라이브 및 디스크 쉘프에서 최신 펌웨어 버전이 실행되고 있는지 확인합니다.
+
쉘프를 추가하기 전에 MetroCluster 구성 전반에서 디스크 및 쉘프 펌웨어를 업데이트할 수 있습니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["업그레이드, 되돌리기 또는 다운그레이드를 수행할 수 있습니다"]



[NOTE]
====
시스템에서 지원되는 ONTAP 버전을 실행하는 경우 동일한 스택 내에서 IOM12 모듈과 IOM6 모듈을 함께 사용할 수 있습니다. ONTAP 버전에서 쉘프 혼합을 지원하는지 확인하려면 을 link:https://imt.netapp.com/matrix/["상호 운용성 매트릭스 툴(IMT)"^]참조하십시오. 사용 중인 ONTAP 버전이 지원되지 않고 기존 스택이나 지원되는 IOM 모듈 조합에 추가할 새 쉘프에서 IOM 모듈을 업그레이드하거나 다운그레이드할 수 없는 경우 다음 중 하나를 수행해야 합니다.

* 새 SAS 포트에서 새 스택을 시작합니다(브리지 페어에서 지원되는 경우).
* 추가 브리지 쌍에서 새 스택을 시작합니다.


====
.단계
. NetApp Support 사이트에서 다음 문서를 다운로드하거나 볼 수 있습니다.
+
** https://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴"]
** 디스크 쉘프 모델의 _설치 가이드_를 참조하십시오.


. 추가하고 있는 디스크 쉘프가 지원되는지 확인하십시오.
+
https://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴"^]

. 최신 디스크 및 디스크 쉘프 펌웨어 다운로드:
+

NOTE: 이 단계에서는 지침의 다운로드 부분만 완료합니다. 의 단계에 따라 디스크 쉘프를 설치해야 <<step_2_hot_add_shelf,디스크 쉘프를 핫 추가합니다>>합니다.

+
.. 디스크 펌웨어를 다운로드하고 나중에 참조할 수 있도록 디스크 펌웨어 지침 사본을 만듭니다.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"^]

.. 디스크 쉘프 펌웨어를 다운로드하고 나중에 참조할 수 있도록 디스크 쉘프 펌웨어 지침의 복사본을 만드십시오.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"^]







== 2단계: 디스크 쉘프를 핫 추가

다음 절차를 사용하여 디스크 쉘프를 스택에 핫 추가합니다.

.시작하기 전에
* 시스템이 의 모든 요구 사항을 충족하는지 <<prepare_to_hot_add_disk,핫 추가 SAS 디스크 쉘프를 준비합니다>>확인합니다.
* 쉘프를 핫 추가하기 전에 환경이 다음 시나리오 중 하나를 충족하는지 확인하십시오.
+
** 2개의 FiberBridge 7500N 브리지가 SAS 디스크 쉘프 스택에 연결되어 있습니다.
** SAS 디스크 쉘프 스택에 연결되는 FiberBridge 7600N 브리지 2개를 사용할 수 있습니다.
** SAS 디스크 쉘프 스택에 FibreBridge 7500N 브리지 1개와 FibreBridge 7600N 브리지 1개를 연결할 수 있습니다.




.이 작업에 대해
* 이 절차는 디스크 쉘프를 스택의 마지막 디스크 쉘프에 핫 추가하기 위한 것입니다.
+
이 절차는 스택의 마지막 디스크 쉘프가 IOM A에서 브리지 A로, IOM B에서 브리지 B로 연결된다고 가정하고 작성되었습니다

* 이는 무중단으로 수행할 수 있는 절차입니다.
* 각 사이트에서 동일한 수의 디스크 쉘프를 핫 추가해야 합니다.
* 둘 이상의 디스크 쉘프를 핫 추가할 경우, 한 번에 하나의 디스크 쉘프를 핫 추가해야 합니다.
+
FiberBridge 7500N 또는 7600N 브리지의 각 쌍은 최대 4개의 스택을 지원할 수 있습니다.



[CAUTION]
====
디스크 쉘프를 핫 추가하려면 고급 모드에서 '스토리지 디스크 펌웨어 업데이트' 명령을 실행하여 핫 추가 디스크 쉘프의 디스크 드라이브 펌웨어를 업데이트해야 합니다. 시스템의 기존 디스크 드라이브의 펌웨어가 이전 버전인 경우 이 명령을 실행하면 작업이 중단될 수 있습니다.

SAS 케이블을 잘못된 포트에 삽입한 경우, SAS 포트에서 케이블을 분리한 후 120초 이상 기다린 후 다른 SAS 포트에 케이블을 연결해야 합니다. 그렇게 하지 않으면 시스템에서 케이블을 다른 포트로 이동한 것을 인식하지 못합니다.

====
.단계
. 적절하게 접지합니다.
. 다음 중 하나의 컨트롤러의 시스템 콘솔에서 디스크 쉘프의 연결을 확인합니다.
+
'Sysconfig-v'입니다

+
출력은 다음과 유사합니다.

+
** FiberBridge 7500N 브리지 세트에 디스크 쉘프를 핫 추가하면 다음과 같은 결과를 얻을 수 있습니다. 예를 들어, 개별 라인과 각 FC 포트 아래에 각 브리지가 표시됩니다.
+
[listing]
----
FC-to-SAS Bridge:
cisco_A_1-1:9.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100189
cisco_A_1-2:1.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100162
----
** 각 FC 포트 아래의 개별 행에 있는 각 디스크 쉘프:
+
[listing]
----
Shelf   0: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
Shelf   1: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
----
** 각 디스크 드라이브는 각 FC 포트 아래의 별도의 줄에 있으며 이 포트가 표시됩니다.
+
[listing]
----
cisco_A_1-1:9.126L1   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
cisco_A_1-1:9.126L2   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
----


. 시스템에 두 컨트롤러 중 하나의 콘솔에서 디스크 자동 할당이 활성화되어 있는지 확인합니다.
+
'스토리지 디스크 옵션 표시'

+
자동 할당 정책이 자동 할당 열에 표시됩니다.

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 시스템에 디스크 자동 할당이 활성화되어 있지 않거나 동일한 스택에 있는 디스크 드라이브가 두 컨트롤러 모두에 의해 소유된 경우 디스크 드라이브를 적절한 풀에 할당합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"]

+
[NOTE]
====
** 두 컨트롤러 간에 단일 디스크 쉘프 스택을 분할하는 경우, 디스크 소유권을 할당하기 전에 디스크 자동 할당을 해제해야 합니다. 그렇지 않으면 단일 디스크 드라이브를 할당할 때 나머지 디스크 드라이브가 동일한 컨트롤러 및 풀에 자동으로 할당될 수 있습니다.
+
 `storage disk option modify -node <node-name> -autoassign off`명령을 실행하면 디스크 자동 할당이 비활성화됩니다.

** 디스크 드라이브 및 디스크 쉘프 펌웨어를 업데이트할 때까지 드라이브를 Aggregate 또는 볼륨에 추가할 수 없습니다.


====
. 다운로드한 펌웨어의 지침을 사용하여 디스크 쉘프 펌웨어를 최신 버전으로 업데이트합니다.
+
두 컨트롤러의 시스템 콘솔에서 절차의 명령을 실행할 수 있습니다.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"]

. 디스크 쉘프 설치 및 케이블 연결:
+

NOTE: 커넥터를 포트에 억지로 밀어 넣지 마십시오. 미니 SAS 케이블은 SAS 포트에 올바르게 연결될 때 딸깍 소리가 나면서 제자리에 고정되며 디스크 쉘프 SAS 포트 LNK LED가 녹색으로 켜집니다. 디스크 쉘프의 경우 풀 탭이 위로 향하게 SAS 케이블 커넥터를 삽입합니다(커넥터 윗면에 있음).

+
.. 디스크 쉘프를 설치하고 전원을 켠 다음 쉘프 ID를 설정합니다.
+
디스크 쉘프 설치에 대한 자세한 내용은 디스크 쉘프 모델의 _설치 가이드_를 참조하십시오.

+

NOTE: 디스크 쉘프의 전원을 껐다가 켠 후 전체 스토리지 시스템 내에서 각 SAS 디스크 쉘프의 쉘프 ID를 고유하게 유지해야 합니다.

.. 스택의 마지막 쉘프 IOM B 포트에서 SAS 케이블을 분리한 다음 새 쉘프의 같은 포트에 다시 연결합니다.
+
이 케이블의 다른 쪽 끝은 브리지 B에 연결되어 있습니다

.. IOM A 및 IOM B의 새 쉘프 IOM 포트(IOM A 및 IOM B)를 마지막 쉘프 IOM 포트(IOM A 및 IOM B)에 연결하여 새 디스크 쉘프를 데이지 체인 방식으로 연결합니다.


+
디스크 쉘프 모델의 _설치 가이드_에서 디스크 쉘프 데이지 체인 방식으로 연결되는 방법에 대한 자세한 정보를 얻을 수 있습니다.

. 시스템 콘솔에서 디스크 드라이브 펌웨어를 최신 버전으로 업데이트합니다.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"]

+
.. advanced 권한 수준으로 변경합니다. +
`set -privilege advanced`
+
고급 모드로 계속 진행하고 고급 모드 프롬프트(*>)를 보려면 "* y*"로 응답해야 합니다.

.. 시스템 콘솔에서 디스크 드라이브 펌웨어를 최신 버전으로 업데이트합니다. +
`storage disk firmware update`
.. 관리자 권한 수준으로 돌아가기: + 'Set-Privilege admin
.. 다른 컨트롤러에서 이전 하위 단계를 반복합니다.


. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템에 다중 경로 가 있는지 확인합니다.
+
`node run -node <node-name> sysconfig -a`

.. 두 클러스터에 대한 상태 알림이 있는지 확인합니다. + 'system health alert show'
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 확인합니다. + 'MetroCluster show'
.. MetroCluster check 수행: + 'MetroCluster check run
.. MetroCluster 검사 결과를 표시합니다.
+
MetroCluster 체크 쇼

.. 스위치에 대한 상태 경고를 확인합니다(있는 경우).
+
'스토리지 스위치 쇼'

.. Active IQ Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.


. 핫 추가할 디스크 쉘프가 2개 이상인 경우, 핫 애드할 각 디스크 쉘프에 대해 이전 단계를 반복합니다.

