---
permalink: maintain/task_replace_a_sle_fc_to_sas_bridge.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, replace, single, fc, sas, bridge 
summary: 브리지를 동일한 모델 브리지로 또는 새 모델 브리지로 중단 없이 교체할 수 있습니다. 
---
= 단일 FC-to-SAS 브릿지 교체
:icons: font
:imagesdir: ../media/


[role="lead"]
브리지를 동일한 모델 브리지로 또는 새 모델 브리지로 중단 없이 교체할 수 있습니다.

FTP 또는 SCP 서버에 대한 액세스 및 관리자 암호가 필요합니다.

이 절차는 무중단으로 진행되며 완료까지 약 60분이 소요됩니다.

이 절차에서는 브리지 CLI를 사용하여 브리지를 구성 및 관리하고 브리지 펌웨어 및 ATTO Quicknav 유틸리티를 업데이트하여 브리지 이더넷 관리 1 포트를 구성합니다. 요구 사항을 충족하는 다른 인터페이스를 사용할 수 있습니다.

link:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html["FiberBridge 브리지를 구성 및 관리하기 위한 다른 인터페이스 사용 요구 사항"]

link:task_fb_consolidate_replace_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.html["FiberBridge 6500N 브리지 쌍을 7600N 또는 7500N 브리지로 교체"]



== 스토리지 접속을 확인하는 중입니다

브리지를 교체하기 전에 브리지 및 스토리지 연결을 확인해야 합니다. 명령 출력에 익숙해질 경우 구성을 변경한 후 나중에 연결을 확인할 수 있습니다.

유지보수 중인 사이트의 MetroCluster 구성에 있는 컨트롤러 모듈의 admin 프롬프트에서 이러한 명령을 실행할 수 있습니다.

.단계
. MetroCluster 노드 중 하나에 다음 명령을 입력하여 디스크 연결을 확인합니다.
+
로컬 sysconfig -v를 실행합니다

+
이 출력에서는 컨트롤러의 이니시에이터 포트에 연결된 디스크를 표시하고 FC-to-SAS 브리지에 연결된 쉘프를 식별합니다.

+
[listing]
----

node_A_1> run local sysconfig -v
NetApp Release 9.3.2X18: Sun Dec 13 01:23:24 PST 2017
System ID: 4068741258 (node_A_1); partner ID: 4068741260 (node_B_1)
System Serial Number: 940001025471 (node_A_1)
System Rev: 70
System Storage Configuration: Multi-Path HA**<=== Configuration should be multi-path HA**
.
.
.
slot 0: FC Host Adapter 0g (QLogic 8324 rev. 2, N-port, <UP>)**<=== Initiator port**
		Firmware rev:      7.5.0
		Flash rev:         0.0.0
		Host Port Id:      0x60130
		FC Node Name:      5:00a:098201:bae312
		FC Port Name:      5:00a:098201:bae312
		SFP Vendor:        UTILITIES CORP.
		SFP Part Number:   FTLF8529P3BCVAN1
		SFP Serial Number: URQ0Q9R
		SFP Capabilities:  4, 8 or 16 Gbit
		Link Data Rate:    16 Gbit
		Switch Port:       brcd6505-fcs40:1
  **<List of disks visible to port\>**
		 ID     Vendor   Model            FW    Size
		brcd6505-fcs29:12.126L1527     : NETAPP   X302_HJUPI01TSSM NA04 847.5GB (1953525168 512B/sect)
		brcd6505-fcs29:12.126L1528     : NETAPP   X302_HJUPI01TSSA NA02 847.5GB (1953525168 512B/sect)
		.
		.
		.
		**<List of FC-to-SAS bridges visible to port\>**
		FC-to-SAS Bridge:
		brcd6505-fcs40:12.126L0        : ATTO     FibreBridge6500N 1.61  FB6500N102980
		brcd6505-fcs42:13.126L0        : ATTO     FibreBridge6500N 1.61  FB6500N102980
		brcd6505-fcs42:6.126L0         : ATTO     FibreBridge6500N 1.61  FB6500N101167
		brcd6505-fcs42:7.126L0         : ATTO     FibreBridge6500N 1.61  FB6500N102974
		.
		.
		.
  **<List of storage shelves visible to port\>**
		brcd6505-fcs40:12.shelf6: DS4243  Firmware rev. IOM3 A: 0200  IOM3 B: 0200
		brcd6505-fcs40:12.shelf8: DS4243  Firmware rev. IOM3 A: 0200  IOM3 B: 0200
		.
		.
		.
----




== 동일한 모델의 교체 브리지로 브리지를 핫 스왑하는 경우

장애가 발생한 브리지를 동일한 모델의 다른 브리지로 핫 스왑할 수 있습니다.

IP 관리 대신 브리지의 대역 내 관리를 사용하는 경우 관련 단계에 설명된 대로 이더넷 포트 및 IP 설정 구성 단계를 건너뛸 수 있습니다.


NOTE: ONTAP 9.8부터 스토리지 브리지 명령이 시스템 브리지로 바뀌었습니다. 다음 단계에서는 'Storage bridge' 명령어를 보여주지만, ONTAP 9.8 이상을 실행 중인 경우에는 'system bridge' 명령어를 사용한다.

.단계
. 이전 브리지에 액세스할 수 있는 경우 구성 정보를 검색할 수 있습니다.
+
[cols="35,65"]
|===


| 만약... | 그러면... 


 a| 
* IP 관리 * 를 사용하고 있습니다
 a| 
텔넷 연결을 사용하여 이전 브리지에 연결하고 브리지 구성의 출력을 복사합니다.



 a| 
* 대역내 관리를 사용하고 있습니다 *
 a| 
ONTAP CLI를 사용하여 다음 명령으로 구성 정보를 검색할 수 있습니다.

'Storage bridge run-cli-name_bridge-name_-command "info"

'Storage bridge run-cli-name_bridge-name_-command "sasportlist"

|===
+
.. 다음 명령을 입력합니다.
+
'Storage bridge run-cli-name bridge_a1 - command "info"

+
[listing]
----
info

Device Status         = Good
Unsaved Changes       = None
Device                = "FibreBridge 7500N"
Serial Number         = FB7500N100000
Device Version        = 3.10
Board Revision        = 7
Build Number          = 007A
Build Type            = Release
Build Date            = "Aug 20 2019" 11:01:24
Flash Revision        = 0.02
Firmware Version      = 3.10
BCE Version (FPGA 1)  = 15
BAU Version (FPGA 2)  = 33
User-defined name     = "bridgeA1"
World Wide Name       = 20 00 00 10 86 A1 C7 00
MB of RAM Installed   = 512
FC1 Node Name         = 20 00 00 10 86 A1 C7 00
FC1 Port Name         = 21 00 00 10 86 A1 C7 00
FC1 Data Rate         = 16Gb
FC1 Connection Mode   = ptp
FC1 FW Revision       = 11.4.337.0
FC2 Node Name         = 20 00 00 10 86 A1 C7 00
FC2 Port Name         = 22 00 00 10 86 A1 C7 00
FC2 Data Rate         = 16Gb
FC2 Connection Mode   = ptp
FC2 FW Revision       = 11.4.337.0
SAS FW Revision       = 3.09.52
MP1 IP Address        = 10.10.10.10
MP1 IP Subnet Mask    = 255.255.255.0
MP1 IP Gateway        = 10.10.10.1
MP1 IP DHCP           = disabled
MP1 MAC Address       = 00-10-86-A1-C7-00
MP2 IP Address        = 0.0.0.0 (disabled)
MP2 IP Subnet Mask    = 0.0.0.0
MP2 IP Gateway        = 0.0.0.0
MP2 IP DHCP           = enabled
MP2 MAC Address       = 00-10-86-A1-C7-01
SNMP                  = enabled
SNMP Community String = public
PS A Status           = Up
PS B Status           = Up
Active Configuration  = NetApp

Ready.
----
.. 다음 명령을 입력합니다.
+
'Storage bridge run-cli-name bridge_A1 - 명령 "sasportlist"

+
[listing]
----


SASPortList

;Connector      PHY     Link            Speed   SAS Address
;=============================================================
Device  A       1       Up              6Gb     5001086000a1c700
Device  A       2       Up              6Gb     5001086000a1c700
Device  A       3       Up              6Gb     5001086000a1c700
Device  A       4       Up              6Gb     5001086000a1c700
Device  B       1       Disabled        12Gb    5001086000a1c704
Device  B       2       Disabled        12Gb    5001086000a1c704
Device  B       3       Disabled        12Gb    5001086000a1c704
Device  B       4       Disabled        12Gb    5001086000a1c704
Device  C       1       Disabled        12Gb    5001086000a1c708
Device  C       2       Disabled        12Gb    5001086000a1c708
Device  C       3       Disabled        12Gb    5001086000a1c708
Device  C       4       Disabled        12Gb    5001086000a1c708
Device  D       1       Disabled        12Gb    5001086000a1c70c
Device  D       2       Disabled        12Gb    5001086000a1c70c
Device  D       3       Disabled        12Gb    5001086000a1c70c
Device  D       4       Disabled        12Gb    5001086000a1c70c
----


. 브리지가 패브릭 연결 MetroCluster 구성에 있는 경우 브리지 FC 포트에 연결되는 모든 스위치 포트를 해제합니다.
. ONTAP 클러스터 프롬프트에서 상태 모니터링에서 유지보수를 수행 중인 브리지를 제거합니다.
+
.. 브리지를 제거합니다. + 'Storage bridge remove-name_bridge-name_'
.. 모니터링되는 브리지 목록을 보고 제거된 브리지가 존재하지 않는지 확인합니다. + 'Storage bridge show'


. 적절하게 접지합니다.
. ATTO 브리지의 전원을 끕니다.
+
[cols="35,65"]
|===


| 을 사용하는 경우... | 그러면... 


 a| 
FiberBridge 7600N 또는 7500N 브리지
 a| 
브리지에 연결된 전원 케이블을 분리합니다.



 a| 
FiberBridge 6500N 브리지
 a| 
브리지의 전원 스위치를 끕니다.

|===
. 기존 브리지에 연결된 케이블을 분리합니다.
+
각 케이블이 연결된 포트를 기록해 두어야 합니다.

. 랙에서 기존 브리지를 분리합니다.
. 새 브리지를 랙에 설치합니다.
. 전원 코드를 다시 연결하고, 브리지에 대한 IP 액세스를 구성하는 경우 차폐된 이더넷 케이블을 연결합니다.
+

IMPORTANT: 이때 SAS 또는 FC 케이블을 다시 연결하면 안 됩니다.

. 브리지를 전원에 연결한 다음 전원을 켭니다.
+
브리지 준비 LED가 켜지려면 최대 30초가 걸릴 수 있으며 이는 브리지가 전원 공급 자체 테스트 시퀀스를 완료했음을 나타냅니다.

. 대역내 관리를 위해 구성하는 경우 FiberBridge RS-232 직렬 포트의 케이블을 PC의 직렬(COM) 포트에 연결합니다.
+
직렬 연결은 초기 구성에 사용된 다음 ONTAP 및 FC 포트를 통한 대역내 관리를 사용하여 브리지를 모니터링 및 관리할 수 있습니다.

. IP 관리를 위해 구성하는 경우 브리지 모델에 대한 _ATTO FiberBridge 설치 및 작동 설명서_의 2.0절에 나와 있는 절차에 따라 각 브리지에 대해 이더넷 관리 1 포트를 구성합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
Quicknav를 실행하여 이더넷 관리 포트를 구성하는 경우 이더넷 케이블로 연결된 이더넷 관리 포트만 구성됩니다. 예를 들어, 이더넷 관리 2 포트도 구성하려면 이더넷 케이블을 포트 2에 연결하고 Quicknav를 실행해야 합니다.

. 브리지를 구성합니다.
+
이전 브리지에서 구성 정보를 검색한 경우 해당 정보를 사용하여 새 브리지를 구성합니다.

+
지정한 사용자 이름과 암호를 기록해 두십시오.

+
브리지 모델의 _ATTO FiberBridge 설치 및 작동 설명서_에는 사용 가능한 명령과 사용 방법에 대한 최신 정보가 들어 있습니다.

+

NOTE: ATTO FiberBridge 7600N 또는 7500N에서 시간 동기화를 구성하지 마십시오. ONTAP에서 브리지가 검색된 후 ATTO FiberBridge 7600N 또는 7500N에 대한 시간 동기화가 클러스터 시간으로 설정됩니다. 또한 하루에 한 번 주기적으로 동기화됩니다. 사용된 표준 시간대는 GMT로 변경할 수 없습니다.

+
.. IP 관리를 구성하는 경우 브리지의 IP 설정을 구성합니다.
+
Qunav 유틸리티 없이 IP 주소를 설정하려면 FiberBridge에 대한 직렬 연결이 있어야 합니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
세트 ipaddress mp1_ip-address

+
'세트 ipsubnetmask mp1_subnet-mask_'

+
Set ipgateway mp1 x.x.x.x"입니다

+
세트 ipdhcp mp1이 비활성화되었습니다

+
세트 에테더넷스피드 mp1 1000

.. 브리지 이름을 구성합니다.
+
브리지는 MetroCluster 구성 내에서 각각 고유한 이름을 가져야 합니다.

+
각 사이트의 스택 그룹 하나에 대한 브리지 이름 예:

+
*** Bridge_A_1a
*** Bridge_a_1b
*** Bridge_B_1a
*** Bridge_B_1b
+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'메이 브리지네미_브리지네메 _'



.. ONTAP 9.4 이하를 실행하는 경우 브리지에서 SNMP를 활성화합니다.
+
'SNMP 설정 사용'을 선택합니다

+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.



. 브리지 FC 포트를 구성합니다.
+
.. 브리지 FC 포트의 데이터 속도/속도를 구성합니다.
+
지원되는 FC 데이터 속도는 모델 브리지에 따라 다릅니다.

+
*** FiberBridge 7600 브리지는 최대 32, 16 또는 8Gbps를 지원합니다.
*** FiberBridge 7500 브리지는 최대 16, 8 또는 4Gbps를 지원합니다.
*** FiberBridge 6500 브리지는 최대 8, 4 또는 2Gbps를 지원합니다.
+

NOTE: 선택한 FCDataRate 속도는 브리지 및 브리지 포트가 연결되는 스위치에서 지원하는 최대 속도로 제한됩니다. 케이블 연결 거리가 SFP 및 기타 하드웨어의 제한을 초과해서는 안 됩니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'Set FCDataRate_port-number port-speed_'를 참조하십시오



.. FiberBridge 7500N 또는 6500N 브리지를 구성하는 경우 해당 포트가 PTP에 사용하는 연결 모드를 구성합니다.
+

NOTE: FiberBridge 7600N 브리지를 구성할 때는 FCConnMode 설정이 필요하지 않습니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'Set FCConnMode_port-number_PTP'를 선택합니다

.. FiberBridge 7600N 또는 7500N 브리지를 구성하는 경우 FC2 포트를 구성하거나 비활성화해야 합니다.
+
*** 두 번째 포트를 사용하는 경우 FC2 포트에 대해 이전 하위 단계를 반복해야 합니다.
*** 두 번째 포트를 사용하지 않는 경우 포트를 비활성화해야 합니다.
+
'FCPortDisable_port-number _'



.. FiberBridge 7600N 또는 7500N 브리지를 구성하는 경우 사용하지 않는 SAS 포트를 비활성화합니다.
+
'SASPortDisable_SAS-PORT_'를 선택합니다

+

NOTE: SAS 포트 A~D는 기본적으로 활성화되어 있습니다. 사용하지 않는 SAS 포트는 비활성화해야 합니다. SAS 포트 A만 사용하는 경우 SAS 포트 B, C 및 D를 비활성화해야 합니다.



. 브리지에 대한 액세스를 보호하고 브리지의 구성을 저장합니다.
+
.. 컨트롤러 프롬프트에서 브릿지의 상태를 'Storage bridge show'로 확인한다
+
출력에는 고정되지 않은 브리지가 표시됩니다.

.. 비보안 브리지 포트의 상태를 확인합니다.
+
'정보'

+
출력에는 이더넷 포트 MP1 및 MP2의 상태가 표시됩니다.

.. 이더넷 포트 MP1이 활성화된 경우 다음 명령을 실행합니다.
+
'Eet EthernetPort mp1 disabled'

+

NOTE: 이더넷 포트 MP2도 활성화된 경우 포트 MP2에 대해 이전 하위 단계를 반복합니다.

.. 브리지의 구성을 저장합니다.
+
다음 명령을 실행해야 합니다.

+
'SaveConfiguration

+
펌웨어 재시작

+
브리지를 재시작하라는 메시지가 나타납니다.



. 각 브리지에서 FiberBridge 펌웨어를 업데이트합니다.
+
새 브리지가 파트너 브리지와 동일한 유형인 경우 파트너 브리지와 동일한 펌웨어로 업그레이드하십시오. 새 브리지가 파트너 브리지와 다른 유형인 경우 ONTAP 브리지 및 버전에서 지원하는 최신 펌웨어로 업그레이드하십시오. MetroCluster 유지 관리 가이드 _ 의 "FiberBridge 브리지에서 펌웨어 업데이트" 섹션을 참조하십시오.

. [[step17-reconnect-Newbridge] SAS와 FC 케이블을 새 브리지의 동일한 포트에 다시 연결합니다.
+
새 브리지가 FiberBridge 7600N 또는 7500N인 경우, 브리지를 선반 스택의 상단 또는 하단에 연결하는 케이블을 교체해야 합니다. FiberBridge 6500N 브리지는 SAS 케이블을 사용하며, FiberBridge 7600N 및 7500N 브리지는 이러한 연결을 위해 미니 SAS 케이블이 필요합니다.

+

NOTE: 포트를 연결하기 전에 10초 이상 기다립니다. SAS 케이블 커넥터는 SAS 포트에 올바르게 연결되었을 때 딸깍 소리가 나면서 제자리에 끼며 디스크 쉘프 SAS 포트 LNK LED가 녹색으로 켜집니다. 디스크 쉘프의 경우 당김 탭을 아래로 향하게 하여(커넥터 아래쪽에 있음) SAS 케이블 커넥터를 삽입합니다. 컨트롤러의 경우 SAS 포트 방향은 플랫폼 모델에 따라 다를 수 있으므로 SAS 케이블 커넥터의 올바른 방향은 서로 다릅니다.

. [[step18-verify-each-bridge] 각 브리지에서 브리지가 연결된 모든 디스크 드라이브와 디스크 쉘프를 볼 수 있는지 확인합니다.
+
[cols="35,65"]
|===


| 를 사용하는 경우... | 그러면... 


 a| 
ATTO ExpressNAV GUI
 a| 
.. 지원되는 웹 브라우저의 브라우저 상자에 브리지의 IP 주소를 입력합니다.
+
링크가 있는 ATTO FiberBridge 홈페이지로 이동합니다.

.. 링크를 클릭한 다음 브리지를 구성할 때 지정한 사용자 이름과 암호를 입력합니다.
+
왼쪽에 메뉴가 있는 ATTO FiberBridge 상태 페이지가 나타납니다.

.. 메뉴에서 * 고급 * 을 클릭합니다.
.. 연결된 장치 보기:
+
'아스타우다스다'

.. 제출 * 을 클릭합니다.




 a| 
직렬 포트 연결
 a| 
연결된 장치 보기:

'아스타우다스다'

|===
+
출력에는 브리지가 연결되는 장치(디스크 및 디스크 쉘프)가 표시됩니다. 출력 줄에 순차적으로 번호가 매겨서 장치를 빠르게 계산할 수 있습니다.

+

NOTE: 출력 시작 부분에 잘린 텍스트 응답이 나타나면 텔넷을 사용하여 브리지에 연결한 다음 '스타우더' 명령을 사용하여 모든 출력을 볼 수 있습니다.

+
다음 출력에서는 10개의 디스크가 연결되어 있음을 보여 줍니다.

+
[listing]
----
Tgt VendorID ProductID        Type SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK 3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK 3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK 3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK 3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK 3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK 3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK 3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK 3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK 3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK 3QP1FXW600009940VERQ
----
. 명령 출력에 브리지가 스택의 모든 해당 디스크 및 디스크 쉘프에 연결되어 있는지 확인합니다.
+
[cols="35,65"]
|===


| 출력이 다음과 같은 경우... | 그러면... 


 a| 
정답입니다
 a| 
반복합니다 <<step18-verify-each-bridge,18단계>> 각 나머지 브리지에 대해.



 a| 
정답이 아닙니다
 a| 
.. SAS 케이블이 느슨하게 연결되었는지 확인하거나 SAS 케이블을 다시 연결하여 문제를 해결하십시오 <<step17-reconnect-newbridge,17단계>>.
.. 반복합니다 <<step18-verify-each-bridge,18단계>>.


|===
. 브리지가 패브릭 연결 MetroCluster 구성에 있는 경우 이 절차를 시작할 때 비활성화한 FC 스위치 포트를 다시 활성화합니다.
+
이 포트는 브리지에 연결되는 포트여야 합니다.

. 두 컨트롤러 모듈의 시스템 콘솔에서 모든 컨트롤러 모듈이 새 브리지를 통해 디스크 쉘프에 액세스할 수 있는지(즉, 시스템이 다중 경로 HA를 위해 케이블로 연결되어 있는지) 확인합니다.
+
로컬 Sysconfig를 실행합니다

+

NOTE: 시스템이 검색을 완료하는 데 최대 1분이 걸릴 수 있습니다.

+
다중 경로 HA로 표시되지 않는 경우 새 브리지를 통해 모든 디스크 드라이브에 액세스할 수 있는 것은 아니므로 SAS 및 FC 케이블을 수정해야 합니다.

+
다음 출력에는 다중 경로 HA를 위해 시스템이 케이블로 연결되었다고 나와 있습니다.

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:41:49 PDT 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+

IMPORTANT: 시스템이 다중 경로 HA로 연결되지 않은 경우 브리지를 다시 시작하면 디스크 드라이브에 대한 액세스가 손실되어 다중 디스크 패닉이 발생할 수 있습니다.

. ONTAP 9.4 이하를 실행하는 경우 브리지가 SNMP용으로 구성되었는지 확인합니다.
+
브리지 CLI를 사용하는 경우 다음 명령을 실행합니다.

+
[listing]
----
get snmp
----
. ONTAP 클러스터 프롬프트에서 상태 모니터링에 브리지를 추가합니다.
+
.. 사용 중인 ONTAP 버전에 대한 명령을 사용하여 브리지를 추가합니다.
+
[cols="25,75"]
|===


| ONTAP 버전입니다 | 명령 


 a| 
9.5 이상
 a| 
스토리지 브리지 추가 주소 0.0.0.0 - 대역내 관리 이름_브리지-이름_



 a| 
9.4 이하
 a| 
'Storage bridge add-address_bridge-ip-address_-name_bridge-name_'

|===
.. 브리지가 추가되었으며 올바르게 구성되었는지 확인합니다.
+
'스토리지 브리지 쇼'

+
폴링 간격 때문에 모든 데이터가 반영되는 데 15분 정도 걸릴 수 있습니다. ONTAP 상태 모니터는 '상태' 열의 값이 '정상'이고 WWN(월드와이드 이름) 등의 정보가 표시되면 브리지와 연결하고 모니터링할 수 있습니다.

+
다음 예는 FC-to-SAS 브리지가 구성된 경우를 보여줍니다.

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템이 multipathed인지 확인한다: + 'node run-node_node-name_sysconfig-a'
.. 두 클러스터에 대한 상태 알림이 있는지 확인합니다. + 'system health alert show'
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 확인합니다. + 'MetroCluster show'
.. MetroCluster check 수행: + 'MetroCluster check run
.. MetroCluster check:+'MetroCluster check show'의 결과를 출력한다
.. 스위치에 대한 상태 경고(있는 경우): + 스토리지 스위치 표시 여부를 확인합니다
.. Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"^]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.




link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC-to-SAS 브리지의 대역 내 관리"]



== FiberBridge 7500N을 7600N 브리지로 핫 스와핑

FiberBridge 7500N 브리지를 7600N 브리지로 핫 스왑할 수 있습니다.

IP 관리 대신 브리지의 대역 내 관리를 사용하는 경우 관련 단계에 설명된 대로 이더넷 포트 및 IP 설정 구성 단계를 건너뛸 수 있습니다.


NOTE: ONTAP 9.8부터 스토리지 브리지 명령이 시스템 브리지로 바뀌었습니다. 다음 단계에서는 'Storage bridge' 명령어를 보여주지만, ONTAP 9.8 이상을 실행 중인 경우에는 'system bridge' 명령어를 사용한다.

.단계
. 브리지가 패브릭 연결 MetroCluster 구성에 있는 경우 브리지 FC 포트에 연결되는 모든 스위치 포트를 해제합니다.
. ONTAP 클러스터 프롬프트에서 상태 모니터링에서 유지보수를 수행 중인 브리지를 제거합니다.
+
.. 브리지를 제거합니다. + 'Storage bridge remove-name_bridge-name_'
.. 모니터링되는 브리지 목록을 보고 제거된 브리지가 존재하지 않는지 확인합니다. + 'Storage bridge show'


. 적절하게 접지합니다.
. 브리지에 연결된 전원 케이블을 제거하여 브리지의 전원을 끕니다.
. 기존 브리지에 연결된 케이블을 분리합니다.
+
각 케이블이 연결된 포트를 기록해 두어야 합니다.

. 랙에서 기존 브리지를 분리합니다.
. 새 브리지를 랙에 설치합니다.
. 전원 코드와 차폐 이더넷 케이블을 다시 연결합니다.
+

IMPORTANT: 이때 SAS 또는 FC 케이블을 다시 연결하면 안 됩니다.

. 브리지를 전원에 연결한 다음 전원을 켭니다.
+
브리지 준비 LED가 켜지려면 최대 30초가 걸릴 수 있으며 이는 브리지가 전원 공급 자체 테스트 시퀀스를 완료했음을 나타냅니다.

. 대역내 관리를 위해 구성하는 경우 FiberBridge RS-232 직렬 포트의 케이블을 PC의 직렬(COM) 포트에 연결합니다.
+
직렬 연결은 초기 구성에 사용된 다음 ONTAP 및 FC 포트를 통한 대역내 관리를 사용하여 브리지를 모니터링 및 관리할 수 있습니다.

. 대역내 관리를 위해 구성하는 경우 FiberBridge RS-232 직렬 포트의 케이블을 PC의 직렬(COM) 포트에 연결합니다.
+
직렬 연결은 초기 구성에 사용된 다음 ONTAP 및 FC 포트를 통한 대역내 관리를 사용하여 브리지를 모니터링 및 관리할 수 있습니다.

. IP 관리를 위해 구성하는 경우 브리지 모델에 대한 _ATTO FiberBridge 설치 및 작동 설명서_의 2.0절에 나와 있는 절차에 따라 각 브리지에 대해 이더넷 관리 1 포트를 구성합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
Quicknav를 실행하여 이더넷 관리 포트를 구성하는 경우 이더넷 케이블로 연결된 이더넷 관리 포트만 구성됩니다. 예를 들어, 이더넷 관리 2 포트도 구성하려면 이더넷 케이블을 포트 2에 연결하고 Quicknav를 실행해야 합니다.

. 브리지를 구성합니다.
+
지정한 사용자 이름과 암호를 기록해 두십시오.

+
브리지 모델의 _ATTO FiberBridge 설치 및 작동 설명서_에는 사용 가능한 명령과 사용 방법에 대한 최신 정보가 들어 있습니다.

+

NOTE: FiberBridge 7600N에서 시간 동기화를 구성하지 마십시오. FiberBridge 7600N에 대한 시간 동기화는 ONTAP에서 브리지를 검색한 후 클러스터 시간으로 설정됩니다. 또한 하루에 한 번 주기적으로 동기화됩니다. 사용된 표준 시간대는 GMT로 변경할 수 없습니다.

+
.. IP 관리를 구성하는 경우 브리지의 IP 설정을 구성합니다.
+
Qunav 유틸리티 없이 IP 주소를 설정하려면 FiberBridge에 대한 직렬 연결이 있어야 합니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'세트 ipaddress mp1_ip-address_'

+
'세트 ipsubnetmask mp1_subnet-mask_'

+
Set ipgateway mp1 x.x.x.x"입니다

+
세트 ipdhcp mp1이 비활성화되었습니다

+
세트 에테더넷스피드 mp1 1000

.. 브리지 이름을 구성합니다.
+
브리지는 MetroCluster 구성 내에서 각각 고유한 이름을 가져야 합니다.

+
각 사이트의 스택 그룹 하나에 대한 브리지 이름 예:

+
*** Bridge_A_1a
*** Bridge_a_1b
*** Bridge_B_1a
*** Bridge_B_1b
+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'메이 브리지네미_브리지네메 _'



.. ONTAP 9.4 이하를 실행하는 경우 브리지에서 SNMP를 활성화합니다. + 'SNMP 설정 활성화'
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.



. 브리지 FC 포트를 구성합니다.
+
.. 브리지 FC 포트의 데이터 속도/속도를 구성합니다.
+
지원되는 FC 데이터 속도는 모델 브리지에 따라 다릅니다.

+
*** FiberBridge 7600 브리지는 최대 32, 16 또는 8Gbps를 지원합니다.
*** FiberBridge 7500 브리지는 최대 16, 8 또는 4Gbps를 지원합니다.
*** FiberBridge 6500 브리지는 최대 8, 4 또는 2Gbps를 지원합니다.
+

NOTE: 선택한 FCDataRate 속도는 컨트롤러 모듈의 브리지 및 FC 포트에서 지원하는 최대 속도나 브리지 포트가 연결되는 스위치로 제한됩니다. 케이블 연결 거리가 SFP 및 기타 하드웨어의 제한을 초과해서는 안 됩니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'Set FCDataRate_port-number port-speed_'를 참조하십시오



.. FC2 포트를 구성하거나 비활성화해야 합니다.
+
*** 두 번째 포트를 사용하는 경우 FC2 포트에 대해 이전 하위 단계를 반복해야 합니다.
*** 두 번째 포트를 사용하지 않는 경우 사용하지 않는 포트를 비활성화해야 합니다.
+
FCPortDisable 포트 번호

+
다음 예는 FC 포트 2의 비활성화 상태를 보여줍니다.

+
[listing]
----
FCPortDisable 2

Fibre Channel Port 2 has been disabled.
----


.. 사용하지 않는 SAS 포트를 비활성화합니다.
+
'SASPortDisable_SAS-PORT_'를 선택합니다

+

NOTE: SAS 포트 A~D는 기본적으로 활성화되어 있습니다. 사용하지 않는 SAS 포트는 비활성화해야 합니다.

+
SAS 포트 A만 사용하는 경우 SAS 포트 B, C 및 D를 비활성화해야 합니다. 다음 예는 SAS 포트 B의 비활성화를 보여줍니다 마찬가지로 SAS 포트 C와 D를 비활성화해야 합니다.

+
[listing]
----
SASPortDisable b

SAS Port B has been disabled.
----


. 브리지에 대한 액세스를 보호하고 브리지의 구성을 저장합니다.
+
.. 컨트롤러 프롬프트에서 브리지 상태를 확인합니다.
+
'스토리지 브리지 쇼'

+
출력에는 고정되지 않은 브리지가 표시됩니다.

.. 비보안 브리지 포트의 상태를 확인합니다.
+
'정보'

+
출력에는 이더넷 포트 MP1 및 MP2의 상태가 표시됩니다.

.. 이더넷 포트 MP1이 활성화된 경우 다음 명령을 실행합니다.
+
'Eet EthernetPort mp1 disabled'

+

NOTE: 이더넷 포트 MP2도 활성화된 경우 포트 MP2에 대해 이전 하위 단계를 반복합니다.

.. 브리지의 구성을 저장합니다.
+
다음 명령을 실행해야 합니다. +

+
'SaveConfiguration

+
펌웨어 재시작

+
브리지를 재시작하라는 메시지가 나타납니다.



. 각 브리지에서 FiberBridge 펌웨어를 업데이트합니다.
+
link:task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["ONTAP 9.4 이상을 실행하는 구성에서 FiberBridge 7600N 또는 7500N 브리지에서 펌웨어 업데이트"]

. [[step17-reconnect-cables]] SAS 및 FC 케이블을 새 브리지의 동일한 포트에 다시 연결합니다.
+

NOTE: 포트를 연결하기 전에 10초 이상 기다립니다. SAS 케이블 커넥터는 SAS 포트에 올바르게 연결되었을 때 딸깍 소리가 나면서 제자리에 끼며 디스크 쉘프 SAS 포트 LNK LED가 녹색으로 켜집니다. 디스크 쉘프의 경우 당김 탭을 아래로 향하게 하여(커넥터 아래쪽에 있음) SAS 케이블 커넥터를 삽입합니다. 컨트롤러의 경우 SAS 포트 방향은 플랫폼 모델에 따라 다를 수 있으므로 SAS 케이블 커넥터의 올바른 방향은 서로 다릅니다.

. 각 브리지에서 브리지가 연결된 모든 디스크 드라이브와 디스크 쉘프를 볼 수 있는지 확인합니다.
+
'아스타우다스다'

+
출력에는 브리지가 연결되는 장치(디스크 및 디스크 쉘프)가 표시됩니다. 출력 줄에 순차적으로 번호가 매겨서 장치를 빠르게 계산할 수 있습니다.

+
다음 출력에서는 10개의 디스크가 연결되어 있음을 보여 줍니다.

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. 명령 출력에 브리지가 스택의 모든 해당 디스크 및 디스크 쉘프에 연결되어 있는지 확인합니다.
+
[cols="25,75"]
|===


| 출력이 다음과 같은 경우... | 그러면... 


 a| 
정답입니다
 a| 
나머지 각 브리지에 대해 이전 단계를 반복합니다.



 a| 
정답이 아닙니다
 a| 
.. SAS 케이블이 느슨하게 연결되었는지 확인하거나 SAS 케이블을 다시 연결하여 문제를 해결하십시오 <<step17-reconnect-cables,17단계>>.
.. 이전 단계를 반복합니다.


|===
. 브리지가 패브릭 연결 MetroCluster 구성에 있는 경우 이 절차를 시작할 때 비활성화한 FC 스위치 포트를 다시 활성화합니다.
+
이 포트는 브리지에 연결되는 포트여야 합니다.

. 두 컨트롤러 모듈의 시스템 콘솔에서 모든 컨트롤러 모듈이 새 브리지를 통해 디스크 쉘프에 액세스할 수 있는지(즉, 시스템이 다중 경로 HA를 위해 케이블로 연결되어 있는지) 확인합니다.
+
로컬 Sysconfig를 실행합니다

+

NOTE: 시스템이 검색을 완료하는 데 최대 1분이 걸릴 수 있습니다.

+
다중 경로 HA로 표시되지 않는 경우 새 브리지를 통해 모든 디스크 드라이브에 액세스할 수 있는 것은 아니므로 SAS 및 FC 케이블을 수정해야 합니다.

+
다음 출력에는 다중 경로 HA를 위해 시스템이 케이블로 연결되었다고 나와 있습니다.

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:41:49 PDT 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+

IMPORTANT: 시스템이 다중 경로 HA로 연결되지 않은 경우 브리지를 다시 시작하면 디스크 드라이브에 대한 액세스가 손실되어 다중 디스크 패닉이 발생할 수 있습니다.

. ONTAP 9.4 이하를 실행하는 경우 브리지가 SNMP용으로 구성되었는지 확인합니다.
+
브리지 CLI를 사용하는 경우 다음 명령을 실행합니다.

+
"SNMP를 가져오십시오.

. ONTAP 클러스터 프롬프트에서 상태 모니터링에 브리지를 추가합니다.
+
.. 사용 중인 ONTAP 버전에 대한 명령을 사용하여 브리지를 추가합니다.
+
[cols="25,75"]
|===


| ONTAP 버전입니다 | 명령 


 a| 
9.5 이상
 a| 
스토리지 브리지 추가 주소 0.0.0.0 - 대역내 관리 이름_브리지-이름_



 a| 
9.4 이하
 a| 
'Storage bridge add-address_bridge-ip-address_-name_bridge-name_'

|===
.. 브리지가 추가되었으며 올바르게 구성되었는지 확인합니다.
+
'스토리지 브리지 쇼'

+
폴링 간격 때문에 모든 데이터가 반영되는 데 15분 정도 걸릴 수 있습니다. ONTAP 상태 모니터는 '상태' 열의 값이 '정상'이고 WWN(월드와이드 이름) 등의 정보가 표시되면 브리지와 연결하고 모니터링할 수 있습니다.

+
다음 예는 FC-to-SAS 브리지가 구성된 경우를 보여줍니다.

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템이 multipathed인지 확인한다: + 'node run-node_node-name_sysconfig-a'
.. 두 클러스터에 대한 상태 알림이 있는지 확인합니다. + 'system health alert show'
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 확인합니다. + 'MetroCluster show'
.. MetroCluster check 수행: + 'MetroCluster check run
.. MetroCluster 검사 결과를 표시합니다: +
+
MetroCluster 체크 쇼

.. 스위치에 대한 상태 경고(있는 경우): + 스토리지 스위치 표시 여부를 확인합니다
.. Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"^]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.




link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC-to-SAS 브리지의 대역 내 관리"]



== FiberBridge 7600N 브리지를 FiberBridge 7600N 또는 7500N 브리지로 핫 스와핑합니다

FiberBridge 6500N 브리지를 FiberBridge 7600N 또는 7500N 브리지로 핫 스왑하여 장애가 발생한 브리지를 교체하거나 패브릭 연결 또는 브리지 연결 MetroCluster 구성에서 브리지를 업그레이드할 수 있습니다.

.이 작업에 대해
* 이 절차는 단일 FiberBridge 7600N 또는 7500N 브리지와 단일 FiberBridge 7600N 브리지를 핫 스왑하는 데 사용됩니다.
* FiberBridge 7600N 브리지를 FiberBridge 7600N 또는 7500N 브리지로 핫 스왑하는 경우 FiberBridge 7600N 또는 7500N 브리지에서 FC 포트 1개와 SAS 포트 1개만 사용해야 합니다.
* IP 관리 대신 브리지의 대역 내 관리를 사용하는 경우 관련 단계에 설명된 대로 이더넷 포트 및 IP 설정 구성 단계를 건너뛸 수 있습니다.



IMPORTANT: 한 쌍의 FiberBridge 6500N 브리지를 모두 핫 스왑하는 경우 를 사용해야 합니다 link:task_fb_consolidate_replace_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.html["여러 스토리지 스택 통합"] 조닝 지침 절차: 브리지의 FiberBridge 6500N 브리지를 모두 교체하면 FiberBridge 7600N 또는 7500N 브리지의 추가 포트를 활용할 수 있습니다.


NOTE: ONTAP 9.8부터 스토리지 브리지 명령이 시스템 브리지로 바뀌었습니다. 다음 단계에서는 'Storage bridge' 명령어를 보여주지만, ONTAP 9.8 이상을 실행 중인 경우에는 'system bridge' 명령어를 사용한다.

.단계
. 다음 중 하나를 수행합니다.
+
** 장애가 발생한 브리지가 패브릭 연결 MetroCluster 구성에 있는 경우 브리지 FC 포트에 연결되는 스위치 포트를 해제합니다.
** 장애가 발생한 브리지가 확장 MetroCluster 구성에 있는 경우 사용 가능한 FC 포트 중 하나를 사용합니다.


. ONTAP 클러스터 프롬프트에서 상태 모니터링에서 유지보수를 수행 중인 브리지를 제거합니다.
+
.. 브리지를 제거합니다.
+
'Storage bridge remove-name_bridge-name_'

.. 모니터링되는 브리지 목록을 보고 제거된 브리지가 존재하지 않는지 확인합니다.
+
'스토리지 브리지 쇼'



. 적절하게 접지합니다.
. 브리지의 전원 스위치를 끕니다.
. 선반에서 FiberBridge 6500N 브리지 포트 및 전원 케이블에 연결된 케이블을 분리합니다.
+
각 케이블이 연결된 포트를 기록해 두어야 합니다.

. 랙에서 교체해야 하는 FiberBridge 6500N 브리지를 제거합니다.
. 새 FiberBridge 7600N 또는 7500N 브리지를 랙에 설치합니다.
. 전원 코드와 필요한 경우 차폐된 이더넷 케이블을 다시 연결합니다.
+

IMPORTANT: 이때 SAS 또는 FC 케이블을 다시 연결하지 마십시오.

. 대역내 관리를 위해 구성하는 경우 FiberBridge RS-232 직렬 포트의 케이블을 PC의 직렬(COM) 포트에 연결합니다.
+
직렬 연결은 초기 구성에 사용된 다음 ONTAP 및 FC 포트를 통한 대역내 관리를 사용하여 브리지를 모니터링 및 관리할 수 있습니다.

. IP 관리를 구성하는 경우 이더넷 케이블을 사용하여 각 브리지의 이더넷 관리 1 포트를 네트워크에 연결합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
이더넷 관리 1 포트를 사용하면 브리지 펌웨어(ATTO ExpressNAV 또는 FTP 관리 인터페이스 사용)를 빠르게 다운로드하고 코어 파일을 검색하고 로그를 추출할 수 있습니다.

. IP 관리를 위해 구성하는 경우 브리지 모델에 대한 _ATTO FiberBridge 설치 및 작동 설명서_의 2.0절에 나와 있는 절차에 따라 각 브리지에 대해 이더넷 관리 1 포트를 구성합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
Quicknav를 실행하여 이더넷 관리 포트를 구성하는 경우 이더넷 케이블로 연결된 이더넷 관리 포트만 구성됩니다. 예를 들어, 이더넷 관리 2 포트도 구성하려면 이더넷 케이블을 포트 2에 연결하고 Quicknav를 실행해야 합니다.

. 브리지를 구성합니다.
+
이전 브리지에서 구성 정보를 검색한 경우 해당 정보를 사용하여 새 브리지를 구성합니다.

+
지정한 사용자 이름과 암호를 기록해 두십시오.

+
브리지 모델의 _ATTO FiberBridge 설치 및 작동 설명서_에는 사용 가능한 명령과 사용 방법에 대한 최신 정보가 들어 있습니다.

+

NOTE: ATTO FiberBridge 7600N 또는 7500N에서 시간 동기화를 구성하지 마십시오. ONTAP에서 브리지가 검색된 후 ATTO FiberBridge 7600N 또는 7500N에 대한 시간 동기화가 클러스터 시간으로 설정됩니다. 또한 하루에 한 번 주기적으로 동기화됩니다. 사용된 표준 시간대는 GMT로 변경할 수 없습니다.

+
.. IP 관리를 구성하는 경우 브리지의 IP 설정을 구성합니다.
+
Qunav 유틸리티 없이 IP 주소를 설정하려면 FiberBridge에 대한 직렬 연결이 있어야 합니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'세트 ipaddress mp1_ip-address_'

+
'세트 ipsubnetmask mp1_subnet-mask_'

+
Set ipgateway mp1 x.x.x.x"입니다

+
세트 ipdhcp mp1이 비활성화되었습니다

+
세트 에테더넷스피드 mp1 1000

.. 브리지 이름을 구성합니다.
+
브리지는 MetroCluster 구성 내에서 각각 고유한 이름을 가져야 합니다.

+
각 사이트의 스택 그룹 하나에 대한 브리지 이름 예:

+
*** Bridge_A_1a
*** Bridge_a_1b
*** Bridge_B_1a
*** Bridge_B_1b
+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'메이 브리지네미_브리지네메 _'



.. ONTAP 9.4 이하를 실행하는 경우 브리지에서 SNMP를 활성화합니다. + 'SNMP 설정 활성화'
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.



. 브리지 FC 포트를 구성합니다.
+
.. 브리지 FC 포트의 데이터 속도/속도를 구성합니다.
+
지원되는 FC 데이터 속도는 모델 브리지에 따라 다릅니다.

+
*** FiberBridge 7600 브리지는 최대 32, 16 또는 8Gbps를 지원합니다.
*** FiberBridge 7500 브리지는 최대 16, 8 또는 4Gbps를 지원합니다.
*** FiberBridge 6500 브리지는 최대 8, 4 또는 2Gbps를 지원합니다.
+

NOTE: 선택한 FCDataRate 속도는 브리지 및 브리지 포트가 연결되는 스위치에서 지원하는 최대 속도로 제한됩니다. 케이블 연결 거리가 SFP 및 기타 하드웨어의 제한을 초과해서는 안 됩니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'Set FCDataRate_port-number port-speed_'를 참조하십시오



.. FiberBridge 7500N 또는 6500N 브리지를 구성하는 경우 해당 포트가 PTP에 사용하는 연결 모드를 구성합니다.
+

NOTE: FiberBridge 7600N 브리지를 구성할 때는 FCConnMode 설정이 필요하지 않습니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'Set FCConnMode_port-number_PTP'를 선택합니다

.. FiberBridge 7600N 또는 7500N 브리지를 구성하는 경우 FC2 포트를 구성하거나 비활성화해야 합니다.
+
*** 두 번째 포트를 사용하는 경우 FC2 포트에 대해 이전 하위 단계를 반복해야 합니다.
*** 두 번째 포트를 사용하지 않는 경우 포트를 비활성화해야 합니다.
+
'FCPortDisable_port-number _'



.. FiberBridge 7600N 또는 7500N 브리지를 구성하는 경우 사용하지 않는 SAS 포트를 비활성화합니다.
+
'SASPortDisable_SAS-PORT_'를 선택합니다

+

NOTE: SAS 포트 A~D는 기본적으로 활성화되어 있습니다. 사용하지 않는 SAS 포트는 비활성화해야 합니다. SAS 포트 A만 사용하는 경우 SAS 포트 B, C 및 D를 비활성화해야 합니다.



. 브리지에 대한 액세스를 보호하고 브리지의 구성을 저장합니다.
+
.. 컨트롤러 프롬프트에서 브리지 상태를 확인합니다.
+
'스토리지 브리지 쇼'

+
출력에는 고정되지 않은 브리지가 표시됩니다.

.. 비보안 브리지 포트의 상태를 확인합니다.
+
'정보'

+
출력에는 이더넷 포트 MP1 및 MP2의 상태가 표시됩니다.

.. 이더넷 포트 MP1이 활성화된 경우 다음 명령을 실행합니다.
+
'Eet EthernetPort mp1 disabled'

+

NOTE: 이더넷 포트 MP2도 활성화된 경우 포트 MP2에 대해 이전 하위 단계를 반복합니다.

.. 브리지의 구성을 저장합니다.
+
다음 명령을 실행해야 합니다.

+
'SaveConfiguration

+
펌웨어 재시작

+
브리지를 재시작하라는 메시지가 나타납니다.



. FiberBridge 7600N 또는 7500N 브리지에 대한 상태 모니터링을 켭니다.
. 각 브리지에서 FiberBridge 펌웨어를 업데이트합니다.
+
새 브리지가 파트너 브리지와 동일한 유형인 경우 파트너 브리지와 동일한 펌웨어로 업그레이드하십시오. 새 브리지가 파트너 브리지와 다른 유형인 경우 ONTAP 브리지 및 버전에서 지원하는 최신 펌웨어로 업그레이드하십시오. MetroCluster 유지 관리 가이드 _ 의 "FiberBridge 브리지에서 펌웨어 업데이트" 섹션을 참조하십시오.

. [[step17-recable]] SAS 및 FC 케이블을 새 브리지의 SAS A 및 파이버 채널 1 포트에 다시 연결합니다.
+
SAS 포트는 FiberBridge 6500N 브리지가 연결된 동일한 쉘프 포트에 케이블로 연결되어야 합니다.

+
FC 포트는 FiberBridge 6500N 브리지가 연결된 동일한 스위치 또는 컨트롤러 포트에 케이블로 연결되어야 합니다.

+

NOTE: 커넥터를 포트에 억지로 밀어 넣지 마십시오. 미니 SAS 케이블은 SAS 포트에 올바르게 연결되었을 때 딸깍 소리가 나면서 SAS 케이블이 제자리에 고정되며 디스크 쉘프 SAS 포트 LNK LED가 녹색으로 켜집니다. 디스크 쉘프의 경우 당김 탭을 아래로 향하게 하여 SAS 케이블 커넥터를 삽입합니다(커넥터 아래쪽에 있음). 컨트롤러의 경우 SAS 포트의 방향은 플랫폼 모델에 따라 다를 수 있으므로 SAS 케이블 커넥터의 올바른 방향은 서로 다릅니다.

. 브리지가 연결된 모든 디스크 드라이브와 디스크 쉘프를 감지할 수 있는지 확인합니다.
+
[cols="25,75"]
|===


| 를 사용하는 경우... | 그러면... 


 a| 
ATTO ExpressNAV GUI
 a| 
.. 지원되는 웹 브라우저의 브라우저 상자에 브리지의 IP 주소를 입력합니다.
+
링크가 있는 ATTO FiberBridge 홈페이지로 이동합니다.

.. 링크를 클릭한 다음 브리지를 구성할 때 지정한 사용자 이름과 암호를 입력합니다.
+
왼쪽에 메뉴가 있는 ATTO FiberBridge 상태 페이지가 나타납니다.

.. 메뉴에서 * 고급 * 을 클릭합니다.
.. 다음 명령을 입력한 다음 * 제출 * 을 클릭하여 브리지에 표시되는 디스크 목록을 확인합니다.
+
'아스타우다스다'





 a| 
직렬 포트 연결
 a| 
브리지에 표시되는 디스크 목록을 표시합니다.

'아스타우다스다'

|===
+
출력에는 브리지가 연결된 장치(디스크 및 디스크 쉘프)가 표시됩니다. 출력 줄은 순차적으로 번호가 매겨지며, 이를 통해 장치의 수를 빠르게 계산할 수 있습니다. 예를 들어, 다음 출력에서는 10개의 디스크가 연결되어 있음을 보여 줍니다.

+
[listing]
----

Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
+

NOTE: 출력 시작 부분에 "respongse 잘린" 텍스트가 나타나면 텔넷을 사용하여 브리지에 액세스하고 동일한 명령을 입력하여 모든 출력을 볼 수 있습니다.

. 명령 출력에 브리지가 스택의 모든 필수 디스크 및 디스크 쉘프에 연결되어 있는지 확인합니다.
+
[cols="25,75"]
|===


| 출력이 다음과 같은 경우... | 그러면... 


 a| 
정답입니다
 a| 
나머지 각 브리지에 대해 이전 단계를 반복합니다.



 a| 
정답이 아닙니다
 a| 
.. SAS 케이블이 느슨하게 연결되었는지 확인하거나 SAS 케이블을 다시 연결하여 문제를 해결하십시오 <<step17-recable,17단계>>.
.. 나머지 각 브리지에 대해 이전 단계를 반복합니다.


|===
. 브리지에 연결되는 FC 스위치 포트를 다시 활성화합니다.
. 두 컨트롤러의 시스템 콘솔에서 새 브리지를 통해 디스크 쉘프(다중 경로 HA를 위해 시스템이 케이블로 연결됨)에 액세스할 수 있는지 확인합니다.
+
로컬 Sysconfig를 실행합니다

+

NOTE: 시스템이 검색을 완료하는 데 최대 1분이 걸릴 수 있습니다.

+
예를 들어, 다음 출력은 시스템이 다중 경로 HA에 대해 케이블로 연결되었음을 보여 줍니다.

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:23:24 PST 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+
명령 출력에 해당 구성이 혼합 경로 또는 단일 경로 HA로 표시되는 경우 새 브리지를 통해 모든 디스크 드라이브에 액세스할 수 있는 것은 아니므로 SAS 및 FC 케이블을 수정해야 합니다.

+

IMPORTANT: 시스템이 다중 경로 HA로 연결되지 않은 경우 브리지를 다시 시작하면 디스크 드라이브에 대한 액세스가 손실되어 다중 디스크 패닉이 발생할 수 있습니다.

. ONTAP 클러스터 프롬프트에서 상태 모니터링에 브리지를 추가합니다.
+
.. 사용 중인 ONTAP 버전에 대한 명령을 사용하여 브리지를 추가합니다.
+
[cols="25,75"]
|===


| ONTAP 버전입니다 | 명령 


 a| 
9.5 이상
 a| 
스토리지 브리지 추가 주소 0.0.0.0 - 대역내 관리 이름_브리지-이름_



 a| 
9.4 이하
 a| 
'Storage bridge add-address_bridge-ip-address_-name_bridge-name_'

|===
.. 브리지가 추가되었고 제대로 구성되었는지 확인합니다. + 'Storage bridge show'
+
폴링 간격 때문에 모든 데이터가 반영되는 데 15분 정도 걸릴 수 있습니다. ONTAP 상태 모니터는 '상태' 열의 값이 '정상'이고 WWN(월드와이드 이름) 등의 정보가 표시되면 브리지와 연결하고 모니터링할 수 있습니다.

+
다음 예는 FC-to-SAS 브리지가 구성된 경우를 보여줍니다.

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템에 다중 경로 가 있는지 확인합니다.
+
'node run-node_node-name_sysconfig-a'

.. 두 클러스터에 대한 상태 알림이 있는지 확인합니다. + 'system health alert show'
.. MetroCluster 구성을 확인하고 운영 모드가 정상인지 확인합니다.
+
MetroCluster 쇼

.. MetroCluster 검사를 수행합니다.
+
'MetroCluster check run

.. MetroCluster 검사 결과를 표시합니다.
+
MetroCluster 체크 쇼

.. 스위치에 대한 상태 경고를 확인합니다(있는 경우).
+
'스토리지 스위치 쇼'

.. Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"^]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.


. 키트와 함께 제공된 RMA 명령에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다.
+
기술 지원 부서(에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^], 888-463-8277 (북미), 00-800-44-638277 (유럽) 또는 +800-800-80-800 (아시아/태평양) 교체 절차에 대한 추가 지원이 필요한 경우.



link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC-to-SAS 브리지의 대역 내 관리"]
