---
permalink: maintain/task_disable_encryption_on_brocade_fc_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, disable, encryption, brocade, fc, switch 
summary: Brocade FC 스위치에서 암호화를 비활성화해야 할 수 있습니다. 
---
= Brocade FC 스위치에서 암호화를 해제합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Brocade FC 스위치에서 암호화를 비활성화해야 할 수 있습니다.

.단계
. 유지 관리의 시작을 알리는 AutoSupport 메시지를 두 사이트에서 보냅니다.
+
[listing]
----
cluster_A::> autosupport invoke -node * -type all -message MAINT=4h
----
+
[listing]
----
cluster_B::> autosupport invoke -node * -type all -message MAINT=4h
----
. 클러스터 A에서 MetroCluster 구성이 작동하는지 확인합니다
+
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 확인합니다. + " * MetroCluster show * "
+
[listing]
----
cluster_A::> metrocluster show
----
.. MetroCluster check 수행: + ` * MetroCluster check run * '
+
[source, nolinebreak]
----
cluster_A::> metrocluster check run
----
.. MetroCluster check 결과 표시: + ` * MetroCluster check show * '
+
[source, nolinebreak]
----
cluster_A::> metrocluster check show
----


. 두 스위치의 상태를 점검하십시오.
+
``fabric show *’’입니다

+
[listing]
----
switch_A_1:admin> fabric show
----
+
[listing]
----
switch_B_1:admin> fabric show
----
. 두 스위치를 모두 비활성화합니다.
+
'* switchdisable*'

+
[listing]
----
switch_A_1:admin> switchdisable
----
+
[listing]
----
switch_B_1:admin> switchdisable
----
. 각 클러스터에서 노드에 대해 사용 가능한 경로를 확인합니다.
+
' * sysconfig * '

+
[listing]
----
cluster_A::> system node run -node node-name -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node node-name -command sysconfig -a
----
+
이제 스위치 패브릭이 비활성화되어 있으므로 시스템 스토리지 구성은 단일 경로 HA가 되어야 합니다.

. 두 클러스터의 총 상태를 확인합니다.
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
시스템 출력에는 두 클러스터에 모두 미러링된 애그리게이트와 정상이 표시되어야 합니다.

+
[listing]
----
mirrored,normal
----
. 두 스위치의 관리자 프롬프트에서 다음 하위 단계를 반복합니다.
+
.. 암호화된 포트를 표시합니다: + " * portenccompshow * "
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. 암호화된 포트에서 암호화 해제: + " * portcfgencrypt – disable_port-number_ *"
+
[listing]
----
switch_A_1:admin> portcfgencrypt --disable 40
switch_A_1:admin> portcfgencrypt --disable 41
switch_A_1:admin> portcfgencrypt --disable 42
switch_A_1:admin> portcfgencrypt --disable 43
----
.. 인증 유형을 모두로 설정합니다.
+
``authUtil--set-a all *’

+
[listing]
----
switch_A_1:admin> authUtil --set -a all
----
.. 스위치에 인증 정책을 설정합니다. OFF: + " * authutil - -policy -sw off * "로 설정합니다
+
[listing]
----
switch_A_1:admin> authutil --policy -sw off
----
.. Diffie-Hellman 그룹 인증을 + * +: + " * authutil - -set -g**"로 설정합니다
+
[listing]
----
switch_A_1:admin> authUtil --set -g *
----
.. 비밀 키 데이터베이스(+'* secAuthSecSecSecSecret--remove-all*)를 삭제합니다
+
[listing]
----
switch_A_1:admin> secAuthSecret --remove -all
----
.. 포트: + " * portenccompshow * "에서 암호화가 비활성화되었는지 확인합니다
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. '* switchenable*' 스위치를 활성화합니다
+
[listing]
----
switch_A_1:admin> switchenable
----
.. ISL의 상태 확인: + " * islshow * "
+
[listing]
----
switch_A_1:admin> islshow
----


. 각 클러스터에서 노드에 대해 사용 가능한 경로를 확인합니다.
+
' * sysconfig * '

+
[listing]
----
cluster_A::> system node run -node * -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node * -command sysconfig -a
----
+
시스템 출력은 시스템 스토리지 구성이 다시 4중 경로 HA로 변경되었음을 나타냅니다.

. 두 클러스터의 총 상태를 확인합니다.
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
시스템은 다음 시스템 출력에 표시된 것처럼 양쪽 클러스터에 대해 애그리게이트가 미러링되고 정상임을 보여 주어야 합니다.

+
[listing]
----
mirrored,normal
----
. 클러스터 A에서 MetroCluster 구성이 작동하는지 확인합니다
+
.. MetroCluster check 수행: + ` * MetroCluster check run * '
+
[listing]
----
cluster_A::> metrocluster check run
----
.. MetroCluster check 결과 표시: + ` * MetroCluster check show * '
+
[listing]
----
cluster_A::> metrocluster check show
----


. 두 사이트에서 유지 보수 종료를 나타내는 AutoSupport 메시지를 보냅니다.
+
[listing]
----
cluster_A::> autosupport invoke -node node-name -type all -message MAINT=END
----
+
[listing]
----
cluster_B::> autosupport invoke -node node-name -type all -message MAINT=END
----

