---
permalink: maintain/task_fb_hot_add_shelf_prepare_7500n.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, prepare, hot, add, sas, disk, shelves 
summary: SAS 디스크 쉘프 핫 추가를 준비하기 위해 디스크 드라이브와 디스크 쉘프 펌웨어를 함께 다운로드하십시오. 
---
= SAS 디스크 쉘프 핫 추가 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAS 디스크 쉘프 핫 추가를 준비하기 위해 디스크 드라이브와 디스크 쉘프 펌웨어를 함께 다운로드하십시오.

* 시스템은 지원되는 구성이어야 하며 지원되는 ONTAP 버전을 실행 중이어야 합니다.
* 시스템의 모든 디스크 드라이브와 디스크 쉘프는 최신 펌웨어 버전을 실행해야 합니다.
+
쉘프를 추가하기 전에 MetroCluster 구성 전체에서 디스크 및 쉘프 펌웨어를 업데이트할 수 있습니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["업그레이드, 되돌리기 또는 다운그레이드를 수행할 수 있습니다"]




NOTE: 시스템에서 지원되는 ONTAP 버전을 실행 중인 경우 동일한 스택 내에서 IOM12 모듈과 IOM6 모듈의 조합이 지원됩니다. 사용 중인 ONTAP 버전에서 쉘프 혼합을 지원하는지 확인하려면 을 참조하십시오 link:https://imt.netapp.com/matrix/["상호 운용성 매트릭스 툴(IMT)"^]. 사용 중인 ONTAP 버전이 지원되지 않고 기존 스택이나 지원되는 IOM 모듈 조합에 추가할 새 쉘프에서 IOM 모듈을 업그레이드하거나 다운그레이드할 수 없는 경우 다음 중 하나를 수행해야 합니다.

* 새 SAS 포트에서 새 스택을 시작합니다(브리지 페어에서 지원되는 경우).
* 추가 브리지 쌍에서 새 스택을 시작합니다.


.단계
. NetApp Support 사이트에서 다음 문서를 다운로드하거나 볼 수 있습니다.
+
** https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]
** 디스크 쉘프 모델의 _설치 가이드_를 참조하십시오.


. 추가하고 있는 디스크 쉘프가 지원되는지 확인하십시오.
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]

. 최신 디스크 및 디스크 쉘프 펌웨어 다운로드:
+

NOTE: 이 단계에서는 링크에 제공된 지침의 다운로드 부분만 완료합니다. 에 나와 있는 단계를 따라야 합니다 link:task_fb_hot_add_a_disk_shelf_install_7500n.html["디스크 쉘프 핫 추가"] 섹션을 참조하십시오.

+
.. 디스크 펌웨어를 다운로드하고 나중에 참조할 수 있도록 디스크 펌웨어 지침 사본을 만듭니다.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"]

.. 디스크 쉘프 펌웨어를 다운로드하고 나중에 참조할 수 있도록 디스크 쉘프 펌웨어 지침의 복사본을 만드십시오.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"]




