---
permalink: maintain/task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, replace, shelf, nondisruptively, stretch, configuration 
summary: 확장 MetroCluster 구성에서 중단 없이 디스크 쉘프를 교체할 수 있습니다. 즉, 완전히 채워진 디스크 쉘프 또는 디스크 쉘프 섀시를 사용하고, 분리하려는 쉘프에서 구성요소를 전송할 수 있습니다. 
---
= 확장 MetroCluster 구성에서 쉘프를 중단 없이 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 MetroCluster 구성에서 중단 없이 디스크 쉘프를 교체할 수 있습니다. 즉, 완전히 채워진 디스크 쉘프 또는 디스크 쉘프 섀시를 사용하고, 분리하려는 쉘프에서 구성요소를 전송할 수 있습니다.

설치할 디스크 쉘프 모델은 에 지정된 스토리지 시스템 요구사항을 충족해야 합니다 link:https://hwu.netapp.com["Hardware Universe"^]지원되는 쉘프 모델, 지원되는 디스크 드라이브 유형, 스택의 최대 디스크 쉘프 수, 지원되는 ONTAP 버전이 포함됩니다.

.단계
. 적절하게 접지합니다.
. 교체할 쉘프가 포함된 루프의 디스크가 있는 모든 애그리게이트 및 볼륨을 식별하고 영향을 받는 plex 이름을 기록합니다.
+
각 노드에는 영향을 받는 쉘프 및 호스트 애그리게이트 또는 호스트 볼륨의 루프에 있는 디스크가 포함될 수 있습니다.

. 계획 중인 대체 시나리오에 따라 다음 두 옵션 중 하나를 선택합니다.
+
** 쉘프 섀시, 디스크 및 I/O 모듈(IOM)을 포함하여 전체 디스크 쉘프를 교체하려면 아래 표에 설명된 대로 해당 작업을 수행하십시오.
+
|===


| 시나리오 | 조치 


 a| 
영향을 받는 플렉스에 영향을 받는 셸프에서 디스크 수가 적습니다.
 a| 
영향을 받는 쉘프의 디스크를 하나씩 다른 쉘프의 스페어로 교체합니다.


NOTE: 디스크 교체를 완료한 후 플렉스를 오프라인 상태로 전환할 수 있습니다.



 a| 
영향을 받는 플렉스에는 영향을 받는 셸프에 있는 것보다 많은 디스크가 포함되어 있습니다.
 a| 
플렉스를 오프라인 상태로 이동한 다음 플렉스를 삭제합니다.



 a| 
영향을 받는 플렉스에 영향을 받는 쉘프의 디스크가 있습니다.
 a| 
플렉스를 오프라인 상태로 이동하지만 삭제하지 마십시오.

|===
** 디스크 쉘프 섀시만 교체하고 다른 구성 요소는 사용하지 않는 경우, 다음 단계를 수행하십시오.
+
... 영향을 받는 플렉스가 호스팅된 컨트롤러에서 오프라인 상태로 전환:
+
'집계 오프라인'

... 플렉스가 오프라인 상태인지 확인합니다.
+
집계 상태 -r





. 영향을 받는 쉘프 루프가 연결되는 컨트롤러 SAS 포트를 식별하고 두 사이트 컨트롤러의 SAS 포트를 비활성화합니다.
+
'Storage port disable-node_name_-port_sas_port_'

+
영향을 받는 쉘프 루프는 두 사이트에 모두 연결됩니다.

. ONTAP가 디스크가 누락되었음을 인식할 때까지 기다립니다.
+
.. 디스크가 누락되었는지 확인합니다.
+
시즈config-a 또는 Sysconfig-r



. 디스크 쉘프의 전원 스위치를 끕니다.
. 디스크 쉘프에서 모든 전원 코드를 뽑습니다.
. 새 디스크 쉘프의 케이블을 같은 방법으로 케이블을 연결할 수 있도록 케이블을 분리하는 포트에 대한 기록을 만듭니다.
. 디스크 쉘프를 다른 디스크 쉘프 또는 스토리지 시스템에 연결하는 케이블을 뽑았다가 뺍니다.
. 랙에서 디스크 쉘프를 분리합니다.
+
디스크 쉘프를 손쉽게 조작하려면 전원 공급 장치 및 IOM을 제거하십시오. 디스크 쉘프 섀시를 설치할 경우, 디스크 드라이브 또는 캐리어도 분리합니다. 그렇지 않으면 디스크 드라이브 또는 캐리어를 너무 많이 다루면 내부 드라이브가 손상될 수 있으므로 가능하면 분리하지 마십시오.

. 교체 디스크 쉘프를 지원 브래킷 및 랙에 설치하고 고정합니다.
. 디스크 쉘프 섀시를 설치한 경우 전원 공급 장치와 IOM을 다시 설치합니다.
. 분리한 디스크 쉘프에 구성한 대로 모든 케이블을 교체 디스크 쉘프 포트에 정확하게 연결하여 디스크 쉘프 스택을 다시 구성하십시오.
. 교체 디스크 쉘프의 전원을 켜고 디스크 드라이브가 회전할 때까지 기다립니다.
. 디스크 쉘프 ID를 0에서 98까지의 고유 ID로 변경합니다.
. 이전에 비활성화한 SAS 포트를 모두 활성화합니다.
+
.. ONTAP가 디스크가 삽입되었는지 인식할 때까지 기다립니다.
.. 디스크가 삽입되었는지 확인합니다.
+
시즈config-a 또는 Sysconfig-r



. 전체 디스크 쉘프(디스크 쉘프 섀시, 디스크, IOM)를 교체하려면 다음 단계를 수행하십시오.
+

NOTE: 디스크 쉘프 섀시만 교체하는 경우 다른 구성 요소는 사용하지 않는 경우 19단계로 이동하십시오.

+
.. 디스크 자동 할당이 설정되었는지 확인합니다(켜짐).
+
'스토리지 디스크 옵션 수정 - 자동 할당'

+
디스크가 자동으로 할당됩니다.

.. 디스크 자동 할당이 활성화되지 않은 경우 디스크 소유권을 수동으로 할당합니다.


. 플렉스를 다시 온라인으로 이동합니다.
+
'집계 online_plex name _'

. 애그리게이트를 미러링하여 삭제된 플렉스를 다시 생성합니다.
. 재동기화를 시작할 때 플렉스를 모니터링합니다.
+
'집계 상태 - r<집계 이름>'

. 스토리지 시스템이 예상대로 작동하는지 확인합니다.
+
'시스템 상태 경고 표시


