---
permalink: maintain/task_rename_the_cluster_for_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, rename, cluster, configuration 
summary: MetroCluster 구성에서 클러스터의 이름을 바꾸는 작업은 변경을 수행한 다음 로컬 및 원격 클러스터에서 변경 사항이 올바르게 적용되었는지 확인하는 것입니다. 
---
= MetroCluster 구성에서 클러스터 이름 바꾸기
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성에서 클러스터의 이름을 바꾸는 작업은 변경을 수행한 다음 로컬 및 원격 클러스터에서 변경 사항이 올바르게 적용되었는지 확인하는 것입니다.

.단계
. 를 사용하여 클러스터 이름을 봅니다
+
'* MetroCluster node show * '

+
명령:

+
[listing]
----
cluster_1::*> metrocluster node show
DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_1
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
      cluster_2
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
4 entries were displayed.
----
. 클러스터 이름 바꾸기:
+
'* 클러스터 ID 수정 -name_new_name_*'

+
다음 예에서는 cluster_1 클러스터 이름이 cluster_a로 바뀌었습니다.

+
[listing]
----
cluster_1::*> cluster identity modify -name cluster_A
----
. 로컬 클러스터에서 이름이 바뀐 클러스터가 정상적으로 실행 중인지 확인합니다.
+
'* MetroCluster node show * '

+
다음 예에서는 새로 이름이 바뀐 cluster_a가 정상적으로 실행되고 있습니다.

+
[listing]
----
cluster_A::*> metrocluster node show
DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
      cluster_2
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
4 entries were displayed.
----
. 원격 클러스터의 이름을 바꿉니다.
+
``클러스터 피어 수정 - local-name-cluster_2_-new-name_cluster_B_*'

+
다음 예에서는 cluster_2 이름이 cluster_B로 바뀌었습니다.

+
[listing]
----
cluster_2::> cluster peer modify-local-name -name cluster_2 -new-name
cluster_B
----
. 원격 클러스터에서 로컬 클러스터의 이름이 변경되었으며 정상적으로 실행 중인지 확인합니다.
+
'_MetroCluster node show _'

+
다음 예에서는 새로 이름이 바뀐 cluster_B가 정상적으로 실행되고 있습니다.

+
[listing]
----

cluster_B::*> metrocluster node show
DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_B
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
      cluster_A
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
4 entries were displayed.
----
. 이름을 바꿀 각 클러스터에 대해 이 단계를 반복합니다.

