---
permalink: maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, update, firmware, fibrebridge, bridge, update, configuration 
summary: 브리지 펌웨어 업데이트 절차는 브리지 모델과 ONTAP 버전에 따라 다릅니다. 
---
= FiberBridge 브리지에서 펌웨어 업데이트 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
브리지 펌웨어 업데이트 절차는 브리지 모델과 ONTAP 버전에 따라 다릅니다.



== ONTAP 9.4 이상을 실행하는 구성에서 FiberBridge 7600N 또는 7500N 브리지에서 펌웨어 업데이트

FiberBridge 브리지의 펌웨어를 업데이트하여 최신 기능을 사용하거나 가능한 문제를 해결해야 할 수 있습니다. 이 절차는 ONTAP 9.4 이상을 실행하는 구성에서 FiberBridge 7600N 또는 7500N 브리지에 사용해야 합니다.

* MetroCluster 구성이 정상적으로 작동해야 합니다.
* MetroCluster 구성의 모든 FiberBridge 브리지는 가동 및 작동해야 합니다.
* 모든 스토리지 경로를 사용할 수 있어야 합니다.
* 관리자 암호와 HTTP 서버에 대한 액세스가 필요합니다.
* 지원되는 펌웨어 버전을 사용하고 있어야 합니다.
+
https://["NetApp 상호 운용성 매트릭스 툴"^]

+
IMT에서 스토리지 솔루션 필드를 사용하여 MetroCluster 솔루션을 선택할 수 있습니다. 부품 탐색기 * 를 사용하여 부품 및 ONTAP 버전을 선택하여 검색을 구체화합니다. 결과 표시 * 를 클릭하여 조건에 맞는 지원되는 설정 목록을 표시할 수 있습니다.

* ONTAP 9.4 이상을 실행하는 구성에서 FiberBridge 7600N 또는 7500N 브리지에서만 이 작업을 사용할 수 있습니다.
* 모든 브리지가 동일한 펌웨어 버전을 실행할 수 있도록 MetroCluster 구성의 각 FiberBridge 브리지에서 이 작업을 수행해야 합니다.



NOTE: 이 절차는 무중단으로 진행되며 완료하는 데 약 30분이 소요됩니다.


NOTE: ONTAP 9.8부터 스토리지 브리지 명령이 시스템 브리지로 바뀌었습니다. 다음 단계에서는 'Storage bridge' 명령어를 보여주지만, ONTAP 9.8 이상을 실행 중인 경우에는 'system bridge' 명령어를 사용한다.

.단계
. 유지 관리의 시작을 나타내는 AutoSupport 메시지를 호출합니다.
+
'System node AutoSupport invoke-node * -type all-message MAINT=_maintenance -window-in-hours _'

+
유지보수 기간은 최대 72시간으로 지정합니다. 시간이 경과하기 전에 유지 관리가 완료된 경우 유지 보수 기간이 종료되었음을 나타내는 AutoSupport 메시지를 호출할 수 있습니다.

+
'System node AutoSupport invoke-node * -type all-message maINT=end'

. ATTO FiberBridge 페이지로 이동하여 브리지에 적합한 펌웨어를 선택합니다.
+
https://["ATTO FiberBridge 펌웨어 다운로드 페이지"^]

. 주의/MustRead 및 최종 사용자 계약을 검토하고 확인란을 클릭하여 수락을 표시하고 계속 진행합니다.
. 컨트롤러 모듈이 네트워크에 액세스할 수 있는 네트워크 위치에 펌웨어 파일을 배치합니다.
+
두 컨트롤러 모듈 중 하나의 콘솔에서 나머지 단계에 명령을 입력할 수 있습니다.

. 고급 권한 레벨로 변경:
+
세트 프리빌리지 고급

+
고급 모드로 계속 진행하고 고급 모드 프롬프트(*>)를 보려면 ""y""로 응답해야 합니다.

. 브리지 펌웨어 업데이트:
+
'Storage bridge firmware update-bridge name-Uri_url-of-firmware-package_

+
[listing]
----
cluster_A> storage bridge firmware update -bridge bridge_A_1a -uri http://192.168.132.97/firmware.ZBD
----
. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다

. 펌웨어 업그레이드가 완료되었는지 확인합니다.
+
'job show-name'_job-name_'

+
다음 예에서는 "'Storage bridge firmware update'(저장소 브리지 펌웨어 업데이트) 작업이 여전히 실행 중인 것을 보여 줍니다.

+
[listing]
----
cluster_A> job show -name "storage bridge firmware update"
Owning

Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
2246   job-name
                            cluster_A
                                       node_A_1
                                                      Running
Description: Storage bridge firmware update job
----
+
약 10분 후 새 펌웨어가 완전히 설치되고 작업 상태가 성공:

+
[listing]
----
cluster_A> job show -name "storage bridge firmware update"

                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
2246   Storage bridge firmware update
                            cluster_A
                                       node_A_1
                                                      Success
Description: Storage bridge firmware update job
----
. 대역내 관리가 활성화되었는지 여부와 시스템이 실행 중인 ONTAP의 버전에 따라 다음 단계를 완료합니다.
+
** ONTAP 9.4를 실행 중인 경우 대역내 관리가 지원되지 않으며 브리지 콘솔에서 명령을 실행해야 합니다.
+
... 브리지 콘솔에서 'flashimages' 명령을 실행하고 올바른 펌웨어 버전이 표시되는지 확인합니다.
+

NOTE: 이 예에서는 1차 플래시 이미지에 새 펌웨어 이미지가 표시되고 2차 플래시 이미지에는 이전 이미지가 표시됩니다.





+
[listing]
----
flashimages

 ;Type Version
;=====================================================
Primary 3.16 001H
Secondary 3.15 002S
Ready.
----
+
.. 브리지에서 firmwarerestart 명령을 실행하여 브리지를 재부팅합니다.
+
*** ONTAP 9.5 이상을 실행 중인 경우 대역 내 관리가 지원되며 클러스터 프롬프트에서 명령을 실행할 수 있습니다.


.. 'storage bridge run-cli-name_bridge-name_-command FlashImages' 명령을 실행합니다.
+

NOTE: 이 예에서는 1차 플래시 이미지에 새 펌웨어 이미지가 표시되고 2차 플래시 이미지에는 이전 이미지가 표시됩니다.

+
[listing]
----
cluster_A> storage bridge run-cli -name ATTO_7500N_IB_1 -command FlashImages

[Job 2257]

;Type         Version
;=====================================================
Primary 3.16 001H
Secondary 3.15 002S
Ready.


[Job 2257] Job succeeded.
----
.. 필요한 경우 브리지를 다시 시작합니다.
+
'Storage bridge run-cli-name ATTO_7500N_IB_1 - command FirmwareRestart

+

NOTE: ATTO 펌웨어 버전 2.95부터 브리지가 자동으로 다시 시작되며 이 단계는 필요하지 않습니다.



. 브리지가 올바르게 다시 시작되었는지 확인합니다.
+
'시즈구성'을 선택합니다

+
다중 경로 고가용성을 위해 시스템을 케이블로 연결해야 합니다. 두 컨트롤러 모두 각 스택의 디스크 쉘프에 대한 브리지를 통해 액세스할 수 있습니다.

+
[listing]
----
cluster_A> node run -node cluster_A-01 -command sysconfig
NetApp Release 9.6P8: Sat May 23 16:20:55 EDT 2020
System ID: 1234567890 (cluster_A-01); partner ID: 0123456789 (cluster_A-02)
System Serial Number: 200012345678 (cluster_A-01)
System Rev: A4
System Storage Configuration: Quad-Path HA
----
. FiberBridge 펌웨어가 업데이트되었는지 확인합니다.
+
스토리지 브리지 표시 필드 FW 버전, 심볼릭 이름

+
[listing]
----
cluster_A> storage bridge show -fields fw-version,symbolic-name
name fw-version symbolic-name
----------------- ----------------- -------------
ATTO_20000010affeaffe 3.10 A06X bridge_A_1a
ATTO_20000010affeffae 3.10 A06X bridge_A_1b
ATTO_20000010affeafff 3.10 A06X bridge_A_2a
ATTO_20000010affeaffa 3.10 A06X bridge_A_2b
4 entries were displayed.
----
. 브리지의 프롬프트에서 파티션이 업데이트되었는지 확인합니다.
+
플래시이미지

+
1차 플래시 이미지는 새 펌웨어 이미지를 표시하고 2차 플래시 이미지는 이전 이미지를 표시합니다.

+
[listing]
----
Ready.
flashimages

;Type         Version
;=====================================================
   Primary    3.16 001H
 Secondary    3.15 002S

 Ready.
----
. 5단계부터 10단계까지 반복하여 두 플래시 이미지가 동일한 버전으로 업데이트되도록 합니다.
. 두 플래시 이미지가 동일한 버전으로 업데이트되었는지 확인합니다.
+
플래시이미지

+
출력에는 두 파티션의 버전이 동일해야 합니다.

+
[listing]
----
Ready.
flashimages

;Type         Version
;=====================================================
   Primary    3.16 001H
 Secondary    3.16 001H

 Ready.
----
. MetroCluster 구성의 모든 브리지가 업데이트될 때까지 다음 브리지에서 5-13단계를 반복합니다.




== ONTAP 9.3.x 이하 또는 6500N 브리지를 실행하는 구성에서 FiberBridge 7500N의 펌웨어를 업데이트합니다

FiberBridge 브리지의 펌웨어를 업데이트하여 최신 기능을 사용하거나 가능한 문제를 해결해야 할 수 있습니다. 이 절차는 ONTAP 9.3.x를 실행하는 구성에서 FiberBridge 7500N에 사용하거나 지원되는 모든 버전의 ONTAP에서 FiberBridge 6500N 브리지에 사용해야 합니다.

.시작하기 전에
* MetroCluster 구성이 정상적으로 작동해야 합니다.
* MetroCluster 구성의 모든 FiberBridge 브리지는 가동 및 작동해야 합니다.
* 모든 스토리지 경로를 사용할 수 있어야 합니다.
* FTP 또는 SCP 서버에 대한 액세스 및 관리자 암호가 필요합니다.
* 지원되는 펌웨어 버전을 사용하고 있어야 합니다.
+
https://["NetApp 상호 운용성 매트릭스 툴"^]

+
IMT에서 스토리지 솔루션 필드를 사용하여 MetroCluster 솔루션을 선택할 수 있습니다. 부품 탐색기 * 를 사용하여 부품 및 ONTAP 버전을 선택하여 검색을 구체화합니다. 결과 표시 * 를 클릭하여 조건에 맞는 지원되는 설정 목록을 표시할 수 있습니다.



FiberBridge 7500N 또는 6500N 브리지에서 이 작업을 사용할 수 있습니다. ONTAP 9.3부터 ONTAP storage bridge firmware update 명령을 사용하여 FiberBridge 7500N 브리지의 브리지 펌웨어를 업데이트할 수 있습니다.

link:task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["ONTAP 9.4 이상을 실행하는 구성에서 FiberBridge 7600N 또는 7500N 브리지에서 펌웨어 업데이트"]

모든 브리지가 동일한 펌웨어 버전을 실행할 수 있도록 MetroCluster 구성의 각 FiberBridge 브리지에서 이 작업을 수행해야 합니다.


NOTE: 이 절차는 무중단으로 진행되며 완료하는 데 약 30분이 소요됩니다.

.단계
. 유지 관리의 시작을 나타내는 AutoSupport 메시지를 호출합니다.
+
'System node AutoSupport invoke-node * -type all-message MAINT=_maintenance -window-in-hours _'

+
"_ maintenance -window-in-hours _ " 는 최대 72시간의 유지 보수 기간을 지정합니다. 시간이 경과하기 전에 유지 관리가 완료된 경우 유지 보수 기간이 종료되었음을 나타내는 AutoSupport 메시지를 호출할 수 있습니다.

+
'System node AutoSupport invoke-node * -type all-message maINT=end'

. ATTO FiberBridge 페이지로 이동하여 브리지에 적합한 펌웨어를 선택합니다.
+
https://["ATTO FiberBridge 펌웨어 다운로드 페이지"^]

. 주의/MustRead 및 최종 사용자 계약을 검토하고 확인란을 클릭하여 수락을 표시하고 계속 진행합니다.
. ATTO FiberBridge 펌웨어 다운로드 페이지의 절차의 1단계부터 3단계까지 사용하여 브리지 펌웨어 파일을 다운로드합니다.
. 각 브리지에서 펌웨어를 업데이트하라는 지시가 있을 때 참조할 수 있도록 ATTO FiberBridge 펌웨어 다운로드 페이지 및 릴리스 노트를 복사합니다.
. 브리지 업데이트:
+
.. FiberBridge 브리지에 펌웨어를 설치합니다.
+
*** ATTO FiberBridge 7500N 브리지를 사용하는 경우, _ATTO FiberBridge 7500N 설치 및 작동 설명서_의 ""펌웨어 업데이트"" 섹션에 나와 있는 지침을 참조해야 합니다.
*** ATTO FiberBridge 6500N 브리지를 사용하는 경우, _ATTO FiberBridge 6500N 설치 및 작동 설명서_의 ""펌웨어 업데이트"" 섹션에 나와 있는 지침을 참조해야 합니다.
+
* 주의: * 지금 개별 브리지의 전원을 껐다 켜십시오. 스택의 두 브리지 전원을 동시에 껐다가 켜면 컨트롤러에서 드라이브에 대한 액세스 권한을 상실하여 plex 장애가 발생하거나 여러 디스크 패닉이 발생할 수 있습니다.

+
브리지가 다시 시작됩니다.



.. 두 컨트롤러 중 하나의 콘솔에서 브리지가 올바르게 다시 시작되었는지 확인합니다.
+
'시즈구성'을 선택합니다

+
다중 경로 고가용성을 위해 시스템을 케이블로 연결해야 합니다. 두 컨트롤러 모두 각 스택의 디스크 쉘프에 대한 브리지를 통해 액세스할 수 있습니다.

+
[listing]
----
cluster_A::> node run -node cluster_A-01 -command sysconfig
NetApp Release 9.1P7: Sun Aug 13 22:33:49 PDT 2017
System ID: 1234567890 (cluster_A-01); partner ID: 0123456789 (cluster_A-02)
System Serial Number: 200012345678 (cluster_A-01)
System Rev: A4
System Storage Configuration: Quad-Path HA
----
.. 두 컨트롤러 중 하나의 콘솔에서 FiberBridge 펌웨어가 업데이트되었는지 확인합니다.
+
스토리지 브리지 표시 필드 FW 버전, 심볼릭 이름

+
[listing]
----
cluster_A::> storage bridge show -fields fw-version,symbolic-name
 name              fw-version        symbolic-name
 ----------------- ----------------- -------------
 ATTO_10.0.0.1     1.63 071C 51.01   bridge_A_1a
 ATTO_10.0.0.2     1.63 071C 51.01   bridge_A_1b
 ATTO_10.0.1.1     1.63 071C 51.01   bridge_B_1a
 ATTO_10.0.1.2     1.63 071C 51.01   bridge_B_1b
 4 entries were displayed.
----
.. 동일한 브리지에서 이전 하위 단계를 반복하여 두 번째 파티션을 업데이트합니다.
.. 두 파티션이 모두 업데이트되었는지 확인합니다.
+
플래시이미지

+
출력에는 두 파티션의 버전이 동일해야 합니다.

+
[listing]
----
Ready.
flashimages
4
;Type         Version
;=====================================================
Primary    2.80 003T
Secondary    2.80 003T
Ready.
----


. MetroCluster 구성의 모든 브리지가 업데이트될 때까지 다음 브리지에서 이전 단계를 반복합니다.

