---
permalink: maintain/task_change_an_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, fc, switch 
summary: 'FC 스위치의 공급업체를 변경하거나(Cisco에서 Brocade로, 또는 그 반대) 스위치 모델을 변경하거나, 둘 다 변경해야 할 수 있습니다.' 
---
= FC 스위치의 공급업체 또는 모델을 변경합니다
:allow-uri-read: 


[role="lead"]
FC 스위치의 공급업체를 Cisco에서 Brocade로 변경하거나 그 반대로 변경하거나 스위치 모델을 변경하거나, 두 가지를 모두 변경해야 할 수 있습니다.

.이 작업에 대해
* 이 절차는 NetApp 검증 스위치를 사용하는 경우에 적용됩니다.
* link:enable-console-logging-before-maintenance.html["콘솔 로깅을 활성화합니다"] 이 작업을 수행하기 전에
* 구성의 두 Fabric에 대해 한 번에 하나의 Fabric에 대해 이 절차의 단계를 수행해야 합니다.


.단계
. [[STEP_1, 1단계]] 구성의 상태를 확인합니다.
+
.. MetroCluster가 각 클러스터에서 정상 모드로 구성되어 있는지 확인합니다. (* MetroCluster show *
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 각 노드에서 미러링이 활성화되어 있는지 확인합니다. (* MetroCluster node show *
+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. MetroCluster 구성부품이 정상 상태인지 점검한다. (* MetroCluster check run *
+
[listing]
----
cluster_A::> metrocluster check run

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. '* 시스템 상태 경고 표시*'라는 상태 경고가 없는지 확인하십시오


. 설치하기 전에 새 스위치를 구성하십시오.
+
의 단계를 link:../install-fc/concept-configure-fc-switches.html["FC 스위치를 구성합니다"]따릅니다.

. 다음 순서로 연결부를 분리하여 이전 스위치에서 연결을 끊습니다.
+
.. MetroCluster FC 및 FCVI 인터페이스를 분리합니다.
.. ATTO FiberBridge 브리지를 분리합니다.
.. MetroCluster ISL을 분리합니다.


. 이전 스위치의 전원을 끄고 케이블을 제거한 다음 기존 스위치를 새 스위치로 물리적으로 교체합니다.
. 다음과 같은 순서로 스위치를 케이블로 연결합니다.
+
의 단계를 수행해야 link:../install-fc/task_configure_the_mcc_hardware_components_fabric.html["패브릭 연결 MetroCluster 구성 케이블링"]합니다.

+
.. 원격 사이트에 ISL 케이블 연결
.. ATTO FiberBridge 브리지를 케이블로 연결합니다.
.. MetroCluster FC 및 FCVI 인터페이스에 케이블을 연결합니다.


. 스위치 전원을 켭니다.
. MetroCluster 구성이 정상인지 확인하려면 이 과정을 반복합니다 <<1단계>>.
. 구성의 두 번째 Fabric에 대해 1단계부터 7단계까지 반복합니다.

