---
permalink: maintain/task_fb_hot_add_stack_of_shelves_and_bridges.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, stack, sas, disk, shelves, bridges, system 
summary:  
---
= MetroCluster 시스템에 SAS 디스크 쉘프 및 브리지 스택 핫 추가
:icons: font
:imagesdir: ../media/


[role="lead"]
브리지를 포함한 전체 스택을 MetroCluster 시스템에 중단 없이 핫 추가할 수 있습니다. FC 스위치에는 사용 가능한 포트가 있어야 하며 변경 사항을 반영하려면 스위치 조닝을 업데이트해야 합니다.

.이 작업에 대해
* 이 절차는 FiberBridge 7500N 또는 6500N 브리지를 사용하여 스택을 추가하는 데 사용할 수 있습니다.
* 이 절차는 ATTO ExpressNAV GUI 및 ATTO Quicknav 유틸리티와 같은 권장 브리지 관리 인터페이스를 사용하고 있다고 가정하고 작성되었습니다.
+
** ATTO ExpressNAV GUI를 사용하여 브리지를 구성 및 관리하고 브리지 펌웨어를 업데이트할 수 있습니다. ATTO Quicknav 유틸리티를 사용하여 브리지 이더넷 관리 1 포트를 구성합니다.
** 필요한 경우 다른 관리 인터페이스를 사용할 수 있습니다. 이러한 옵션에는 직렬 포트 또는 텔넷을 사용하여 브리지를 구성 및 관리하고 이더넷 관리 1 포트를 구성하고 FTP를 사용하여 브리지 펌웨어를 업데이트하는 것이 포함됩니다. 이러한 관리 인터페이스를 선택하는 경우 시스템은 의 해당 요구 사항을 충족해야 합니다 link:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html["기타 브리지 관리 인터페이스"]






== SAS 디스크 쉘프 및 브리지 스택 핫추가 준비

SAS 디스크 쉘프 스택과 브리지 쌍을 핫 애드할 준비를 하려면 디스크 드라이브 및 디스크 쉘프 펌웨어와 문서를 다운로드해야 합니다.

.시작하기 전에
* 시스템은 지원되는 구성이어야 하며 지원되는 ONTAP 버전을 실행 중이어야 합니다.
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]

* 시스템의 모든 디스크 드라이브와 디스크 쉘프는 최신 펌웨어 버전을 실행해야 합니다.
+
쉘프를 추가하기 전에 MetroCluster 구성 전체에서 디스크 및 쉘프 펌웨어를 업데이트할 수 있습니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["업그레이드, 되돌리기 또는 다운그레이드를 수행할 수 있습니다"^]

* 각 FC 스위치에는 한 브리지에 연결할 수 있는 FC 포트가 하나 있어야 합니다.
+

NOTE: FC 스위치 호환성에 따라 FC 스위치를 업그레이드해야 할 수도 있습니다.

* 브리지 설정에 사용하는 컴퓨터는 ATTO ExpressNAV GUI(Internet Explorer 8 또는 9) 또는 Mozilla Firefox 3을 사용하려면 ATTO 지원 웹 브라우저를 실행해야 합니다.
+
ATTO 제품 릴리스 노트_에는 지원되는 웹 브라우저의 최신 목록이 있습니다. 단계의 정보를 사용하여 이 문서에 액세스할 수 있습니다.



.단계
. NetApp Support 사이트에서 다음 문서를 다운로드하거나 볼 수 있습니다.
+
** https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]
** 디스크 쉘프 모델의 _설치 및 서비스 가이드_입니다.


. ATTO 웹 사이트와 NetApp 웹 사이트에서 콘텐츠를 다운로드하십시오.
+
.. ATTO FiberBridge 설명 페이지로 이동합니다.
.. ATTO FiberBridge Description(ATTO FiberBridge 설명) 페이지의 링크를 사용하여 ATTO 웹 사이트에 액세스한 후 다음을 다운로드하십시오.
+
*** _ATTO FiberBridge 설치 및 작동 설명서_ 를 참조하십시오.
*** ATTO Quicknav 유틸리티(설치 시 사용 중인 컴퓨터)


.. ATTO FiberBridge 설명 페이지 끝에 있는 * Continue * 를 클릭하여 ATTO FiberBridge 펌웨어 다운로드 페이지로 이동한 후 다음을 수행합니다.
+
*** 다운로드 페이지의 지시에 따라 브리지 펌웨어 파일을 다운로드합니다.
+
이 단계에서는 링크에 제공된 지침의 다운로드 부분만 완료합니다. 에서 업데이트하라는 지시가 있을 때 각 브리지의 펌웨어를 나중에 업데이트합니다 link:task_fb_hot_add_stack_of_shelves_and_bridges.html["쉘프 스택 핫 추가"] 섹션을 참조하십시오.

*** 나중에 참조할 수 있도록 ATTO FiberBridge 펌웨어 다운로드 페이지 및 릴리스 정보를 복사합니다.




. 최신 디스크 및 디스크 쉘프 펌웨어를 다운로드하고 나중에 참조할 수 있도록 설치 항목의 복사본을 만드십시오.
+
MetroCluster 구성의 모든 디스크 쉘프(새 쉘프와 기존 쉘프 모두)에서 동일한 펌웨어 버전을 실행해야 합니다.

+

NOTE: 이 단계에서는 링크에 제공된 지침의 다운로드 부분만 완료하고 설치 지침의 복사본을 만듭니다. 의 지침에 따라 각 디스크 및 디스크 쉘프의 펌웨어를 나중에 업데이트합니다 link:task_fb_hot_add_stack_of_shelves_and_bridges.html["쉘프 스택 핫 추가"] 섹션을 참조하십시오.

+
.. 디스크 펌웨어를 다운로드하고 나중에 참조할 수 있도록 디스크 펌웨어 지침 사본을 만듭니다.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"^]

.. 디스크 쉘프 펌웨어를 다운로드하고 나중에 참조할 수 있도록 디스크 쉘프 펌웨어 지침의 복사본을 만드십시오.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"^]



. 권장되는 브리지 관리 인터페이스(ATTO ExpressNAV GUI 및 ATTO Quicknav 유틸리티)를 사용하는 데 필요한 하드웨어 및 정보를 수집합니다.
+
.. 표준 이더넷 케이블을 사용하여 브리지 이더넷 관리 1 포트에서 네트워크로 연결합니다.
.. 브리지에 액세스하기 위한 기본이 아닌 사용자 이름과 암호를 결정합니다.
+
기본 사용자 이름과 암호를 변경하는 것이 좋습니다.

.. 각 브리지의 이더넷 관리 1 포트에 대한 IP 주소, 서브넷 마스크 및 게이트웨이 정보를 얻습니다.
.. 설정에 사용 중인 컴퓨터에서 VPN 클라이언트를 비활성화합니다.
+
활성 VPN 클라이언트는 브리지에 대한 Quicknav 스캔을 실패하게 합니다.



. 브리지 ""L"" 브래킷을 랙 전면에 안전하게 장착하려면 각 브리지에 4개의 나사를 끼웁니다.
+
브리지 ""L"" 브래킷의 개구부는 19인치(482.6mm) 랙에 대한 랙 표준 ETA-310-X를 준수합니다.

. 필요한 경우 구성에 추가되는 새 브리지를 수용하기 위해 FC 스위치 조닝을 업데이트합니다.
+
NetApp에서 제공하는 참조 구성 파일을 사용하는 경우 모든 포트에 대해 영역이 생성되므로 조닝 업데이트를 수행할 필요가 없습니다. 브리지의 FC 포트에 연결되는 각 스위치 포트에 대한 스토리지 영역이 있어야 합니다.





== SAS 디스크 쉘프 및 브리지 스택 핫 추가

SAS 디스크 쉘프 및 브리지 스택을 핫 추가할 수 있어 브리지 용량을 늘릴 수 있습니다.

시스템은 SAS 디스크 쉘프 및 브리지 스택을 핫 추가하기 위한 모든 요구사항을 충족해야 합니다.

link:task_fb_hot_add_stack_of_shelves_and_bridges.html["SAS 디스크 쉘프 및 브리지 스택 핫추가 준비"]

* 상호 운용성 요구사항을 모두 충족하는 경우, SAS 디스크 쉘프 및 브리지 스택을 핫 추가하는 무중단 절차입니다.
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]

+
link:concept_using_the_interoperability_matrix_tool_to_find_mcc_information.concept_using_the_interoperability_matrix_tool_to_find_mcc_information.html["상호 운용성 매트릭스 툴을 사용하여 MetroCluster 정보 찾기"]

* 다중 경로 HA는 브리지를 사용하는 MetroCluster 시스템에 대해 지원되는 유일한 구성입니다.
+
두 컨트롤러 모듈 모두 각 스택의 디스크 쉘프에 대한 브리지를 통해 액세스할 수 있어야 합니다.

* 각 사이트에서 동일한 수의 디스크 쉘프를 핫 추가해야 합니다.
* IP 관리 대신 브리지의 대역 내 관리를 사용하는 경우 관련 단계에 설명된 대로 이더넷 포트 및 IP 설정 구성 단계를 건너뛸 수 있습니다.



NOTE: ONTAP 9.8부터 스토리지 브리지 명령이 시스템 브리지로 바뀌었습니다. 다음 단계에서는 'Storage bridge' 명령어를 보여주지만, ONTAP 9.8 이상을 실행 중인 경우에는 'system bridge' 명령어를 사용한다.


IMPORTANT: SAS 케이블을 잘못된 포트에 삽입한 경우 SAS 포트에서 케이블을 분리할 때 다른 SAS 포트에 케이블을 연결하기 전에 최소 120초 정도 기다려야 합니다. 그렇지 않으면 시스템이 케이블이 다른 포트로 이동되었음을 인식하지 못합니다.

.단계
. 적절하게 접지합니다.
. 두 컨트롤러 모듈 중 하나의 콘솔에서 시스템에 디스크 자동 할당이 활성화되어 있는지 확인합니다.
+
'스토리지 디스크 옵션 표시'

+
자동 할당 열은 디스크 자동 할당이 설정되었는지 여부를 나타냅니다.

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 새 스택에 대한 스위치 포트를 비활성화합니다.
. 대역내 관리를 위해 구성하는 경우 FiberBridge RS-232 직렬 포트의 케이블을 PC의 직렬(COM) 포트에 연결합니다.
+
직렬 연결은 초기 구성에 사용된 다음 ONTAP 및 FC 포트를 통한 대역내 관리를 사용하여 브리지를 모니터링 및 관리할 수 있습니다.

. IP 관리를 위해 구성하는 경우 브리지 모델에 대한 _ATTO FiberBridge 설치 및 작동 설명서_의 2.0절에 나와 있는 절차에 따라 각 브리지에 대해 이더넷 관리 1 포트를 구성합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
Quicknav를 실행하여 이더넷 관리 포트를 구성하는 경우 이더넷 케이블로 연결된 이더넷 관리 포트만 구성됩니다. 예를 들어, 이더넷 관리 2 포트도 구성하려면 이더넷 케이블을 포트 2에 연결하고 Quicknav를 실행해야 합니다.

. 브리지를 구성합니다.
+
이전 브리지에서 구성 정보를 검색한 경우 해당 정보를 사용하여 새 브리지를 구성합니다.

+
지정한 사용자 이름과 암호를 기록해 두십시오.

+
브리지 모델의 _ATTO FiberBridge 설치 및 작동 설명서_에는 사용 가능한 명령과 사용 방법에 대한 최신 정보가 들어 있습니다.

+

NOTE: ATTO FiberBridge 7600N 또는 7500N에서 시간 동기화를 구성하지 마십시오. ONTAP에서 브리지가 검색된 후 ATTO FiberBridge 7600N 또는 7500N에 대한 시간 동기화가 클러스터 시간으로 설정됩니다. 또한 하루에 한 번 주기적으로 동기화됩니다. 사용된 표준 시간대는 GMT로 변경할 수 없습니다.

+
.. IP 관리를 구성하는 경우 브리지의 IP 설정을 구성합니다.
+
Qunav 유틸리티 없이 IP 주소를 설정하려면 FiberBridge에 대한 직렬 연결이 있어야 합니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'세트 ipaddress mp1_ip-address_'

+
'세트 ipsubnetmask mp1_subnet-mask_'

+
Set ipgateway mp1 x.x.x.x"입니다

+
세트 ipdhcp mp1이 비활성화되었습니다

+
세트 에테더넷스피드 mp1 1000

.. 브리지 이름을 구성합니다.
+
브리지는 MetroCluster 구성 내에서 각각 고유한 이름을 가져야 합니다.

+
각 사이트의 스택 그룹 하나에 대한 브리지 이름 예:

+
*** Bridge_A_1a
*** Bridge_a_1b
*** Bridge_B_1a
*** bridge_B_1b CLI를 사용하는 경우 다음 명령을 실행해야 합니다.
+
'메이 브리지네미_브리지네메 _'



.. ONTAP 9.4 이하를 실행하는 경우 브리지에서 SNMP를 활성화합니다. + 'SNMP 설정 활성화'
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.



. 브리지 FC 포트를 구성합니다.
+
.. 브리지 FC 포트의 데이터 속도/속도를 구성합니다.
+
지원되는 FC 데이터 속도는 모델 브리지에 따라 다릅니다.

+
*** FiberBridge 7600 브리지는 최대 32, 16 또는 8Gbps를 지원합니다.
*** FiberBridge 7500 브리지는 최대 16, 8 또는 4Gbps를 지원합니다.
*** FiberBridge 6500 브리지는 최대 8, 4 또는 2Gbps를 지원합니다.
+

NOTE: 선택한 FCDataRate 속도는 브리지 및 브리지 포트가 연결되는 스위치에서 지원하는 최대 속도로 제한됩니다. 케이블 연결 거리가 SFP 및 기타 하드웨어의 제한을 초과해서는 안 됩니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'Set FCDataRate_port-number port-speed_'를 참조하십시오



.. FiberBridge 7500N 또는 6500N 브리지를 구성하는 경우 해당 포트가 PTP에 사용하는 연결 모드를 구성합니다.
+

NOTE: FiberBridge 7600N 브리지를 구성할 때는 FCConnMode 설정이 필요하지 않습니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'Set FCConnMode_port-number_PTP'를 선택합니다

.. FiberBridge 7600N 또는 7500N 브리지를 구성하는 경우 FC2 포트를 구성하거나 비활성화해야 합니다.
+
*** 두 번째 포트를 사용하는 경우 FC2 포트에 대해 이전 하위 단계를 반복해야 합니다.
*** 두 번째 포트를 사용하지 않는 경우, + 'FCPortDisable_port-number_' 포트를 비활성화해야 합니다


.. FiberBridge 7600N 또는 7500N 브리지를 구성할 경우 사용하지 않는 SAS 포트(+'SASPortDisable_SAS-PORT_')를 비활성화합니다
+

NOTE: SAS 포트 A~D는 기본적으로 활성화되어 있습니다. 사용하지 않는 SAS 포트는 비활성화해야 합니다. SAS 포트 A만 사용하는 경우 SAS 포트 B, C 및 D를 비활성화해야 합니다.



. 브리지에 대한 액세스를 보호하고 브리지의 구성을 저장합니다.
+
.. 컨트롤러 프롬프트에서 브리지 상태를 확인합니다.
+
'스토리지 브리지 쇼'

+
출력에는 고정되지 않은 브리지가 표시됩니다.

.. 보안되지 않은 브리지의 포트 상태를 + "정보"로 확인한다
+
출력에는 이더넷 포트 MP1 및 MP2의 상태가 표시됩니다.

.. 이더넷 포트 MP1이 활성화된 경우 +'et EthernetPort mp1 disabled' 명령을 실행합니다
+

NOTE: 이더넷 포트 MP2도 활성화된 경우 포트 MP2에 대해 이전 하위 단계를 반복합니다.

.. 브리지의 구성을 저장합니다.
+
다음 명령을 실행해야 합니다.

+
'SaveConfiguration

+
펌웨어 재시작

+
브리지를 재시작하라는 메시지가 나타납니다.



. 각 브리지에서 FiberBridge 펌웨어를 업데이트합니다.
+
새 브리지가 파트너 브리지와 동일한 유형인 경우 파트너 브리지와 동일한 펌웨어로 업그레이드하십시오. 새 브리지가 파트너 브리지와 다른 유형인 경우 ONTAP 브리지 및 버전에서 지원하는 최신 펌웨어로 업그레이드하십시오. MetroCluster 유지 관리 가이드 _ 의 "FiberBridge 브리지에서 펌웨어 업데이트" 섹션을 참조하십시오.

. [[step10-cable-shelf-bridges]] 브리지에 디스크 쉘프 케이블 연결:
+
.. 각 스택의 디스크 쉘프를 데이지 체인 방식으로 연결합니다.
+
디스크 쉘프 모델의 _설치 가이드_에서 디스크 쉘프 데이지 체인 방식으로 연결되는 방법에 대한 자세한 정보를 얻을 수 있습니다.

.. 각 디스크 쉘프 스택의 경우, 첫 번째 쉘프의 IOM A를 FiberBridge A의 SAS 포트 A에 케이블로 연결한 다음, 마지막 쉘프의 IOM B를 FiberBridge B의 SAS 포트 A에 연결합니다
+
link:../install-fc/index.html["패브릭 연결 MetroCluster 설치 및 구성"]

+
link:../install-stretch/concept_considerations_differences.html["스트레치 MetroCluster 설치 및 구성"]

+
각 브리지는 디스크 쉘프 쌓기 위한 하나의 경로를 가지고 있으며, 브리지 A는 첫 번째 쉘프를 통해 스택의 A 측에 연결되고, 브리지 B는 마지막 쉘프를 통해 스택의 B 측에 연결됩니다.

+

NOTE: 브리지 SAS 포트 B가 비활성화되었습니다.



. [[step11-verify-each-bridge-detect] 각 브리지가 연결된 모든 디스크 드라이브와 디스크 쉘프를 브리지가 감지할 수 있는지 확인합니다.
+
[cols="30,70"]
|===


| 를 사용하는 경우... | 그러면... 


 a| 
ATTO ExpressNAV GUI
 a| 
.. 지원되는 웹 브라우저의 브라우저 상자에 브리지의 IP 주소를 입력합니다.
+
링크가 있는 ATTO FiberBridge 홈 페이지로 이동합니다.

.. 링크를 클릭한 다음 브리지를 구성할 때 지정한 사용자 이름과 암호를 입력합니다.
+
왼쪽에 메뉴가 있는 ATTO FiberBridge 상태 페이지가 나타납니다.

.. 메뉴에서 * 고급 * 을 클릭합니다.
.. 연결된 장치를 봅니다. + '시작
.. 제출 * 을 클릭합니다.




 a| 
직렬 포트 연결
 a| 
연결된 장치 보기:

'아스타우다스다'

|===
+
출력에는 브리지가 연결되는 장치(디스크 및 디스크 쉘프)가 표시됩니다. 출력 줄에 순차적으로 번호가 매겨서 장치를 빠르게 계산할 수 있습니다.

+

NOTE: 출력 시작 부분에 잘린 텍스트 응답이 나타나면 텔넷을 사용하여 브리지에 연결한 다음 '스타우더' 명령을 사용하여 모든 출력을 볼 수 있습니다.

+
다음 출력에서는 10개의 디스크가 연결되어 있음을 보여 줍니다.

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. 명령 출력에 브리지가 스택의 모든 해당 디스크 및 디스크 쉘프에 연결되어 있는지 확인합니다.
+
[cols="30,70"]
|===


| 출력이 다음과 같은 경우... | 그러면... 


 a| 
정답입니다
 a| 
반복합니다 <<step11-verify-each-bridge-detect,11단계>> 각 나머지 브리지에 대해.



 a| 
정답이 아닙니다
 a| 
.. SAS 케이블이 느슨하게 연결되었는지 확인하거나 SAS 케이블을 다시 연결하여 문제를 해결하십시오 <<step10-cable-shelves-bridges,10단계>>.
.. 반복합니다 <<step11-verify-each-bridge-detect,11단계>>.


|===
. 패브릭 연결 MetroCluster 구성을 구성하는 경우 구성, 스위치 모델 및 FC-to-SAS 브리지 모델에 대한 표에 나와 있는 케이블을 사용하여 각 브리지를 로컬 FC 스위치에 연결합니다.
+

NOTE: Brocade 및 Cisco 스위치는 다음 표와 같이 다른 포트 번호를 사용합니다.

+
** Brocade 스위치에서 첫 번째 포트는 ""0""으로 번호가 지정됩니다.
** Cisco 스위치에서 첫 번째 포트는 ""1""로 번호가 지정됩니다.
+
|===


13+| FC 포트(FC1 및 FC2)를 모두 사용하는 FiberBridge 7500N 또는 7600N을 사용하는 구성 


13+| DR 그룹 1 


3+|  2+| Brocade 6505 2+| Brocade 6510, Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G620, Brocade G620-1, Brocade G630, Brocade G630-1 2+| Brocade G720 


2+| 구성 요소 | 포트 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 


 a| 
스택 1
 a| 
Bridge_x_1a
 a| 
FC1
 a| 
8
 a| 
 a| 
8
 a| 
 a| 
8
 a| 
 a| 
8
 a| 
 a| 
10
 a| 



 a| 
FC2
 a| 
-
 a| 
8
 a| 
-
 a| 
8
 a| 
-
 a| 
8
 a| 
-
 a| 
8
 a| 
-
 a| 
10



 a| 
Bridge_x_1B
 a| 
FC1
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
11
 a| 
-



 a| 
FC2
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
11



 a| 
스택 2
 a| 
bridge_x_2a
 a| 
FC1
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
14
 a| 
-



 a| 
FC2
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
14



 a| 
Bridge_x_2B
 a| 
FC1
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
17
 a| 
-



 a| 
FC2
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
17



 a| 
스택 3
 a| 
Bridge_x_3a
 a| 
FC1
 a| 
12
 a| 
-
 a| 
12
 a| 
-
 a| 
12
 a| 
-
 a| 
12
 a| 
-
 a| 
18
 a| 
-



 a| 
FC2
 a| 
-
 a| 
12
 a| 
-
 a| 
12
 a| 
-
 a| 
12
 a| 
-
 a| 
12
 a| 
-
 a| 
18



 a| 
Bridge_x_3B
 a| 
FC1
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
19
 a| 
-



 a| 
FC2
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
19



 a| 
스택 y
 a| 
브리지 x _ 야
 a| 
FC1
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
20
 a| 
-



 a| 
FC2
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
20



 a| 
Bridge_x_yb입니다
 a| 
FC1
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
21
 a| 
-



 a| 
FC2
 a| 
--

-- a| 
15
 a| 
--

-- a| 
15
 a| 
--

-- a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
21



 a| 

NOTE: G620, G630, G620-1 및 G630-1 스위치의 포트 16, 17, 20 및 21에 추가 브리지를 연결할 수 있습니다.

|===
+
|===


11+| FC 포트(FC1 및 FC2)를 모두 사용하는 FiberBridge 7500N 또는 7600N을 사용하는 구성 


11+| DR 그룹 2 


3+|  2+| Brocade G620, Brocade G620-1, Brocade G630, Brocade G630-1 2+| Brocade 6510, Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G720 


2+| 구성 요소 | 포트 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 


 a| 
스택 1
 a| 
Bridge_x_51A
 a| 
FC1
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-
 a| 
32
 a| 
-



 a| 
FC2
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-
 a| 
32



 a| 
Bridge_x_51b
 a| 
FC1
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-
 a| 
33
 a| 
-



 a| 
FC2
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-
 a| 
33



 a| 
스택 2
 a| 
Bridge_x_52A
 a| 
FC1
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-
 a| 
34
 a| 
-



 a| 
FC2
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-
 a| 
34



 a| 
Bridge_x_52b
 a| 
FC1
 a| 
31
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-
 a| 
35
 a| 
-



 a| 
FC2
 a| 
-
 a| 
31
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-
 a| 
35



 a| 
스택 3
 a| 
Bridge_x_53a
 a| 
FC1
 a| 
32
 a| 
-
 a| 
36
 a| 
-
 a| 
60
 a| 
-
 a| 
36
 a| 
-



 a| 
FC2
 a| 
-
 a| 
32
 a| 
-
 a| 
36
 a| 
-
 a| 
60
 a| 
-
 a| 
36



 a| 
Bridge_x_53B
 a| 
FC1
 a| 
33
 a| 
-
 a| 
37
 a| 
-
 a| 
61
 a| 
-
 a| 
37
 a| 
-



 a| 
FC2
 a| 
-
 a| 
33
 a| 
-
 a| 
37
 a| 
-
 a| 
61
 a| 
-
 a| 
37



 a| 
스택 y
 a| 
브리지 x _ 5ya
 a| 
FC1
 a| 
34
 a| 
-
 a| 
38
 a| 
-
 a| 
62
 a| 
-
 a| 
38
 a| 
-



 a| 
FC2
 a| 
-
 a| 
34
 a| 
-
 a| 
38
 a| 
-
 a| 
62
 a| 
-
 a| 
38



 a| 
Bridge_x_5yb
 a| 
FC1
 a| 
35
 a| 
-
 a| 
39
 a| 
-
 a| 
63
 a| 
-
 a| 
39
 a| 
-



 a| 
FC2
 a| 
-
 a| 
35
 a| 
-
 a| 
39
 a| 
-
 a| 
63
 a| 
-
 a| 
39



 a| 

NOTE: G620, G630, G620-1 및 G-630-1 스위치의 포트 36-39에 추가 브리지를 연결할 수 있습니다.

|===
+
|===


12+| FC 포트(FC1 또는 FC2)를 하나만 사용하여 FiberBridge 6500N 브리지 또는 FiberBridge 7500N 또는 7600N을 사용하는 구성입니다 


12+| DR 그룹 1 


2+|  2+| Brocade 6505 2+| Brocade 6510, Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G620, Brocade G620-1, Brocade G630, Brocade G630-1 2+| Brocade G720 


| 구성 요소 | 포트 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 | 스위치 1 | 스위치 2 


 a| 
스택 1
 a| 
Bridge_x_1a
 a| 
8
 a| 
 a| 
8
 a| 
 a| 
8
 a| 
 a| 
8
 a| 
 a| 
10
 a| 



 a| 
Bridge_x_1b
 a| 
-
 a| 
8
 a| 
-
 a| 
8
 a| 
-
 a| 
8
 a| 
-
 a| 
8
 a| 
-
 a| 
10



 a| 
스택 2
 a| 
bridge_x_2a
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
11
 a| 
-



 a| 
Bridge_x_2b
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
9
 a| 
-
 a| 
11



 a| 
스택 3
 a| 
Bridge_x_3a
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
14
 a| 
-



 a| 
Bridge_x_4b
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
10
 a| 
-
 a| 
14



 a| 
스택 y
 a| 
브리지 x _ 야
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
15
 a| 
-



 a| 
Bridge_x_yb입니다
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
11
 a| 
-
 a| 
15



 a| 

NOTE: G620, G630, G620-1 및 G630-1 스위치의 포트 12-17, 20, 21에 추가 브리지를 연결할 수 있습니다. 포트 16-17, 20 및 21 G720 스위치에 추가 브리지를 연결할 수 있습니다.

|===
+
|===


10+| FC 포트(FC1 또는 FC2)를 하나만 사용하여 FiberBridge 6500N 브리지 또는 FiberBridge 7500N 또는 7600N을 사용하는 구성입니다 


10+| DR 그룹 2 


2+|  2+| Brocade G720 2+| Brocade G620, Brocade G620-1, Brocade G630, Brocade G630-1 2+| Brocade 6510, Brocade DCX 8510-8 2+| Brocade 6520 


 a| 
스택 1
 a| 
Bridge_x_51A
 a| 
32
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-



 a| 
Bridge_x_51b
 a| 
-
 a| 
32
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56



 a| 
스택 2
 a| 
Bridge_x_52A
 a| 
33
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-



 a| 
Bridge_x_52b
 a| 
-
 a| 
33
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57



 a| 
스택 3
 a| 
Bridge_x_53a
 a| 
34
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-



 a| 
Bridge_x_54b
 a| 
-
 a| 
34
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58



 a| 
스택 y
 a| 
브리지 x _ 야
 a| 
35
 a| 
-
 a| 
31
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-



 a| 
Bridge_x_yb입니다
 a| 
-
 a| 
35
 a| 
-
 a| 
31
 a| 
-
 a| 
35
 a| 
-
 a| 
59



 a| 

NOTE: G620, G630, G620-1 및 G630-1 스위치의 포트 32에서 39까지 추가 브리지를 연결할 수 있습니다. G720 스위치의 포트 36 - 39에 추가 브리지를 연결할 수 있습니다.

|===


. 브리지 연결 MetroCluster 시스템을 구성하는 경우 각 브리지를 컨트롤러 모듈에 케이블로 연결합니다.
+
.. 브리지의 FC 포트 1을 cluster_A의 컨트롤러 모듈에 있는 16Gb 또는 8Gb FC 포트에 케이블로 연결합니다
.. 브리지의 FC 포트 2를 cluster_A에 있는 컨트롤러 모듈의 동일한 속도 FC 포트에 연결합니다
.. 모든 브리지가 케이블로 연결될 때까지 다른 후속 브리지에서 이 하위 단계를 반복합니다.


. 시스템 콘솔에서 디스크 드라이브 펌웨어를 최신 버전으로 업데이트합니다.
+
"디스크_FW_UPDATE"입니다

+
두 컨트롤러 모듈 모두에서 이 명령을 실행해야 합니다.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"^]

. 다운로드한 펌웨어의 지침을 사용하여 디스크 쉘프 펌웨어를 최신 버전으로 업데이트합니다.
+
절차의 명령은 두 컨트롤러 모듈 중 하나의 시스템 콘솔에서 실행할 수 있습니다.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"^]

. 시스템에 디스크 자동 할당이 설정되어 있지 않으면 디스크 드라이브 소유권을 할당합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"^]

+

NOTE: 단일 디스크 쉘프 스택의 소유권을 여러 컨트롤러 모듈로 분할하는 경우 디스크 소유권을 할당하기 전에 클러스터의 두 노드에서 디스크 자동 할당을 비활성화해야 합니다('스토리지 디스크 옵션 수정 - 자동 할당 해제 *'). 그렇지 않으면 단일 디스크 드라이브를 할당할 때 나머지 디스크 드라이브가 동일한 컨트롤러 모듈 및 풀에 자동으로 할당될 수 있습니다.

+

NOTE: 디스크 드라이브 펌웨어 및 디스크 쉘프 펌웨어가 업데이트되고 이 작업의 검증 단계가 완료될 때까지 디스크 드라이브를 Aggregate 또는 볼륨에 추가할 수 없습니다.

. 새 스택에 대한 스위치 포트를 활성화합니다.
. ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 시스템이 multipathed인지 확인한다: + 'node run-node_node-name_sysconfig-a'
.. 두 클러스터에 대한 상태 알림이 있는지 확인합니다. + 'system health alert show'
.. MetroCluster 설정을 확인하고 운영 모드가 정상인지 확인합니다. + 'MetroCluster show'
.. MetroCluster check 수행: + 'MetroCluster check run
.. MetroCluster check:+'MetroCluster check show'의 결과를 출력한다
.. 스위치에 대한 상태 경고(있는 경우): + 스토리지 스위치 표시 여부를 확인합니다
.. Config Advisor를 실행합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"^]

.. Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.


. 해당되는 경우 파트너 사이트에 대해 이 절차를 반복합니다.


link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC-to-SAS 브리지의 대역 내 관리"]
