---
permalink: maintain/task_add_lsls_to_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, isl, cisco, switch 
summary: 추가 또는 더 빠른 컨트롤러 또는 더 빠른 스위치와 같은 하드웨어를 추가하거나 업그레이드하는 경우 스위치에 ISL을 추가해야 할 수 있습니다. 
---
= Cisco 스위치에 lSLs 추가
:icons: font
:imagesdir: ../media/


[role="lead"]
추가 또는 더 빠른 컨트롤러 또는 더 빠른 스위치와 같은 하드웨어를 추가하거나 업그레이드하는 경우 스위치에 ISL을 추가해야 할 수 있습니다.

한 스위치에서 완료된 단계는 ISL 연결을 보장하기 위해 다른 스위치에서도 완료해야 합니다.

.단계
. Fabric의 두 스위치에 추가할 ISL의 ISL 포트 비활성화:
+
``FC_SWITCH_A_1#config t *’

+
구성 명령을 한 줄에 하나씩 입력합니다. 모든 설정 명령을 입력한 후 CTRL-Z로 종료합니다.

+
[listing]
----

	FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. ISL 포트로 추가할 포트에 SFP를 삽입하고 _설치 및 구성 가이드_에 따라 케이블을 연결합니다.
+
이러한 포트가 추가하는 스위치의 _설치 및 구성 안내서_에 나열되어 있는지 확인합니다.

. 설치 및 구성 가이드 _ 에 따라 ISL 포트를 구성합니다.
. Fabric의 두 스위치에서 모든 ISL 포트(활성화되지 않은 경우)를 활성화합니다.
+
``FC_SWITCH_A_1#config t *’

+
구성 명령을 한 줄에 하나씩 입력합니다. CTRL-Z로 끝냅니다

+
[listing]
----

 FC_switch_A_1# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. 두 스위치 간에 ISL이 설정되었는지 확인합니다.
+
'* show topology ISL * '

. 두 번째 패브릭에서 이 절차를 반복합니다.
+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----

