---
permalink: install-stretch/reference_information_gathering_worksheet_for_fc_to_sas_bridges_2_node_atto.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, worksheet, fc, sas, bridges, information 
summary: MetroCluster 사이트를 구성하기 전에 필요한 구성 정보를 수집해야 합니다. 
---
= FC-to-SAS 브리지에 대한 정보 수집 워크시트
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 사이트를 구성하기 전에 필요한 구성 정보를 수집해야 합니다.



== 사이트 A, FC-to-SAS 브리지 1(FC_bridge_A_1a)

각 SAS 스택에는 FC-to-SAS 브리지가 2개 이상 필요합니다.

각 브리지는 Controller_A_1_"__port-number_" 및 Controller_B_1_"__port-number_"에 연결됩니다.

|===


| 사이트 A | 귀사의 가치 


 a| 
bridge_a_1a IP 주소입니다
 a| 



 a| 
Bridge_A_1a 사용자 이름
 a| 



 a| 
bridge_a_1a 암호
 a| 

|===


== 사이트 A, FC-to-SAS 브리지 2(FC_bridge_A_1b)

각 SAS 스택에는 FC-to-SAS 브리지가 2개 이상 필요합니다.

각 브리지는 Controller_A_1_"__port-number_" 및 Controller_B_1_"__port-number_"에 연결됩니다.

|===


| 사이트 A | 귀사의 가치 


 a| 
bridge_a_1b IP 주소입니다
 a| 



 a| 
bridge_a_1b 사용자 이름
 a| 



 a| 
bridge_a_1b 암호
 a| 

|===


== 사이트 B, FC-to-SAS 브리지 1(FC_bridge_B_1a)

각 SAS 스택에는 FC-to-SAS 브리지가 2개 이상 필요합니다.

각 브리지는 Controller_A_1_'__port-number_' 및 Controller_B_1_'__port-number_'에 연결됩니다.

|===


| 사이트 B | 귀사의 가치 


 a| 
bridge_B_1a IP 주소입니다
 a| 



 a| 
Bridge_B_1a 사용자 이름
 a| 



 a| 
bridge_B_1a 암호
 a| 

|===


== 사이트 B, FC-to-SAS 브리지 2(FC_bridge_B_1b)

각 SAS 스택에는 FC-to-SAS 브리지가 2개 이상 필요합니다.

각 브리지는 Controller_A_1_'__port-number_' 및 Controller_B_1_'__port-number_'에 연결됩니다.

|===


| 사이트 B | 귀사의 가치 


 a| 
bridge_B_1b IP 주소입니다
 a| 



 a| 
Bridge_B_1b 사용자 이름
 a| 



 a| 
Bridge_B_1b 암호
 a| 

|===