---
permalink: install-stretch/task_fb_new_install_prepare.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, prepare 
summary: 새 MetroCluster 시스템의 일부로 브리지를 설치할 준비가 되면 시스템이 특정 요구 사항을 충족하는지 확인해야 합니다. 여기에는 브리지의 설정 및 구성 요구 사항을 충족하는 작업이 포함됩니다. 기타 요구사항으로는 필요한 문서 다운로드, ATTO Quicknav 유틸리티 및 브리지 펌웨어 등이 있습니다. 
---
= 설치 준비 중
:icons: font
:imagesdir: ../media/


[role="lead"]
새 MetroCluster 시스템의 일부로 브리지를 설치할 준비가 되면 시스템이 특정 요구 사항을 충족하는지 확인해야 합니다. 여기에는 브리지의 설정 및 구성 요구 사항을 충족하는 작업이 포함됩니다. 기타 요구사항으로는 필요한 문서 다운로드, ATTO Quicknav 유틸리티 및 브리지 펌웨어 등이 있습니다.



== 시작하기 전에

* 시스템이 시스템 캐비닛에 제공되지 않은 경우 랙에 설치되어 있어야 합니다.
* 지원되는 하드웨어 모델 및 소프트웨어 버전을 사용하여 구성해야 합니다.
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]

+
IMT에서 스토리지 솔루션 필드를 사용하여 MetroCluster 솔루션을 선택할 수 있습니다. 부품 탐색기 * 를 사용하여 부품 및 ONTAP 버전을 선택하여 검색을 구체화합니다. 결과 표시 * 를 클릭하여 조건에 맞는 지원되는 설정 목록을 표시할 수 있습니다.

* 각 FC 스위치에는 한 브리지에 연결할 수 있는 FC 포트가 하나 있어야 합니다.
* SAS 케이블을 처리하는 방법과 디스크 쉘프 설치 및 케이블 연결에 대한 고려 사항 및 모범 사례를 숙지해야 합니다.
+
디스크 쉘프 모델의 _설치 및 서비스 가이드_에서 고려 사항 및 모범 사례를 설명합니다.

* 브리지를 설정하는 데 사용하는 컴퓨터는 ATTO ExpressNAV GUI를 사용하려면 ATTO 지원 웹 브라우저를 실행해야 합니다.
+
ATTO 제품 릴리스 노트_에는 지원되는 웹 브라우저의 최신 목록이 있습니다. 다음 단계에 설명된 대로 ATTO 웹 사이트에서 이 문서에 액세스할 수 있습니다.



.단계
. 디스크 쉘프 모델의 _설치 및 서비스 가이드_를 다운로드하십시오.
. FiberBridge 모델에 제공된 링크를 사용하여 ATTO 웹 사이트에 액세스하고 설명서 및 Qunickav 유틸리티를 다운로드합니다.
+
[NOTE]
====
모델 브리지의 _ATTO FiberBridge 설치 및 작동 설명서_에는 관리 인터페이스에 대한 자세한 정보가 나와 있습니다.

ATTO Fiberbridge Description(ATTO Fiberbridge 설명) 페이지에 제공된 링크를 사용하여 ATTO 웹 사이트의 이 콘텐츠 및 기타 콘텐츠에 액세스할 수 있습니다.

====
. 권장되는 브리지 관리 인터페이스, ATTO ExpressNAV GUI 및 ATTO Qunav 유틸리티를 사용하는 데 필요한 하드웨어 및 정보를 수집합니다.
+
.. 기본 사용자 이름과 암호가 아닌 사용자 이름 및 암호를 확인합니다(브리지 액세스용).
+
기본 사용자 이름과 암호를 변경해야 합니다.

.. 브리지의 IP 관리를 구성하는 경우 브리지와 함께 제공되는 차폐 이더넷 케이블이 필요합니다(브리지 이더넷 관리 1 포트에서 네트워크로 연결).
.. 브리지의 IP 관리를 구성하려면 각 브리지의 이더넷 관리 1 포트에 대한 IP 주소, 서브넷 마스크 및 게이트웨이 정보가 필요합니다.
.. 설정에 사용 중인 컴퓨터에서 VPN 클라이언트를 비활성화합니다.
+
활성 VPN 클라이언트는 브리지에 대한 Quicknav 스캔을 실패하게 합니다.




