---
permalink: install-stretch/task_configure_the_fc_to_sas_bridges_fb_new_install_configure.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, configuration, fc, sas, bridges 
summary: FC-to-SAS 브릿지의 모델을 케이블로 연결하기 전에 FiberBridge 소프트웨어에서 설정을 구성해야 합니다. 
---
= FC-to-SAS 브릿지 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FC-to-SAS 브릿지의 모델을 케이블로 연결하기 전에 FiberBridge 소프트웨어에서 설정을 구성해야 합니다.

.이 작업에 대해
브리지 대역 내 관리를 사용할지 여부를 결정해야 합니다.


NOTE: ONTAP 9.8부터 스토리지 브리지 명령이 시스템 브리지로 바뀌었습니다. 다음 단계에서는 'Storage bridge' 명령을 보여 줍니다. 그러나 ONTAP 9.8 이상을 실행 중인 경우에는 시스템 브리지 명령을 사용하는 것이 좋습니다.

IP 관리 대신 브리지의 대역 내 관리를 사용하는 경우 이더넷 포트 및 IP 설정 구성 단계를 건너뛸 수 있습니다.

.단계
. 대역내 관리를 위해 구성하는 경우 FiberBridge RS-232 직렬 포트의 케이블을 PC의 직렬(COM) 포트에 연결합니다.
+
직렬 연결은 초기 구성에 사용됩니다. 그런 다음 ONTAP 및 FC 포트를 통한 대역 내 관리를 사용하여 브리지를 모니터링하고 관리할 수 있습니다.

. IP 관리를 구성하는 경우 이더넷 케이블을 사용하여 각 브리지의 이더넷 관리 1 포트를 네트워크에 연결합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
이더넷 관리 1 포트를 사용하면 브리지 펌웨어(ATTO ExpressNAV 또는 FTP 관리 인터페이스 사용)를 빠르게 다운로드하고 코어 파일을 검색하고 로그를 추출할 수 있습니다.

. IP 관리를 위해 구성하는 경우 브리지 모델에 대한 _ATTO FiberBridge 설치 및 작동 설명서_의 2.0절에 나와 있는 절차에 따라 각 브리지에 대해 이더넷 관리 1 포트를 구성합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
Quicknav를 실행하여 이더넷 관리 포트를 구성하는 경우 이더넷 케이블로 연결된 이더넷 관리 포트만 구성됩니다. 예를 들어, 이더넷 관리 2 포트도 구성하려면 이더넷 케이블을 포트 2에 연결하고 Quicknav를 실행해야 합니다.

. 브리지를 구성합니다.
+
지정한 사용자 이름과 암호를 기록해 두어야 합니다.

+

NOTE: ATTO FiberBridge 7600N 또는 7500N에서 시간 동기화를 구성하지 마십시오. ONTAP에서 브리지가 검색된 후 ATTO FiberBridge 7600N 또는 7500N에 대한 시간 동기화가 클러스터 시간으로 설정됩니다. 또한 하루에 한 번 주기적으로 동기화됩니다. 사용된 표준 시간대는 GMT로 변경할 수 없습니다.

+
.. IP 관리를 구성하는 경우 브리지의 IP 설정을 구성합니다.
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.

+
Qunav 유틸리티 없이 IP 주소를 설정하려면 FiberBridge에 대한 직렬 연결이 있어야 합니다.

+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'세트 ipaddress mp1_ip-address_'

+
'세트 ipsubnetmask mp1_subnet-mask_'

+
Set ipgateway mp1 x.x.x.x"입니다

+
세트 ipdhcp mp1이 비활성화되었습니다

+
세트 에테더넷스피드 mp1 1000

.. 브리지 이름을 구성합니다.
+
브리지는 MetroCluster 구성 내에서 각각 고유한 이름을 가져야 합니다.

+
각 사이트의 스택 그룹 하나에 대한 브리지 이름 예:

+
*** Bridge_A_1a
*** Bridge_a_1b
*** Bridge_B_1a
*** Bridge_B_1b
+
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

+
'메이 브리지네미_브리지네메 _'



.. ONTAP 9.4 이하를 실행하는 경우 브리지에서 SNMP를 활성화합니다. + 'SNMP 설정 활성화'
+
ONTAP 9.5 이상을 실행하는 시스템에서 대역내 관리를 사용하여 이더넷 포트가 아닌 FC 포트를 통해 브리지에 액세스할 수 있습니다. ONTAP 9.8부터는 대역내 관리만 지원되며 SNMP 관리는 사용되지 않습니다.



. 브리지 FC 포트를 구성합니다.
+
.. 브리지 FC 포트의 데이터 속도/속도를 구성합니다.
+
지원되는 FC 데이터 속도는 모델 브리지에 따라 다릅니다.

+
*** FiberBridge 7600N 브리지는 최대 32, 16 또는 8Gbps를 지원합니다.
*** FiberBridge 7500N 브리지는 최대 16, 8 또는 4Gbps를 지원합니다.
+

NOTE: 선택한 FCDataRate 속도는 브리지 포트가 연결되는 컨트롤러 모듈의 브리지 및 FC 포트에서 지원하는 최대 속도로 제한됩니다. 케이블 연결 거리가 SFP 및 기타 하드웨어의 제한을 초과해서는 안 됩니다.

+
--
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

'Set FCDataRate_port-numberport-speed_'를 참조하십시오

--


.. FiberBridge 7500N 브리지를 구성하는 경우 포트가 "PTP"에 사용하는 연결 모드를 구성합니다.
+

NOTE: FiberBridge 7600N 브리지를 구성할 때는 FCConnMode 설정이 필요하지 않습니다.

+
--
CLI를 사용하는 경우 다음 명령을 실행해야 합니다.

'Set FCConnMode_port-number_PTP'를 선택합니다

--
.. FiberBridge 7600N 또는 7500N 브리지를 구성하는 경우 FC2 포트를 구성하거나 비활성화해야 합니다.
+
*** 두 번째 포트를 사용하는 경우 FC2 포트에 대해 이전 하위 단계를 반복해야 합니다.
*** 두 번째 포트를 사용하지 않는 경우 포트 + "FCPortDisable port-number"를 비활성화해야 합니다
+
다음 예는 FC 포트 2의 비활성화 상태를 보여줍니다.

+
[listing]
----
FCPortDisable 2

Fibre Channel Port 2 has been disabled.
----


.. FiberBridge 7600N 또는 7500N 브리지를 구성할 경우 사용하지 않는 SAS 포트(+'SASPortDisable_SAS-PORT_')를 비활성화합니다
+

NOTE: SAS 포트 A~D는 기본적으로 활성화되어 있습니다. 사용하지 않는 SAS 포트는 비활성화해야 합니다.

+
SAS 포트 A만 사용하는 경우 SAS 포트 B, C 및 D를 비활성화해야 합니다. 다음 예는 SAS 포트 B의 비활성화를 보여줍니다 마찬가지로 SAS 포트 C와 D를 비활성화해야 합니다.

+
....
SASPortDisable b

SAS Port B has been disabled.
....


. 브리지에 대한 액세스를 보호하고 브리지의 구성을 저장합니다. 시스템이 실행 중인 ONTAP 버전에 따라 아래에서 옵션을 선택합니다.
+
|===


| ONTAP 버전입니다 | 단계 


 a| 
* ONTAP 9.5 이상 *
 a| 
.. 교량 현황 보기: 'Storage bridge show'
+
출력에는 고정되지 않은 브리지가 표시됩니다.

.. 다리를 단단히 고정하세요




 a| 
* ONTAP 9.4 이하 *
 a| 
.. 교량 현황 보기: 'Storage bridge show'
+
출력에는 고정되지 않은 브리지가 표시됩니다.

.. 비보안 브리지 포트의 상태를 확인합니다.
+
'정보'

+
출력에는 이더넷 포트 MP1 및 MP2의 상태가 표시됩니다.

.. 이더넷 포트 MP1이 활성화된 경우 다음을 실행합니다.
+
'Eet EthernetPort mp1 disabled'

+
이더넷 포트 MP2도 활성화된 경우 포트 MP2에 대해 이전 하위 단계를 반복합니다.

.. 브리지의 구성을 저장합니다.
+
다음 명령을 실행해야 합니다.

+
'SaveConfiguration

+
펌웨어 재시작

+
브리지를 재시작하라는 메시지가 나타납니다.



|===
. MetroCluster 구성을 완료한 후 'flashimages' 명령을 사용하여 FiberBridge 펌웨어 버전을 확인하고 브리지가 지원되는 최신 버전을 사용하지 않는 경우 구성의 모든 브리지에서 펌웨어를 업데이트합니다.
+
link:../maintain/index.html["MetroCluster 부품 유지 관리"]



.관련 정보
link:concept_in_band_management_of_the_fc_to_sas_bridges.html["FC-to-SAS 브리지의 대역 내 관리"]
