---
permalink: manage/concept_monitoring_the_mcc_configuration.html 
sidebar: sidebar 
keywords: ontap, metrocluster, command, active, iq, unified, manager, oncommand, unified, monitor, health, software, state, component, operation, check, configuration, configuration, detect, failure, netapp, tiebreaker, software 
summary: 'ONTAP MetroCluster 명령 및 Active IQ Unified Manager(이전의 OnCommand Unified Manager)를 사용하여 다양한 소프트웨어 구성 요소의 상태와 MetroCluster 작업 상태를 모니터링할 수 있습니다.' 
---
= MetroCluster 구성 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP MetroCluster 명령 및 Active IQ Unified Manager(이전의 OnCommand Unified Manager)를 사용하여 다양한 소프트웨어 구성 요소의 상태와 MetroCluster 작업 상태를 모니터링할 수 있습니다.



== MetroCluster 구성 확인

MetroCluster 설정의 구성 요소와 관계가 올바르게 작동하는지 확인할 수 있습니다. 초기 구성 후 MetroCluster 구성을 변경한 후 확인해야 합니다. 또한 협상된(계획된) 스위치오버 또는 스위치백 작업 전에 확인해야 합니다.

.이 작업에 대해
둘 중 하나 또는 두 클러스터에서 짧은 시간 내에 'MetroCluster check run' 명령을 두 번 실행하면 충돌이 발생하고 명령이 모든 데이터를 수집하지 못할 수 있습니다. 이후 'MetroCluster check show' 명령어에서는 예상 출력이 표시되지 않습니다.

.단계
. 구성을 확인합니다.
+
'MetroCluster check run

+
명령은 백그라운드 작업으로 실행되며 즉시 완료되지 않을 수 있습니다.

+
[listing]
----
cluster_A::> metrocluster check run
The operation has been started and is running in the background. Wait for
it to complete and run "metrocluster check show" to view the results. To
check the status of the running metrocluster check operation, use the command,
"metrocluster operation history show -job-id 2245"
----
. 가장 최근의 'MetroCluster check run' 명령어를 통해 보다 상세한 결과를 출력한다.
+
'MetroCluster check aggregate show'

+
'MetroCluster check cluster show'를 선택합니다

+
'MetroCluster check config-replication show'를 선택합니다

+
'MetroCluster check lif show'

+
MetroCluster check node show

+
MetroCluster check show 명령은 최근 MetroCluster check run 명령의 결과를 보여준다. MetroCluster check show 명령을 사용하기 전에 항상 MetroCluster check run 명령을 실행하여 표시되는 정보가 최신 정보가 되도록 해야 합니다.

+
다음 예는 양호한 4노드 MetroCluster 구성을 위한 'MetroCluster check aggregate show' 명령 출력을 보여줍니다.

+
[listing]
----
cluster_A::> metrocluster check aggregate show

Last Checked On: 8/5/2014 00:42:58

Node                  Aggregate                  Check                      Result
---------------       --------------------       ---------------------      ---------
controller_A_1        controller_A_1_aggr0
                                                 mirroring-status           ok
                                                 disk-pool-allocation       ok
                                                 ownership-state            ok
                      controller_A_1_aggr1
                                                 mirroring-status           ok
                                                 disk-pool-allocation       ok
                                                 ownership-state            ok
                      controller_A_1_aggr2
                                                 mirroring-status           ok
                                                 disk-pool-allocation       ok
                                                 ownership-state            ok


controller_A_2        controller_A_2_aggr0
                                                 mirroring-status           ok
                                                 disk-pool-allocation       ok
                                                 ownership-state            ok
                      controller_A_2_aggr1
                                                 mirroring-status           ok
                                                 disk-pool-allocation       ok
                                                 ownership-state            ok
                      controller_A_2_aggr2
                                                 mirroring-status           ok
                                                 disk-pool-allocation       ok
                                                 ownership-state            ok

18 entries were displayed.
----
+
다음 예에서는 양호한 4노드 MetroCluster 구성을 위한 'MetroCluster check cluster show' 명령 출력을 보여 줍니다. 이는 필요한 경우 클러스터가 협상된 전환을 수행할 준비가 되었음을 나타냅니다.

+
[listing]
----
Last Checked On: 9/13/2017 20:47:04

Cluster               Check                           Result
--------------------- ------------------------------- ---------
mccint-fas9000-0102
                      negotiated-switchover-ready     not-applicable
                      switchback-ready                not-applicable
                      job-schedules                   ok
                      licenses                        ok
                      periodic-check-enabled          ok
mccint-fas9000-0304
                      negotiated-switchover-ready     not-applicable
                      switchback-ready                not-applicable
                      job-schedules                   ok
                      licenses                        ok
                      periodic-check-enabled          ok
10 entries were displayed.
----




== MetroCluster 구성 확인 및 모니터링을 위한 명령입니다

MetroCluster 구성을 모니터링하고 MetroCluster 작업을 확인하기 위한 특정 ONTAP 명령이 있습니다.



=== MetroCluster 작업을 확인하는 명령입니다

|===


| 원하는 작업 | 이 명령 사용... 


 a| 
MetroCluster 작업을 확인합니다.

* 참고: * 이 명령은 사전 DR 운영 시스템 유효성 검사를 위한 유일한 명령으로 사용해서는 안 됩니다.
 a| 
'MetroCluster check run



 a| 
MetroCluster 작업에 대한 마지막 확인 결과를 봅니다.
 a| 
MetroCluster 쇼



 a| 
사이트 간 구성 복제에 대한 검사 결과를 봅니다.
 a| 
'MetroCluster check config-replication show MetroCluster check config-replication show-aggregate-eligibility'를 참조하십시오



 a| 
노드 구성에서 검사 결과를 봅니다.
 a| 
MetroCluster check node show



 a| 
애그리게이트 구성에서 검사 결과를 봅니다.
 a| 
'MetroCluster check aggregate show'



 a| 
MetroCluster 구성에서 LIF 배치 오류를 봅니다.
 a| 
'MetroCluster check lif show'

|===


=== MetroCluster 상호 연결을 모니터링하는 명령입니다

|===


| 원하는 작업 | 이 명령 사용... 


 a| 
클러스터의 MetroCluster 노드에 대한 HA 및 DR 미러링 상태와 정보를 표시합니다.
 a| 
MetroCluster 상호 연결 미러 쇼

|===


=== MetroCluster SVM을 모니터링하는 명령

|===


| 원하는 작업 | 이 명령 사용... 


 a| 
MetroCluster 구성의 두 사이트 모두에서 모든 SVM을 확인합니다.
 a| 
'MetroCluster vserver show'

|===


== MetroCluster Tiebreaker 또는 ONTAP 중재자를 사용하여 구성을 모니터링합니다

을 참조하십시오 link:../install-ip/concept_considerations_mediator.html["ONTAP 중재자와 MetroCluster Tiebreaker의 차이점"] MetroCluster 구성을 모니터링하고 자동 전환을 시작하는 두 가지 방법의 차이점을 이해합니다.

다음 링크를 사용하여 Tiebreaker 또는 중재자를 설치 및 구성합니다.

* link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker 소프트웨어를 설치하고 구성합니다"]
* link:../install-ip/concept_mediator_requirements.html["ONTAP 중재자 서비스 설치 준비"]




== NetApp MetroCluster Tiebreaker 소프트웨어가 장애를 감지하는 방식

Tiebreaker 소프트웨어는 Linux 호스트에 상주합니다. 두 클러스터를 모니터링하고 세 번째 사이트에서 클러스터 간 연결 상태를 모니터링하려는 경우에만 Tiebreaker 소프트웨어가 필요합니다. 이렇게 하면 클러스터의 각 파트너가 사이트 간 링크가 다운된 경우 사이트 장애와 ISL 장애를 구분할 수 있습니다.

Linux 호스트에 Tiebreaker 소프트웨어를 설치한 후 MetroCluster 구성에서 클러스터를 구성하여 재해 상황을 모니터링할 수 있습니다.



=== Tiebreaker 소프트웨어가 사이트 간 연결 장애를 감지하는 방식

MetroCluster Tiebreaker 소프트웨어는 사이트 간 연결이 모두 끊어지면 알려줍니다.



==== 네트워크 경로의 유형입니다

구성에 따라 MetroCluster 구성의 두 클러스터 간에는 세 가지 유형의 네트워크 경로가 있습니다.

* * FC 네트워크(패브릭 연결 MetroCluster 구성에 제공) *
+
이 유형의 네트워크는 두 개의 이중화 FC 스위치 패브릭으로 구성됩니다. 각 스위치 패브릭은 2개의 FC 스위치를 가지고 있으며, 각 스위치 패브릭은 클러스터와 함께 배치되어 있습니다. 각 클러스터에는 각 스위치 패브릭에서 하나씩 두 개의 FC 스위치가 있습니다. 모든 노드에는 공동 배치된 각 IP 스위치에 대한 FC(NV 상호 연결 및 FCP 이니시에이터) 연결이 있습니다. 데이터는 ISL을 통해 클러스터에서 클러스터로 복제됩니다.

* * 클러스터 간 피어링 네트워크 *
+
이 유형의 네트워크는 두 클러스터 간의 중복 IP 네트워크 경로로 구성됩니다. 클러스터 피어링 네트워크는 SVM(스토리지 가상 머신) 구성을 미러링하는 데 필요한 연결을 제공합니다. 단일 클러스터에 있는 모든 SVM의 구성은 파트너 클러스터에 의해 미러링됩니다.

* * IP 네트워크(MetroCluster IP 구성에 있음) *
+
이 유형의 네트워크는 두 개의 중복 IP 스위치 네트워크로 구성됩니다. 각 네트워크에는 2개의 IP 스위치가 있으며 각 스위치 패브릭의 스위치는 클러스터와 함께 위치합니다. 각 클러스터에는 각 스위치 패브릭에서 하나씩 두 개의 IP 스위치가 있습니다. 모든 노드는 공동 배치된 각 FC 스위치에 연결됩니다. 데이터는 ISL을 통해 클러스터에서 클러스터로 복제됩니다.





==== 사이트 간 연결 모니터링

Tiebreaker 소프트웨어는 노드에서 사이트 간 연결 상태를 정기적으로 검색합니다. NV 상호 연결 연결이 끊어지고 인터클러스터 피어링이 핑에 응답하지 않는 경우 클러스터는 사이트가 격리되었다고 간주하고 Tiebreaker 소프트웨어는 경고를 "AllLinksSegan"으로 트리거합니다. 클러스터에서 "AllLinksSegable" 상태를 식별하고 다른 클러스터에 연결할 수 없는 경우 Tiebreaker 소프트웨어는 경고를 "재해"로 트리거합니다.



=== Tiebreaker 소프트웨어가 사이트 장애를 감지하는 방식

NetApp MetroCluster Tiebreaker 소프트웨어는 MetroCluster 구성과 클러스터에서 노드의 내성을 확인하여 사이트 장애가 발생했는지 판단합니다. Tiebreaker 소프트웨어는 특정 조건에서 경고를 트리거합니다.



==== Tiebreaker 소프트웨어를 통해 모니터링되는 구성 요소입니다

Tiebreaker 소프트웨어는 노드 관리 LIF와 클러스터 관리 LIF에 대한 다중 경로를 통해 이중 연결을 설정하고, 둘 다 IP 네트워크에서 호스팅되는 클러스터 관리 LIF를 설정하여 MetroCluster 구성의 각 컨트롤러를 모니터링합니다.

Tiebreaker 소프트웨어는 MetroCluster 구성에서 다음 구성 요소를 모니터링합니다.

* 노드에서 워크로드 지원
* 클러스터에서 지정된 인터페이스를 통해 클러스터링합니다
* 장애가 발생한 사이트(NV 상호 연결, 스토리지 및 피어링)에 대한 연결이 있는지 평가할 수 있는 정상적인 클러스터


Tiebreaker 소프트웨어와 클러스터의 모든 노드 및 클러스터 자체 간에 연결이 끊어지면 Tiebreaker 소프트웨어가 클러스터를 ""연결할 수 없음""으로 선언합니다. 연결 장애를 감지하는 데 약 3~5초 정도 걸립니다. Tiebreaker 소프트웨어에서 클러스터에 연결할 수 없는 경우, Tiebreaker 소프트웨어가 경고를 트리거하기 전에 정상적인 클러스터(아직 연결할 수 있는 클러스터)에서 파트너 클러스터에 대한 모든 링크가 분리되었음을 표시해야 합니다.


NOTE: 정상적인 클러스터가 FC(NV 상호 연결 및 스토리지) 및 인터클러스터 피어링을 통해 재해 사이트의 클러스터와 더 이상 통신할 수 없는 경우 모든 링크가 끊깁니다.



==== Tiebreaker 소프트웨어가 알림을 트리거하는 실패 시나리오

Tiebreaker 소프트웨어는 재해 사이트의 클러스터(모든 노드)가 다운되거나 연결할 수 없을 때 경고를 트리거하고, 정상적인 사이트의 클러스터에 "AllLinksSegan" 상태가 표시됩니다.

Tiebreaker 소프트웨어는 다음 시나리오에서 경고를 트리거하지(또는 경고에 거부권을 행사하지 않음).

* 8노드 MetroCluster 구성에서는 재해 사이트에서 HA 쌍 하나가 다운된 경우
* 재해 사이트의 모든 노드가 다운된 클러스터에서 정상 작동 중인 사이트 다운에 있는 HA 쌍 하나, 정상적인 사이트의 클러스터는 "AllLinksSe존경된" 상태를 나타냅니다
+
Tiebreaker 소프트웨어가 알림을 트리거하지만, ONTAP은 알림을 확인합니다. 이 상황에서는 수동 스위치오버도 거부됩니다

* Tiebreaker 소프트웨어가 재해 사이트에서 하나 이상의 노드 또는 클러스터 인터페이스에 연결할 수 있거나, 정상적인 사이트에서 FC(NV 상호 연결 및 스토리지) 또는 인터클러스터 피어링을 통해 재해 사이트의 어느 노드에도 계속 연결할 수 있는 시나리오입니다




=== ONTAP 중재자가 자동 계획되지 않은 전환을 지원하는 방법

link:../install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP mediator가 MetroCluster IP 구성에서 예기치 않은 자동 전환을 지원하는 방법에 대해 알아보십시오"].
