---
permalink: manage/reference_where_to_find_additional_information_dr_guide.html 
sidebar: sidebar 
keywords: learn, metrocluster, configuration, operation, netapp, extensive, documentation, additional, information, miscellaneous, guide 
summary: MetroCluster 구성 및 작동에 대한 자세한 내용은 NetApp의 광범위한 문서를 참조하십시오. 
---
= 추가 정보를 찾을 수 있는 위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성 및 작동에 대해 자세히 알아볼 수 있습니다.



== MetroCluster 및 기타 정보

|===


| 정보 | 제목 


 a| 
link:../index.html["MetroCluster 문서"]
 a| 
* 모든 MetroCluster 정보




 a| 
https://www.netapp.com/pdf.html?item=/media/13482-tr4375pdf.pdf["NetApp 기술 보고서 4375: ONTAP 9.3을 위한 NetApp MetroCluster"^]
 a| 
* MetroCluster 구성 및 작동에 대한 기술적 개요
* MetroCluster 구성에 대한 모범 사례




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html["패브릭 연결 MetroCluster 설치 및 구성"]
 a| 
* 패브릭 연결 MetroCluster 아키텍처
* 구성 케이블 연결
* FC-to-SAS 브릿지 구성
* FC 스위치 구성
* ONTAP에서 MetroCluster 구성




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html["스트레치 MetroCluster 설치 및 구성"]
 a| 
* MetroCluster 아키텍처 확장
* 구성 케이블 연결
* FC-to-SAS 브릿지 구성
* ONTAP에서 MetroCluster 구성




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html["MetroCluster IP 설치 및 구성"]
 a| 
* MetroCluster IP 아키텍처
* 구성 케이블 연결
* ONTAP에서 MetroCluster 구성




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker 1.21 소프트웨어 설치 및 구성"]
 a| 
* MetroCluster Tiebreaker 소프트웨어로 MetroCluster 구성 모니터링




 a| 
Active IQ Unified Manager 설명서 https://www.netapp.com/support-and-training/documentation/["NetApp 설명서: 제품 가이드 및 리소스"^]
 a| 
* MetroCluster 구성 및 성능 모니터링




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["복사 기반 전환"]
 a| 
* 7-Mode 스토리지 시스템에서 클러스터 스토리지 시스템으로 데이터 전환


|===