---
permalink: manage/task_verify_a_successful_switchback.html 
sidebar: sidebar 
keywords: perform, switchback, aggregate, storage, virtual, machine, svm, switch, back, online, verify, successful 
summary: '스위치백을 수행한 후 모든 애그리게이트 및 스토리지 가상 머신(SVM\)이 온라인 상태로 전환되었는지 확인할 수 있습니다.' 
---
= 스위치백을 성공적으로 확인하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치백을 수행한 후 모든 애그리게이트 및 SVM(스토리지 가상 머신)이 온라인 상태로 전환되었는지 확인할 수 있습니다.

. 전환된 데이터 애그리게이트가 다시 전환되는지 확인합니다.
+
'스토리지 집계 쇼'

+
다음 예제에서 노드 B2의 aggr_b2는 다시 전환되었습니다.

+
[listing]
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal

node_A_1::> aggr show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2          -         -     - unknown      - node_A_1
----
+
재해 사이트에 미러링되지 않은 애그리게이트가 포함되어 있고 미러링되지 않은 애그리게이트가 더 이상 존재하지 않는 경우, 'storage aggregate show' 명령의 출력에 "unknown" 상태로 나타날 수 있습니다. 기술 지원 부서에 문의하여 미러링되지 않은 애그리게이트에 대한 오래된 항목을 제거하십시오.

. 정상 작동하는 클러스터의 모든 동기화 대상 SVM이 휴면 상태이고("가동 상태"를 나타냄), 재해 클러스터의 동기화 소스 SVM이 실행 중인지 확인합니다.
+
'vserver show-subtype sync-source'를 선택합니다

+
[listing]
----
node_B_1::> vserver show -subtype sync-source
                               Admin      Root                       Name    Name
Vserver     Type    Subtype    State      Volume     Aggregate       Service Mapping
----------- ------- ---------- ---------- ---------- ----------      ------- -------
...
vs1a        data    sync-source
                               running    vs1a_vol   node_B_2        file    file
                                                                     aggr_b2

node_A_1::> vserver show -subtype sync-destination
                               Admin      Root                         Name    Name
Vserver            Type    Subtype    State      Volume     Aggregate  Service Mapping
-----------        ------- ---------- ---------- ---------- ---------- ------- -------
...
cluster_A-vs1a-mc  data    sync-destination
                                      stopped    vs1a_vol   sosb_      file    file
                                                                       aggr_b2
----
+
MetroCluster 구성의 동기화 대상 애그리게이트에는 식별을 위해 이름에 ""-mc" 접미사가 자동으로 추가됩니다.

. MetroCluster operation show 명령을 사용하여 스위치백 작업이 성공했는지 확인합니다.
+
|===


| 명령 출력에 다음과 같은 내용이 표시되는 경우 | 그러면... 


 a| 
스위치백 작업 상태가 성공입니다.
 a| 
스위치백 프로세스가 완료되었으며 시스템 작동을 계속할 수 있습니다.



 a| 
스위치백 작업 또는 스위치백 연속 - 상담원 작업이 부분적으로 성공했음을 나타냅니다.
 a| 
'MetroCluster operation show' 명령의 출력에서 제시된 픽스를 수행한다.

|===


반대 방향으로 스위치백을 수행하려면 이전 섹션을 반복해야 합니다. site_A가 site_B의 전환을 수행하는 경우 site_B가 site_A의 전환을 수행합니다
