---
permalink: manage/task_perform_a_negotiated_switchover.html 
sidebar: sidebar 
keywords: negotiate, switchover, clean, shut, down, partner, site, operation, metrocluster, perform 
summary: 협상된 전환은 파트너 사이트에서 프로세스를 완전히 종료한 다음 파트너 사이트에서 운영을 전환합니다. 협상된 전환을 사용하여 MetroCluster 사이트에 대한 유지 관리를 수행하거나 전환 기능을 테스트할 수 있습니다. 
---
= 협상된 전환 수행
:icons: font
:imagesdir: ../media/


[role="lead"]
협상된 전환은 파트너 사이트에서 프로세스를 완전히 종료한 다음 파트너 사이트에서 운영을 전환합니다. 협상된 전환을 사용하여 MetroCluster 사이트에 대한 유지 관리를 수행하거나 전환 기능을 테스트할 수 있습니다.

* 스위치백 작업을 수행하기 전에 이전의 모든 구성 변경을 완료해야 합니다.
+
이는 협상된 전환 또는 스위치백 작업으로 인한 경쟁을 피하기 위한 것입니다.

* 이전에 중단된 노드는 모두 부팅되고 클러스터 쿼럼에 있어야 합니다.
+
시스템 관리 참조_에는 "'쿼럼 및 epsilon 이해' 섹션에 클러스터 쿼럼에 대한 자세한 정보가 있습니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["시스템 관리"]

* 클러스터 피어링 네트워크는 두 사이트에서 모두 사용할 수 있어야 합니다.
* MetroCluster 구성의 모든 노드에서 동일한 버전의 ONTAP 소프트웨어를 실행해야 합니다.
* 새 SnapMirror 관계를 생성하기 전에 MetroCluster 구성의 두 사이트에서 replication.create_data_protection_irels.enable 옵션을 On으로 설정해야 합니다.
* 2노드 MetroCluster 구성의 경우 사이트 간에 ONTAP 버전이 일치하지 않으면 업그레이드 중에 새 SnapMirror 관계를 생성할 수 없습니다.
* 4노드 MetroCluster 구성의 경우 사이트 간에 일치하지 않는 버전의 ONTAP는 지원되지 않습니다.


복구 사이트에서 스위치백 작업을 수행하는 데 몇 시간이 걸릴 수 있습니다.

MetroCluster switchover 명령은 MetroCluster 구성의 모든 DR 그룹에 있는 노드로 전환합니다. 예를 들어, 8노드 MetroCluster 구성에서는 두 DR 그룹 모두에서 노드를 전환합니다.

협상된 전환을 준비 및 실행하는 동안 클러스터의 구성을 변경하거나 테이크오버 또는 반환 작업을 수행하지 않아야 합니다.

MetroCluster FC 구성의 경우:

* 원격 스토리지에 액세스할 수 있는 경우 미러링된 애그리게이트는 정상 상태로 유지됩니다.
* 원격 스토리지에 대한 액세스가 손실되면 협상된 전환 후 미러링된 애그리게이트의 성능이 저하됩니다.
* 원격 스토리지에 대한 액세스가 손실되면 재해 사이트에 있는 미러링되지 않은 애그리게이트를 사용할 수 없게 됩니다. 이로 인해 컨트롤러 중단이 발생할 수 있습니다.


MetroCluster IP 구성의 경우:


NOTE: 유지보수 작업을 수행하기 전에 Tiebreaker 또는 중재자 유틸리티를 사용하여 MetroCluster 구성을 모니터링하는 경우 모니터링을 제거해야 합니다.link:../maintain/concept_remove_mediator_or_tiebreaker_when_performing_maintenance_tasks.html["유지보수 작업을 수행하기 전에 ONTAP 중재자 또는 Tiebreaker 모니터링을 제거합니다"]

* ONTAP 9.4 및 이전 버전의 경우:
+
** 협상된 전환 후 미러링된 Aggregate가 성능 저하 상태가 됩니다.


* ONTAP 9.5 이상:
+
** 원격 스토리지에 액세스할 수 있는 경우 미러링된 애그리게이트는 정상 상태로 유지됩니다.
** 원격 스토리지에 대한 액세스가 손실되면 협상된 전환 후 미러링된 애그리게이트의 성능이 저하됩니다.


* ONTAP 9.8 이상:
+
** 원격 스토리지에 대한 액세스가 손실되면 재해 사이트에 있는 미러링되지 않은 애그리게이트를 사용할 수 없게 됩니다. 이로 인해 컨트롤러 중단이 발생할 수 있습니다.
+
... MetroCluster check run, MetroCluster check show 및 MetroCluster check config-replication show 명령을 사용하여 진행 중이거나 보류 중인 구성 업데이트가 없는지 확인하십시오. 사이트에서 작동 중인 명령을 실행합니다.
... 가동 및 운영 중인 사이트에서 MetroCluster 절체(switchover)를 실행한다
+
작업을 완료하는 데 몇 분 정도 걸릴 수 있습니다.

... MetroCluster Operation show로 전환 완료 여부를 모니터링한다
+
[listing]
----
cluster_A::*> metrocluster operation show
  Operation: Switchover
 Start time: 10/4/2012 19:04:13
      State: in-progress
   End time: -
     Errors:

cluster_A::*> metrocluster operation show
  Operation: Switchover
 Start time: 10/4/2012 19:04:13
      State: successful
   End time: 10/4/2012 19:04:22
     Errors: -
----
... SnapMirror 또는 SnapVault 구성을 다시 설정합니다.





