---
permalink: manage/task_verifiy_that_your_system_is_ready_for_a_switchover.html 
sidebar: sidebar 
keywords: simulate, option, preview, result, switchover, operation, verification, check, precondition, succesful, verify, ready, example 
summary: simulate 옵션을 사용하여 전환 작업의 결과를 미리 볼 수 있습니다. 확인 검사를 통해 작업을 시작하기 전에 성공적인 실행을 위한 대부분의 전제 조건이 충족되었는지 확인할 수 있습니다. 
---
= 시스템을 전환할 준비가 되었는지 확인
:icons: font
:imagesdir: ../media/


[role="lead"]
'-simulate' 옵션을 사용하여 전환 작업의 결과를 미리 볼 수 있습니다. 확인 검사를 통해 작업을 시작하기 전에 성공적인 실행을 위한 대부분의 전제 조건이 충족되었는지 확인할 수 있습니다. 사이트에서 작동 중인 다음 명령을 실행하십시오.

. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
. 가동 및 운영 중인 사이트에서 스위치오버 작업인 MetroCluster Switchover-Simulate를 시뮬레이션합니다
. 반환되는 출력을 검토합니다.
+
출력에는 전환 작업을 방해하는 트레인이 있는지 여부가 표시됩니다. MetroCluster 작업을 수행할 때마다 작업의 성공을 위한 일련의 기준을 확인해야 합니다. "to"는 하나 이상의 기준이 충족되지 않을 경우 작동을 금지하는 메커니즘입니다. 거부권은 소프트 거부권, 강경한 거부권 등 두 가지가 있습니다. 당신은 소프트 거부권을 무효화할 수 있지만, 하드 거부권은 무효가 될 수 없습니다. 예를 들어, 4노드 MetroCluster 구성에서 협상된 전환을 수행하기 위한 한 가지 기준은 모든 노드가 정상 작동하는 것입니다. 한 노드가 다운되어 HA 파트너가 인수되었다고 가정해 보겠습니다. 스위치오버 작업은 모든 노드가 정상 상태여야 한다는 하드 조건이므로 거부되지 않습니다. 이는 거부권을 행사하기 때문에 거부권을 무효화할 수 없습니다.

+

IMPORTANT: 거부권을 무시하지 않는 것이 가장 좋습니다.





== 예: 확인 결과

다음 예에서는 스위치오버 작업 시뮬레이션에서 발생한 오류를 보여 줍니다.

[listing]
----
cluster4::*> metrocluster switchover -simulate

[Job 126] Preparing the cluster for the switchover operation...
[Job 126] Job failed: Failed to prepare the cluster for the switchover
operation. Use the "metrocluster operation show" command to view detailed error
information. Resolve the errors, then try the command again.
----

NOTE: 협상된 전환 및 스위치백을 장애가 발생한 모든 디스크를 교체할 때까지 실패합니다. 장애가 발생한 디스크를 교체한 후 재해 복구를 수행할 수 있습니다. 오류가 발생한 디스크에 대한 경고를 무시하려면 협상된 전환 및 스위치백에 대해 소프트 거부를 추가할 수 있습니다.
